apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: local-root-ca
spec:
    selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: local-root-ca
    namespace: cert-manager
spec:
    isCA: true
    commonName: local-root-ca
    secretName: local-root-ca-secret
    duration: 87600h
    renewBefore: 78840h
    privateKey:
        algorithm: ECDSA
        size: 256
    issuerRef:
        name: local-root-ca
        kind: ClusterIssuer
        group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: local-issuer
spec:
    ca:
        secretName: local-root-ca-secret
