apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: forwards.iaas.phorge.fr
spec:
  scope: Cluster
  group: iaas.phorge.fr
  names:
    kind: Forward
    plural: forwards
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              network:
                type: string
              listen_address:
                type: string
              description:
                type: string
              config:
                type: object
                additionalProperties:
                  type: string
              project:
                type: string
              remote:
                type: string
              ports:
                type: array
                items:
                  type: object
                  properties:
                    protocol:
                      type: string
                    listen_port:
                      type: array
                      items:
                        type: string
                    target_address:
                      type: string
                    target_port:
                      type: array
                      items:
                        type: string
                    description:
                      type: string
                  required:
                    - protocol
                    - listen_port
                    - target_address
            required:
              - network
              - listen_address
              - project
          status:
            type: object
            properties:
              error:
                description: Returns tofu error message if the workspace creation failed
                type: string
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: forward.iaas.phorge.fr
  labels:
    provider: incus
spec:
  compositeTypeRef:
    apiVersion: iaas.phorge.fr/v1alpha1
    kind: Forward
  mode: Pipeline
  pipeline:
  - step: create-forward
    functionRef:
      name: fn-pythonic
    input:
      apiVersion: pythonic.fn.crossplane.io/v1alpha1
      kind: Composite
      composite: |
        import json
        import re
        import base64
        import gzip

        class ForwardComposite(BaseComposite):
          def compose(self):

            specs = json.loads(format(self.request.observed.composite.resource["spec"], "json"))

            ports = [{"protocol": backend["protocol"], "listen_port": ','.join(backend["listen_port"]), "target_address": backend["target_address"], "target_port": ','.join(backend.get("target_port", "")), "description": backend.get("description", "")} for backend in specs.get("ports", [])]

            if ports == []: # Handle empty ports
                ports = None

            forward = self.resources.forward("opentofu.upbound.io/v1beta1", "Workspace")
            forward.spec.providerConfigRef.name = "iaas"
            forward.spec.forProvider.source = "Inline"
            forward.spec.forProvider.module = f"""resource "incus_network_forward" "forward" {{
            network        = "{specs['network']}"
            listen_address = "{specs['listen_address']}"
            description    = "{specs.get('description', 'crosssplane;;;')}"
            config   = {json.dumps(specs.get("config", {}))}
            project = "{specs['project']}"
            remote      = "{specs.get('remote', 'iaas')}"
            ports = {json.dumps(ports)}
            }}
            """

            if forward.status:
                forward_status = json.loads(format(forward.status, "json"))
                message = next((c["message"] for c in forward_status["conditions"] if "message" in c), None)
                status = next((c["status"] for c in forward_status["conditions"] if "observedGeneration" in c), None).lower() == "true"

                if message:
                    match = re.search(r'echo\s+"([A-Za-z0-9+/=]+)"\s*\|\s*base64', message)
                    decoded = base64.b64decode(match.group(1))
                    message = gzip.decompress(decoded).decode('utf-8')

                self.ready = status
                self.status.error = str(message)