apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: instances.iaas.phorge.fr
spec:
  scope: Cluster
  group: iaas.phorge.fr
  names:
    kind: Instance
    plural: instances
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              image:
                type: string
              description:
                type: string
              type:
                type: string
              ephemeral:
                type: boolean
              running:
                type: boolean
              wait_for:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    delay:
                      type: string
                    nic:
                      type: string
                  required:
                    - type
              profiles:
                type: array
                items:
                  type: string
              devices:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    properties:
                      type: object
                      additionalProperties:
                        type: string
              config:
                type: object
                additionalProperties:
                  type: string
              project:
                type: string
              remote:
                type: string
              target:
                type: string
            required:
              - name
              - image
              - project
          status:
            type: object
            properties:
              error:
                description: Returns tofu error message if the workspace creation failed
                type: string
              ipv4_address:
                description: The IPv4 address of the created instance
                type: string
              ipv6_address:
                description: The IPv6 address of the created instance
                type: string
              target:
                description: The target of the created instance
                type: string
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: instance.iaas.phorge.fr
  labels:
    provider: incus
spec:
  compositeTypeRef:
    apiVersion: iaas.phorge.fr/v1alpha1
    kind: Instance
  mode: Pipeline
  pipeline:
  - step: create-instance
    functionRef:
      name: fn-pythonic
    input:
      apiVersion: pythonic.fn.crossplane.io/v1alpha1
      kind: Composite
      composite: |
        import json
        import re
        import base64
        import gzip

        def terraformize(k: str, v):
            result = ""
            for value in v:
                result += f"{k} {{\n"
                for key, val in value.items():
                    result += f"   {key} = {json.dumps(val)}\n"
                result += "  }\n"
            
            return result

        class InstanceComposite(BaseComposite):
          def compose(self):

            specs = json.loads(format(self.request.observed.composite.resource["spec"], "json"))

            devices = [{"name": device["name"], "type": device["type"], "properties": device["properties"]} for device in specs.get("devices", [])]
            wait_for = [{"type": item["type"], **{key: item[key] for key in item if key != "type"}} for item in specs.get("wait_for", [])]

            instance = self.resources.instance("opentofu.upbound.io/v1beta1", "Workspace")
            instance.spec.providerConfigRef.name = "iaas"
            instance.spec.forProvider.source = "Inline"
            instance.spec.forProvider.enableTofuCLILogging = True
            instance.spec.forProvider.module = f"""resource "incus_instance" "instance" {{
            name        = "{specs['name']}"
            image       = "{specs['image']}"
            description = "{specs.get('description', 'crosssplane;;;')}"
            type        = "{specs.get('type', 'container')}"
            ephemeral   = {str(specs.get('ephemeral', False)).lower()}
            running     = {str(specs.get('running', True)).lower()}
            {terraformize("wait_for", wait_for)}
            profiles = {json.dumps(specs.get("profiles", []))}
            {terraformize("device", devices)}
            config   = {json.dumps(specs.get("config", {}))}
            project     = "{specs['project']}"
            remote      = "{specs.get('remote', 'iaas')}"
            target      = {specs.get("target", "null")}
            }}
            output "instance_config" {{
              value = incus_instance.instance
            }}
            """

            if instance.status:
              instance_status = json.loads(format(instance.status, "json"))
              message = next((c["message"] for c in instance_status["conditions"] if "message" in c), None)
              status = next((c["status"] for c in instance_status["conditions"] if "observedGeneration" in c), None).lower() == "true"

              instance_config = json.loads(format(instance.status.atProvider.outputs.instance_config, "json"))

              if message:
                match = re.search(r'echo\s+"([A-Za-z0-9+/=]+)"\s*\|\s*base64', message)
                decoded = base64.b64decode(match.group(1))
                message = gzip.decompress(decoded).decode('utf-8')

              self.status.ipv4_address = str(instance_config.get("ipv4_address"))
              self.status.ipv6_address = str(instance_config.get("ipv6_address"))
              self.status.target = str(instance_config.get("target"))
              self.ready = status
              self.status.error = str(message)