apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: profiles.iaas.phorge.fr
spec:
  scope: Cluster
  group: iaas.phorge.fr
  names:
    kind: Profile
    plural: profiles
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              devices:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    properties:
                      type: object
                      additionalProperties:
                        type: string
              config:
                type: object
                additionalProperties:
                  type: string
              project:
                type: string
              remote:
                type: string
            required:
              - name
              - project
          status:
            type: object
            properties:
              error:
                description: Returns tofu error message if the workspace creation failed
                type: string
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: profile.iaas.phorge.fr
  labels:
    provider: incus
spec:
  compositeTypeRef:
    apiVersion: iaas.phorge.fr/v1alpha1
    kind: Profile
  mode: Pipeline
  pipeline:
  - step: create-profile
    functionRef:
      name: fn-pythonic
    input:
      apiVersion: pythonic.fn.crossplane.io/v1alpha1
      kind: Composite
      composite: |
        import json
        import re
        import base64
        import gzip

        def terraformize(k: str, v):
          result = ""
          for value in v:
            result += f"{k} {{\n"
            for key, val in value.items():
              result += f"   {key} = {json.dumps(val)}\n"
            result += "  }\n"
            
          return result

        def handle_status(status: any):
          if isinstance(status, str):
            return {}
          else:
            return json.loads(status)

        class ProfileComposite(BaseComposite):
          def compose(self):

            specs = json.loads(format(self.request.observed.composite.resource["spec"], "json"))

            devices = [{"name": device["name"], "type": device["type"], "properties": device["properties"]} for device in specs.get("devices", [])]
            wait_for = [{"type": item["type"], **{key: item[key] for key in item if key != "type"}} for item in specs.get("wait_for", [])]

            profile = self.resources.profile("opentofu.upbound.io/v1beta1", "Workspace")
            profile.spec.providerConfigRef.name = "iaas"
            profile.spec.forProvider.source = "Inline"
            profile.spec.forProvider.module = f"""resource "incus_profile" "profile" {{
            name        = "{specs['name']}"
            description = "{specs.get('description', 'crosssplane;;;')}"
            {terraformize("device", devices)}
            config   = {json.dumps(specs.get("config", {}))}
            project     = "{specs['project']}"
            remote      = "{specs.get('remote', 'iaas')}"
            }}
            """

            if profile.status:
              profile_status = json.loads(format(profile.status, "json"))
              message = next((c["message"] for c in profile_status["conditions"] if "message" in c), None)
              status = next((c["status"] for c in profile_status["conditions"] if "observedGeneration" in c), None).lower() == "true"
              
              if message:
                match = re.search(r'echo\s+"([A-Za-z0-9+/=]+)"\s*\|\s*base64', message)
                decoded = base64.b64decode(match.group(1))
                message = gzip.decompress(decoded).decode('utf-8')

              self.ready = status
              self.status.error = str(message)