apiVersion: opentofu.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: iaas
spec:
  configuration: |
    terraform {
      required_providers {
        incus = {
          source = "lxc/incus"
          version = "1.0.2"
        }
      }
      backend "kubernetes" {
        secret_suffix     = "providerconfig-default"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }
    }

    provider "incus" {
      accept_remote_certificate = true
      default_remote            = "iaas"
      config_dir                = "/tofu/config/incus"
      remote {
        name    = "iaas"
        address = "https://iaas.phorge.fr:443"
      }
    }

---
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: vms.iaas.phorge.fr
spec:
  scope: Cluster
  group: iaas.phorge.fr
  names:
    kind: VM
    plural: vms
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              project:
                type: string
              remote:
                type: string
              description:
                type: string
              image:
                type: string
              type:
                type: string
              profiles:
                type: array
                items:
                  type: string
              ephemeral:
                type: boolean
              running:
                type: boolean
              target:
                type: string
              config:
                type: object
                additionalProperties:
                  type: string
              device:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    properties:
                      type: object
                      additionalProperties:
                        type: string
              wait_for:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    delay:
                      type: string
                    nic:
                      type: string
                  required:
                    - type
            required:
              - name
              - image
              - project
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type: { type: string }
                    status: { type: string }
                    reason: { type: string }
                    message: { type: string }
                    lastTransitionTime: { type: string }

---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vm.iaas.phorge.fr
  labels:
    provider: incus
spec:
  compositeTypeRef:
    apiVersion: iaas.phorge.fr/v1alpha1
    kind: VM
  mode: Pipeline
  pipeline:
  - step: compose-a-resource-with-python
    functionRef:
      name: crossplane-contrib-function-python
    input:
      apiVersion: python.fn.crossplane.io/v1beta1
      kind: Script
      script: |
        import json
        from crossplane.function.proto.v1 import run_function_pb2 as fnv1
        from google.protobuf.json_format import MessageToDict

        def terraformize(k: str, v):
            result = ""
            for device in v:
                result += f"{k} {{\n"
                for key, value in device.items():
                    result += f"   {key} = {json.dumps(value)}\n"
                result += "  }\n"
            
            return result

        def compose(req: fnv1.RunFunctionRequest, rsp: fnv1.RunFunctionResponse):
            
            specs = MessageToDict(req.observed.composite.resource["spec"])

            devices = [{"name": device["name"], "type": device["type"], "properties": device["properties"]} for device in specs.get("device", [])]
            wait_for = [{"type": item["type"], **{key: item[key] for key in item if key != "type"}} for item in specs.get("wait_for", [])]

            rsp.desired.resources["vm"].resource.update({
                "apiVersion": "opentofu.upbound.io/v1beta1",
                "kind": "Workspace",
                "spec": {
                    "providerConfigRef": {"name": "iaas"},
                    "forProvider": {
                        "source": "Inline",
                        "module":f"""resource "incus_instance" "this" {{
          name        = "{specs['name']}"
          project     = "{specs['project']}"
          remote      = "{specs.get('remote', 'iaas')}"
          target      = {specs.get("target", "null")}
          description = "{specs.get('description', '')}"
          image       = "{specs['image']}"
          type        = "{specs.get('type', 'container')}"
          ephemeral   = {str(specs.get('ephemeral', False)).lower()}
          running     = {str(specs.get('running', True)).lower()}
          config   = {json.dumps(specs.get("config", {}))}
          profiles = {json.dumps(specs.get("profiles", []))}

          {terraformize("device", devices)}
          {terraformize("wait_for", wait_for)}
        }}
        """,
                    },
                },
            })
            