apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: frontplane
  user: phorge-admin
spec:
  k0s:
    version: 1.34.1+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          extraArgs:
            oidc-issuer-url: https://git.phorge.fr/
            oidc-client-id: b8622e31-f19d-4526-ab64-7793eb071835
            oidc-username-claim: email
          k0sApiPort: 9443
          port: 6443
          sans:
            - 10.0.0.7
        network:
          provider: custom
          kubeProxy:
            disabled: true
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          controlPlaneLoadBalancing:
            enabled: true
            type: Keepalived
            keepalived:
              vrrpInstances:
                - virtualIPs: ["10.0.0.7/24"]
                  authPass: "@Ph0rg3@"
                  interface: end0
          nodeLocalLoadBalancing:
            enabled: true
            type: EnvoyProxy
        storage:
          type: etcd
          etcd:
            extraArgs:
              listen-peer-urls: https://0.0.0.0:2380
              listen-client-urls: https://0.0.0.0:2379
        telemetry:
          enabled: false
  hosts:
    - ssh:
        address: 10.0.0.1
        user: root
        port: 22
      role: controller+worker
      installFlags:
        - --disable-components=konnectivity-server
        - --kubelet-extra-args=--image-gc-high-threshold=50 --image-gc-low-threshold=45
      noTaints: true
      privateAddress: 10.0.0.1
      privateInterface: end0
    - ssh:
        address: 10.0.0.2
        user: root
        port: 22
      role: controller+worker
      installFlags:
        - --disable-components=konnectivity-server
        - --kubelet-extra-args=--image-gc-high-threshold=50 --image-gc-low-threshold=45
      noTaints: true
      privateAddress: 10.0.0.2
      privateInterface: end0
    - ssh:
        address: 10.0.0.3
        user: root
        port: 22
      role: controller+worker
      installFlags:
        - --disable-components=konnectivity-server
        - --kubelet-extra-args=--image-gc-high-threshold=50 --image-gc-low-threshold=45
      noTaints: true
      privateAddress: 10.0.0.3
      privateInterface: end0
    - ssh:
        address: 10.0.0.4
        user: root
        port: 22
      role: worker
      installFlags:
        - --kubelet-extra-args=--image-gc-high-threshold=50 --image-gc-low-threshold=45
    - ssh:
        address: 10.0.0.5
        user: root
        port: 22
      role: worker
      installFlags:
        - --kubelet-extra-args=--image-gc-high-threshold=50 --image-gc-low-threshold=45
    - ssh:
        address: 10.0.0.6
        user: root
        port: 22
      role: worker
      installFlags:
        - --kubelet-extra-args=--image-gc-high-threshold=50 --image-gc-low-threshold=45