apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
    name: control
    user: phorge-admin
spec:
    k0s:
        version: 1.36.4+k0s.0
        config:
            apiVersion: k0s.k0sproject.io/v1beta1
            kind: Cluster
            metadata:
                name: k0s
            spec:
                api:
                    k0sApiPort: 9443
                    port: 6443
                    sans:
                        - 10.1.0.4
                network:
                    provider: custom
                    kubeProxy:
                        disabled: true
                    podCIDR: 10.244.0.0/16
                    serviceCIDR: 10.96.0.0/12
                    controlPlaneLoadBalancing:
                        enabled: true
                        type: Keepalived
                        keepalived:
                            vrrpInstances:
                                - virtualIPs:
                                    - 10.1.0.4/24
                                  authPass: ENC[AES256_GCM,data:8bDO0uR5WK0=,iv:NKmI1hIR+mHp5rYPCvhkHYm9qmiPgZlAgHHITFiXfcQ=,tag:6/ctVfxK5jUU9a21cL5oMg==,type:str]
                                  interface: eth0
                    nodeLocalLoadBalancing:
                        enabled: true
                        type: Traefik
                storage:
                    type: etcd
                    etcd:
                        extraArgs:
                            listen-peer-urls: https://0.0.0.0:2380
                            listen-client-urls: https://0.0.0.0:2379
                            listen-metrics-urls: http://127.0.0.1:2381
                telemetry:
                    enabled: false
    hosts:
        - ssh:
            address: 10.1.0.1
            user: root
            port: 22
          role: controller+worker
          installFlags:
            - --disable-components=konnectivity-server
            - --kubelet-extra-args=--image-gc-high-threshold=50 --image-gc-low-threshold=45
          noTaints: true
          privateAddress: 10.1.0.1
          privateInterface: eth0
        - ssh:
            address: 10.1.0.2
            user: root
            port: 22
          role: controller+worker
          installFlags:
            - --disable-components=konnectivity-server
            - --kubelet-extra-args=--image-gc-high-threshold=50 --image-gc-low-threshold=45
          noTaints: true
          privateAddress: 10.1.0.2
          privateInterface: eth0
        - ssh:
            address: 10.1.0.3
            user: root
            port: 22
          role: controller+worker
          installFlags:
            - --disable-components=konnectivity-server
            - --kubelet-extra-args=--image-gc-high-threshold=50 --image-gc-low-threshold=45
          noTaints: true
          privateAddress: 10.1.0.3
          privateInterface: eth0
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YkEyVEgxVHJ2L1FNeXRP
            U1hJdTM1UXMvaFhCMGNnSFMvKzlVTUdFa1VjCmFlK2FJMUlvY3NUVnpHbzZGTVNx
            YlRKNHpIOGJwQVc0Q3hRWUxOQTBoWGsKLS0tIGJPQXc3QVo2blhmSTd5SWxEWUxJ
            NGFGODFsL1FuYzNSdndoRmExNkU0M2cKOHXxPvI6KqirDMMjnS0WqSTw+YeXOpvY
            iiXzB24OgdsVhoIhGlA0ivLBtazgVuAXVt2Ty+URSxjDzKwd9S/plQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T16:17:18Z"
    mac: ENC[AES256_GCM,data:5jGHtnorudz/asw0SwDfD7yzokHn6Vd4qckVd0EF5VvkdKgGiRLzckIKSi6lOBud7dSHJQ9I7lW9q16ui3fU+Z1JblTlh78wvkbf8YzO9RxwZ+01jtNMLHedKYiuYy6XcG4aaATWSM5DBzQDvjAkAiTfWrZsqQuUliLc/LZJdas=,iv:8O9RkRodlezQhiU2mNWlXDnHs3Ptn+KZVktAwVdAr0A=,tag:n3wYjTD1BxZDJCj09YdWeg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
