apiVersion: v1
kind: Namespace
metadata:
    name: authentik
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRDJ1T1A1QzNoTERtQVZn
            bG1Obmx6VFJKNHVPYmJqdlVGQ0pkb0lSM0VFCjFOVGFMS20rby9qZkpYa2FTVXhP
            R1ZyT1ZUQkN2SkZLcFdQK2FQUmo4VEEKLS0tIG5rYzF0Ymt0ZlJkaFV0dURyMWEw
            UDY4aHdQOHVVQWhpQWtSdVl3RU1Mb0kKoXR2mRB5w0Hb7SlxQjtWfYDx9kUDG38e
            oojE+N2Z6Ap91ACTs9B6lvTEgNcKw5JQuKB+5FFvDe7AvCh6bj4Vcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T01:32:57Z"
    mac: ENC[AES256_GCM,data:3EFAebB6mt5HgonZ9RTw/aiA8VpravLYC5au+IbzqyS6o+g2+gqJsXqNRx1kDN0sWk2nQN8ipnNHePBFN/cE9b4hVKex7JgILnF/bAcv9+oBpQecm8xsM6zgGaV4HLZc//vilspHCdxUwCDgXuCJ3PwXYT8PU1GXIkXhh4WiDiE=,iv:DY0h4exO4x+FOzJsAAIvT1Roy4wVZdEE7HFupsHNyv0=,tag:xRpobapDlPt9gloIvt51Ew==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: authentik
    namespace: authentik
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://charts.goauthentik.io
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRDJ1T1A1QzNoTERtQVZn
            bG1Obmx6VFJKNHVPYmJqdlVGQ0pkb0lSM0VFCjFOVGFMS20rby9qZkpYa2FTVXhP
            R1ZyT1ZUQkN2SkZLcFdQK2FQUmo4VEEKLS0tIG5rYzF0Ymt0ZlJkaFV0dURyMWEw
            UDY4aHdQOHVVQWhpQWtSdVl3RU1Mb0kKoXR2mRB5w0Hb7SlxQjtWfYDx9kUDG38e
            oojE+N2Z6Ap91ACTs9B6lvTEgNcKw5JQuKB+5FFvDe7AvCh6bj4Vcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T01:32:57Z"
    mac: ENC[AES256_GCM,data:3EFAebB6mt5HgonZ9RTw/aiA8VpravLYC5au+IbzqyS6o+g2+gqJsXqNRx1kDN0sWk2nQN8ipnNHePBFN/cE9b4hVKex7JgILnF/bAcv9+oBpQecm8xsM6zgGaV4HLZc//vilspHCdxUwCDgXuCJ3PwXYT8PU1GXIkXhh4WiDiE=,iv:DY0h4exO4x+FOzJsAAIvT1Roy4wVZdEE7HFupsHNyv0=,tag:xRpobapDlPt9gloIvt51Ew==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: authentik
    namespace: authentik
spec:
    chart:
        spec:
            chart: authentik
            sourceRef:
                kind: HelmRepository
                name: authentik
            version: '*'
    interval: 1m0s
    timeout: 10m0s
    values:
        global:
            security:
                allowInsecureImages: true
            image:
                repository: ghcr.io/goauthentik/server
                tag: 2026.5.5
            addPrometheusAnnotations: false
            env: []
            envFrom: []
            volumeMounts: []
            volumes: []
        blueprints:
            configMaps:
                - authentik-grafana-oauth-blueprint
                - authentik-forgejo-oauth-blueprint
                - authentik-brand
        authentik:
            enabled: true
            log_level: info
            secret_key: ENC[AES256_GCM,data:DT9ASigHFwCcy677ErL9baQLZN5AkjTsZd/D1CV2aGBgEAtOAKt9yXSXV2bmyTdS31F6/XSGbFKHp3kuEfBPIg==,iv:ePRe4hZtsjzzVv3A2n0S88MZiaWTZnHxTyKCzG4dy7I=,tag:y2TtbjbVOGDvFr+RWZ13bA==,type:str]
            existingSecret:
                secretName: ""
            events:
                context_processors:
                    geoip: /geoip/GeoLite2-City.mmdb
                    asn: /geoip/GeoLite2-ASN.mmdb
            web:
                path: /
            email:
                host: ""
                port: ENC[AES256_GCM,data:dnnD,iv:eJhzWn4JvfSF1eky6fW8ya/DyZ1fOC0hDOkIi7tgLTc=,tag:7NRFOSn18hFbEbuiX75K2w==,type:int]
                username: ""
                password: ""
                use_tls: ENC[AES256_GCM,data:5puieFw=,iv:UPQyezk9NrTTzclsDR790p6b62NsfqDnJHaDBpXZKoM=,tag:iBYE+hVj8TVM+DmEoRYxJw==,type:bool]
                use_ssl: ENC[AES256_GCM,data:L9jyLZc=,iv:tqHwec7Z5ltz3jUGj6wOAjMPwyzvKxsuKWju+aGYRbU=,tag:OXkPpHdmejiqgcKSsdlUjQ==,type:bool]
                timeout: ENC[AES256_GCM,data:quE=,iv:CJcHCgmNIUI8XQORtC0BcEiKUFEMGo3m1rKv9aqT3cY=,tag:i25FHY7gOlHQo4gZsXS6iA==,type:int]
                from: ""
            outposts:
                container_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
            error_reporting:
                enabled: false
                environment: k8s
                send_pii: false
            postgresql:
                host: '{{ .Release.Name }}-postgresql'
                name: authentik
                user: authentik
                password: ENC[AES256_GCM,data:tJjXJ6mARpnyhs20NL2Y1SerN4QhQ/P8hDksNkMANA==,iv:DsgGeb2Z9L/UwPmZt33sNy3c0Zyh3ftJIEl/xHETZB8=,tag:4QVD1MP+E9l5Jy0pnJkFZw==,type:str]
                port: 5432
        server:
            enabled: true
            name: server
            replicas: 1
            env: []
            envFrom: []
            extraContainers: []
            initContainers: []
            volumeMounts: []
            volumes: []
            containerPorts:
                http: 9000
                https: 9443
                metrics: 9300
            hostNetwork: false
            service:
                annotations: {}
                labels: {}
                type: ClusterIP
                nodePortHttp: 30080
                nodePortHttps: 30443
                servicePortHttp: 80
                servicePortHttps: 443
                servicePortHttpName: http
                servicePortHttpsName: https
                loadBalancerIP: ""
                loadBalancerSourceRanges: []
                externalIPs: []
                externalTrafficPolicy: ""
                sessionAffinity: ""
                sessionAffinityConfig: {}
            metrics:
                enabled: false
                service:
                    type: ClusterIP
                    clusterIP: ""
                    annotations: {}
                    labels: {}
                    servicePort: 9300
                    portName: metrics
                serviceMonitor:
                    enabled: false
                    interval: 30s
                    scrapeTimeout: 3s
                    relabelings: []
                    metricRelabelings: []
                    selector: {}
                    scheme: ""
                    tlsConfig: {}
                    namespace: ""
                    labels: {}
                    annotations: {}
            ingress:
                enabled: true
                annotations:
                    cert-manager.io/cluster-issuer: public-issuer
                labels: {}
                ingressClassName: traefik-public
                hosts:
                    - auth.phorge.fr
                paths:
                    - '{{ .Values.authentik.web.path }}'
                pathType: Prefix
                tls:
                    - hosts:
                        - auth.phorge.fr
                      secretName: authentik-tls
                https: false
        worker:
            enabled: true
            name: worker
            replicas: 1
            env: []
            envFrom: []
            extraContainers: []
            initContainers: []
            volumeMounts: []
            volumes: []
            containerPorts:
                http: 9000
                metrics: 9300
            metrics:
                enabled: false
                service:
                    type: ClusterIP
                    clusterIP: ""
                    annotations: {}
                    labels: {}
                    servicePort: 9300
                    portName: metrics
                serviceMonitor:
                    enabled: false
                    interval: 30s
                    scrapeTimeout: 3s
                    relabelings: []
                    metricRelabelings: []
                    selector: {}
                    scheme: ""
                    tlsConfig: {}
                    namespace: ""
                    labels: {}
                    annotations: {}
        serviceAccount:
            create: ENC[AES256_GCM,data:ZYFo1g==,iv:1l7qvyej295aCObyCt36GCSXaumROK9vWCqW1YJ4G2w=,tag:3J1g6NxDzL7sAVE9pcCWHg==,type:bool]
            annotations: {}
            serviceAccountSecret:
                enabled: ENC[AES256_GCM,data:wkCVAFY=,iv:0QzGND3it447dopjSiU52lHAAJK3QZwaRH1YEhbzaPQ=,tag:Y8zQ87OvpA7O2gPACkrakQ==,type:bool]
            fullnameOverride: ENC[AES256_GCM,data:HmwM7/yfp5/V,iv:xsWo57i1+wdiAU/QgeJNfCH+1GddswoNtBzxdMCZwpc=,tag:1zwwHBk/WVZ7p0+JjxGOhA==,type:str]
        geoip:
            enabled: false
            editionIds: GeoLite2-City GeoLite2-ASN
            updateInterval: 8
            accountId: ""
            licenseKey: ""
            existingSecret:
                secretName: ""
                accountId: account_id
                licenseKey: license_key
            image:
                repository: ghcr.io/maxmind/geoipupdate
                tag: v7.1.1
                digest: ""
                pullPolicy: IfNotPresent
            env: []
            envFrom: []
            volumeMounts: []
            resources: {}
            containerSecurityContext: {}
        prometheus:
            rules:
                enabled: false
                namespace: ""
                selector: {}
                labels: {}
                annotations: {}
                additionalRuleGroupAnnotations: {}
        postgresql:
            enabled: true
            image:
                registry: docker.io
                repository: library/postgres
                tag: 17.10-bookworm
            auth:
                username: ENC[AES256_GCM,data:SA7qSSYkz451,iv:GhO+63pClsHSAySzdbEkgu/CoA3CzAJC1Ywg98ABa+Y=,tag:1f6/yT+hfSf1PIM0Da9IYA==,type:str]
                database: authentik
                password: ENC[AES256_GCM,data:kPi1tx39n6e+1a9JYWYpqZYWICHOv5R8JODCcbDlSQ==,iv:Rf/aos0HuMSOfk3gBQDBb6K4qzWaFv+uyDg1QUPRbrE=,tag:t7r5mQe1VAZDtVSoWDGcMw==,type:str]
            primary:
                args:
                    - -c
                    - config_file=/bitnami/postgresql/conf/postgresql.conf
                    - -c
                    - hba_file=/bitnami/postgresql/conf/pg_hba.conf
                configuration: |
                    listen_addresses = '*'
                    port = '5432'
                    wal_level = 'replica'
                    fsync = 'on'
                    hot_standby = 'on'
                    log_connections = 'false'
                    log_disconnections = 'false'
                    log_hostname = 'false'
                    client_min_messages = 'error'
                    include_dir = 'conf.d'
                pgHbaConfiguration: |
                    host     all             all             0.0.0.0/0               scram-sha-256
                    host     all             all             ::/0                    scram-sha-256
                    local    all             all                                     scram-sha-256
                    host     all             all        127.0.0.1/32                 scram-sha-256
                    host     all             all        ::1/128                      scram-sha-256
                extendedConfiguration: |
                    max_connections = 500
                extraEnvVars:
                    - name: POSTGRES_DB
                      value: '{{ (include "postgresql.v1.database" .) }}'
                resourcesPreset: none
                containerSecurityContext:
                    readOnlyRootFilesystem: true
                extraVolumeMounts:
                    - name: postgresql-socket
                      mountPath: /var/run/postgresql
                extraVolumes:
                    - name: postgresql-socket
                      emptyDir: {}
            readReplicas:
                resourcesPreset: none
            backup:
                resourcesPreset: none
            passwordUpdateJob:
                resourcesPreset: none
            volumePermissions:
                resourcesPreset: none
                image:
                    repository: debian
                    tag: 13-slim
            metrics:
                resourcesPreset: none
                image:
                    repository: prometheuscommunity/postgres-exporter
                    tag: v0.19.1
        redis:
            enabled: true
        additionalObjects: []
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRDJ1T1A1QzNoTERtQVZn
            bG1Obmx6VFJKNHVPYmJqdlVGQ0pkb0lSM0VFCjFOVGFMS20rby9qZkpYa2FTVXhP
            R1ZyT1ZUQkN2SkZLcFdQK2FQUmo4VEEKLS0tIG5rYzF0Ymt0ZlJkaFV0dURyMWEw
            UDY4aHdQOHVVQWhpQWtSdVl3RU1Mb0kKoXR2mRB5w0Hb7SlxQjtWfYDx9kUDG38e
            oojE+N2Z6Ap91ACTs9B6lvTEgNcKw5JQuKB+5FFvDe7AvCh6bj4Vcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T01:32:57Z"
    mac: ENC[AES256_GCM,data:3EFAebB6mt5HgonZ9RTw/aiA8VpravLYC5au+IbzqyS6o+g2+gqJsXqNRx1kDN0sWk2nQN8ipnNHePBFN/cE9b4hVKex7JgILnF/bAcv9+oBpQecm8xsM6zgGaV4HLZc//vilspHCdxUwCDgXuCJ3PwXYT8PU1GXIkXhh4WiDiE=,iv:DY0h4exO4x+FOzJsAAIvT1Roy4wVZdEE7HFupsHNyv0=,tag:xRpobapDlPt9gloIvt51Ew==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
