apiVersion: v1
kind: Namespace
metadata:
    name: authentik
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTDJCQ3JXblVlRWJSQStD
            azhIREk4cnBRSHkyQ2dpL3FFSzAxcmNTdVRjClRkYzVPZWIxTkNIcVN6a1RpNlg0
            dGtwVlg4VGJrTVVjVXkxV0JuQjNlbE0KLS0tIE1Xd1ZnK01JbFZjakVPbXJWdGli
            VTN5QmZwbTdlUW5FVnR0YkJEb0kyZGMKCDe9DwZkxCJRlo5D5B9VyTsLEifnG+iE
            ygUO/zhq/07P2Sjtcoc7qDoXQpWy/6wlilKSzInMo3RqvphCbXKBqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T21:44:58Z"
    mac: ENC[AES256_GCM,data:4pucY19zGo3QnjARC7Ff5xqSTFsc62o4F88Tv8iJzU2Ms6IjsKY9SFMRFb6Ike0OJR7WoXXQYTSvDKgEH0Nww0FYEz3ljhJsuufaxmrfZDfyARX+sbLqMv1S0B6LldS+8Hmf1JRgd8ENcW/CyNlBxcGMIm45ZgcKoeH3UqbFEqI=,iv:FMQKAV7ot8QqaRrH1ijCFCJkc5mDBnsh8kaXnWTlswI=,tag:j1V6mMhzC9Z1qSP/iGUDIA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: authentik
    namespace: authentik
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://charts.goauthentik.io
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTDJCQ3JXblVlRWJSQStD
            azhIREk4cnBRSHkyQ2dpL3FFSzAxcmNTdVRjClRkYzVPZWIxTkNIcVN6a1RpNlg0
            dGtwVlg4VGJrTVVjVXkxV0JuQjNlbE0KLS0tIE1Xd1ZnK01JbFZjakVPbXJWdGli
            VTN5QmZwbTdlUW5FVnR0YkJEb0kyZGMKCDe9DwZkxCJRlo5D5B9VyTsLEifnG+iE
            ygUO/zhq/07P2Sjtcoc7qDoXQpWy/6wlilKSzInMo3RqvphCbXKBqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T21:44:58Z"
    mac: ENC[AES256_GCM,data:4pucY19zGo3QnjARC7Ff5xqSTFsc62o4F88Tv8iJzU2Ms6IjsKY9SFMRFb6Ike0OJR7WoXXQYTSvDKgEH0Nww0FYEz3ljhJsuufaxmrfZDfyARX+sbLqMv1S0B6LldS+8Hmf1JRgd8ENcW/CyNlBxcGMIm45ZgcKoeH3UqbFEqI=,iv:FMQKAV7ot8QqaRrH1ijCFCJkc5mDBnsh8kaXnWTlswI=,tag:j1V6mMhzC9Z1qSP/iGUDIA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: authentik
    namespace: authentik
spec:
    chart:
        spec:
            chart: authentik
            sourceRef:
                kind: HelmRepository
                name: authentik
            version: '*'
    interval: 1m0s
    timeout: 10m0s
    values:
        global:
            security:
                allowInsecureImages: true
            image:
                repository: ghcr.io/goauthentik/server
                tag: ""
            addPrometheusAnnotations: false
            env: []
            envFrom: []
            volumeMounts: []
            volumes: []
        blueprints:
            configMaps:
                - authentik-grafana-oauth-blueprint
                - authentik-forgejo-oauth-blueprint
        authentik:
            enabled: true
            log_level: info
            secret_key: ENC[AES256_GCM,data:2pgFHyjWlOQrqxx9M7Fz+SuaeQhgRmOnqHtZfUvQPPE4yU7+bU2aQjFA5OFoVMN/Y01Awof6sWFGGbXqs8GQEw==,iv:/RxlwiYjtZDz8AGS/Fx+/Qf0tPteBizcbWblMCzD2Hs=,tag:tHrCdjhbgC5sVw8LsV++Zg==,type:str]
            existingSecret:
                secretName: ""
            events:
                context_processors:
                    geoip: /geoip/GeoLite2-City.mmdb
                    asn: /geoip/GeoLite2-ASN.mmdb
            web:
                path: /
            email:
                host: ""
                port: ENC[AES256_GCM,data:d3aZ,iv:beLw+UC8CIUl8sqpYIrLE/BBW/QAg3Bp3JngB92cluI=,tag:rHJhAoX2vMd1lsiZiW2BhQ==,type:int]
                username: ""
                password: ""
                use_tls: ENC[AES256_GCM,data:Wltgfck=,iv:vYKnrc2EERED9wtE0Ttuok8OVYQPL9JE07gxcgayNNE=,tag:LqmzmDOgzt+J8N97lZ/LZw==,type:bool]
                use_ssl: ENC[AES256_GCM,data:DzC8xQI=,iv:JoOfUdYGhHezUl1cduww8SU+3GWKUkEzufKNUXKKtGc=,tag:Ca+5h2ruzBMC/XEyvcoAqQ==,type:bool]
                timeout: ENC[AES256_GCM,data:F6U=,iv:aJ3H28ilK0h2NvE8vg952JfULnVmWWO8Ee5B7qJo8vk=,tag:ZiAEm3eENT3P9w7IArMPxg==,type:int]
                from: ""
            outposts:
                container_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
            error_reporting:
                enabled: false
                environment: k8s
                send_pii: false
            postgresql:
                host: '{{ .Release.Name }}-postgresql'
                name: authentik
                user: authentik
                password: ENC[AES256_GCM,data:sDn8r0d4Wgcnrvj5NBrVisYuVltj7DV4zWZ4+wIWXA==,iv:SXePpZIdX0fNPcRzuGHAEj4UrFm3bCu/Cve2bDK9Zm0=,tag:CvINjGSGKxK+bHnmWxWaRg==,type:str]
                port: 5432
        server:
            enabled: true
            name: server
            replicas: 1
            env: []
            envFrom: []
            extraContainers: []
            initContainers: []
            volumeMounts: []
            volumes: []
            containerPorts:
                http: 9000
                https: 9443
                metrics: 9300
            hostNetwork: false
            service:
                annotations: {}
                labels: {}
                type: ClusterIP
                nodePortHttp: 30080
                nodePortHttps: 30443
                servicePortHttp: 80
                servicePortHttps: 443
                servicePortHttpName: http
                servicePortHttpsName: https
                loadBalancerIP: ""
                loadBalancerSourceRanges: []
                externalIPs: []
                externalTrafficPolicy: ""
                sessionAffinity: ""
                sessionAffinityConfig: {}
            metrics:
                enabled: false
                service:
                    type: ClusterIP
                    clusterIP: ""
                    annotations: {}
                    labels: {}
                    servicePort: 9300
                    portName: metrics
                serviceMonitor:
                    enabled: false
                    interval: 30s
                    scrapeTimeout: 3s
                    relabelings: []
                    metricRelabelings: []
                    selector: {}
                    scheme: ""
                    tlsConfig: {}
                    namespace: ""
                    labels: {}
                    annotations: {}
            ingress:
                enabled: true
                annotations:
                    cert-manager.io/cluster-issuer: public-issuer
                labels: {}
                ingressClassName: traefik-public
                hosts:
                    - auth.phorge.fr
                paths:
                    - '{{ .Values.authentik.web.path }}'
                pathType: Prefix
                tls:
                    - hosts:
                        - auth.phorge.fr
                      secretName: authentik-tls
                https: false
        worker:
            enabled: true
            name: worker
            replicas: 1
            env: []
            envFrom: []
            extraContainers: []
            initContainers: []
            volumeMounts: []
            volumes: []
            containerPorts:
                http: 9000
                metrics: 9300
            metrics:
                enabled: false
                service:
                    type: ClusterIP
                    clusterIP: ""
                    annotations: {}
                    labels: {}
                    servicePort: 9300
                    portName: metrics
                serviceMonitor:
                    enabled: false
                    interval: 30s
                    scrapeTimeout: 3s
                    relabelings: []
                    metricRelabelings: []
                    selector: {}
                    scheme: ""
                    tlsConfig: {}
                    namespace: ""
                    labels: {}
                    annotations: {}
        serviceAccount:
            create: ENC[AES256_GCM,data:4IrkgA==,iv:F9qHWTCOo85DLnw5hjaWM+UVq8dhmSOSN1jPLt1amKg=,tag:kDbtUAdI3vnARecH+ePaUg==,type:bool]
            annotations: {}
            serviceAccountSecret:
                enabled: ENC[AES256_GCM,data:SUcnUWs=,iv:lPAF56ZfX3618N9fSFwhbAGQHAXhO6srExqWChmWsr0=,tag:dHqyaPN1mqa78ph6Oj4miw==,type:bool]
            fullnameOverride: ENC[AES256_GCM,data:kQ1x9WOC91v7,iv:Cok+lJHroihFnTE2LzCE8DXCl1dfA1DPjNA+My6NNo0=,tag:XulpxiLReBMNOagV9S1bnQ==,type:str]
        geoip:
            enabled: false
            editionIds: GeoLite2-City GeoLite2-ASN
            updateInterval: 8
            accountId: ""
            licenseKey: ""
            existingSecret:
                secretName: ""
                accountId: account_id
                licenseKey: license_key
            image:
                repository: ghcr.io/maxmind/geoipupdate
                tag: v7.1.1
                digest: ""
                pullPolicy: IfNotPresent
            env: []
            envFrom: []
            volumeMounts: []
            resources: {}
            containerSecurityContext: {}
        prometheus:
            rules:
                enabled: false
                namespace: ""
                selector: {}
                labels: {}
                annotations: {}
                additionalRuleGroupAnnotations: {}
        postgresql:
            enabled: true
            image:
                registry: docker.io
                repository: library/postgres
                tag: 17.10-bookworm
            auth:
                username: ENC[AES256_GCM,data:kyZMCXCL5se6,iv:I3qZRz1DyxiD82D9acDdCdiSBIKZOUHC75J01fASs8U=,tag:PIcR6CJx4YnIj4wfW9MZmQ==,type:str]
                database: authentik
                password: ENC[AES256_GCM,data:MDeO4zX+lf49m1L3Ar44/GenP1tiUYCTWlHS2+6vwg==,iv:k2hX+8MMZJqC/TG+SGgP9geg0ps2WW31TyjBRhrIRX4=,tag:+if1wXnLVv3xw9AmwVfScA==,type:str]
            primary:
                args:
                    - -c
                    - config_file=/bitnami/postgresql/conf/postgresql.conf
                    - -c
                    - hba_file=/bitnami/postgresql/conf/pg_hba.conf
                configuration: |
                    listen_addresses = '*'
                    port = '5432'
                    wal_level = 'replica'
                    fsync = 'on'
                    hot_standby = 'on'
                    log_connections = 'false'
                    log_disconnections = 'false'
                    log_hostname = 'false'
                    client_min_messages = 'error'
                    include_dir = 'conf.d'
                pgHbaConfiguration: |
                    host     all             all             0.0.0.0/0               scram-sha-256
                    host     all             all             ::/0                    scram-sha-256
                    local    all             all                                     scram-sha-256
                    host     all             all        127.0.0.1/32                 scram-sha-256
                    host     all             all        ::1/128                      scram-sha-256
                extendedConfiguration: |
                    max_connections = 500
                extraEnvVars:
                    - name: POSTGRES_DB
                      value: '{{ (include "postgresql.v1.database" .) }}'
                resourcesPreset: none
                containerSecurityContext:
                    readOnlyRootFilesystem: true
                extraVolumeMounts:
                    - name: postgresql-socket
                      mountPath: /var/run/postgresql
                extraVolumes:
                    - name: postgresql-socket
                      emptyDir: {}
            readReplicas:
                resourcesPreset: none
            backup:
                resourcesPreset: none
            passwordUpdateJob:
                resourcesPreset: none
            volumePermissions:
                resourcesPreset: none
                image:
                    repository: debian
                    tag: 13-slim
            metrics:
                resourcesPreset: none
                image:
                    repository: prometheuscommunity/postgres-exporter
                    tag: v0.19.1
        redis:
            enabled: true
        additionalObjects: []
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTDJCQ3JXblVlRWJSQStD
            azhIREk4cnBRSHkyQ2dpL3FFSzAxcmNTdVRjClRkYzVPZWIxTkNIcVN6a1RpNlg0
            dGtwVlg4VGJrTVVjVXkxV0JuQjNlbE0KLS0tIE1Xd1ZnK01JbFZjakVPbXJWdGli
            VTN5QmZwbTdlUW5FVnR0YkJEb0kyZGMKCDe9DwZkxCJRlo5D5B9VyTsLEifnG+iE
            ygUO/zhq/07P2Sjtcoc7qDoXQpWy/6wlilKSzInMo3RqvphCbXKBqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T21:44:58Z"
    mac: ENC[AES256_GCM,data:4pucY19zGo3QnjARC7Ff5xqSTFsc62o4F88Tv8iJzU2Ms6IjsKY9SFMRFb6Ike0OJR7WoXXQYTSvDKgEH0Nww0FYEz3ljhJsuufaxmrfZDfyARX+sbLqMv1S0B6LldS+8Hmf1JRgd8ENcW/CyNlBxcGMIm45ZgcKoeH3UqbFEqI=,iv:FMQKAV7ot8QqaRrH1ijCFCJkc5mDBnsh8kaXnWTlswI=,tag:j1V6mMhzC9Z1qSP/iGUDIA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
