apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    secretKey: ENC[AES256_GCM,data:KXzKTFbW9iev0IKtgR8DEhrAobQ4qLXgplfy8V1M57/mmiy1lCwUJv24GD3raGlTS2fzsWK1sAC5g0h/P68aYg==,iv:zhcSykA/e2M4J3PiEtYzNDEe1+NnsizCx3zZwmNHsho=,tag:UCzKeBNQvJh/lHWC0YmYjQ==,type:str]
    postgresPassword: ENC[AES256_GCM,data:bYp9FY+N0JrL0JMPCzlFvmptqSsMvx1fzG9P2uT69w==,iv:wpvGhM87hNbWp+Ns4Bb79c2TlDghntznnG7YHR1/9vc=,tag:VZfWo2jyDglFnT38axqzVQ==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd1FwNW5wS2trQm9GMlhJ
            c3Z3NFBrNThha042NytSVGRyaXZWa3JPMzJzCnByV3RqWWZrWmVzdDgrcmcyYm9Y
            UDVoL1JaK1ZTUmI5ZUs2ZVZGYjhnY1EKLS0tIGpFcEgzaElaSlV6d1FBSHRGQWI4
            UUVzYWRXQTlJaEdZVk9yMTRUK1lVTUEKXONWbR0LkjmYIbWau10F1g0R+kmjoPfT
            OmUgWQqX7Vty0WMoOaPoVFgz0U7RJPtFUdZSI0EuoYWS7defc5NJlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T16:29:04Z"
    mac: ENC[AES256_GCM,data:tJSdzXDUUVpbf05Njh0uxoI4NNyMfQzmh8upbqvNERFLQ0XHuR4uDLX016zGIA46mzxduw3KH8O4nfvbuwbheezIdUKISNr62s9r1w0W9VZubzhBJZhuooEETkwNyfRlkXXMN7LBXuiNnUomaojHMYGqn3hON1/MfS8lMabwxyg=,iv:rvKHlCzkRMRXk2mvw2XtpwUA0a2t5SiEJmHiT7xD/7M=,tag:ToesjWxCxhT+RrDqkOfImg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
