apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    secretKey: ENC[AES256_GCM,data:x3lQYSGgSsHvokDOaTsPAoYLTN8HOTkcLG9j44KIzd4yNW+aEBGKZ81vEggTqDBXg7p9lKNsP76nn/E9F2GzNw==,iv:gfu5eTjn5Vr7PEPqKMdrfT5bhzbajgAggrS3b+Gxm4A=,tag:lXRhyZelucO853ZsClOLgQ==,type:str]
    postgresPassword: ENC[AES256_GCM,data:Hkd26D4hPlXn1Ni8G7SQBY6QN42FoZ+hXLVzpwq4AA==,iv:NlYydH2tD2MdYrlLW3oHtch2MiG80qFREn4IjuP9odg=,tag:6sh2eMi2p7NKQ/aRwcQUEg==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaThLa2lFV0VEdEVOUk5E
            SHBJZFVQRGx0b01udU1wajhSMzJFWHNmTmo4CnRFL3RmM3pvR3MrWWtxZExrV1A0
            d25lWHhlbFV0b0lWd1dMV0FZamwxVGMKLS0tIFJOQUdjeG9SV01lS2hNc3NUcEhL
            aUJaekppaml2UnlQYkN1RVpCdEFudkkKoHB9/DzY1v2x+gE3dPmcEUV5v2kLK9l2
            dUyoRWRynGMDzqTGEyfOb2N74pmnU8/huwgsW7eXBoeYJ1A1okSm2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T15:27:00Z"
    mac: ENC[AES256_GCM,data:loCvWDdJTm/nxHQyn7dGDuXwf/uJHth+RHBe/33qtPlTqetOdqRLoFojWup2t0CpVriutfEyFaZ6VB0aXee/hRQ+vr11jhnapAKRjhvoMNM2L96zGkgPOwXTgQj5IGBNY/uMhi1u2KIQUdpyjT9RWP27SHgJMY5X9gSmbRmVyto=,iv:xl01K4eOlbAo+xKx9Hv0IGaL0KQTANkULyO7m52vWH0=,tag:Vsjp9PjsvD6U/70Z6X1KIA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
