apiVersion: v1
kind: Secret
metadata:
    name: alloy-secrets
    namespace: alloy
type: Opaque
stringData:
    ALLOY_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:yI1/LaTAg4VRKCGOkU02MewXKkIGZaIn/FFccMKxCQ==,iv:9R89HQgm6R2TiI41i0WTtBFFNDy3F1XKGWOOAmK8y2w=,tag:oxc4mmYX/i/fvTzrTVMiqg==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMTZOSlFiL0loSnk5Tkxx
            YXNnWm0rVGNVQk8zbzZFY0JPWWxOdVU4bkZRCjVpb1NGOFl3OG1NdGs1WFg5eHZQ
            UFIyRFRlNXdIWk42d2ZseEJwVkU0VmcKLS0tIFFyems3ZVgzZHgxTVpCV3FYY0hZ
            a3ZseVU1MjBDaWhZZTI1am11U0lEbjAKHK9/olwwAVrDvC/gAvuRKnvmLz5zSLWH
            cHnm/Jk6BkpueHrPHI/8atpU+fyRRpFt5hT/CFBvshCWYqIr7i9m1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T15:27:00Z"
    mac: ENC[AES256_GCM,data:zynQO2KRGAQBQScez5Sdf03VO+n1LQgebZG6a1UsOSMT4lk8Vuyho8Q1caiEp6dcXZ1qLZvXNznUPop7O6v0mUKrXjqpe3fWJehjyMkLJ6ZHSx5MH9Trc2QP+6/dqlBPCv3tMBFb4pPbYFnPe5yKo1iS80QODPsHevTY+DX378Y=,iv:mc1EjMv6ru8EeBYPgmkehM/JwLqM7l6G6K/dL/pWKJg=,tag:dpZZ+8pFsdFt5Nkv0LvWxg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
