apiVersion: v1
kind: Secret
metadata:
    name: alloy-secrets
    namespace: alloy
type: Opaque
stringData:
    ALLOY_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:zv4W2H+Uf3iuYbVVciEzdNnH0aguUVLdQnaIytxgmg==,iv:1vvmm//urTcFmP0UnYRIFEc2x90/00bZA3L/vWoqE38=,tag:XLsdzljjh6luhFklJHm9Kw==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSnh0YVkyUGlMSERKc3dz
            QSt0NmF0T1I1bnVQa3ZxZFp1Q3FKM3NJWGh3CjdPa2pzNEl3cUpFQUI0ZERqcHo5
            UW1uMmwzcEpaT3dKY0QvMEZjUjNiNm8KLS0tIHFveDcrMFBTUzZ0YmlJb1hkczQ1
            WDhXakVSK2NFVW1GVFZVQU41dnFCMDgKC1lirKDDQnut91aPjl9tRHXy7OrDLmRo
            9INrUDdK1ghXAbstINsIDMIykxpxd0yvpYCY1D5ejN97LzMJXJI4/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T16:46:08Z"
    mac: ENC[AES256_GCM,data:yTGSEO8FPfpzrkJZs3VFm+Nylm53hrpuiADqfBJtiDv7mV1DUPk/JiRabWvRSSLV8no/50p15JXmqEHWHY/ZWbf14ActERqq7J9AE57aG4mqlWDWWvn81dIJI03vd4W/2emHA3OB87ZIar0LYYIcAvBVH0qV7jloYbvR6cMBgj0=,iv:s0lFp9/OCLIdPPREiwMjoV1pqSD7vNYsOvAfKHwvRmM=,tag:X/OfTsAvatHewVc8Zv/p/A==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
