apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
    name: core
    user: phorge-admin
spec:
    k0s:
        version: 1.36.4+k0s.0
        config:
            apiVersion: k0s.k0sproject.io/v1beta1
            kind: Cluster
            metadata:
                name: k0s
            spec:
                api:
                    k0sApiPort: 9443
                    port: 6443
                    sans:
                        - 10.2.0.4
                network:
                    provider: custom
                    kubeProxy:
                        disabled: true
                    podCIDR: 10.244.0.0/16
                    serviceCIDR: 10.96.0.0/12
                    controlPlaneLoadBalancing:
                        enabled: true
                        type: Keepalived
                        keepalived:
                            vrrpInstances:
                                - virtualIPs:
                                    - 10.2.0.4/24
                                  authPass: ENC[AES256_GCM,data:3M0DWMXBKWg=,iv:ao9rHmOa7RDj4wq1r1Yw8CUDIvuDVpoIVRCqHreL/F4=,tag:kMdcCRLlx7M211L9BMfAmg==,type:str]
                                  interface: enp1s0
                    nodeLocalLoadBalancing:
                        enabled: true
                        type: Traefik
                storage:
                    type: etcd
                    etcd:
                        extraArgs:
                            listen-peer-urls: https://0.0.0.0:2380
                            listen-client-urls: https://0.0.0.0:2379
                telemetry:
                    enabled: false
    hosts:
        - ssh:
            address: 10.2.0.1
            user: root
            port: 22
          role: controller+worker
          installFlags:
            - --disable-components=konnectivity-server
            - --kubelet-extra-args=--image-gc-high-threshold=50 --image-gc-low-threshold=45
          noTaints: true
          privateAddress: 10.2.0.1
          privateInterface: enp1s0
        - ssh:
            address: 10.2.0.2
            user: root
            port: 22
          role: controller+worker
          installFlags:
            - --disable-components=konnectivity-server
            - --kubelet-extra-args=--image-gc-high-threshold=50 --image-gc-low-threshold=45
          noTaints: true
          privateAddress: 10.2.0.2
          privateInterface: enp1s0
        - ssh:
            address: 10.2.0.3
            user: root
            port: 22
          role: controller+worker
          installFlags:
            - --disable-components=konnectivity-server
            - --kubelet-extra-args=--image-gc-high-threshold=50 --image-gc-low-threshold=45
          noTaints: true
          privateAddress: 10.2.0.3
          privateInterface: enp1s0
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOVNJOE9vUDZyLzduaHgv
            M2xneXhhTWxxVUFjSXZLaHpVRmZjTXpZTG53CjhaSUJrZ3pYOFpLRjRpUklkNUVR
            cThzMWJVa0g4MjNSVCtXU3VKdGxFbXcKLS0tIC9DMzRVZ25TY1RVRWZnWlR6SXBF
            Z1kvWjZXNGlxMXlNTGFIaFBYVkRSak0KuqVaA9diLS+BYdt44I6aGgv0HDHEW7LK
            aEmZ95cVcinNlWckkowhPCQQlPY/VjdNrbBJLjweSEv0yeQdYBNj8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T13:36:56Z"
    mac: ENC[AES256_GCM,data:vPsp7O3CORi5p4FS5mLbhnSfOhiMe4sg7+O93IoQ5Tr/BKU+f7NKn0jNxGg+RXgMMnX0OQ26IJ5dMW7StsROyy0Nhry/l/AGjJLOxO3jDVZ3QXOQsIaisKaM+vaWC69BHpCKJ5UFEODtjWahlAvJhNkjfY3IWRx1OyGHTj4a5/I=,iv:2XFCHr8IFpzKXnpLGIXG5LbN534J9fdjM6yDrrUiJ8M=,tag:FZufDge2jMdmORFBopZjvQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
