apiVersion: v1
kind: Secret
metadata:
    name: incus-client-config
    namespace: crossplane-system
type: Opaque
stringData:
    client.crt: ENC[AES256_GCM,data:UNBE+yNk86I3P0qrQuFxTkmQy2cEEnZ+yZbcgr5ucd5dFtMeeHCDpnMCsVi3tubTCJVZoQOjEJly6HQ8q8hicbUn92e+mySL3hkSEp4vj08D+ey/7P/H6nYJopVWtaV+j1vAepHg6kVIn9qzl9zhGXe+kpdPHwTqoxhk1+WX7UvkA5pvTedbdjIARBbiedCXdyTJin5OSeSoKFGCvS/MnYgOsB+v7ag9aWvhI9OOAPL5axo85Funh51NFQn/Mve6G/fNMmPT+G9A57ISxalXOwWo/IOvuK3diHFQ3u+/+LYy8/FXpC0QFMCxCitfNaT2Axb/mley/B9Y8h4YtrsGOdkm5OCWkL/U1HLriVudJhaD6n/D8t0jMLke1aYR8ryfNUUBidVBwbZnm9NCDAaI3wWdy0/NcB8B+sBIrUDUdpbF3SfRW1lIGgi60gngr77OMsactL6BIQxF96kdau8IcL9ppvrnhxieL8nlkZLJ4e+uyd94nonYMOF4HHU26JGbCyVVvZJj0MESMAxz9yi1q21tLn9BQWQX3KOBAWZJvukgxWOEtgwjiltDOmRmSJIFVY9Asv9ju0GdGDKg1htj3yiCdbUyV+OcpjGNzJhYF9KLQ8sRbyQmO3g4GKGpZGNYy2iCgAjU3SYQ7SiIkIyLdjRO8IjWJmlSzgG1BBaCkMkbUytQ+rYibdSoVCDegcohoIotNw7CpZtS9xpq3mIxg7P7GJ3v3Renc8YamuJZLL3iPkdvf/GKg1p/b6Lb9xAr5O1IzjDguRhYXtuU++wD1vPu1n/TGbfHWaBM17gGTnROZgMrwm/bmLFwabeDU26Z6Gko59J05lpCq3UlQV7RduKs/VYveeHYFoYF9KBh/j2vOkDvSbSEeYPDd//BhTzYgVuowt1E9RE=,iv:0W16YDvEo+7Hza79PPZZ/EGh/QFfWFRBC1LuPk+XJts=,tag:sGTuSRCWXw3qN32rO4rtjQ==,type:str]
    client.key: ENC[AES256_GCM,data:t6sKPjoOQm6C9qfpnJC675+5TboGFvM6Mm7jWmnRdrSthDzHtHJAkUZt78m51U2lWe3Pe9jHg6SLlVLzBTvquOk+wMG3U7Nk8By3BCFT771eJclVf5o6/hhye9M4PdZhVEYKKOV9nuTWg198BQjygIM2s70e6JDFLWJfG2c6ym2xTtu18Qh6mwSwbaS6m2iQnsQnR/PPhetRWxA81wAn8134tDSGoRcjFGsOQnOfBlSv3IVGcdpl+jVPu/gtE4CA1IL41cwvgnBwQpGxlLPGb1ndj5sh0BkiB+LuXuYGpF66hg76UPujyO7WHkKdxGZST00U5Z0YM5M2HOYarKOrBvqCzVfEcE/MDzLzfiZjeq1DkiMdeP9rdoT5038wiHRhl+SE+Atw5IHSiW4da+zPmgU6,iv:YtGRABo/644So8Pj6KGJJDm9jcAxoXV3xmclRpapmFQ=,tag:OFSf5eZ2wfaDLcSwLR9OlQ==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SUdrakp0MHhVMUNzQ0M2
            c0Z5ekVJdDBkelhJVWVOTy9qNDdGdDJRS1RNClFWMGgvbUNKcEt3RTVDelVxZUR6
            ZThvNWFVZ084V3RVWXZvTzRxVUpoMFkKLS0tIFd3Ym1Mc1drOEE4U0RVS0kwUWh4
            NTZCYUQ2OTAzS1Z0anNlSnhkNHl6bzgKcDWAQ0fTgNJuiKs+X+3MbJoYXxF5WPWv
            0d5+jZopFaof6Xr7ZIXvTNi/fRoUbPWDfObxoMYN78yWh8k+OXEgQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T18:35:06Z"
    mac: ENC[AES256_GCM,data:wVYfwT6pdiA/cj+coc/9dJDG9WVR0bk7L7r4Z6fvTqtyZwZ7rKWNw5ZBWX1lTEoAUAiJ7RJvolC0W5bdDBmIWxxBsnKnbtcpXQYM75S7b+McfuxgyYDPnROph+FwLvh1YFUTXECxvXl6wXK+cekJZqvqchpat4UNflvzkdpKl30=,iv:7+Z4JzgCV7gkluDXGrgAXbGohCMufl3Atp+Zskq4AHA=,tag:nmUD+3vj70Nl/t1ui+kCWw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
    name: iaas-provider
spec:
    package: xpkg.upbound.io/upbound/provider-opentofu:v1.0.3
    runtimeConfigRef:
        name: iaas-provider-config
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SUdrakp0MHhVMUNzQ0M2
            c0Z5ekVJdDBkelhJVWVOTy9qNDdGdDJRS1RNClFWMGgvbUNKcEt3RTVDelVxZUR6
            ZThvNWFVZ084V3RVWXZvTzRxVUpoMFkKLS0tIFd3Ym1Mc1drOEE4U0RVS0kwUWh4
            NTZCYUQ2OTAzS1Z0anNlSnhkNHl6bzgKcDWAQ0fTgNJuiKs+X+3MbJoYXxF5WPWv
            0d5+jZopFaof6Xr7ZIXvTNi/fRoUbPWDfObxoMYN78yWh8k+OXEgQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T18:35:06Z"
    mac: ENC[AES256_GCM,data:wVYfwT6pdiA/cj+coc/9dJDG9WVR0bk7L7r4Z6fvTqtyZwZ7rKWNw5ZBWX1lTEoAUAiJ7RJvolC0W5bdDBmIWxxBsnKnbtcpXQYM75S7b+McfuxgyYDPnROph+FwLvh1YFUTXECxvXl6wXK+cekJZqvqchpat4UNflvzkdpKl30=,iv:7+Z4JzgCV7gkluDXGrgAXbGohCMufl3Atp+Zskq4AHA=,tag:nmUD+3vj70Nl/t1ui+kCWw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
    name: iaas-provider-config
spec:
    deploymentTemplate:
        spec:
            selector: {}
            replicas: 1
            template:
                spec:
                    volumes:
                        - name: incus-config
                          secret:
                            secretName: ENC[AES256_GCM,data:bTTYJzLjqKqyQT7zjylZlK7+ug==,iv:/H+sai3JBM6wwPwhrnL+jvJUZA+6aFOFavDoSRfz7LE=,tag:RD5UH9cVFRYrsOYta8zx4Q==,type:str]
                    containers:
                        - name: package-runtime
                          # securityContext:
                          #   runAsUser: 0
                          #   runAsNonRoot: false
                          # command:
                          #   - sh
                          #   - -c
                          #   - |
                          #     apk add --no-cache \
                          #       --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community \
                          #       incus-client &&
                          #     crossplane-opentofu-provider
                          volumeMounts:
                            - name: incus-config
                              mountPath: /root/.config/incus
                              readOnly: false
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SUdrakp0MHhVMUNzQ0M2
            c0Z5ekVJdDBkelhJVWVOTy9qNDdGdDJRS1RNClFWMGgvbUNKcEt3RTVDelVxZUR6
            ZThvNWFVZ084V3RVWXZvTzRxVUpoMFkKLS0tIFd3Ym1Mc1drOEE4U0RVS0kwUWh4
            NTZCYUQ2OTAzS1Z0anNlSnhkNHl6bzgKcDWAQ0fTgNJuiKs+X+3MbJoYXxF5WPWv
            0d5+jZopFaof6Xr7ZIXvTNi/fRoUbPWDfObxoMYN78yWh8k+OXEgQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T18:35:06Z"
    mac: ENC[AES256_GCM,data:wVYfwT6pdiA/cj+coc/9dJDG9WVR0bk7L7r4Z6fvTqtyZwZ7rKWNw5ZBWX1lTEoAUAiJ7RJvolC0W5bdDBmIWxxBsnKnbtcpXQYM75S7b+McfuxgyYDPnROph+FwLvh1YFUTXECxvXl6wXK+cekJZqvqchpat4UNflvzkdpKl30=,iv:7+Z4JzgCV7gkluDXGrgAXbGohCMufl3Atp+Zskq4AHA=,tag:nmUD+3vj70Nl/t1ui+kCWw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
