apiVersion: v1
kind: Secret
metadata:
    name: incus-client-config
    namespace: crossplane-system
type: Opaque
stringData:
    client.crt: ENC[AES256_GCM,data:TsZoDZZa0+mZs+RX5ZekzELnoj4qA8cLhtw/m4bibSiuZdlsSqtII0PMXgVnLkJGY23fNh4rAd58D7aWY2K2Y1t+49cChWtZvMAwHlhd9pQAcuBlhPlTzEKpkl3zBBK1U/CpzsYthwXocuB8DkrYNflbBbMisxx+4jDQQi+IX7At6XFVnt3dBRK713IKLZ79m+pDuic+HWqfdhNkbwKV0II9oaXQZIjHpZ77y53HDLBr/SuU29fTUdx0qFfmWB8KM+VwsPPYIgT1H5NfUn3i+KydL0H7f+ntSTfdhDOy57N45+OEPnSVNWBF5CtiBpzfyn5LISpvllaH82IHc/2KIquWaJ3zASotAnYGnw9yivm1XEUWmTp8iexC5HtWJX1Ha8w0WbO1jAxixI9K2ovnsunYb9na4DdUPZwGYpCtUSYLdfe4ByV8P4/NSgy7b1gWhOMZkQS6CDqiOvZb4PYakRwAijnNq9j4IjD0LhBLt1tktyxTKocr20dzna1X2vnlHTye+7Pv/8oC1BMapX5fK0F/MjBNqgyLUJaGW0B+4tlKkro4zcHqDECNNHqo63DeO3n30mfw9OmZf9KcG/NVjE1K2x4Jq/qCwqywfmixDj3imHsPqRzYGdk/WyB/qvrbDhXAIESYjfbmNwEmWYzDL53QFtYUe0sq7X5UKAQ0xRukkiw+J0piXxm6F8w3AMK0iG6c8oYPv1x0XE3poz9AcBuYeZvO2YinwIz3EDAC/X5IX01LHO/YgZmuR1HxYd94LLH07fUWce0lMNi59cYz7tewbvD7sF8MjBZqaUsYHXYo3vMNUCPA6cblH3H37zydN14UCieGDFj2JmQST50C+Ghde4FM9LEd65mMSzYJ1ebAxg5KOuQdCI9lp6ly0X8E25PLyV2pNkw=,iv:kl/ncaAFfOKk0vBoa8TYFJ83aBusUVh1K7j8QFcimBo=,tag:xbDhuTBz2KNAkEhr0JEmNg==,type:str]
    client.key: ENC[AES256_GCM,data:rRTP8is1fmxD5cpi5Zb5PKClL23YaTOCVii6AfS7SOhl1QdhzbpLJSLc0sx1+xKeTlFD/ejT0+qA9QJgvGQdQ8OvdarWKNVIKUVZwaW0aRN0jjds92yw9zXOtncDf3C4Ee5fWKMYZFwF0lCnXMuxHj7t2zO3r+F7QvAHIU2uYeHVWer4LnD7TieW3bsku7eDi5L4Kt3+4Si8/QuIaoJv5zpR/IxDnJEimg0U3V2s5dnbROL6kvJPQ4rfZjkLnZAebZXDKhVCVbWYkEu/kzis6wMkCgnURE332lHqAULMYiFthukUGCh2JTHBMRm1SNf8Vnl1JQx4ULy1L1gQJDqNJ4aC4gJjsQsRtv8E2PKznZEHnP/Vazgv4dRKlIowOrHC0ng0ujE4I3CYhR3/5vOckLok,iv:q+mMNwSggDp/MUYYzuetbDT+KPrLMybf8FrNnmwERHc=,tag:tuSePVFEs892obgf23OoDw==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSCs3d0dIRmJoK3hLbWRW
            ckcwSXpRVjN1RGlOM3MzczJLeDhobW5xRURnCjZXWWJZRWEyb1kwZW5JdzRsMkta
            SGNQNU54QkVieUJpb2RUTVpYalkvWmsKLS0tIE8vUmtZRmdWT2FVZ3Y1N0lnUm9x
            UEQ4M2tSSndIMTFIYi85S1BEWXJHZzgKHC+ZWAaKwdWHQEByqurQMtEaAFFrgV9e
            fkAaD0xZwcsCitBNmt4xt7sDaduXi1bQeFe+lz+UkjZTj/nz4WgPPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:13:12Z"
    mac: ENC[AES256_GCM,data:Eg9Ff0n0WYnRIljtt3LF7IV0d98U+UqlhFWN49r/AHJpjE2d3hN4qz0RrgWUwUJTlQBfLVcYjeRibIxmQ3VQNZFfxUJsW6W7F4sh+3rNci/Ss/2CS8ucLQ1wNthGWU7it1G+IfcCYFDjp7G2Yl+2eXZbW+MzzRD1wl0W9qo3i5o=,iv:hndqx8je38DYRGFyvJK/vwywjY8GoTdk2f904dXRAsk=,tag:w1k+5GNkqy5P1pc6S0f6jA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
    name: iaas-provider
spec:
    package: xpkg.upbound.io/upbound/provider-opentofu:v1.0.3
    runtimeConfigRef:
        name: iaas-provider-config
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSCs3d0dIRmJoK3hLbWRW
            ckcwSXpRVjN1RGlOM3MzczJLeDhobW5xRURnCjZXWWJZRWEyb1kwZW5JdzRsMkta
            SGNQNU54QkVieUJpb2RUTVpYalkvWmsKLS0tIE8vUmtZRmdWT2FVZ3Y1N0lnUm9x
            UEQ4M2tSSndIMTFIYi85S1BEWXJHZzgKHC+ZWAaKwdWHQEByqurQMtEaAFFrgV9e
            fkAaD0xZwcsCitBNmt4xt7sDaduXi1bQeFe+lz+UkjZTj/nz4WgPPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:13:12Z"
    mac: ENC[AES256_GCM,data:Eg9Ff0n0WYnRIljtt3LF7IV0d98U+UqlhFWN49r/AHJpjE2d3hN4qz0RrgWUwUJTlQBfLVcYjeRibIxmQ3VQNZFfxUJsW6W7F4sh+3rNci/Ss/2CS8ucLQ1wNthGWU7it1G+IfcCYFDjp7G2Yl+2eXZbW+MzzRD1wl0W9qo3i5o=,iv:hndqx8je38DYRGFyvJK/vwywjY8GoTdk2f904dXRAsk=,tag:w1k+5GNkqy5P1pc6S0f6jA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
    name: iaas-provider-config
spec:
    deploymentTemplate:
        spec:
            selector: {}
            replicas: 1
            template:
                spec:
                    volumes:
                        - name: incus-config
                          secret:
                            secretName: ENC[AES256_GCM,data:BhIxxk8U5eA3v7vwXcgxtd4lYQ==,iv:csEgD9IdOUbWlry3XLjorrksGO2nhM0YfbsIhG0XGXk=,tag:BPvaNTrmWE+TP7bZVfJyZg==,type:str]
                    containers:
                        - name: package-runtime
                          command:
                            - sh
                            - -c
                            - |
                              mkdir -p /tofu/config/incus \
                              && cp -L /tmp/credentials/* /tofu/config/incus/ \
                              && crossplane-opentofu-provider
                          volumeMounts:
                            - name: incus-config
                              mountPath: /tmp/credentials
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSCs3d0dIRmJoK3hLbWRW
            ckcwSXpRVjN1RGlOM3MzczJLeDhobW5xRURnCjZXWWJZRWEyb1kwZW5JdzRsMkta
            SGNQNU54QkVieUJpb2RUTVpYalkvWmsKLS0tIE8vUmtZRmdWT2FVZ3Y1N0lnUm9x
            UEQ4M2tSSndIMTFIYi85S1BEWXJHZzgKHC+ZWAaKwdWHQEByqurQMtEaAFFrgV9e
            fkAaD0xZwcsCitBNmt4xt7sDaduXi1bQeFe+lz+UkjZTj/nz4WgPPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:13:12Z"
    mac: ENC[AES256_GCM,data:Eg9Ff0n0WYnRIljtt3LF7IV0d98U+UqlhFWN49r/AHJpjE2d3hN4qz0RrgWUwUJTlQBfLVcYjeRibIxmQ3VQNZFfxUJsW6W7F4sh+3rNci/Ss/2CS8ucLQ1wNthGWU7it1G+IfcCYFDjp7G2Yl+2eXZbW+MzzRD1wl0W9qo3i5o=,iv:hndqx8je38DYRGFyvJK/vwywjY8GoTdk2f904dXRAsk=,tag:w1k+5GNkqy5P1pc6S0f6jA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
