apiVersion: v1
kind: Secret
metadata:
    name: incus-client-config
    namespace: crossplane-system
type: Opaque
stringData:
    client.crt: ENC[AES256_GCM,data:FFST8tx/SN0LKL4z0QChoPPaiLSIAJYtyFTkVbwgZhFMicL1ZAuIdvxKtix1MSKuMiKTW7sSyckdtFGyltcAAUvO5WMUfpaBmkCaoOqn8EYxWkpdCnOLO68Sjcw43crGHN2d2yB8963+jF0kZgXEvqUoWs4mV6YrQ11wsQnLzHOvdRoeeCeRXFxmZtHP4KPF9NzlmMEaYYsQhtt3UyOpz5obXCsWXWKE9xm0FYZfIGJ4VakO1GgJX6yBLWSE6j8IWimtM5Zh/jAfoKrOdBFzk5Q3+7ARWuRnJkOpbwwCxvDyDj+pL+W1nE+Tl8HYridJv9Yq/a1LvtjBNhSNdQyZNQTt7bmgKOYN3JaH9wJJDUPywlfqCUAw7FP+lej8QVLwlNW1Kx3j12KFC6G2f0ZTNjw7lI6UiprL0egr3UN0hR2ZUq5W8i4pnwFCi7GdrZqRercAH8sXyG/zGnqQc8YBrhBKHfpY+H2fnZqJ5otrYlFCOcFVnpEv3J+2lMp1ZGvPrhkMtRGBND+IN5MQbofpiUb7Vcg5yPM6rWE5d1h0spCYPFrx0ICOQnjqbPe4aKpMED4v/OsHTkBp/QlIiVNrPmgjgsMP2biKJl4LSsn6NRoKvfqRg0BNTz676DSpaeBYtVAb6mAWS53ZzWFH9kyM67w6exJCQWGE3v9DRI5n5j66x8Q4XLy1po62EyymROQn3n2tl8XX7YA27Y5YDhBvjlK5UWasOrvocRYIwlWJ/hDVhT/bt/Z95V1T4elRJpm6gcQp4v0oBw7rZ2bAVaNMa30fAa4yO4nvtTV2N7Srqhdz4XHiJwRz3BPEpO9O7do3DfvOnOT1qfB2Aie7Qzsc6fseWZGMM0D/bh2arGbSR/ZU0DkBfu+lXX8N71xChwVimu8szkPloZA=,iv:4ceKu5LpVnnko/JMIvawcY9cleOGXQvpaLExG3XyP1k=,tag:7w3dtGL+zVNVL0+UGq6ANA==,type:str]
    client.key: ENC[AES256_GCM,data:3xZRM3wmV5MvHoeoI+hreJBtr+8SgaP6xVAnr6RYhZb6vPQZwxjBXQYoGlhvGN76Z/I+ehwkGgJ7ovUaMw5Nzq+/dKI5s7MTlzxWoQhy30Zx3o/Kdl6yEdUX7o65XWRkxAojnzylaNTGffHYSmk+zto7Jod/xfB74fNa2pNwZF9uaeACBqZKTWI+uaXoNRs29bbeRSjBvpCwZh8cJKTwwEvRbKBKwCF/UOSOJ4rL7Kaw9uzpCt8074Z+VIqDhN/WNM9WBEUMCjBm//9r7rvlSTixtKPHv/Sx+Bu/EwmBT3UTnp9ZiuGJ03rKtTSGU7gVhNkKmSFKK0PQmNS6A498n7nlLq0SB0dENcAkMN/sQOsli+XKzzN7mPyXyUKJ89ZKynFUjstGzYinZM4V8zgzu8Mz,iv:+Aqy6gb8fmldycxmj5Y6W+qoKn4zpEIyJKnd5d3p9/g=,tag:vhPWhHkoULq4klk9+iAjKw==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK2ZOYXZHclo2S1YrR1Qz
            MHh4Qm41YUsreFRiQUdrUFV1NkUxekJ4elMwClpnZzk1TjRxRU9rZlJHeEw5T2lo
            RWdJZkd2WkgveXoxcy9lOWFnV2RUbjAKLS0tIDdWUUVtOWxwRm5oUmh0LytWTU9X
            N0M2MEV4bis2b0IvNjkvT2tVMUJhR0kKf2tgmV6rBkqcU4pdROlEIUVUzatp3QIu
            09KbCW9la5+CwA/hq2HiJZOwiSnFN7SakVR5fVbe0gfiPIkI6HZm4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T22:30:59Z"
    mac: ENC[AES256_GCM,data:uSs9FJY35RoZPGhIMV1fw2m24tGcXdau824LC3m9D/IbMqPJC/1rMGv9I/ujkkJvODwfNGR6DTGxpEFUhOPNdO7phkisgyWU7y61C++D8RoxV0MeLtUvZojmuZxtCRax0UojR1m0tqdrqfsP9alZJugIG4FvUlSiByaSPOQ7VQU=,iv:ev/v4aze+wYfJdK8TmdKR2+SUhNCCsP8TZc4GdhNtHM=,tag:MpY9bS0mBkCy10e3ylxSsA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
    name: iaas-provider
spec:
    package: xpkg.upbound.io/upbound/provider-opentofu:v1.0.3
    runtimeConfigRef:
        name: iaas-provider-config
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK2ZOYXZHclo2S1YrR1Qz
            MHh4Qm41YUsreFRiQUdrUFV1NkUxekJ4elMwClpnZzk1TjRxRU9rZlJHeEw5T2lo
            RWdJZkd2WkgveXoxcy9lOWFnV2RUbjAKLS0tIDdWUUVtOWxwRm5oUmh0LytWTU9X
            N0M2MEV4bis2b0IvNjkvT2tVMUJhR0kKf2tgmV6rBkqcU4pdROlEIUVUzatp3QIu
            09KbCW9la5+CwA/hq2HiJZOwiSnFN7SakVR5fVbe0gfiPIkI6HZm4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T22:30:59Z"
    mac: ENC[AES256_GCM,data:uSs9FJY35RoZPGhIMV1fw2m24tGcXdau824LC3m9D/IbMqPJC/1rMGv9I/ujkkJvODwfNGR6DTGxpEFUhOPNdO7phkisgyWU7y61C++D8RoxV0MeLtUvZojmuZxtCRax0UojR1m0tqdrqfsP9alZJugIG4FvUlSiByaSPOQ7VQU=,iv:ev/v4aze+wYfJdK8TmdKR2+SUhNCCsP8TZc4GdhNtHM=,tag:MpY9bS0mBkCy10e3ylxSsA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
    name: iaas-provider-config
spec:
    deploymentTemplate:
        spec:
            selector: {}
            replicas: 1
            template:
                spec:
                    volumes:
                        - name: incus-config
                          secret:
                            secretName: ENC[AES256_GCM,data:Vo5KYYFuqDcNnsOmoLzExeLj/Q==,iv:GS+TPU7XmC+Jq9kurZeWFPdowPmeycMJOujFzeYrulE=,tag:Ps9hK9cp+TYiWj/859Hwqw==,type:str]
                    containers:
                        - name: package-runtime
                          command:
                            - sh
                            - -c
                            - |
                              mkdir -p /tofu/config/incus \
                              && cp -L /tmp/credentials/* /tofu/config/incus/ \
                              && crossplane-opentofu-provider
                          volumeMounts:
                            - name: incus-config
                              mountPath: /tmp/credentials
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK2ZOYXZHclo2S1YrR1Qz
            MHh4Qm41YUsreFRiQUdrUFV1NkUxekJ4elMwClpnZzk1TjRxRU9rZlJHeEw5T2lo
            RWdJZkd2WkgveXoxcy9lOWFnV2RUbjAKLS0tIDdWUUVtOWxwRm5oUmh0LytWTU9X
            N0M2MEV4bis2b0IvNjkvT2tVMUJhR0kKf2tgmV6rBkqcU4pdROlEIUVUzatp3QIu
            09KbCW9la5+CwA/hq2HiJZOwiSnFN7SakVR5fVbe0gfiPIkI6HZm4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T22:30:59Z"
    mac: ENC[AES256_GCM,data:uSs9FJY35RoZPGhIMV1fw2m24tGcXdau824LC3m9D/IbMqPJC/1rMGv9I/ujkkJvODwfNGR6DTGxpEFUhOPNdO7phkisgyWU7y61C++D8RoxV0MeLtUvZojmuZxtCRax0UojR1m0tqdrqfsP9alZJugIG4FvUlSiByaSPOQ7VQU=,iv:ev/v4aze+wYfJdK8TmdKR2+SUhNCCsP8TZc4GdhNtHM=,tag:MpY9bS0mBkCy10e3ylxSsA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: opentofu.upbound.io/v1beta1
kind: ProviderConfig
metadata:
    name: iaas
spec:
    configuration: |
        terraform {
          required_providers {
            incus = {
              source = "lxc/incus"
              version = "1.0.2"
            }
          }
          backend "kubernetes" {
            secret_suffix     = "providerconfig-default"
            namespace         = "crossplane-system"
            in_cluster_config = true
          }
        }

        provider "incus" {
          accept_remote_certificate = true
          default_remote            = "iaas"
          config_dir                = "/tofu/config/incus"
          remote {
            name    = "iaas"
            address = "https://iaas.phorge.fr:443"
          }
        }
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK2ZOYXZHclo2S1YrR1Qz
            MHh4Qm41YUsreFRiQUdrUFV1NkUxekJ4elMwClpnZzk1TjRxRU9rZlJHeEw5T2lo
            RWdJZkd2WkgveXoxcy9lOWFnV2RUbjAKLS0tIDdWUUVtOWxwRm5oUmh0LytWTU9X
            N0M2MEV4bis2b0IvNjkvT2tVMUJhR0kKf2tgmV6rBkqcU4pdROlEIUVUzatp3QIu
            09KbCW9la5+CwA/hq2HiJZOwiSnFN7SakVR5fVbe0gfiPIkI6HZm4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T22:30:59Z"
    mac: ENC[AES256_GCM,data:uSs9FJY35RoZPGhIMV1fw2m24tGcXdau824LC3m9D/IbMqPJC/1rMGv9I/ujkkJvODwfNGR6DTGxpEFUhOPNdO7phkisgyWU7y61C++D8RoxV0MeLtUvZojmuZxtCRax0UojR1m0tqdrqfsP9alZJugIG4FvUlSiByaSPOQ7VQU=,iv:ev/v4aze+wYfJdK8TmdKR2+SUhNCCsP8TZc4GdhNtHM=,tag:MpY9bS0mBkCy10e3ylxSsA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
