apiVersion: iaas.phorge.fr/v1alpha1
kind: Project
metadata:
    name: phorge
spec:
    name: Phorge
    description: Main project for Phorge instances
    config:
        features.images: "true"
        features.networks: "true"
        features.networks.zones: "false"
        features.profiles: "true"
        features.storage.volumes: "true"
        restricted: "true"
        restricted.cluster.target: allow
        restricted.networks.uplinks: UPLINK
        restricted.snapshots: allow
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveTFtcnJZdDZQcExwQzFY
            RkIwK0ZJVENSZkFQditib2VBRFlBVEs2QVhVCllEL21zQTJ3YkFMdTkycU5DVXNT
            OGVtN0NRbVdITWN1dDd4VkUwZit1eFUKLS0tIFM5WnB4Z0NxK2dNdjdVV3FKU3ZD
            aXoybjVHSW1BYjNIL3JUQ0g3UUxFcUUKWB+nnhQwcneMcl6vF0OlaSdz0dLpNCs9
            JPYVAoU9i7geyRTEaXBPQeo0ZDfGBKYQOeSW+uJxtKI4yAbJnje/fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T21:26:06Z"
    mac: ENC[AES256_GCM,data:kL+QMlOMxQAETNgYSCXgdZsQ0AdiYzk2h/Hn/AeM4llaRcrmc7IhizhHi+sIQu0IBrRATyMdY0j6v4foiNR6uaZoOLr5nahDFov0XggZNaqQgYxvQ7hUyPURnSule5zMGQ5vFpu3iUS30vi78AzBGnVotNx75TK//X+BaMC65p4=,iv:l6zskJK7vTR7ja4vbCQ7+fLRyqdu8wNvBS+h203CJMM=,tag:9Vq1SX2e4Wv+rJWaqftsLA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: iaas.phorge.fr/v1alpha1
kind: Network
metadata:
    name: main
spec:
    name: Main
    type: ovn
    project: Phorge
    config:
        ipv4.address: 10.215.12.1/24
        ipv6.address: none
        ipv4.nat: "true"
        ipv6.nat: "false"
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveTFtcnJZdDZQcExwQzFY
            RkIwK0ZJVENSZkFQditib2VBRFlBVEs2QVhVCllEL21zQTJ3YkFMdTkycU5DVXNT
            OGVtN0NRbVdITWN1dDd4VkUwZit1eFUKLS0tIFM5WnB4Z0NxK2dNdjdVV3FKU3ZD
            aXoybjVHSW1BYjNIL3JUQ0g3UUxFcUUKWB+nnhQwcneMcl6vF0OlaSdz0dLpNCs9
            JPYVAoU9i7geyRTEaXBPQeo0ZDfGBKYQOeSW+uJxtKI4yAbJnje/fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T21:26:06Z"
    mac: ENC[AES256_GCM,data:kL+QMlOMxQAETNgYSCXgdZsQ0AdiYzk2h/Hn/AeM4llaRcrmc7IhizhHi+sIQu0IBrRATyMdY0j6v4foiNR6uaZoOLr5nahDFov0XggZNaqQgYxvQ7hUyPURnSule5zMGQ5vFpu3iUS30vi78AzBGnVotNx75TK//X+BaMC65p4=,iv:l6zskJK7vTR7ja4vbCQ7+fLRyqdu8wNvBS+h203CJMM=,tag:9Vq1SX2e4Wv+rJWaqftsLA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: iaas.phorge.fr/v1alpha1
kind: Instance
metadata:
    name: gitea-runner-0
spec:
    name: gitea-runner-0
    image: images:alpine/3.23/cloud
    description: Gitea runner instance
    project: Phorge
    type: virtual-machine
    running: true
    config:
        limits.cpu: "2"
        limits.memory: 2048MiB
        security.secureboot: "false"
        cloud-init.user-data: ENC[AES256_GCM,data:EqmCBj1XjRChb56s/mGFYhG2tgZQP9wFkScqfoUwnCujC1shy6XrdYymgZWxaLmgJx0yOovA/L7MkZ97ui7z7SAlEHG3hofiO01tuk2vaYlzkXhjKvH89NwOlb/bXYzTZTh0WUMOsLGhf9K5PvlCfYFuocA6u0cdtrNef3NwCAPDIM7OQgzl3ZIgY4zsQXlhEdFUbO7J+4k15vCEPduDm6nYdzdL0yRiNjLZB7DnnW70gr4YpDM5YUrBs2q4i5HdJZzi8AVaO9GMoER9BGH9/HNthMO0qyBZITeH6ozDjWzOZmMZh3B8t5iy7VQCrcG9sqcf831Uf8GGeCK1recniE44nG2mRQHlnaVxhQs8Sl0u+yBr0vYBYyZ54mr90PHMxyvF2GxbXY9lt2xGkcbLYNvxIzk2YHrrb9mOLr3kxPrmg6HPFgskrJ6vsyqWbh7lzSHDECHyb2/NMQuozr/8lrRgkkF1dztINk7Dy3A4KrtH638TA2JeHMH091ohirzb7MSBdKKwZ/E/YrmVJHfsFUqDq3rxZFLaz6ViRh0DZmdKdrczFieKEJ4nGw/xZ+GCUjhRuSWSpiJIrinUpLlPNuwCRQtX6iYD8rS7sWO9sJdvZg3H5lof+I71cM8mnSJ5FFIsYixcadrM+ZmNR7FD6zRBAbJOBhTQbSHEzihq1UmT3lcQs0BnstoFRf0rkEp/wdOCKpkzBPNetTaE+s8icYUJhDiEeZYRkkrwbDBdP5Hjko2ArHerqrP5RsLKyRK1AUkxkDRzHiwivF/2rRf/DpZCLNn5lrdJ//jdWDlyHBAX6bCvHIbxmGpSNeZaMKyOWrEzDf3ChRWXkFwVvKGncAgY/7jNDLzKcLxEpX2b1468L7STXoHxFhr0poBx5TIgDIhqz2LJlTxx+r4jhco92X+a2nRK3gxFAYyYgORVJ8oqVb1mNl0MsOLAZ8LWkO/EwkdjVMqBPfBot7M3aEs4AsdQgCnTrPV/XstQCRQWdf+oHaSZlGihw2tR9e6OcYUBmMPOMCdxm5zt61RUO41Sn5PtBT0bviYgBSgmHaEPXBhTxa0m56cAELFC24+rnn73EOak6pVYF6/XfRtQWUykbSxZKXP8ZzBCiyX1eoIeWm2mI7RznBf4VJBhaLOrgpU5rcPsDvD085nDBcCOX+LoSJr9/11QLdoVL6a87QbZ/w==,iv:ZOBJ4DIMxWRW8PUYPU2ykTCbnH4gYz7QZ6ZVlusVkcw=,tag:VO1vdeWC9pBklaYHoy+nWw==,type:str]
    devices:
        - name: root
          type: disk
          properties:
            pool: local
            path: /
            size: 50GiB
        - name: eth0
          type: nic
          properties:
            network: Main
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveTFtcnJZdDZQcExwQzFY
            RkIwK0ZJVENSZkFQditib2VBRFlBVEs2QVhVCllEL21zQTJ3YkFMdTkycU5DVXNT
            OGVtN0NRbVdITWN1dDd4VkUwZit1eFUKLS0tIFM5WnB4Z0NxK2dNdjdVV3FKU3ZD
            aXoybjVHSW1BYjNIL3JUQ0g3UUxFcUUKWB+nnhQwcneMcl6vF0OlaSdz0dLpNCs9
            JPYVAoU9i7geyRTEaXBPQeo0ZDfGBKYQOeSW+uJxtKI4yAbJnje/fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T21:26:06Z"
    mac: ENC[AES256_GCM,data:kL+QMlOMxQAETNgYSCXgdZsQ0AdiYzk2h/Hn/AeM4llaRcrmc7IhizhHi+sIQu0IBrRATyMdY0j6v4foiNR6uaZoOLr5nahDFov0XggZNaqQgYxvQ7hUyPURnSule5zMGQ5vFpu3iUS30vi78AzBGnVotNx75TK//X+BaMC65p4=,iv:l6zskJK7vTR7ja4vbCQ7+fLRyqdu8wNvBS+h203CJMM=,tag:9Vq1SX2e4Wv+rJWaqftsLA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
