apiVersion: iaas.phorge.fr/v1alpha1
kind: Project
metadata:
    name: phorge
spec:
    name: Phorge
    description: Main project for Phorge instances
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TUkwR29KTVlYdzdMckh0
            TXpDajhZMitSOURxbjVHRE1pazI3V050OWtBCkk0MXhmSlFJaTFhZ3dGbFdLUE5T
            djc0cmlvWUY2NVBOZkR2aTFkaEMza00KLS0tIDl6SDlncVpjeER5bzJSdHpQcEtO
            THBTS0R2dW85VGdVeWF1S1RmMlJuTlEKyJbAst3mrAmkGmHjPpwA84dYISimnX3n
            8dx/V2nHPQEimQW/Dog8P1C2G6e9NhDhntfpySp+dkYADhI9izFBCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:36:03Z"
    mac: ENC[AES256_GCM,data:jE0ZOumhY7758+QiV4UJ9Ct9YM/kSdnkCbIYcGosnTFNqzI7jRKwnX5hBP83Z5E+OCbYJPPPikSHPwe/Z8fGkpF7AIo1U5cEUKJI6c6rv8suTk5CC8Xef8jFcBvsGbcLnnC3rDucylQs3aNhdhGK2yivt2zFCaEuQDkr49L+3hQ=,iv:fzKkKMLvi3qctIdt7E8H//MrVU84NuE0+06mudmYnU8=,tag:pNBcjA+klYA+LHFMdz+iVA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data)$
    version: 3.11.0
---
apiVersion: iaas.phorge.fr/v1alpha1
kind: Network
metadata:
    name: main
spec:
    name: Main
    type: ovn
    project: Phorge
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TUkwR29KTVlYdzdMckh0
            TXpDajhZMitSOURxbjVHRE1pazI3V050OWtBCkk0MXhmSlFJaTFhZ3dGbFdLUE5T
            djc0cmlvWUY2NVBOZkR2aTFkaEMza00KLS0tIDl6SDlncVpjeER5bzJSdHpQcEtO
            THBTS0R2dW85VGdVeWF1S1RmMlJuTlEKyJbAst3mrAmkGmHjPpwA84dYISimnX3n
            8dx/V2nHPQEimQW/Dog8P1C2G6e9NhDhntfpySp+dkYADhI9izFBCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:36:03Z"
    mac: ENC[AES256_GCM,data:jE0ZOumhY7758+QiV4UJ9Ct9YM/kSdnkCbIYcGosnTFNqzI7jRKwnX5hBP83Z5E+OCbYJPPPikSHPwe/Z8fGkpF7AIo1U5cEUKJI6c6rv8suTk5CC8Xef8jFcBvsGbcLnnC3rDucylQs3aNhdhGK2yivt2zFCaEuQDkr49L+3hQ=,iv:fzKkKMLvi3qctIdt7E8H//MrVU84NuE0+06mudmYnU8=,tag:pNBcjA+klYA+LHFMdz+iVA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data)$
    version: 3.11.0
---
apiVersion: iaas.phorge.fr/v1alpha1
kind: Instance
metadata:
    name: rustfs-s3-main
spec:
    name: rustfs-s3-main
    image: images:alpine/3.23/cloud
    description: RustFS S3 main instance
    project: Phorge
    type: virtual-machine
    running: true
    config:
        limits.cpu: "1"
        limits.memory: 1024MiB
        security.secureboot: "false"
        cloud-init.user-data: ENC[AES256_GCM,data:fBCGEnXOzaOI/D1mlB9NbFkj/4nWw0zhFOI3+lxNfWyf/GEjp6OaunQbrhlvdOMo09wfclBa1rlMJ1hXMMAhK2uxvPua8+dqh9cAugVcKBTBDA6bpSf2XOUROnMgLo+OJXE+HENfac8QGcb5lZWh8exOlFAxx3CKbzmEuOiVyCLG3da+vl2auiBai8RGDavRb2Zenh8njnjLfeh5ijEffn4/Oz3UZpaTRiRzQ20+lbnROuxmU0WlTrhLKX24BV4tdIEAwOlxJPNYovxIRe9+Py/G6eXPgEOrDlwuDTCojGNkS6f+IlKuBq1zZYmP4DMNQlFDjZGl744AWlSPriJG9sCtjP0i84xG3o6Z6j3kAmuBGoKRMrFh9uPs2C2CAOWyCOMN7ITSqrOGgW255GbWC5EQ0vqLdhX1rQmgPMkweRr3IJZ29M9Ef7KJ62qZTLJzfbPla9mONeAQXPNKZjpfaMKQWWbYFlKX3WNQPEbe9Rmjua0MNnE7Y3nkxLL/whTI1bChIvHQDkWTZlv2ljTq3EesxwGSo/SJKtVjKN6wbWcQRqcbl68EmbDzrLgPT/q7OXKEPOeMJbjEOeUpkGXBM3Ot3Weo1JSyPDkD1iRpuAJR/Fbqsuq9jxf11sj5SJy2ajPoZjOSE9iSbi//Bo8+aFNJdWUX8szvr8tHM3hIdSIbfs51X6PSiALbmEoGtmAXJ5u10DLZzkfG9oTIObeNehbRnBt3VxZvs4dAbTXLuNBolt2mXqb3nU0tcC3g0p1vvFabIPlxRAOHF/ZNQyaFTE2i49bYuV1MGv8r1RDj8rfEn7W5bClKmZjf5rz+ZS7r39zFX2Y8H2TUpbsWLFrqcmOgjGw3Lx4q8V0iM3axGmKQCgSAvIMStSP9GNQaP2o/iU8MAlqCpgz4grS4BG6Ntk5vhkBbz4I3nWCnnOeNwOXUTgb/nWdlnXsA/IccZ2ylv9lXFTEbUwuY8qF5F/mhrIsr8u7iPsuQoALp2oyXo78QBoXm6APkKyCZz9mpQFKPcwcmB4RHlQXFYrjBgjJJi5TmwTo7SwMwDUXh0Qo9Bz5llbikHjRXUEOLIa5akmKZtLFBq/TaCWtZyrEyc/FgvuvKnYWTfgUwzLb40Lq0yRxKaJKeqH94xJMkacmK2Pv5tRfD9Y2Njw30eyNClCgDTyim6BJkkBotQ2Zl6m6b0WkSi8VraXtzan6ddYyUXPePdYUZlbrEFvEao5tqflJOxes7gJ2i2L9GcvL02pDdYAKI7mGdPUuAE9SXoBG/C9ibiEnLZjTAn7iOlMbFeNIXqy0hulOUEYp19CniypFOkxiA6h8d/Z642vHjv7ELEff1ehzirXmv3F3L52VaUFkwHzMVlekyKQAZ8hMbwAHZHzJr9cUHLPxT690vplrRT7l8V2UmBNp9bdIhbFgihLiO73AfCqeijTgLCMFHS6YickMfChWLzJ484LcX,iv:2GFbFMWCdfSOqQw2YQAQFjpzXwtdm9y06XmlRRlEh6c=,tag:WcQfUXWquUlgzehTrFNRKA==,type:str]
    devices:
        - name: root
          type: disk
          properties:
            pool: local
            path: /
            size: 100GiB
        - name: eth0
          type: nic
          properties:
            network: Main
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TUkwR29KTVlYdzdMckh0
            TXpDajhZMitSOURxbjVHRE1pazI3V050OWtBCkk0MXhmSlFJaTFhZ3dGbFdLUE5T
            djc0cmlvWUY2NVBOZkR2aTFkaEMza00KLS0tIDl6SDlncVpjeER5bzJSdHpQcEtO
            THBTS0R2dW85VGdVeWF1S1RmMlJuTlEKyJbAst3mrAmkGmHjPpwA84dYISimnX3n
            8dx/V2nHPQEimQW/Dog8P1C2G6e9NhDhntfpySp+dkYADhI9izFBCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:36:03Z"
    mac: ENC[AES256_GCM,data:jE0ZOumhY7758+QiV4UJ9Ct9YM/kSdnkCbIYcGosnTFNqzI7jRKwnX5hBP83Z5E+OCbYJPPPikSHPwe/Z8fGkpF7AIo1U5cEUKJI6c6rv8suTk5CC8Xef8jFcBvsGbcLnnC3rDucylQs3aNhdhGK2yivt2zFCaEuQDkr49L+3hQ=,iv:fzKkKMLvi3qctIdt7E8H//MrVU84NuE0+06mudmYnU8=,tag:pNBcjA+klYA+LHFMdz+iVA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data)$
    version: 3.11.0
---
apiVersion: iaas.phorge.fr/v1alpha1
kind: Forward
metadata:
    name: rustfs-s3-main-forward
spec:
    network: Main
    description: Forward for RustFS S3
    project: Phorge
    listen_address: 10.3.0.1
    ports:
        - protocol: tcp
          listen_port:
            - "9000"
            - "9001"
          target_address: 10.145.33.2
          target_port:
            - "9000"
            - "9001"
          description: Forward for RustFS S3
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TUkwR29KTVlYdzdMckh0
            TXpDajhZMitSOURxbjVHRE1pazI3V050OWtBCkk0MXhmSlFJaTFhZ3dGbFdLUE5T
            djc0cmlvWUY2NVBOZkR2aTFkaEMza00KLS0tIDl6SDlncVpjeER5bzJSdHpQcEtO
            THBTS0R2dW85VGdVeWF1S1RmMlJuTlEKyJbAst3mrAmkGmHjPpwA84dYISimnX3n
            8dx/V2nHPQEimQW/Dog8P1C2G6e9NhDhntfpySp+dkYADhI9izFBCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:36:03Z"
    mac: ENC[AES256_GCM,data:jE0ZOumhY7758+QiV4UJ9Ct9YM/kSdnkCbIYcGosnTFNqzI7jRKwnX5hBP83Z5E+OCbYJPPPikSHPwe/Z8fGkpF7AIo1U5cEUKJI6c6rv8suTk5CC8Xef8jFcBvsGbcLnnC3rDucylQs3aNhdhGK2yivt2zFCaEuQDkr49L+3hQ=,iv:fzKkKMLvi3qctIdt7E8H//MrVU84NuE0+06mudmYnU8=,tag:pNBcjA+klYA+LHFMdz+iVA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data)$
    version: 3.11.0
