apiVersion: iaas.phorge.fr/v1alpha1
kind: Project
metadata:
    name: phorge
spec:
    name: Phorge
    description: Main project for Phorge instances
    config:
        features.images: "true"
        features.networks: "true"
        features.networks.zones: "false"
        features.profiles: "true"
        features.storage.volumes: "true"
        restricted: "true"
        restricted.cluster.target: allow
        restricted.networks.uplinks: UPLINK
        restricted.snapshots: allow
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTlZmUWQ0YkVNQS8xbW9B
            MC9ZUFp5czczQlBiUEJjeE9CSzY4ejlPd0hBCit4QzdNYnZTUGFmSm1RUGtNZ1hi
            ZjA2RmFFY0paMmlBVitpU1dxNmhJbG8KLS0tIG00U0xDWEk3TktCZDAwQ09wYTkv
            UHZTRnZHa2s3cGxSNy9JZTlIc2dMQ3cKYVw9B5Z2Y/ofiap74DMBjtLJiGGGUaLY
            CWxCZSXgoSRMmr446ZVwsJuSMPLb5tJIbc2pB9nd+Qh30fVnjEnYJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T23:30:52Z"
    mac: ENC[AES256_GCM,data:ojWUbQYNkOKeHu0wqXbb7VQqCPGulVHIxAcO5buj4FhplcG+9+EWqJH3gaswA2vWNucAhY1rUdwwqz9yeLQmt1byixaGJ4rMjNElxH4d0gRPKg1udROJCkll7sockomzlMpjhhYLiddmJSN9vRS4M/x2yM5mO7LE6KY7tbAWyoQ=,iv:Bv9sNnD5prOaaFoqDuzne8njqifKjRvDMYdgt4tQaBc=,tag:YdTI6dl11R8PnqMLRLJ2fg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: iaas.phorge.fr/v1alpha1
kind: Network
metadata:
    name: phorge-main
spec:
    name: Main
    type: ovn
    project: Phorge
    config:
        ipv4.address: 10.215.12.1/24
        ipv6.address: none
        ipv4.nat: "true"
        ipv6.nat: "false"
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTlZmUWQ0YkVNQS8xbW9B
            MC9ZUFp5czczQlBiUEJjeE9CSzY4ejlPd0hBCit4QzdNYnZTUGFmSm1RUGtNZ1hi
            ZjA2RmFFY0paMmlBVitpU1dxNmhJbG8KLS0tIG00U0xDWEk3TktCZDAwQ09wYTkv
            UHZTRnZHa2s3cGxSNy9JZTlIc2dMQ3cKYVw9B5Z2Y/ofiap74DMBjtLJiGGGUaLY
            CWxCZSXgoSRMmr446ZVwsJuSMPLb5tJIbc2pB9nd+Qh30fVnjEnYJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T23:30:52Z"
    mac: ENC[AES256_GCM,data:ojWUbQYNkOKeHu0wqXbb7VQqCPGulVHIxAcO5buj4FhplcG+9+EWqJH3gaswA2vWNucAhY1rUdwwqz9yeLQmt1byixaGJ4rMjNElxH4d0gRPKg1udROJCkll7sockomzlMpjhhYLiddmJSN9vRS4M/x2yM5mO7LE6KY7tbAWyoQ=,iv:Bv9sNnD5prOaaFoqDuzne8njqifKjRvDMYdgt4tQaBc=,tag:YdTI6dl11R8PnqMLRLJ2fg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: iaas.phorge.fr/v1alpha1
kind: Instance
metadata:
    name: gitea-runner-0
spec:
    name: gitea-runner-0
    image: images:alpine/3.23/cloud
    description: Gitea runner instance
    project: Phorge
    type: virtual-machine
    running: true
    config:
        limits.cpu: "2"
        limits.memory: 3072MiB
        security.secureboot: "false"
        cloud-init.user-data: ENC[AES256_GCM,data:Dk7gDBcILf7kPoqfJRIvmQHAQm0vwbj9lKba4x6WO75AaJaBchQLq/fqeOIfEqiig90D/LumTQlZcGDiUP3iiWUnrZmeRPunqUwe5boXIQQmKk9yVN3jKpeCGn7DHvUz9PQowKH1hG1wGX9rRL9R3ZjNRytHn5i/fW1IAmNJeJw9KV/zYVFtHpXx27nkc762XlzkRWFZQMn4bsvdHnIEWoDqyzK3mHZ5eSYlCBHRleOb6BjBtdvYxn0hUUFyDH8rvhsyr1FbYwBwCSDpRzbyFV+647S+IEhtKqlShe89hLtPjFKVLxc6fYxaKJvpHzd6UwwuiHgV3IU5DJtDOKNSoFI60PtdK56WCz0lQ57V1cqRGaywSGHh6YAbN72QQc1GJw+nB7xF0z/BMyt3yFxs2gS60Baqmgif1M3xguW8pww/bD3TxRPI9JO4Soh6k1nkjAeSqMiwpRdLV2W5B7v8jk/BfKsgBp3AyaUHjBjym0CLsAkC6cvs4ntsanHEgPLIMrzwdBQ24VMIM01HAtzIcp/xO7lTBX7KTCPmd9l16ycl8gryWZ17e6PtdsGy9UR+nhhSg62pERXRpp78nPsQxK6Luv9muTItRq18Hf57aAmJW/dKo6703qtFCCiU8M7Mt84Zfh6Piucc5E/XndEne/rIcBsVFjQDChOjqSZ+K7I4uCRv0cJ6WDZUNHH1/cfgHsmPDOVISYHdfUsTDl4B3Lqix0SO+Kp9QL1KFuq9br4sCDX2f5SXuFEwZxBAvB8jW4L0xdMdzySXUparz9FyAGGhgQZ40SP5OKVfUh+kRsKns3cwWcYeEvZJ30weJeeLOSx5zSFbxLXX1eR8p06D1Pm/VLBbP1ecSweWsIHYq0ybT8A9rnEvspELLxU1Aec/0vvxbbSu94bpk/XCfyw4CFdKIiBM6yCa61TyF3HVfqT5CvcKk/E2Z9zKz5bfTy1tTrozxNzHxij7Ef99t/cae8kU4VFIYTKWBnPs2x8d17MagL83PHzg//VMxbERjx0HBg7RMI7BATbBd91UsrWPT6I8FUX9hF4mIzWKqAYxHcbijP5Q8ogDQfI7XYRuMrLfmjH/8jHDi/5UlBN4KDfHJfpXa1WEl3uDF3042z44pMd/XR5fe5qJ0uBdMpG7w9jRKHki5OmuTxZ00VwWVNV7JMXL8zuPGzcpTPEGTk7O9qHjBHeK1ZD4MIef/JcgNYSUPMYPIHOFoD+B/6SqTr00hzcVco+JInAzvlGFVbkfFKuXNlmR7g4Pjd0UjpDbnO4OAQlIvgvSkIYQp5sBObMTdS4NaLoc8sVXR9/sATURT+O8TLyg4oPrmBuNdMAM7O2ZFvXG9ZG/8H/mMuQpOGk6S9SNKYezECixDM9dAj1x8V18VrrPP99Kxrbz9HtLhfninCOZAnZuMpr58GuCA5Dq+x9UeRNrwKVRzQBlO4qntJx5HguSbG5kFTueur0nWqv1GLToMEbUt+4bKOEwtr4VS81+bAq2D7U/OE4cIduxy2L0QO6RlgnEsQhECC5aO1WYT2J8iBY6tGwF6k7bOuy19yiS8pcvBEr/JTQILnQt5W+p0V+lZlrVymrLNheZzVEtK4vaBtq0EJN0aC3lHcCHZ6pgvBWzKBvEU0I8mXphbKooSyP+OmrOo2O5tetcjbmBB51WuXtcCJHYHBA5grkJlGXjU8ueaXMDFpR6nVComqGLuh+LLjW/n42BcrKP8+V//xCGWyCKJayWAbYRPp8QxLFdhERjv2t1Sh4KYueHNLjHpZX18fSx2r1c/nlGSsBFlTSN2jy3TQhYDHLfsGilTwXTluqgNryjEaKRkXQliwSC/vFNrLRr2miFuyuD6OOnDJ1azDhj/2TJDUZc3KjIDu5ldjXVVDCL83h2fZOcn3KPHJ5qE3lGdtUVmD+ETeNlRaRRMk/hZjl9VJEI9H8HiOQ+G4LaML9pUOCeUzS33rYb+nEIQyR2xt/ix/7JEBm8rHP8Uscz0PeHFcfO9ELGHpF2VHHv/zvB78f9mKzY0y82W73XZxNIAozCTU2Nb5XcS2Pdv+1nWpAR0IVkmIdradIfkUQtaTv5yld5y8rQ9pZspx6mvz0YVdcoFGfb905s5QeSsSwu/hJisA1Vf7siOcDCn6rvZrkv11XYq9THqs7buzE5TN8a2SPyjmg2ODMdCTiTvsVT3zWSxURhSn5sT2jVMOWRbfeHx6n27NbdAyV/b/ppn51VlG2BXUA5Sa8b05yaJmMCpKV9AD3yEqviEwsM5wRUEKYGqf/Y+9wvaPy8DgIgEctLLJfFMAqnkOWSTIGzJBT4IknoFhGCGPnXh1YErqYuSkdrJvsDwyRGv1r64xOaESMDXvlTbNQcwXeDaG3z+MegSyAAPz/YVpx4SLTx1JxdrCVTHhi3YXpLjJ/O4XOSzLKtkp1m7HERhYu4/8PmAL6nsvQjzwCswVfWcQS2NfIMeaVd/orN6CD96bep2FiWRq5iSaOTldVVvG66ijkzBsnenyrBixmaOVuQ9qk0Z9n4QT72hpiYHE+AxK0BC1dvgObk9/jNyMk8cCuT5SHv0uClXRsV/g5Ootoh2rhA3K+AOCKGMz7VEu2VN9LPINHdciiSTkXX6DOCajFV75t2UaXfhkZsy5xPmdfKg3zaMpdA4tIyEEoyrU4ys3tnlKSTIZF7dT78Iw+/fPEU40q1Av/m4rb2ZQ==,iv:C9qd1SLv5R7zgDnbH4FcP3iHTBW5CrkP/h7dXd9S/uM=,tag:YQjMWqBnZuhOd1yF8BYH6A==,type:str]
    devices:
        - name: root
          type: disk
          properties:
            pool: local
            path: /
            size: 50GiB
        - name: eth0
          type: nic
          properties:
            network: Main
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTlZmUWQ0YkVNQS8xbW9B
            MC9ZUFp5czczQlBiUEJjeE9CSzY4ejlPd0hBCit4QzdNYnZTUGFmSm1RUGtNZ1hi
            ZjA2RmFFY0paMmlBVitpU1dxNmhJbG8KLS0tIG00U0xDWEk3TktCZDAwQ09wYTkv
            UHZTRnZHa2s3cGxSNy9JZTlIc2dMQ3cKYVw9B5Z2Y/ofiap74DMBjtLJiGGGUaLY
            CWxCZSXgoSRMmr446ZVwsJuSMPLb5tJIbc2pB9nd+Qh30fVnjEnYJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T23:30:52Z"
    mac: ENC[AES256_GCM,data:ojWUbQYNkOKeHu0wqXbb7VQqCPGulVHIxAcO5buj4FhplcG+9+EWqJH3gaswA2vWNucAhY1rUdwwqz9yeLQmt1byixaGJ4rMjNElxH4d0gRPKg1udROJCkll7sockomzlMpjhhYLiddmJSN9vRS4M/x2yM5mO7LE6KY7tbAWyoQ=,iv:Bv9sNnD5prOaaFoqDuzne8njqifKjRvDMYdgt4tQaBc=,tag:YdTI6dl11R8PnqMLRLJ2fg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
