apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-issuer.yml
  - cluster-issuer-local.yml
  - cluster-issuer-retake.yml
  - users.yml
  - ip-pools.yml
  - l2announcementpolicy.yml
  - sc-nfs-uncritical.yml