apiVersion: v1
kind: Namespace
metadata:
    name: coder
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKb2NSZDFFUEZHSEVFdGNN
            L3cwVWRndXhVSFo5aWFqdmxPUnp4WUhTKzMwCjFzZHo2dTBTNU54dGR3UmszMThh
            VEV0dS9yaDdGZkFVU2hXQWhPQmFGWXMKLS0tIE5CejQ1RnBjYmhFdHFqK21FWXJC
            UW9zbHlvRnNIZ2NsZUNPbkJqVmorYlUKV0bpc8Qz/gkHLUicEfgfHDt8/f0vhiDb
            THKQKnFTbE8MJUPx9oQBDIna8cyefEJNBhbbKzIv3HEEntyyoKsK6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T02:00:58Z"
    mac: ENC[AES256_GCM,data:CG0BZwLcCtopqO9r4eRryZDeprEZ3MTwDQ0F79jETZyxCEtr2MTcjH6kCml8knSLEW5aRrvmPrAg/se55PZu2SGTOt6fUgCMbvHNXit9Fw58EIuUMNGuQHmEA9ct5bo3VPal9R09gi6HcKEfftsbontt+YTB+ftJHh8+M/F20ac=,iv:5/i2BlxXIiwZYExexVbgW+ZyHkJXTSPpUf4KEnJVbJ0=,tag:OJPGKwQnACDRQZ48Xo6TEg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
    name: bitnami
    namespace: coder
spec:
    interval: 1m0s
    timeout: 1m0s
    layerSelector:
        mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
        operation: copy
    url: oci://registry-1.docker.io/bitnamicharts/postgresql
    ref:
        semver: '*'
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKb2NSZDFFUEZHSEVFdGNN
            L3cwVWRndXhVSFo5aWFqdmxPUnp4WUhTKzMwCjFzZHo2dTBTNU54dGR3UmszMThh
            VEV0dS9yaDdGZkFVU2hXQWhPQmFGWXMKLS0tIE5CejQ1RnBjYmhFdHFqK21FWXJC
            UW9zbHlvRnNIZ2NsZUNPbkJqVmorYlUKV0bpc8Qz/gkHLUicEfgfHDt8/f0vhiDb
            THKQKnFTbE8MJUPx9oQBDIna8cyefEJNBhbbKzIv3HEEntyyoKsK6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T02:00:58Z"
    mac: ENC[AES256_GCM,data:CG0BZwLcCtopqO9r4eRryZDeprEZ3MTwDQ0F79jETZyxCEtr2MTcjH6kCml8knSLEW5aRrvmPrAg/se55PZu2SGTOt6fUgCMbvHNXit9Fw58EIuUMNGuQHmEA9ct5bo3VPal9R09gi6HcKEfftsbontt+YTB+ftJHh8+M/F20ac=,iv:5/i2BlxXIiwZYExexVbgW+ZyHkJXTSPpUf4KEnJVbJ0=,tag:OJPGKwQnACDRQZ48Xo6TEg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: postgresql
    namespace: coder
spec:
    releaseName: postgresql
    chartRef:
        kind: OCIRepository
        name: bitnami
    interval: 1m0s
    values:
        image:
            repository: bitnamilegacy/postgresql
        auth:
            username: ENC[AES256_GCM,data:HsaxnwQ=,iv:ek52U2f50cWKFzWs6qG9f5DDWUxndd4XKCzruCsP5Gg=,tag:5fnXfWzqhc9nKhS584qTDA==,type:str]
            password: ENC[AES256_GCM,data:xxPMiBtnwXEbuey/xjpM5MaSnYwfqLjZ,iv:V1f41FJIkaYcc/cgpWoCDBRWNVwYE0Zf6OZFMmykEo0=,tag:Ywb4lApev7LLWBT0N8DkRA==,type:str]
            database: coder
        primary:
            nodeSelector:
                node-role.kubernetes.io/worker: "true"
            persistence:
                size: 10Gi
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKb2NSZDFFUEZHSEVFdGNN
            L3cwVWRndXhVSFo5aWFqdmxPUnp4WUhTKzMwCjFzZHo2dTBTNU54dGR3UmszMThh
            VEV0dS9yaDdGZkFVU2hXQWhPQmFGWXMKLS0tIE5CejQ1RnBjYmhFdHFqK21FWXJC
            UW9zbHlvRnNIZ2NsZUNPbkJqVmorYlUKV0bpc8Qz/gkHLUicEfgfHDt8/f0vhiDb
            THKQKnFTbE8MJUPx9oQBDIna8cyefEJNBhbbKzIv3HEEntyyoKsK6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T02:00:58Z"
    mac: ENC[AES256_GCM,data:CG0BZwLcCtopqO9r4eRryZDeprEZ3MTwDQ0F79jETZyxCEtr2MTcjH6kCml8knSLEW5aRrvmPrAg/se55PZu2SGTOt6fUgCMbvHNXit9Fw58EIuUMNGuQHmEA9ct5bo3VPal9R09gi6HcKEfftsbontt+YTB+ftJHh8+M/F20ac=,iv:5/i2BlxXIiwZYExexVbgW+ZyHkJXTSPpUf4KEnJVbJ0=,tag:OJPGKwQnACDRQZ48Xo6TEg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: coder-env-secret
    namespace: coder
type: Opaque
stringData:
    CODER_PG_CONNECTION_URL: ENC[AES256_GCM,data:MP91H1a5XWzQSgzKptyjXia+Rx/l91O2KaC3dW4BPOWSzkxqYa96ePH2ux2TMCBjZoYyrrWfVmPOwDCHo5BMD+46WrQphOwEWPW1FYzsrAOUomwjHk1v2DdALJX7rx936UIUscGPCw==,iv:QwNNTKgpLs/LheO58QA+xCXtWfOFsACdCQDgyxzQzvk=,tag:JEUO3neLmwtgE9B7knf+eg==,type:str]
    CODER_ACCESS_URL: ENC[AES256_GCM,data:ezLUh59bCm7VjBeCYkyUNlOZszD7Ydo=,iv:sF8fBFrIBwJAZ27XftSDfKL/KL34XSoZp2Nq7E1s51U=,tag:WNumpRYXqr26rOA+ukMbhg==,type:str]
    CODER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:Lk3JgyU=,iv:k6Yo4Ex9T0gthi6UYRSy+km7VuBmDrz73gxQz80pFvI=,tag:M7uMt4fuCTArQDtqES9Www==,type:str]
    CODER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:wLb0rpN0nIqBs5Mxjw2owzzZTnJpNOMm6ubQ8GKizBA4+FHr,iv:wUsVjRvniEUTMSUChjpBFbp33uAQy3Z0f+v8hDFKfwk=,tag:eSSh7YK8aI2aOkjTyugXyA==,type:str]
    CODER_OIDC_ISSUER_URL: ENC[AES256_GCM,data:2JAb1wNPiezwJVSZX/fRZAkndMZ0pA==,iv:6tCQdof81ULx2UZwE9kwdghyLNyfSnKN20i6D7Lpiuc=,tag:mNcSOlv9bF//fly8hYUalA==,type:str]
    CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE: ENC[AES256_GCM,data:b4e7q3A=,iv:A8MuxWl9WZ+Hug7CevYzxaHVGBX1glFeVeqrPXqbu0I=,tag:KuUi6FFFDdQfHXWWniq4cg==,type:str]
    CODER_PROMETHEUS_ENABLE: ENC[AES256_GCM,data:HwwUPw==,iv:XP/tYZXo2k4BdALRLLULJysme1W1SUO2WTAF8vi3L40=,tag:O+JRocqDz0hM6Cv0Gfiqyg==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKb2NSZDFFUEZHSEVFdGNN
            L3cwVWRndXhVSFo5aWFqdmxPUnp4WUhTKzMwCjFzZHo2dTBTNU54dGR3UmszMThh
            VEV0dS9yaDdGZkFVU2hXQWhPQmFGWXMKLS0tIE5CejQ1RnBjYmhFdHFqK21FWXJC
            UW9zbHlvRnNIZ2NsZUNPbkJqVmorYlUKV0bpc8Qz/gkHLUicEfgfHDt8/f0vhiDb
            THKQKnFTbE8MJUPx9oQBDIna8cyefEJNBhbbKzIv3HEEntyyoKsK6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T02:00:58Z"
    mac: ENC[AES256_GCM,data:CG0BZwLcCtopqO9r4eRryZDeprEZ3MTwDQ0F79jETZyxCEtr2MTcjH6kCml8knSLEW5aRrvmPrAg/se55PZu2SGTOt6fUgCMbvHNXit9Fw58EIuUMNGuQHmEA9ct5bo3VPal9R09gi6HcKEfftsbontt+YTB+ftJHh8+M/F20ac=,iv:5/i2BlxXIiwZYExexVbgW+ZyHkJXTSPpUf4KEnJVbJ0=,tag:OJPGKwQnACDRQZ48Xo6TEg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: coder
    namespace: coder
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://helm.coder.com/v2
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKb2NSZDFFUEZHSEVFdGNN
            L3cwVWRndXhVSFo5aWFqdmxPUnp4WUhTKzMwCjFzZHo2dTBTNU54dGR3UmszMThh
            VEV0dS9yaDdGZkFVU2hXQWhPQmFGWXMKLS0tIE5CejQ1RnBjYmhFdHFqK21FWXJC
            UW9zbHlvRnNIZ2NsZUNPbkJqVmorYlUKV0bpc8Qz/gkHLUicEfgfHDt8/f0vhiDb
            THKQKnFTbE8MJUPx9oQBDIna8cyefEJNBhbbKzIv3HEEntyyoKsK6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T02:00:58Z"
    mac: ENC[AES256_GCM,data:CG0BZwLcCtopqO9r4eRryZDeprEZ3MTwDQ0F79jETZyxCEtr2MTcjH6kCml8knSLEW5aRrvmPrAg/se55PZu2SGTOt6fUgCMbvHNXit9Fw58EIuUMNGuQHmEA9ct5bo3VPal9R09gi6HcKEfftsbontt+YTB+ftJHh8+M/F20ac=,iv:5/i2BlxXIiwZYExexVbgW+ZyHkJXTSPpUf4KEnJVbJ0=,tag:OJPGKwQnACDRQZ48Xo6TEg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: coder
    namespace: coder
spec:
    chart:
        spec:
            chart: coder
            sourceRef:
                kind: HelmRepository
                name: coder
            version: '*'
    interval: 1m0s
    values:
        coder:
            env:
                - name: CODER_PG_CONNECTION_URL
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:44u+Uv7HE+/L73UErTClqNQLhGTgiHU=,iv:C94ZFo3Li9h5wYhzyLQEDawu8EYXAsEXKm9JYR0Pln4=,tag:amqSb+jdV/+f83B7saGiqw==,type:str]
                - name: CODER_ACCESS_URL
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:/dhmfme3g8n+0VLs8EirKw==,iv:HSrVB1VGh4FDGQUOuKQDNSv2wi4shmZraCfJy52KiyQ=,tag:hz4L7cYNEeIg4mSrYMvVgA==,type:str]
                - name: CODER_OIDC_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:YvUq7ZLqJ8KNDEeL64sEvFCTvio=,iv:3WEPzxwDOVYyqcIQEvTQslhuAgVL4Wkx3SV5kISpmBU=,tag:QJfn02rsK8y62FlT8admxA==,type:str]
                - name: CODER_OIDC_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:wllCLI/ZK6MDmbLAzIlxZ/5iIH1QVV/j,iv:UOrZ5G3P9Tq9JZGa4UhHL/pzJNhd/RUAlx15ffPa6X0=,tag:vrK09QecdwKHoVEuOB8wEQ==,type:str]
                - name: CODER_OIDC_ISSUER_URL
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:VuNfjG9LQJJ4PWqYWtACFwJn6xCW,iv:1WQELH/X+lQZ3ajp8ONJpdMi998Fq9vmm9PEMjRRLrs=,tag:39I5wYwlZwffK1bPPdKPww==,type:str]
                - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:s7y/5OwaUzZG18dWRezFkNLou9sabQ/J76gGY44TmB7ZAPpg4Pn65kbatQ==,iv:4tZz19ZmYzSzjrc6k+kYF7Uxh1efuRDJpfLCAQBtO8o=,tag:AUZXqyvGgULenLb1OOiLRg==,type:str]
                - name: CODER_PROMETHEUS_ENABLE
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:tE8/MG8bPa8jBBJFaaLbmSe7fEvQL4k=,iv:+yuIPIovGaMi1yg9rS1OrzxpCw6/9cLR1OJKQ0cb/sU=,tag:fUXOkJ+GSOHV91beIsVHpA==,type:str]
            resources:
                limits:
                    cpu: 1000m
                    memory: 1024Mi
                requests:
                    cpu: 500m
                    memory: 512Mi
            ingress:
                enable: true
                className: nginx
                host: coder.phorge.fr
                annotations:
                    cert-manager.io/cluster-issuer: letsencrypt
                tls:
                    enable: true
                    secretName: coder-tls
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKb2NSZDFFUEZHSEVFdGNN
            L3cwVWRndXhVSFo5aWFqdmxPUnp4WUhTKzMwCjFzZHo2dTBTNU54dGR3UmszMThh
            VEV0dS9yaDdGZkFVU2hXQWhPQmFGWXMKLS0tIE5CejQ1RnBjYmhFdHFqK21FWXJC
            UW9zbHlvRnNIZ2NsZUNPbkJqVmorYlUKV0bpc8Qz/gkHLUicEfgfHDt8/f0vhiDb
            THKQKnFTbE8MJUPx9oQBDIna8cyefEJNBhbbKzIv3HEEntyyoKsK6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T02:00:58Z"
    mac: ENC[AES256_GCM,data:CG0BZwLcCtopqO9r4eRryZDeprEZ3MTwDQ0F79jETZyxCEtr2MTcjH6kCml8knSLEW5aRrvmPrAg/se55PZu2SGTOt6fUgCMbvHNXit9Fw58EIuUMNGuQHmEA9ct5bo3VPal9R09gi6HcKEfftsbontt+YTB+ftJHh8+M/F20ac=,iv:5/i2BlxXIiwZYExexVbgW+ZyHkJXTSPpUf4KEnJVbJ0=,tag:OJPGKwQnACDRQZ48Xo6TEg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: v1
kind: Service
metadata:
    name: coder-prometheus
    namespace: coder
spec:
    clusterIP: None
    ports:
        - name: prom-http
          port: 2112
          protocol: TCP
          targetPort: 2112
    selector:
        app.kubernetes.io/instance: coder
        app.kubernetes.io/name: coder
    type: ClusterIP
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKb2NSZDFFUEZHSEVFdGNN
            L3cwVWRndXhVSFo5aWFqdmxPUnp4WUhTKzMwCjFzZHo2dTBTNU54dGR3UmszMThh
            VEV0dS9yaDdGZkFVU2hXQWhPQmFGWXMKLS0tIE5CejQ1RnBjYmhFdHFqK21FWXJC
            UW9zbHlvRnNIZ2NsZUNPbkJqVmorYlUKV0bpc8Qz/gkHLUicEfgfHDt8/f0vhiDb
            THKQKnFTbE8MJUPx9oQBDIna8cyefEJNBhbbKzIv3HEEntyyoKsK6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T02:00:58Z"
    mac: ENC[AES256_GCM,data:CG0BZwLcCtopqO9r4eRryZDeprEZ3MTwDQ0F79jETZyxCEtr2MTcjH6kCml8knSLEW5aRrvmPrAg/se55PZu2SGTOt6fUgCMbvHNXit9Fw58EIuUMNGuQHmEA9ct5bo3VPal9R09gi6HcKEfftsbontt+YTB+ftJHh8+M/F20ac=,iv:5/i2BlxXIiwZYExexVbgW+ZyHkJXTSPpUf4KEnJVbJ0=,tag:OJPGKwQnACDRQZ48Xo6TEg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: coder-service-monitor
    namespace: coder
spec:
    endpoints:
        - port: prom-http
          interval: 10s
          scrapeTimeout: 10s
    namespaceSelector:
        matchNames:
            - coder
    selector:
        matchLabels:
            app.kubernetes.io/name: coder
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKb2NSZDFFUEZHSEVFdGNN
            L3cwVWRndXhVSFo5aWFqdmxPUnp4WUhTKzMwCjFzZHo2dTBTNU54dGR3UmszMThh
            VEV0dS9yaDdGZkFVU2hXQWhPQmFGWXMKLS0tIE5CejQ1RnBjYmhFdHFqK21FWXJC
            UW9zbHlvRnNIZ2NsZUNPbkJqVmorYlUKV0bpc8Qz/gkHLUicEfgfHDt8/f0vhiDb
            THKQKnFTbE8MJUPx9oQBDIna8cyefEJNBhbbKzIv3HEEntyyoKsK6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T02:00:58Z"
    mac: ENC[AES256_GCM,data:CG0BZwLcCtopqO9r4eRryZDeprEZ3MTwDQ0F79jETZyxCEtr2MTcjH6kCml8knSLEW5aRrvmPrAg/se55PZu2SGTOt6fUgCMbvHNXit9Fw58EIuUMNGuQHmEA9ct5bo3VPal9R09gi6HcKEfftsbontt+YTB+ftJHh8+M/F20ac=,iv:5/i2BlxXIiwZYExexVbgW+ZyHkJXTSPpUf4KEnJVbJ0=,tag:OJPGKwQnACDRQZ48Xo6TEg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
