apiVersion: v1
kind: Namespace
metadata:
    name: coder
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM1dEb21vaDVUdFpVY2x5
            U3JKc2psemI4NFp0ZVZIa05wSjg1R2U3Ym1nCk5zcElycE9GcnY3eC94MDlFWTZ6
            aytER0VTMWloeDhESVpKWEN6d2dOT2cKLS0tIGtIcWgrQUZ4c3RmMjZDUWs1UmRS
            RUgvaEdXTVkvWUpkL1ZWMXRsc1hXMFkKvlH6wQBcs0Kw27iTUf4QTDYI2NycGh4B
            8vyWRAV6uo2RqyPDLna5LHfdxCFlsLXIzEYKSv+pB8hXkiefGqOawg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:55:52Z"
    mac: ENC[AES256_GCM,data:74b9+UXBLMZoCaHgakGZ/1EO5p82gDa4Re3X/PZOtm0FNFNMiuAF4UJjFh0YCxF1PfipRlUtObcbAUbbYAB8Vs1iivIoDikWh11BEwZTKwIXI3buLMEKB1ARadIlMQeOFWRaDmw6cSin0sAIh1kRd+La6TsVwGsEGEDt1mzvU5I=,iv:CI4iCfFldi0zGiaw9q9JEisN1yMY3tEgkC6eSULctyY=,tag:E/ri4Lui6jOivpj+PGL/aw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
    name: bitnami
    namespace: coder
spec:
    interval: 1m0s
    timeout: 1m0s
    layerSelector:
        mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
        operation: copy
    url: oci://registry-1.docker.io/bitnamicharts/postgresql
    ref:
        semver: '*'
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM1dEb21vaDVUdFpVY2x5
            U3JKc2psemI4NFp0ZVZIa05wSjg1R2U3Ym1nCk5zcElycE9GcnY3eC94MDlFWTZ6
            aytER0VTMWloeDhESVpKWEN6d2dOT2cKLS0tIGtIcWgrQUZ4c3RmMjZDUWs1UmRS
            RUgvaEdXTVkvWUpkL1ZWMXRsc1hXMFkKvlH6wQBcs0Kw27iTUf4QTDYI2NycGh4B
            8vyWRAV6uo2RqyPDLna5LHfdxCFlsLXIzEYKSv+pB8hXkiefGqOawg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:55:52Z"
    mac: ENC[AES256_GCM,data:74b9+UXBLMZoCaHgakGZ/1EO5p82gDa4Re3X/PZOtm0FNFNMiuAF4UJjFh0YCxF1PfipRlUtObcbAUbbYAB8Vs1iivIoDikWh11BEwZTKwIXI3buLMEKB1ARadIlMQeOFWRaDmw6cSin0sAIh1kRd+La6TsVwGsEGEDt1mzvU5I=,iv:CI4iCfFldi0zGiaw9q9JEisN1yMY3tEgkC6eSULctyY=,tag:E/ri4Lui6jOivpj+PGL/aw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: postgresql
    namespace: coder
spec:
    releaseName: postgresql
    chartRef:
        kind: OCIRepository
        name: bitnami
    interval: 1m0s
    values:
        image:
            repository: bitnamilegacy/postgresql
        auth:
            username: ENC[AES256_GCM,data:edLU6qQ=,iv:YjMzxLT/gutvw2d+gFEW82ms27wBdxGi622RDH6Frqw=,tag:9Qyejbzkn0vcnrWc+4aPoA==,type:str]
            password: ENC[AES256_GCM,data:W9Xs4rZZTF7M83rpxcGNmAzMM9NI5U/m,iv:PB8KU6ZSS9EUoIbHz6rU4IyQK3PXjwwsSh6xSrf0ewo=,tag:PQ3SaX7D9X8YYbfxKfm1bA==,type:str]
            database: coder
        primary:
            nodeSelector:
                node-role.kubernetes.io/worker: "true"
            persistence:
                size: 10Gi
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM1dEb21vaDVUdFpVY2x5
            U3JKc2psemI4NFp0ZVZIa05wSjg1R2U3Ym1nCk5zcElycE9GcnY3eC94MDlFWTZ6
            aytER0VTMWloeDhESVpKWEN6d2dOT2cKLS0tIGtIcWgrQUZ4c3RmMjZDUWs1UmRS
            RUgvaEdXTVkvWUpkL1ZWMXRsc1hXMFkKvlH6wQBcs0Kw27iTUf4QTDYI2NycGh4B
            8vyWRAV6uo2RqyPDLna5LHfdxCFlsLXIzEYKSv+pB8hXkiefGqOawg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:55:52Z"
    mac: ENC[AES256_GCM,data:74b9+UXBLMZoCaHgakGZ/1EO5p82gDa4Re3X/PZOtm0FNFNMiuAF4UJjFh0YCxF1PfipRlUtObcbAUbbYAB8Vs1iivIoDikWh11BEwZTKwIXI3buLMEKB1ARadIlMQeOFWRaDmw6cSin0sAIh1kRd+La6TsVwGsEGEDt1mzvU5I=,iv:CI4iCfFldi0zGiaw9q9JEisN1yMY3tEgkC6eSULctyY=,tag:E/ri4Lui6jOivpj+PGL/aw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: coder-env-secret
    namespace: coder
type: Opaque
stringData:
    CODER_PG_CONNECTION_URL: ENC[AES256_GCM,data:d7icb2VWk5XSVURni30ilZiHc+nTohltVI2LyM5/NhrWEf/TzVGcsO/D2Bq/cfzjJtlciombBGUylrpoNrz5lcTvKQaaWw3wSe6uL5dwCl2u7ueZwuKcW4grv+2wlul9NRTtgzKsDA==,iv:X9lPoG0i5ZiQ4MSIovnYW/2sfvXwq636e+FcckZ5LMk=,tag:Nxe99jDJdMwbzywBI3JIpg==,type:str]
    CODER_ACCESS_URL: ENC[AES256_GCM,data:Mw/QnVbfCkrhTK11s8TDoz1vgcqrZ5E=,iv:cIMku166y95j+b6ewjdcI23w2eC47mDOVKeOwKOEql0=,tag:xlAgcHdNfAw/NrFS4nybtw==,type:str]
    CODER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:Osqs11k=,iv:S3aasoNXhNMdUfz0HOYyzWy+qwgss2H+YWnu1rIrcDc=,tag:YL11Y8b45oIoV/1nnfqYXQ==,type:str]
    CODER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:8qUypIGPYOCM7GpTgHy656OLsnXjBz491LWRNUxbzALDOkZQ,iv:xMPpj0TFYg+nZ2nJScPPzzME3gqNFrdYtrIrZKe8PtU=,tag:hQctYxO6uju828ECd+Vjgg==,type:str]
    CODER_OIDC_ISSUER_URL: ENC[AES256_GCM,data:oDbci1nuZqA+fb1Sb7JzpmGQWodhaQ==,iv:ljF6AEGU4g859pwfZD4rw0mpfdIdePGUUi7HqJZUt7E=,tag:2703lOtY57UiLmj/wYLwdQ==,type:str]
    CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE: ENC[AES256_GCM,data:raCWdaE=,iv:YzOhCRPp3D2DS82Hb6UHoZSaFhwZ5gaCY5RpJKs8n+c=,tag:ebbC+0HXknyXhCT6gfnrsA==,type:str]
    CODER_PROMETHEUS_ENABLE: ENC[AES256_GCM,data:pB6aCg==,iv:5ca3Ck8rJmmrL+9SoFZpbXu059Vpj9+tiWCqWFAupVU=,tag:d/sUZV89MaKSHQXA0rJgjw==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM1dEb21vaDVUdFpVY2x5
            U3JKc2psemI4NFp0ZVZIa05wSjg1R2U3Ym1nCk5zcElycE9GcnY3eC94MDlFWTZ6
            aytER0VTMWloeDhESVpKWEN6d2dOT2cKLS0tIGtIcWgrQUZ4c3RmMjZDUWs1UmRS
            RUgvaEdXTVkvWUpkL1ZWMXRsc1hXMFkKvlH6wQBcs0Kw27iTUf4QTDYI2NycGh4B
            8vyWRAV6uo2RqyPDLna5LHfdxCFlsLXIzEYKSv+pB8hXkiefGqOawg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:55:52Z"
    mac: ENC[AES256_GCM,data:74b9+UXBLMZoCaHgakGZ/1EO5p82gDa4Re3X/PZOtm0FNFNMiuAF4UJjFh0YCxF1PfipRlUtObcbAUbbYAB8Vs1iivIoDikWh11BEwZTKwIXI3buLMEKB1ARadIlMQeOFWRaDmw6cSin0sAIh1kRd+La6TsVwGsEGEDt1mzvU5I=,iv:CI4iCfFldi0zGiaw9q9JEisN1yMY3tEgkC6eSULctyY=,tag:E/ri4Lui6jOivpj+PGL/aw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: coder
    namespace: coder
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://helm.coder.com/v2
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM1dEb21vaDVUdFpVY2x5
            U3JKc2psemI4NFp0ZVZIa05wSjg1R2U3Ym1nCk5zcElycE9GcnY3eC94MDlFWTZ6
            aytER0VTMWloeDhESVpKWEN6d2dOT2cKLS0tIGtIcWgrQUZ4c3RmMjZDUWs1UmRS
            RUgvaEdXTVkvWUpkL1ZWMXRsc1hXMFkKvlH6wQBcs0Kw27iTUf4QTDYI2NycGh4B
            8vyWRAV6uo2RqyPDLna5LHfdxCFlsLXIzEYKSv+pB8hXkiefGqOawg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:55:52Z"
    mac: ENC[AES256_GCM,data:74b9+UXBLMZoCaHgakGZ/1EO5p82gDa4Re3X/PZOtm0FNFNMiuAF4UJjFh0YCxF1PfipRlUtObcbAUbbYAB8Vs1iivIoDikWh11BEwZTKwIXI3buLMEKB1ARadIlMQeOFWRaDmw6cSin0sAIh1kRd+La6TsVwGsEGEDt1mzvU5I=,iv:CI4iCfFldi0zGiaw9q9JEisN1yMY3tEgkC6eSULctyY=,tag:E/ri4Lui6jOivpj+PGL/aw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: coder
    namespace: coder
spec:
    chart:
        spec:
            chart: coder
            sourceRef:
                kind: HelmRepository
                name: coder
            version: '*'
    interval: 1m0s
    values:
        coder:
            env:
                - name: CODER_PG_CONNECTION_URL
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:jET30e0cBHvkg5P5zkq28vqFOXrBOJk=,iv:VwtU9MR8BMGNqasYbj5NdPCF4+Pd/idMCDe5qHQ1ajU=,tag:wZdvGTovrHsea5xKnSA8Ww==,type:str]
                - name: CODER_ACCESS_URL
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:Ziee7eyZXpaLPMh+9YOohA==,iv:8LXmprTomYAiqeDeViuHgY+5C5glYLfaGT93mMwbH5g=,tag:LJLm3NWNIuhhfaL6MjUZ/w==,type:str]
                - name: CODER_OIDC_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:12kx/vDUdZdQn6wAGMqtAzCuwh0=,iv:XUcPnngg3fjbbLIx0DVPFk/6umu9fJnFm90j6e1YqRI=,tag:7AxLCGC6j8IHTTQrysKryA==,type:str]
                - name: CODER_OIDC_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:7b/DDMgfXQp9Bne2kzeSpqVJQUo/FqZ6,iv:LzgqU8fj2m/J5ogO/LnVlJkEQACAceHphfBlMBl6wmY=,tag:fHdS6FcLofY0rQkvNn2Mwg==,type:str]
                - name: CODER_OIDC_ISSUER_URL
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:GB8UP8iLdnkqZHTM6lkvM21pV44E,iv:kA5blT09w37rtl5hqz6xgaazsW6cPoWSWlMSnR4o9gw=,tag:k+M1tmKUXuVh1E9ExX9dKQ==,type:str]
                - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:mPTZ4t+Lw03BqL1Cdl1t02hp+ZYjSwt+BNkH71Wqox6hfvu1jwARQ1im9w==,iv:isy/iHgIkmpGGrreAX6j54dqhFHiMnt/vNIoX7VbpD4=,tag:miRqxaefPXVdUIuj90E2Bw==,type:str]
                - name: CODER_PROMETHEUS_ENABLE
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:HiOjtYhflSExGTXbt+1gYXx4FDzLcHo=,iv:D99V2VSYWWRlLOaNjdthEpBknpNwGE6aykN1zPsYWeo=,tag:zKDJTKsYufaVyfF7qJkYag==,type:str]
            resources:
                limits:
                    cpu: 1000m
                    memory: 1024Mi
                requests:
                    cpu: 500m
                    memory: 512Mi
            ingress:
                enable: true
                className: traefik-public
                host: coder.phorge.fr
                annotations:
                    cert-manager.io/cluster-issuer: letsencrypt
                tls:
                    enable: true
                    secretName: coder-tls
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM1dEb21vaDVUdFpVY2x5
            U3JKc2psemI4NFp0ZVZIa05wSjg1R2U3Ym1nCk5zcElycE9GcnY3eC94MDlFWTZ6
            aytER0VTMWloeDhESVpKWEN6d2dOT2cKLS0tIGtIcWgrQUZ4c3RmMjZDUWs1UmRS
            RUgvaEdXTVkvWUpkL1ZWMXRsc1hXMFkKvlH6wQBcs0Kw27iTUf4QTDYI2NycGh4B
            8vyWRAV6uo2RqyPDLna5LHfdxCFlsLXIzEYKSv+pB8hXkiefGqOawg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:55:52Z"
    mac: ENC[AES256_GCM,data:74b9+UXBLMZoCaHgakGZ/1EO5p82gDa4Re3X/PZOtm0FNFNMiuAF4UJjFh0YCxF1PfipRlUtObcbAUbbYAB8Vs1iivIoDikWh11BEwZTKwIXI3buLMEKB1ARadIlMQeOFWRaDmw6cSin0sAIh1kRd+La6TsVwGsEGEDt1mzvU5I=,iv:CI4iCfFldi0zGiaw9q9JEisN1yMY3tEgkC6eSULctyY=,tag:E/ri4Lui6jOivpj+PGL/aw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
kind: Service
metadata:
    name: coder-prometheus
    namespace: coder
spec:
    clusterIP: None
    ports:
        - name: prom-http
          port: 2112
          protocol: TCP
          targetPort: 2112
    selector:
        app.kubernetes.io/instance: coder
        app.kubernetes.io/name: coder
    type: ClusterIP
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM1dEb21vaDVUdFpVY2x5
            U3JKc2psemI4NFp0ZVZIa05wSjg1R2U3Ym1nCk5zcElycE9GcnY3eC94MDlFWTZ6
            aytER0VTMWloeDhESVpKWEN6d2dOT2cKLS0tIGtIcWgrQUZ4c3RmMjZDUWs1UmRS
            RUgvaEdXTVkvWUpkL1ZWMXRsc1hXMFkKvlH6wQBcs0Kw27iTUf4QTDYI2NycGh4B
            8vyWRAV6uo2RqyPDLna5LHfdxCFlsLXIzEYKSv+pB8hXkiefGqOawg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:55:52Z"
    mac: ENC[AES256_GCM,data:74b9+UXBLMZoCaHgakGZ/1EO5p82gDa4Re3X/PZOtm0FNFNMiuAF4UJjFh0YCxF1PfipRlUtObcbAUbbYAB8Vs1iivIoDikWh11BEwZTKwIXI3buLMEKB1ARadIlMQeOFWRaDmw6cSin0sAIh1kRd+La6TsVwGsEGEDt1mzvU5I=,iv:CI4iCfFldi0zGiaw9q9JEisN1yMY3tEgkC6eSULctyY=,tag:E/ri4Lui6jOivpj+PGL/aw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: coder-service-monitor
    namespace: coder
spec:
    endpoints:
        - port: prom-http
          interval: 10s
          scrapeTimeout: 10s
    namespaceSelector:
        matchNames:
            - coder
    selector:
        matchLabels:
            app.kubernetes.io/name: coder
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM1dEb21vaDVUdFpVY2x5
            U3JKc2psemI4NFp0ZVZIa05wSjg1R2U3Ym1nCk5zcElycE9GcnY3eC94MDlFWTZ6
            aytER0VTMWloeDhESVpKWEN6d2dOT2cKLS0tIGtIcWgrQUZ4c3RmMjZDUWs1UmRS
            RUgvaEdXTVkvWUpkL1ZWMXRsc1hXMFkKvlH6wQBcs0Kw27iTUf4QTDYI2NycGh4B
            8vyWRAV6uo2RqyPDLna5LHfdxCFlsLXIzEYKSv+pB8hXkiefGqOawg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:55:52Z"
    mac: ENC[AES256_GCM,data:74b9+UXBLMZoCaHgakGZ/1EO5p82gDa4Re3X/PZOtm0FNFNMiuAF4UJjFh0YCxF1PfipRlUtObcbAUbbYAB8Vs1iivIoDikWh11BEwZTKwIXI3buLMEKB1ARadIlMQeOFWRaDmw6cSin0sAIh1kRd+La6TsVwGsEGEDt1mzvU5I=,iv:CI4iCfFldi0zGiaw9q9JEisN1yMY3tEgkC6eSULctyY=,tag:E/ri4Lui6jOivpj+PGL/aw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
