apiVersion: v1
kind: Namespace
metadata:
    name: coder
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQnRDTmwvZnB6RWNKc1BU
            TWhxNWJYYUdkZHArMWtqeG1rUlN4eGNUL0drCmdMWDhXdisxSDZqa0I5Z0JqWFhi
            Y1M2dFRUWFNLL1AxSGw5M2dUd0g1QzAKLS0tIE5nN0FQMHJVazd4STJiKzk5elI2
            NDRMdXN6blU4RkR5NTVOTitVOEJLbTQKmBf+ZA36CqndzeP5SXRGRRoZYF1jpzE4
            OxLPEalNxxhIRZTfjGzKvZNny3+6ueteOjI5eWlJ/mTb7yvXWQsjHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:03:55Z"
    mac: ENC[AES256_GCM,data:x7qMmS4JOQyLc2Jn90e+99Aj4IOtCwIVk+CI8eHurTm8uJ73tJXwCLX1/oE5xDgmhdJWQx/5dUSJLggRSIjTk1vkRrWxAz7OSiavxr41mwDJk4SVuZh7dQahQ3K+87QOGr/ndleWuhfs3dCzw4+X4us5uJN151LGC7Y9IhH6qVY=,iv:oWjiBPaNk5WO0RR26NaCUUY6cPcgicSFiZFu89L51XY=,tag:nZfA/hXpC49dennFirPiMQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
    name: bitnami
    namespace: coder
spec:
    interval: 1m0s
    timeout: 1m0s
    layerSelector:
        mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
        operation: copy
    url: oci://registry-1.docker.io/bitnamicharts/postgresql
    ref:
        semver: '*'
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQnRDTmwvZnB6RWNKc1BU
            TWhxNWJYYUdkZHArMWtqeG1rUlN4eGNUL0drCmdMWDhXdisxSDZqa0I5Z0JqWFhi
            Y1M2dFRUWFNLL1AxSGw5M2dUd0g1QzAKLS0tIE5nN0FQMHJVazd4STJiKzk5elI2
            NDRMdXN6blU4RkR5NTVOTitVOEJLbTQKmBf+ZA36CqndzeP5SXRGRRoZYF1jpzE4
            OxLPEalNxxhIRZTfjGzKvZNny3+6ueteOjI5eWlJ/mTb7yvXWQsjHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:03:55Z"
    mac: ENC[AES256_GCM,data:x7qMmS4JOQyLc2Jn90e+99Aj4IOtCwIVk+CI8eHurTm8uJ73tJXwCLX1/oE5xDgmhdJWQx/5dUSJLggRSIjTk1vkRrWxAz7OSiavxr41mwDJk4SVuZh7dQahQ3K+87QOGr/ndleWuhfs3dCzw4+X4us5uJN151LGC7Y9IhH6qVY=,iv:oWjiBPaNk5WO0RR26NaCUUY6cPcgicSFiZFu89L51XY=,tag:nZfA/hXpC49dennFirPiMQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: postgresql
    namespace: coder
spec:
    releaseName: postgresql
    chartRef:
        kind: OCIRepository
        name: bitnami
    interval: 1m0s
    values:
        image:
            repository: bitnamilegacy/postgresql
        auth:
            username: ENC[AES256_GCM,data:m2cb1a0=,iv:BaqIXDCB238f/hLzv+9/RZUjIa8ohW02YTu1RLUitFs=,tag:0QUm3saQtgLMyMLGxTSLyg==,type:str]
            password: ENC[AES256_GCM,data:4cHyCDLro0O0tvB7Ow5G3UxGjZwAXCXm,iv:gARD7wMd1r1ob7Emlf6drMWDgR8OZ8jWn64y/XzbdSk=,tag:f1OFCz68ClQiw9Z+DoZTbA==,type:str]
            database: coder
        primary:
            nodeSelector:
                node-role.kubernetes.io/worker: "true"
            persistence:
                size: 10Gi
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQnRDTmwvZnB6RWNKc1BU
            TWhxNWJYYUdkZHArMWtqeG1rUlN4eGNUL0drCmdMWDhXdisxSDZqa0I5Z0JqWFhi
            Y1M2dFRUWFNLL1AxSGw5M2dUd0g1QzAKLS0tIE5nN0FQMHJVazd4STJiKzk5elI2
            NDRMdXN6blU4RkR5NTVOTitVOEJLbTQKmBf+ZA36CqndzeP5SXRGRRoZYF1jpzE4
            OxLPEalNxxhIRZTfjGzKvZNny3+6ueteOjI5eWlJ/mTb7yvXWQsjHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:03:55Z"
    mac: ENC[AES256_GCM,data:x7qMmS4JOQyLc2Jn90e+99Aj4IOtCwIVk+CI8eHurTm8uJ73tJXwCLX1/oE5xDgmhdJWQx/5dUSJLggRSIjTk1vkRrWxAz7OSiavxr41mwDJk4SVuZh7dQahQ3K+87QOGr/ndleWuhfs3dCzw4+X4us5uJN151LGC7Y9IhH6qVY=,iv:oWjiBPaNk5WO0RR26NaCUUY6cPcgicSFiZFu89L51XY=,tag:nZfA/hXpC49dennFirPiMQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: coder-env-secret
    namespace: coder
type: Opaque
stringData:
    CODER_PG_CONNECTION_URL: ENC[AES256_GCM,data:22+G18qd1izRiTYN66FNBRZk1h3Ri4jo866JCfy5itV1R63xltnT/4Z1NxLnfwphxwghI5D3KhH8+MD4HWiLVC2onrE42FI6p1qHf3E0vAfYrBrHZnEoktnUtbLAits4NarSKjgTLw==,iv:PSndlGQGQvEKBpqrKH9K+cHUA7eZsnio+2OXP2ts+MA=,tag:7SzrvQWIvEVmQLLzLMaE9A==,type:str]
    CODER_ACCESS_URL: ENC[AES256_GCM,data:ulvsTqKqYfzJG+g4l23aZ4xHaUhTpH4=,iv:Uqe3xs713tzw8Vpbr7wH7UzlHxkblOKsQxRSgD/Mwb4=,tag:AMlKhMUpl84+wOj8G9y6qw==,type:str]
    CODER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:gMZoGt0=,iv:JWth/QFNEeDKZm2vfZUaxrIReVtKYy5D1DnU40kIroY=,tag:9TDE2ot+WrdH6IQdpbVg3A==,type:str]
    CODER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:vL+XcMaqnvAOjG8pbaAFRi8tKm6nFFW5UFQIfel5ffQcgFDc,iv:cDlE9QCC0hP/yJ6i+cDvuLiFyAolZG0jA/xbPSPI0x0=,tag:6HX5vsqpc9tZn4Cr3cawIA==,type:str]
    CODER_OIDC_ISSUER_URL: ENC[AES256_GCM,data:3I3Cd2ViZsDUIUA+CdGM8hOLeJIa4A==,iv:uzkeUDUiZFoFqCBSaAFC3Eevl+pT7MkLKX6B15gMSjE=,tag:Bb2ILQSDYadwjCu03heOow==,type:str]
    CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE: ENC[AES256_GCM,data:NR1NurE=,iv:rQygcwiWdOXs6TP16u0jPOicY943MdZiXSXhiTBfdYc=,tag:CHE0LPgBzufk18sarx9ghQ==,type:str]
    CODER_PROMETHEUS_ENABLE: ENC[AES256_GCM,data:N7ZVoQ==,iv:hHxjsw+Pe6a+OqoD9NGeueY4wPlo+n1gupQPAkFZKW4=,tag:WcJBUK/9n7rSUDqQqcLLEA==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQnRDTmwvZnB6RWNKc1BU
            TWhxNWJYYUdkZHArMWtqeG1rUlN4eGNUL0drCmdMWDhXdisxSDZqa0I5Z0JqWFhi
            Y1M2dFRUWFNLL1AxSGw5M2dUd0g1QzAKLS0tIE5nN0FQMHJVazd4STJiKzk5elI2
            NDRMdXN6blU4RkR5NTVOTitVOEJLbTQKmBf+ZA36CqndzeP5SXRGRRoZYF1jpzE4
            OxLPEalNxxhIRZTfjGzKvZNny3+6ueteOjI5eWlJ/mTb7yvXWQsjHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:03:55Z"
    mac: ENC[AES256_GCM,data:x7qMmS4JOQyLc2Jn90e+99Aj4IOtCwIVk+CI8eHurTm8uJ73tJXwCLX1/oE5xDgmhdJWQx/5dUSJLggRSIjTk1vkRrWxAz7OSiavxr41mwDJk4SVuZh7dQahQ3K+87QOGr/ndleWuhfs3dCzw4+X4us5uJN151LGC7Y9IhH6qVY=,iv:oWjiBPaNk5WO0RR26NaCUUY6cPcgicSFiZFu89L51XY=,tag:nZfA/hXpC49dennFirPiMQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: coder
    namespace: coder
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://helm.coder.com/v2
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQnRDTmwvZnB6RWNKc1BU
            TWhxNWJYYUdkZHArMWtqeG1rUlN4eGNUL0drCmdMWDhXdisxSDZqa0I5Z0JqWFhi
            Y1M2dFRUWFNLL1AxSGw5M2dUd0g1QzAKLS0tIE5nN0FQMHJVazd4STJiKzk5elI2
            NDRMdXN6blU4RkR5NTVOTitVOEJLbTQKmBf+ZA36CqndzeP5SXRGRRoZYF1jpzE4
            OxLPEalNxxhIRZTfjGzKvZNny3+6ueteOjI5eWlJ/mTb7yvXWQsjHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:03:55Z"
    mac: ENC[AES256_GCM,data:x7qMmS4JOQyLc2Jn90e+99Aj4IOtCwIVk+CI8eHurTm8uJ73tJXwCLX1/oE5xDgmhdJWQx/5dUSJLggRSIjTk1vkRrWxAz7OSiavxr41mwDJk4SVuZh7dQahQ3K+87QOGr/ndleWuhfs3dCzw4+X4us5uJN151LGC7Y9IhH6qVY=,iv:oWjiBPaNk5WO0RR26NaCUUY6cPcgicSFiZFu89L51XY=,tag:nZfA/hXpC49dennFirPiMQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: coder
    namespace: coder
spec:
    chart:
        spec:
            chart: coder
            sourceRef:
                kind: HelmRepository
                name: coder
            version: '*'
    interval: 1m0s
    values:
        coder:
            env:
                - name: CODER_PG_CONNECTION_URL
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:pnjuJtxdeqWLZEJvPPP1FcLcVv8jnVs=,iv:xZhJ9k+CGPQ2TGIGicAtBPIj+dW6moAs2nZNu7wzs+E=,tag:zvXnvSBPssUvuqvJmTax9Q==,type:str]
                - name: CODER_ACCESS_URL
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:GwytpPnJLLg5Ttcpn5qtzw==,iv:f1s6ntYfBjcdyXWydxrRjE+H61sHK/Y0uhiA66Co3wg=,tag:Jou9Iz/e3XtiIayLKhNaoA==,type:str]
                - name: CODER_OIDC_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:HhL7n9LX7q3ycDhwY3F+r1tBT3k=,iv:8NmiLdheP9Lo5swvyioecjMwGLMa0+XD9wCej0CGREQ=,tag:taBLXPEZj+qKmPVPx/wPJg==,type:str]
                - name: CODER_OIDC_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:lSj/g300UVx7Cd8X8MqCHjeOivOEAFUX,iv:pmmcdYCDQZqnd+LF7o9lnbBzutplxvPe5rDtes3PhTM=,tag:5lCvv2BrxkJVyLmCbAwB5w==,type:str]
                - name: CODER_OIDC_ISSUER_URL
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:ZPQOeMLXhEO9bl2uS8RxAJBEfY7F,iv:jjWzcAHGXPE/GRCxEVhlRSuIKCYtRnsvKL4YDNcq1Wk=,tag:vWc9AQL4igSljeWusYi8GA==,type:str]
                - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:Y1akFp+I/E7rwuTFrRT7Jq7T8qr/5HJdrZVpIt7SCA/OgMjaUTViD3qamg==,iv:qnHpzP72FqhmAVJ+CRGqjUNHs15Z+Q1QXUqGDCGrdvE=,tag:CUyAqakS2vvtTA3ejDzZyw==,type:str]
                - name: CODER_PROMETHEUS_ENABLE
                  valueFrom:
                    secretKeyRef:
                        name: coder-env-secret
                        key: ENC[AES256_GCM,data:ETZqJwxbVmVWZjPrzXKqswPU1nZNbKM=,iv:KZaJa14s21f46Zf+KbZBmhQ1JRi+7JBFjdfuuTdhPCc=,tag:ihFxPjsxzwqtg5lGtjHFsw==,type:str]
            resources:
                limits:
                    cpu: 1000m
                    memory: 1024Mi
                requests:
                    cpu: 500m
                    memory: 512Mi
            ingress:
                enable: true
                className: traefik
                host: coder.phorge.fr
                annotations:
                    cert-manager.io/cluster-issuer: letsencrypt
                tls:
                    enable: true
                    secretName: coder-tls
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQnRDTmwvZnB6RWNKc1BU
            TWhxNWJYYUdkZHArMWtqeG1rUlN4eGNUL0drCmdMWDhXdisxSDZqa0I5Z0JqWFhi
            Y1M2dFRUWFNLL1AxSGw5M2dUd0g1QzAKLS0tIE5nN0FQMHJVazd4STJiKzk5elI2
            NDRMdXN6blU4RkR5NTVOTitVOEJLbTQKmBf+ZA36CqndzeP5SXRGRRoZYF1jpzE4
            OxLPEalNxxhIRZTfjGzKvZNny3+6ueteOjI5eWlJ/mTb7yvXWQsjHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:03:55Z"
    mac: ENC[AES256_GCM,data:x7qMmS4JOQyLc2Jn90e+99Aj4IOtCwIVk+CI8eHurTm8uJ73tJXwCLX1/oE5xDgmhdJWQx/5dUSJLggRSIjTk1vkRrWxAz7OSiavxr41mwDJk4SVuZh7dQahQ3K+87QOGr/ndleWuhfs3dCzw4+X4us5uJN151LGC7Y9IhH6qVY=,iv:oWjiBPaNk5WO0RR26NaCUUY6cPcgicSFiZFu89L51XY=,tag:nZfA/hXpC49dennFirPiMQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: v1
kind: Service
metadata:
    name: coder-prometheus
    namespace: coder
spec:
    clusterIP: None
    ports:
        - name: prom-http
          port: 2112
          protocol: TCP
          targetPort: 2112
    selector:
        app.kubernetes.io/instance: coder
        app.kubernetes.io/name: coder
    type: ClusterIP
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQnRDTmwvZnB6RWNKc1BU
            TWhxNWJYYUdkZHArMWtqeG1rUlN4eGNUL0drCmdMWDhXdisxSDZqa0I5Z0JqWFhi
            Y1M2dFRUWFNLL1AxSGw5M2dUd0g1QzAKLS0tIE5nN0FQMHJVazd4STJiKzk5elI2
            NDRMdXN6blU4RkR5NTVOTitVOEJLbTQKmBf+ZA36CqndzeP5SXRGRRoZYF1jpzE4
            OxLPEalNxxhIRZTfjGzKvZNny3+6ueteOjI5eWlJ/mTb7yvXWQsjHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:03:55Z"
    mac: ENC[AES256_GCM,data:x7qMmS4JOQyLc2Jn90e+99Aj4IOtCwIVk+CI8eHurTm8uJ73tJXwCLX1/oE5xDgmhdJWQx/5dUSJLggRSIjTk1vkRrWxAz7OSiavxr41mwDJk4SVuZh7dQahQ3K+87QOGr/ndleWuhfs3dCzw4+X4us5uJN151LGC7Y9IhH6qVY=,iv:oWjiBPaNk5WO0RR26NaCUUY6cPcgicSFiZFu89L51XY=,tag:nZfA/hXpC49dennFirPiMQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: coder-service-monitor
    namespace: coder
spec:
    endpoints:
        - port: prom-http
          interval: 10s
          scrapeTimeout: 10s
    namespaceSelector:
        matchNames:
            - coder
    selector:
        matchLabels:
            app.kubernetes.io/name: coder
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQnRDTmwvZnB6RWNKc1BU
            TWhxNWJYYUdkZHArMWtqeG1rUlN4eGNUL0drCmdMWDhXdisxSDZqa0I5Z0JqWFhi
            Y1M2dFRUWFNLL1AxSGw5M2dUd0g1QzAKLS0tIE5nN0FQMHJVazd4STJiKzk5elI2
            NDRMdXN6blU4RkR5NTVOTitVOEJLbTQKmBf+ZA36CqndzeP5SXRGRRoZYF1jpzE4
            OxLPEalNxxhIRZTfjGzKvZNny3+6ueteOjI5eWlJ/mTb7yvXWQsjHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:03:55Z"
    mac: ENC[AES256_GCM,data:x7qMmS4JOQyLc2Jn90e+99Aj4IOtCwIVk+CI8eHurTm8uJ73tJXwCLX1/oE5xDgmhdJWQx/5dUSJLggRSIjTk1vkRrWxAz7OSiavxr41mwDJk4SVuZh7dQahQ3K+87QOGr/ndleWuhfs3dCzw4+X4us5uJN151LGC7Y9IhH6qVY=,iv:oWjiBPaNk5WO0RR26NaCUUY6cPcgicSFiZFu89L51XY=,tag:nZfA/hXpC49dennFirPiMQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
