apiVersion: v1
kind: Namespace
metadata:
    name: dexidp
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc0o4NHVTUldNbWgwY01D
            TjJIbTBjS2NId0lMNlZWbHZCSGNDVGJMVlU0CjZCYkdydVBkTDVBK1FNMTY1WDNu
            bURxM05wdGZkWnR2bkRlYk5uQlhzVEkKLS0tIHUweHNld21wUEkxOGkxNVRjVitm
            VFNMb0VMd0pNcGlsZkxVT3VLemZ2STgKxYxm9hY4zrmO0wUXViLdEGwHYp82bINo
            iYJLwcXh7xsJasImMRjfbPbV6zaMlIpTksMBcnWqHhvUzOwp1Xv2Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T23:12:02Z"
    mac: ENC[AES256_GCM,data:2rVn0L3ewYOnQKN+Q6blD2Nu8qg9BFrb2oA4+sQELd4JsRAc5QLWim8YKXhLMhwuaRhVkpyzp81iHDvlksPmKTz0/bFBhVvxQ41KkBYPHXVQJut/GQ+aXaMcouz43kx9jxEYf3fxS/6vO79AyGOOAKw4vXH8HYo/wVZLOf/jY0E=,iv:po3SSWELbiX/7UVEowGmz4IdBNwPJaXZbrnVviQaq5U=,tag:R/a9ktbHp1GTYrn+TUg4bw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: dexidp
    namespace: dexidp
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://charts.dexidp.io
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc0o4NHVTUldNbWgwY01D
            TjJIbTBjS2NId0lMNlZWbHZCSGNDVGJMVlU0CjZCYkdydVBkTDVBK1FNMTY1WDNu
            bURxM05wdGZkWnR2bkRlYk5uQlhzVEkKLS0tIHUweHNld21wUEkxOGkxNVRjVitm
            VFNMb0VMd0pNcGlsZkxVT3VLemZ2STgKxYxm9hY4zrmO0wUXViLdEGwHYp82bINo
            iYJLwcXh7xsJasImMRjfbPbV6zaMlIpTksMBcnWqHhvUzOwp1Xv2Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T23:12:02Z"
    mac: ENC[AES256_GCM,data:2rVn0L3ewYOnQKN+Q6blD2Nu8qg9BFrb2oA4+sQELd4JsRAc5QLWim8YKXhLMhwuaRhVkpyzp81iHDvlksPmKTz0/bFBhVvxQ41KkBYPHXVQJut/GQ+aXaMcouz43kx9jxEYf3fxS/6vO79AyGOOAKw4vXH8HYo/wVZLOf/jY0E=,iv:po3SSWELbiX/7UVEowGmz4IdBNwPJaXZbrnVviQaq5U=,tag:R/a9ktbHp1GTYrn+TUg4bw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: dex
    namespace: dexidp
spec:
    chart:
        spec:
            chart: dex
            sourceRef:
                kind: HelmRepository
                name: dexidp
            version: '*'
    interval: 1m0s
    values:
        ingress:
            enabled: true
            className: nginx
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
            hosts:
                - host: auth.phorge.fr
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
            tls:
                - secretName: dexidp-tls
                  hosts:
                    - auth.phorge.fr
        config:
            issuer: https://auth.phorge.fr
            web:
                allowedOrigins:
                    - '*'
            oauth2:
                responseTypes:
                    - code
                skipApprovalScreen: true
                alwaysShowLoginScreen: false
            storage:
                type: memory
            connectors:
                - type: oauth
                  id: ENC[AES256_GCM,data:OSqVZR4=,iv:tPBTjYdBhU4ii34yP6LOj3JSApe+s3br5M4zE9AEH1M=,tag:siogdo8i/SRlI9Xc/davWA==,type:str]
                  name: Gitea
                  config:
                    userIDKey: name
                    userNameKey: name
                    issuer: https://git.phorge.fr/
                    clientID: ENC[AES256_GCM,data:SOKw1oEptjaSlXWSJQoiAP4nvdfFiULSz0lSAplwZUmVPVoU,iv:cjW7H45Wdf8muUjM3DWoOco/xU52SA2gdC/ffX5xPCU=,tag:yr4vazN9qB4Qqqe3KOjjYA==,type:str]
                    clientSecret: ENC[AES256_GCM,data:aEhQiK19r9tc/cfhS2KUBt68HyGFZyw0qFnRmFZQyHkvV1fWxlCFb4FayTOyg4MtU9c8Wpa77mY=,iv:Ix4LEScs7i9VY51s18kSHiGBfOGdOJ/hiQSTGLlnuDM=,tag:gUCU1fVGeeOHr82ezt1ucg==,type:str]
                    redirectURI: https://auth.phorge.fr/callback
                    # userNameKey: login
                    scopes:
                        - groups
                        - email
                        - name
                        - profile
                    tokenURL: https://git.phorge.fr/login/oauth/access_token
                    authorizationURL: https://git.phorge.fr/login/oauth/authorize
                    userInfoURL: https://git.phorge.fr/login/oauth/userinfo
                    loadAllGroups: true
                    teamNameField: slug
                    useLoginAsID: false
            staticClients:
                - id: ENC[AES256_GCM,data:dVS33UU=,iv:9aer4ta6q6NXNRpF0+D+uPLZxPBRyMX35hnAqzP6UXM=,tag:4GMQGLqUSDuMoVH29qfEnQ==,type:str]
                  name: Incus
                  public: true
                  redirectURIs:
                    - https://iaas.phorge.fr/oidc/callback
                    - /device/callback
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc0o4NHVTUldNbWgwY01D
            TjJIbTBjS2NId0lMNlZWbHZCSGNDVGJMVlU0CjZCYkdydVBkTDVBK1FNMTY1WDNu
            bURxM05wdGZkWnR2bkRlYk5uQlhzVEkKLS0tIHUweHNld21wUEkxOGkxNVRjVitm
            VFNMb0VMd0pNcGlsZkxVT3VLemZ2STgKxYxm9hY4zrmO0wUXViLdEGwHYp82bINo
            iYJLwcXh7xsJasImMRjfbPbV6zaMlIpTksMBcnWqHhvUzOwp1Xv2Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T23:12:02Z"
    mac: ENC[AES256_GCM,data:2rVn0L3ewYOnQKN+Q6blD2Nu8qg9BFrb2oA4+sQELd4JsRAc5QLWim8YKXhLMhwuaRhVkpyzp81iHDvlksPmKTz0/bFBhVvxQ41KkBYPHXVQJut/GQ+aXaMcouz43kx9jxEYf3fxS/6vO79AyGOOAKw4vXH8HYo/wVZLOf/jY0E=,iv:po3SSWELbiX/7UVEowGmz4IdBNwPJaXZbrnVviQaq5U=,tag:R/a9ktbHp1GTYrn+TUg4bw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
