apiVersion: v1
kind: Namespace
metadata:
    name: dexidp
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFalo5U2dsb2l6d3dSS1k1
            Ui9YMW9RcUJtZ3VvWU0zbFIwN0NtcTBXSVZRClZVQ2FtU3pTN1cxNkdhUklCajBi
            RVl3QjRKRXd3Qkw2dHA4d2dlQ3VRZFUKLS0tICt6RTUrNXZ0ZFlEa2R3dTVCTXNv
            RzBUQXc3NWVkRnEwcHZrdTRJeHBkR1EKjw8jl7zv8HN5/rjXCAuCM+OM6jeo6XC1
            9VZkSAGUU9hIZOvKhQOtf00GoLDaD+7VeM/jJjF0XH3/WHwaD4yDYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T23:32:51Z"
    mac: ENC[AES256_GCM,data:PibI2SsIkQoBEhvMslgSYvQpl/d4wEzJnYUXirUqw77qP3K16BSqZZD5ykuBdp+qM3sG8gMi4hdajLEjIwOO+f5oYUFq7zBVmsfkYpn4gbMBsKQWkMQDmONak7WVjtqP0w2f0QfCUiieLTSNwF6P0ObjnKVgbPXJNTnv77SzZtM=,iv:gHae+QRSEkah7wCb/1HxgqSilwGjHYJ59OMj+ZBV2T8=,tag:No/znH2zNTs0FL6JNHNMhg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: dexidp
    namespace: dexidp
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://charts.dexidp.io
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFalo5U2dsb2l6d3dSS1k1
            Ui9YMW9RcUJtZ3VvWU0zbFIwN0NtcTBXSVZRClZVQ2FtU3pTN1cxNkdhUklCajBi
            RVl3QjRKRXd3Qkw2dHA4d2dlQ3VRZFUKLS0tICt6RTUrNXZ0ZFlEa2R3dTVCTXNv
            RzBUQXc3NWVkRnEwcHZrdTRJeHBkR1EKjw8jl7zv8HN5/rjXCAuCM+OM6jeo6XC1
            9VZkSAGUU9hIZOvKhQOtf00GoLDaD+7VeM/jJjF0XH3/WHwaD4yDYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T23:32:51Z"
    mac: ENC[AES256_GCM,data:PibI2SsIkQoBEhvMslgSYvQpl/d4wEzJnYUXirUqw77qP3K16BSqZZD5ykuBdp+qM3sG8gMi4hdajLEjIwOO+f5oYUFq7zBVmsfkYpn4gbMBsKQWkMQDmONak7WVjtqP0w2f0QfCUiieLTSNwF6P0ObjnKVgbPXJNTnv77SzZtM=,iv:gHae+QRSEkah7wCb/1HxgqSilwGjHYJ59OMj+ZBV2T8=,tag:No/znH2zNTs0FL6JNHNMhg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: dex
    namespace: dexidp
spec:
    chart:
        spec:
            chart: dex
            sourceRef:
                kind: HelmRepository
                name: dexidp
            version: '*'
    interval: 1m0s
    values:
        ingress:
            enabled: true
            className: nginx
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
            hosts:
                - host: auth.phorge.fr
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
            tls:
                - secretName: dexidp-tls
                  hosts:
                    - auth.phorge.fr
        config:
            issuer: https://auth.phorge.fr
            web:
                allowedOrigins:
                    - '*'
            oauth2:
                responseTypes:
                    - code
                skipApprovalScreen: true
                alwaysShowLoginScreen: false
            storage:
                type: memory
            connectors:
                - type: github
                  id: ENC[AES256_GCM,data:kLO3KJN3,iv:eIPassPp3xQtgseeHbZQ8uLyKgLSgbAA+q2YKEKroUA=,tag:KCf6d7zl4bfw/BUX7M10Rw==,type:str]
                  name: GitHub
                  config:
                    clientID: ENC[AES256_GCM,data:o2wB+RJiGoiifpDKmaoWzYFYoMA=,iv:Oy8bZifG5OE2hmNRBy5l6+FV1LZizJ3QFlF+Lxa7neg=,tag:xB1uC0XkCXrSN/L/FtyslQ==,type:str]
                    clientSecret: ENC[AES256_GCM,data:NZ67FVKg9gdJvcNLV7Jf9xenm143iGBr2J07fC4fbBwRORsVCNZpeg==,iv:vGg6uNZ6EeKlxx+7qLqA0zXlcb3H3UFv/mMKNKD7M2c=,tag:LHmwOO+zUC5mRt21YGGkZg==,type:str]
                    redirectURI: https://auth.phorge.fr/callback
                    scopes:
                        - groups
                        - email
                    orgs:
                        - name: phorge-fr
                          teams:
                            - admins
                    loadAllGroups: true
                    teamNameField: slug
                    useLoginAsID: false
            staticClients:
                # - id: <PLACEHOLDER>
                #   name: Grafana
                #   secret: <PLACEHOLDER>
                #   redirectURIs:
                #     - https://monitoring.phorge.fr/login/generic_oauth
                - id: ENC[AES256_GCM,data:e2H+w6+aue70CQ==,iv:8sWXnOYw2Ey4pUzZ2sfkbLi2g5ma5cWHmFYjb7p4w5M=,tag:pMOKqv/9NGiHoKLFvsaelg==,type:str]
                  name: FrontPlane
                  secret: ENC[AES256_GCM,data:h/znJwDYXZ0GO7qLxwhnlYazSJ+MKeT4GxHY,iv:pQA2OSX8hAM8wR2wYihjBwYdZyfx3HL7p5+rVA8/XBI=,tag:je40/Bb3kJW1BA3sy2o+hg==,type:str]
                  redirectURIs:
                    - https://headlamp.frontplane.phorge.fr/oidc-callback
                - id: ENC[AES256_GCM,data:6bg2EG4=,iv:APtprGJKbpuSpoWhKFs1QDg1rUEUgvYtrPbGxOn7Ohc=,tag:+Vz56rCkbIdsJRw1K+fM1w==,type:str]
                  name: Incus
                  public: true
                  redirectURIs:
                    - https://iaas.phorge.fr/oidc/callback
                    - /device/callback
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFalo5U2dsb2l6d3dSS1k1
            Ui9YMW9RcUJtZ3VvWU0zbFIwN0NtcTBXSVZRClZVQ2FtU3pTN1cxNkdhUklCajBi
            RVl3QjRKRXd3Qkw2dHA4d2dlQ3VRZFUKLS0tICt6RTUrNXZ0ZFlEa2R3dTVCTXNv
            RzBUQXc3NWVkRnEwcHZrdTRJeHBkR1EKjw8jl7zv8HN5/rjXCAuCM+OM6jeo6XC1
            9VZkSAGUU9hIZOvKhQOtf00GoLDaD+7VeM/jJjF0XH3/WHwaD4yDYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T23:32:51Z"
    mac: ENC[AES256_GCM,data:PibI2SsIkQoBEhvMslgSYvQpl/d4wEzJnYUXirUqw77qP3K16BSqZZD5ykuBdp+qM3sG8gMi4hdajLEjIwOO+f5oYUFq7zBVmsfkYpn4gbMBsKQWkMQDmONak7WVjtqP0w2f0QfCUiieLTSNwF6P0ObjnKVgbPXJNTnv77SzZtM=,iv:gHae+QRSEkah7wCb/1HxgqSilwGjHYJ59OMj+ZBV2T8=,tag:No/znH2zNTs0FL6JNHNMhg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
