apiVersion: v1
kind: Namespace
metadata:
    name: gitea
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UWlnaklrOHBmdit0QW01
            STRydWgrbnptV3pIUk9ORFdRcGZGcXR4UmhNCmEraGd1T1QvQ3M1cHY0TDN0MW9v
            Z0FzcG5nUVZOT1NlMnRKU1BOeGxNYk0KLS0tIEJFWVpkWCtNUFpBR2ttU0NJbUZi
            M1hHQUNWdWVJUXVqd1dvRHpqYVFKY1UKbaAUeZs5izUs0Gs/L3hCUTeggUuCWetA
            u5CnYCmSL1v9ZheXokGWyi6qvlZYaTq1zy6DidAqdLEz8MPs71z69g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T18:20:37Z"
    mac: ENC[AES256_GCM,data:mQWXZ3SX0AmdfBsguTf5bJI9J6p9KvyZysc5nRsI7gG+Y9cgoVsKUGdr82t+rerJLOgytx4Ln7CGfzqsK3CJcKjBY+gq0MTo5D9NbyU09eGc1CnQYqHwch3bs1NQEXE7eOLHRsUyoh7MkNyDIR9gjt9PfZDrfMbTXaN5DgnR+Jc=,iv:pXWAtPCP0s2h60doxZWqyaW942Ys4UbfENCmmOPmUyg=,tag:CxATKEuk2V0pen/h6oNaYw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: gitea
    namespace: gitea
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://dl.gitea.com/charts/
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UWlnaklrOHBmdit0QW01
            STRydWgrbnptV3pIUk9ORFdRcGZGcXR4UmhNCmEraGd1T1QvQ3M1cHY0TDN0MW9v
            Z0FzcG5nUVZOT1NlMnRKU1BOeGxNYk0KLS0tIEJFWVpkWCtNUFpBR2ttU0NJbUZi
            M1hHQUNWdWVJUXVqd1dvRHpqYVFKY1UKbaAUeZs5izUs0Gs/L3hCUTeggUuCWetA
            u5CnYCmSL1v9ZheXokGWyi6qvlZYaTq1zy6DidAqdLEz8MPs71z69g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T18:20:37Z"
    mac: ENC[AES256_GCM,data:mQWXZ3SX0AmdfBsguTf5bJI9J6p9KvyZysc5nRsI7gG+Y9cgoVsKUGdr82t+rerJLOgytx4Ln7CGfzqsK3CJcKjBY+gq0MTo5D9NbyU09eGc1CnQYqHwch3bs1NQEXE7eOLHRsUyoh7MkNyDIR9gjt9PfZDrfMbTXaN5DgnR+Jc=,iv:pXWAtPCP0s2h60doxZWqyaW942Ys4UbfENCmmOPmUyg=,tag:CxATKEuk2V0pen/h6oNaYw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: gitea
    namespace: gitea
spec:
    chart:
        spec:
            chart: gitea
            sourceRef:
                kind: HelmRepository
                name: gitea
            version: '*'
    interval: 1m0s
    values:
        postExtraInitContainers:
            - name: phorge-theme-install
              image: alpine
              command:
                - sh
                - -c
                - |
                  set -e
                  apk add --no-cache rsync wget unzip
                  mkdir -p /data/gitea
                  wget -O /tmp/main.zip https://github.com/phorge-fr/gitea-phorge-theme/archive/refs/heads/main.zip
                  unzip -n /tmp/main.zip -d /tmp/
                  rsync -a --inplace --checksum /tmp/gitea-phorge-theme-main/ /data/gitea/
                  chown -R 1000:1000 /data/gitea
              volumeMounts:
                - name: data
                  mountPath: /data
        nodeSelector:
            node-role.kubernetes.io/worker: "true"
        gitea:
            admin:
                email: ENC[AES256_GCM,data:qGjPSYbUS3VBEpc3UAGrsQ==,iv:vPb6F8jkun3rw2nenl1pLZFgi587O/y/3NWdl08PkkQ=,tag:PKEO//AncFr60FhxVMSJJw==,type:str]
                password: ENC[AES256_GCM,data:5ZqNJJ7lrWmXl0O0CpSWMXxcgxk=,iv:zj2D6ygRk+69dZx/nuU7+L+OVYPI1PqD1Z2ZHnEzQ10=,tag:3LjIa3Vx8N8WLH169PLYmQ==,type:str]
                passwordMode: keepUpdated
                username: ENC[AES256_GCM,data:2S3rlZ4Rj9DmQYY=,iv:RXMleFqBsbq27zB6mM4y8Bkh3Ottk7faRQnRs/Jyb0g=,tag:UEkHZBq1qNeFrK4AHkLjig==,type:str]
            config:
                APP_NAME: Ï†orge
                server:
                    SSH_LISTEN_PORT: 2222
                    SSH_PORT: 22
                    ROOT_URL: https://git.phorge.fr/
                service:
                    DISABLE_REGISTRATION: "false"
                ui:
                    THEMES: phorge-dark
                    DEFAULT_THEME: phorge-dark
                repository:
                    ACCESS_CONTROL_ALLOW_ORIGIN: '*'
        ingress:
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
                nginx.ingress.kubernetes.io/proxy-body-size: 1024m
            className: nginx
            enabled: true
            hosts:
                - host: git.phorge.fr
                  paths:
                    - path: /
            pathType: Prefix
            tls:
                - hosts:
                    - git.phorge.fr
                  secretName: gitea
        persistence:
            accessModes:
                - ReadWriteOnce
            annotations:
                helm.sh/resource-policy: keep
            claimName: gitea-shared-storage
            create: true
            enabled: true
            labels: {}
            mount: true
            size: 4Gi
            storageClass: null
            subPath: null
            volumeName: ""
        postgresql:
            enabled: true
            global:
                postgresql:
                    auth:
                        database: gitea
                        password: ENC[AES256_GCM,data:9Xg6iaI=,iv:Q9/F6qJR71BLjwydBZEWNnUj+U6+7WYWZ4LsQoYDcfw=,tag:QETb4jk7wJlrJNbmcd1oYQ==,type:str]
                        username: ENC[AES256_GCM,data:sTQnb2w=,iv:xtVO7PIwj6Jbiovsc129M8w3t3Yhr8ArsK84FhUzJTk=,tag:6RaNp0w/K+7Jjp1IiOjIhA==,type:str]
                    service:
                        ports:
                            postgresql: 5432
            image:
                repository: bitnamilegacy/postgresql
            metrics:
                image:
                    repository: bitnamilegacy/postgres-exporter
            primary:
                nodeSelector:
                    node-role.kubernetes.io/worker: "true"
                persistence:
                    size: 10Gi
            volumePermissions:
                image:
                    repository: bitnamilegacy/os-shell
        postgresql-ha:
            enabled: false
        service:
            ssh:
                annotations: {}
                clusterIP: None
                externalIPs: null
                externalTrafficPolicy: null
                hostPort: null
                ipFamilies: null
                ipFamilyPolicy: null
                labels: {}
                loadBalancerClass: null
                loadBalancerIP: 10.0.0.13
                loadBalancerSourceRanges: []
                nodePort: null
                port: 22
                type: LoadBalancer
        signing:
            enabled: false
            existingSecret: ""
            gpgHome: /data/git/.gnupg
            privateKey: ""
        valkey:
            primary:
                nodeSelector:
                    node-role.kubernetes.io/worker: "true"
                persistence:
                    size: 1Gi
            enabled: true
        valkey-cluster:
            enabled: false
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UWlnaklrOHBmdit0QW01
            STRydWgrbnptV3pIUk9ORFdRcGZGcXR4UmhNCmEraGd1T1QvQ3M1cHY0TDN0MW9v
            Z0FzcG5nUVZOT1NlMnRKU1BOeGxNYk0KLS0tIEJFWVpkWCtNUFpBR2ttU0NJbUZi
            M1hHQUNWdWVJUXVqd1dvRHpqYVFKY1UKbaAUeZs5izUs0Gs/L3hCUTeggUuCWetA
            u5CnYCmSL1v9ZheXokGWyi6qvlZYaTq1zy6DidAqdLEz8MPs71z69g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T18:20:37Z"
    mac: ENC[AES256_GCM,data:mQWXZ3SX0AmdfBsguTf5bJI9J6p9KvyZysc5nRsI7gG+Y9cgoVsKUGdr82t+rerJLOgytx4Ln7CGfzqsK3CJcKjBY+gq0MTo5D9NbyU09eGc1CnQYqHwch3bs1NQEXE7eOLHRsUyoh7MkNyDIR9gjt9PfZDrfMbTXaN5DgnR+Jc=,iv:pXWAtPCP0s2h60doxZWqyaW942Ys4UbfENCmmOPmUyg=,tag:CxATKEuk2V0pen/h6oNaYw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
