apiVersion: v1
kind: Namespace
metadata:
    name: gitea
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc003L0xFc2U1L0N5cjRZ
            UndpRHhYNjMrVFR1Y0tPZGUxc2dmWVhWblZJCiswRDdWMjdONnpsWk1JUGZ1K0Vw
            b1BBSVArT3hFelRIc1pGVlFndWdoWVUKLS0tIGFRaVBrY1hNeDltREpsbTBGRmNO
            d05TSmxhQnluNVhtWGUwZGFEcjZHaDQKJJ2K6KUUIZYVLuGTM0XMb/ANr6Ux9X04
            ZryPKAwx3E6hi8qs2vtcMBEFcTGYvuQ5q4KeVp3DA1av3y61CRaNvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T19:22:58Z"
    mac: ENC[AES256_GCM,data:GuNs6K9wGCTEzNC5+R8sK40WrIEtagSJbT9uQOvCKItumM4u5wtn38e4f2f8f7eoOqE7eZNg9PI9RhwrQ07FlqDea98blmqZrH0aTZ09kjUUgp6UV+aFHas+ugnGk0Mv5VOUTegkr29+w3ain3YyR720sGbuYxECciQwSyuEjJc=,iv:hyQ5XbBf3OpXVBLHAhfrb2UhGlv9XWyBT54NNfVEj/A=,tag:H9n0AmQpxn5ybqI4QuS70A==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: gitea-packages-pvc
    namespace: gitea
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 200Gi
    storageClassName: nfs-uncritical
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc003L0xFc2U1L0N5cjRZ
            UndpRHhYNjMrVFR1Y0tPZGUxc2dmWVhWblZJCiswRDdWMjdONnpsWk1JUGZ1K0Vw
            b1BBSVArT3hFelRIc1pGVlFndWdoWVUKLS0tIGFRaVBrY1hNeDltREpsbTBGRmNO
            d05TSmxhQnluNVhtWGUwZGFEcjZHaDQKJJ2K6KUUIZYVLuGTM0XMb/ANr6Ux9X04
            ZryPKAwx3E6hi8qs2vtcMBEFcTGYvuQ5q4KeVp3DA1av3y61CRaNvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T19:22:58Z"
    mac: ENC[AES256_GCM,data:GuNs6K9wGCTEzNC5+R8sK40WrIEtagSJbT9uQOvCKItumM4u5wtn38e4f2f8f7eoOqE7eZNg9PI9RhwrQ07FlqDea98blmqZrH0aTZ09kjUUgp6UV+aFHas+ugnGk0Mv5VOUTegkr29+w3ain3YyR720sGbuYxECciQwSyuEjJc=,iv:hyQ5XbBf3OpXVBLHAhfrb2UhGlv9XWyBT54NNfVEj/A=,tag:H9n0AmQpxn5ybqI4QuS70A==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: gitea-lfs-pvc
    namespace: gitea
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Gi
    storageClassName: nfs-uncritical
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc003L0xFc2U1L0N5cjRZ
            UndpRHhYNjMrVFR1Y0tPZGUxc2dmWVhWblZJCiswRDdWMjdONnpsWk1JUGZ1K0Vw
            b1BBSVArT3hFelRIc1pGVlFndWdoWVUKLS0tIGFRaVBrY1hNeDltREpsbTBGRmNO
            d05TSmxhQnluNVhtWGUwZGFEcjZHaDQKJJ2K6KUUIZYVLuGTM0XMb/ANr6Ux9X04
            ZryPKAwx3E6hi8qs2vtcMBEFcTGYvuQ5q4KeVp3DA1av3y61CRaNvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T19:22:58Z"
    mac: ENC[AES256_GCM,data:GuNs6K9wGCTEzNC5+R8sK40WrIEtagSJbT9uQOvCKItumM4u5wtn38e4f2f8f7eoOqE7eZNg9PI9RhwrQ07FlqDea98blmqZrH0aTZ09kjUUgp6UV+aFHas+ugnGk0Mv5VOUTegkr29+w3ain3YyR720sGbuYxECciQwSyuEjJc=,iv:hyQ5XbBf3OpXVBLHAhfrb2UhGlv9XWyBT54NNfVEj/A=,tag:H9n0AmQpxn5ybqI4QuS70A==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: gitea
    namespace: gitea
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://dl.gitea.com/charts/
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc003L0xFc2U1L0N5cjRZ
            UndpRHhYNjMrVFR1Y0tPZGUxc2dmWVhWblZJCiswRDdWMjdONnpsWk1JUGZ1K0Vw
            b1BBSVArT3hFelRIc1pGVlFndWdoWVUKLS0tIGFRaVBrY1hNeDltREpsbTBGRmNO
            d05TSmxhQnluNVhtWGUwZGFEcjZHaDQKJJ2K6KUUIZYVLuGTM0XMb/ANr6Ux9X04
            ZryPKAwx3E6hi8qs2vtcMBEFcTGYvuQ5q4KeVp3DA1av3y61CRaNvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T19:22:58Z"
    mac: ENC[AES256_GCM,data:GuNs6K9wGCTEzNC5+R8sK40WrIEtagSJbT9uQOvCKItumM4u5wtn38e4f2f8f7eoOqE7eZNg9PI9RhwrQ07FlqDea98blmqZrH0aTZ09kjUUgp6UV+aFHas+ugnGk0Mv5VOUTegkr29+w3ain3YyR720sGbuYxECciQwSyuEjJc=,iv:hyQ5XbBf3OpXVBLHAhfrb2UhGlv9XWyBT54NNfVEj/A=,tag:H9n0AmQpxn5ybqI4QuS70A==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: gitea
    namespace: gitea
spec:
    chart:
        spec:
            chart: gitea
            sourceRef:
                kind: HelmRepository
                name: gitea
            version: '*'
    interval: 1m0s
    timeout: 10m0s
    values:
        postExtraInitContainers:
            - name: phorge-theme-install
              image: alpine
              command:
                - sh
                - -c
                - |
                  set -e
                  apk add --no-cache rsync wget unzip
                  mkdir -p /data/gitea
                  wget -O /tmp/main.zip https://github.com/phorge-fr/gitea-phorge-theme/archive/refs/heads/main.zip
                  unzip -n /tmp/main.zip -d /tmp/
                  rsync -a --inplace --checksum /tmp/gitea-phorge-theme-main/ /data/gitea/
                  chown -R 1000:1000 /data/gitea
                  chmod -R 777 /data/packages
                  chmod -R 777 /data/lfs
              volumeMounts:
                - name: data
                  mountPath: /data
                - name: packages-volume
                  mountPath: /data/packages
                - name: lfs-volume
                  mountPath: /data/lfs
        nodeSelector:
            node-role.kubernetes.io/worker: "true"
        extraVolumes:
            - name: packages-volume
              persistentVolumeClaim:
                claimName: gitea-packages-pvc
            - name: lfs-volume
              persistentVolumeClaim:
                claimName: gitea-lfs-pvc
        extraVolumeMounts:
            - name: packages-volume
              mountPath: /data/packages
            - name: lfs-volume
              mountPath: /data/lfs
        gitea:
            admin:
                email: ENC[AES256_GCM,data:QxYN7+T5cddxBP+uLSGowg==,iv:EsJmuraDXwfD8jmiUY8HFZpxwiM0efd/593jWrYVCtI=,tag:UD4Q+asQBaNMiIVhB4q8DQ==,type:str]
                password: ENC[AES256_GCM,data:ipzpGx/Tmlni31CPTFqC8VXzOFQ=,iv:02wHUue+V61tYrzIFWNYq7r/pR1FULF4k9l3tc/M5U0=,tag:ArwRwPmFXS1+R2J+QWjerQ==,type:str]
                passwordMode: keepUpdated
                username: ENC[AES256_GCM,data:xi05ONPi6g/lwh8=,iv:40n4XhN0gtvl1KFYK55ez71/UWGS6g6O6VDo4fxRQsw=,tag:lt3DQBeGFuYso92QlfksuQ==,type:str]
            config:
                APP_NAME: φorge
                server:
                    SSH_LISTEN_PORT: 2222
                    SSH_PORT: 22
                    ROOT_URL: https://git.phorge.fr/
                service:
                    DISABLE_REGISTRATION: "true"
                ui:
                    THEMES: phorge-dark
                    DEFAULT_THEME: phorge-dark
                repository:
                    ACCESS_CONTROL_ALLOW_ORIGIN: '*'
                storage: {}
        ingress:
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
                nginx.ingress.kubernetes.io/proxy-body-size: 20480m
            className: nginx
            enabled: true
            hosts:
                - host: git.phorge.fr
                  paths:
                    - path: /
            pathType: Prefix
            tls:
                - hosts:
                    - git.phorge.fr
                  secretName: gitea-tls
        persistence:
            accessModes:
                - ReadWriteOnce
            annotations:
                helm.sh/resource-policy: keep
            claimName: gitea-shared-storage
            create: true
            enabled: true
            labels: {}
            mount: true
            size: 10Gi
            storageClass: null
            subPath: null
            volumeName: ""
        postgresql:
            enabled: true
            global:
                postgresql:
                    auth:
                        database: gitea
                        password: ENC[AES256_GCM,data:zFt2U/A=,iv:kS+Khq6YJyxWeWGVfluO3NY8RxAbTE8JPihNAMPcELc=,tag:piOKPnYneqDcx+sm9Yjaug==,type:str]
                        username: ENC[AES256_GCM,data:GbfsWY4=,iv:kV3dgJOj3pJqJ1kGKGxFsBaN57H+BBq0lJ4QAu70A7g=,tag:qpBMl5/+rK0TjhiUzAHWRQ==,type:str]
                    service:
                        ports:
                            postgresql: 5432
            image:
                repository: bitnamilegacy/postgresql
            metrics:
                image:
                    repository: bitnamilegacy/postgres-exporter
            primary:
                nodeSelector:
                    node-role.kubernetes.io/worker: "true"
                persistence:
                    size: 4Gi
            volumePermissions:
                image:
                    repository: bitnamilegacy/os-shell
        postgresql-ha:
            enabled: false
        service:
            ssh:
                annotations: {}
                clusterIP: None
                externalIPs: null
                externalTrafficPolicy: null
                hostPort: null
                ipFamilies: null
                ipFamilyPolicy: null
                labels: {}
                loadBalancerClass: null
                loadBalancerIP: 10.0.0.13
                loadBalancerSourceRanges: []
                nodePort: null
                port: 22
                type: LoadBalancer
        signing:
            enabled: false
            existingSecret: ""
            gpgHome: /data/git/.gnupg
            privateKey: ""
        valkey:
            primary:
                nodeSelector:
                    node-role.kubernetes.io/worker: "true"
                persistence:
                    size: 1Gi
            enabled: true
        valkey-cluster:
            enabled: false
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc003L0xFc2U1L0N5cjRZ
            UndpRHhYNjMrVFR1Y0tPZGUxc2dmWVhWblZJCiswRDdWMjdONnpsWk1JUGZ1K0Vw
            b1BBSVArT3hFelRIc1pGVlFndWdoWVUKLS0tIGFRaVBrY1hNeDltREpsbTBGRmNO
            d05TSmxhQnluNVhtWGUwZGFEcjZHaDQKJJ2K6KUUIZYVLuGTM0XMb/ANr6Ux9X04
            ZryPKAwx3E6hi8qs2vtcMBEFcTGYvuQ5q4KeVp3DA1av3y61CRaNvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T19:22:58Z"
    mac: ENC[AES256_GCM,data:GuNs6K9wGCTEzNC5+R8sK40WrIEtagSJbT9uQOvCKItumM4u5wtn38e4f2f8f7eoOqE7eZNg9PI9RhwrQ07FlqDea98blmqZrH0aTZ09kjUUgp6UV+aFHas+ugnGk0Mv5VOUTegkr29+w3ain3YyR720sGbuYxECciQwSyuEjJc=,iv:hyQ5XbBf3OpXVBLHAhfrb2UhGlv9XWyBT54NNfVEj/A=,tag:H9n0AmQpxn5ybqI4QuS70A==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
