apiVersion: v1
kind: Namespace
metadata:
    name: gitea
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL2c0by9yZzk4akdCSXly
            N3ZpRnNic28vQ2lxcjBzdUZwY2w2dUFjaUhvCkhVRkhRUXlqK2JHY3Vta3dTUVBZ
            cXZqeTdIKzczVEdIRXc5dkhYamlHaXMKLS0tIG9wSU10bGRsZnhGanoya1dKOEwz
            cWE4WjNNc244MGxNTy9pWm84dDRzZXcK38T9ARabRrIY/ycJn0ZaIKBCpTh1ptMO
            J5rxMcC9CylKIut/0YZQ0kL+JY+q+uilc5R6pmG3oi01RNsb8GgOcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T14:20:47Z"
    mac: ENC[AES256_GCM,data:JDa0VPy5gesIowKjNijV1Xr7r0aKyTNQXpbz0MLgdCn1zC2tOP40BiceogUajT+4x3dT1gBkS1wvPU8l4RiE344AkroObwwnRKO9VfEdFXAGUbUVss+Zr9rCOoYu54Nass+nNGGZAPmPpEPSnkmLoRAKDBpEdwGL6c9ypK7sUVM=,iv:sCt1CKdi3AcfljD3EHh6TPjOQZmJb6v1z8wUstdRhMk=,tag:TjDn5U4n0SrmM8Bhoitttw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: gitea
    namespace: gitea
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://dl.gitea.com/charts/
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL2c0by9yZzk4akdCSXly
            N3ZpRnNic28vQ2lxcjBzdUZwY2w2dUFjaUhvCkhVRkhRUXlqK2JHY3Vta3dTUVBZ
            cXZqeTdIKzczVEdIRXc5dkhYamlHaXMKLS0tIG9wSU10bGRsZnhGanoya1dKOEwz
            cWE4WjNNc244MGxNTy9pWm84dDRzZXcK38T9ARabRrIY/ycJn0ZaIKBCpTh1ptMO
            J5rxMcC9CylKIut/0YZQ0kL+JY+q+uilc5R6pmG3oi01RNsb8GgOcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T14:20:47Z"
    mac: ENC[AES256_GCM,data:JDa0VPy5gesIowKjNijV1Xr7r0aKyTNQXpbz0MLgdCn1zC2tOP40BiceogUajT+4x3dT1gBkS1wvPU8l4RiE344AkroObwwnRKO9VfEdFXAGUbUVss+Zr9rCOoYu54Nass+nNGGZAPmPpEPSnkmLoRAKDBpEdwGL6c9ypK7sUVM=,iv:sCt1CKdi3AcfljD3EHh6TPjOQZmJb6v1z8wUstdRhMk=,tag:TjDn5U4n0SrmM8Bhoitttw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: gitea
    namespace: gitea
spec:
    chart:
        spec:
            chart: gitea
            sourceRef:
                kind: HelmRepository
                name: gitea
            version: '*'
    interval: 1m0s
    values:
        postExtraInitContainers:
            - name: phorge-theme-install
              image: alpine
              command:
                - sh
                - -c
                - |
                  set -e
                  apk add --no-cache rsync wget unzip
                  mkdir -p /data/gitea
                  wget -O /tmp/main.zip https://github.com/phorge-fr/gitea-phorge-theme/archive/refs/heads/main.zip
                  unzip -n /tmp/main.zip -d /tmp/
                  rsync -a --inplace --checksum /tmp/gitea-phorge-theme-main/ /data/gitea/
                  chown -R 1000:1000 /data/gitea
              volumeMounts:
                - name: data
                  mountPath: /data
        nodeSelector:
            node-role.kubernetes.io/worker: "true"
        gitea:
            admin:
                email: ENC[AES256_GCM,data:daJE79ngiggasl0l05GtWA==,iv:1hiZP/TvNHPGK1B/XbeYVwZ4eVk+GMMtUVUA64R4hX0=,tag:geFc/eMRwP/S+76so4VCdA==,type:str]
                password: ENC[AES256_GCM,data:36qiHHycUz2WlX4dlThzGaV+rYs=,iv:ueRP4cK6q53RrdG/CjlCebOY1Htpi/SHb2F9k6Ovp6Q=,tag:Px5JENZWUzOQ0bTYJaVizw==,type:str]
                passwordMode: keepUpdated
                username: ENC[AES256_GCM,data:posNjBKK056cTmw=,iv:k3YEoBwdJUrJp2v+oIyzbRCd84SR7HE+CMNbH9FZ1Ag=,tag:7nlUrqlQGC5/6rkGuODnWQ==,type:str]
            config:
                APP_NAME: Ï†orge
                server:
                    SSH_LISTEN_PORT: 2222
                    SSH_PORT: 22
                    ROOT_URL: https://git.phorge.fr/
                service:
                    DISABLE_REGISTRATION: "false"
                ui:
                    THEMES: phorge-dark
                    DEFAULT_THEME: phorge-dark
                repository:
                    ACCESS_CONTROL_ALLOW_ORIGIN: '*'
        ingress:
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
            className: nginx
            enabled: true
            hosts:
                - host: git.phorge.fr
                  paths:
                    - path: /
            pathType: Prefix
            tls:
                - hosts:
                    - git.phorge.fr
                  secretName: gitea
        persistence:
            accessModes:
                - ReadWriteOnce
            annotations:
                helm.sh/resource-policy: keep
            claimName: gitea-shared-storage
            create: true
            enabled: true
            labels: {}
            mount: true
            size: 4Gi
            storageClass: null
            subPath: null
            volumeName: ""
        postgresql:
            enabled: true
            global:
                postgresql:
                    auth:
                        database: gitea
                        password: ENC[AES256_GCM,data:CuutsWY=,iv:N+Vw8jlhmsr12H03IEFsGmIZ0GpsmeTJu9H1MLmuyjw=,tag:uRNPyh1XREb8V0daEs5ISg==,type:str]
                        username: ENC[AES256_GCM,data:K3LKgeg=,iv:NrEptY4yicjffoNvIiK7jAUq/Qjbhu+ISmWylprc5g8=,tag:qM34cjDdZlkWgTtKoFFZSQ==,type:str]
                    service:
                        ports:
                            postgresql: 5432
            image:
                repository: bitnamilegacy/postgresql
            metrics:
                image:
                    repository: bitnamilegacy/postgres-exporter
            primary:
                nodeSelector:
                    node-role.kubernetes.io/worker: "true"
                persistence:
                    size: 10Gi
            volumePermissions:
                image:
                    repository: bitnamilegacy/os-shell
        postgresql-ha:
            enabled: false
        service:
            ssh:
                annotations: {}
                clusterIP: None
                externalIPs: null
                externalTrafficPolicy: null
                hostPort: null
                ipFamilies: null
                ipFamilyPolicy: null
                labels: {}
                loadBalancerClass: null
                loadBalancerIP: 10.0.0.13
                loadBalancerSourceRanges: []
                nodePort: null
                port: 22
                type: LoadBalancer
        signing:
            enabled: false
            existingSecret: ""
            gpgHome: /data/git/.gnupg
            privateKey: ""
        valkey:
            primary:
                nodeSelector:
                    node-role.kubernetes.io/worker: "true"
                persistence:
                    size: 1Gi
            enabled: true
        valkey-cluster:
            enabled: false
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL2c0by9yZzk4akdCSXly
            N3ZpRnNic28vQ2lxcjBzdUZwY2w2dUFjaUhvCkhVRkhRUXlqK2JHY3Vta3dTUVBZ
            cXZqeTdIKzczVEdIRXc5dkhYamlHaXMKLS0tIG9wSU10bGRsZnhGanoya1dKOEwz
            cWE4WjNNc244MGxNTy9pWm84dDRzZXcK38T9ARabRrIY/ycJn0ZaIKBCpTh1ptMO
            J5rxMcC9CylKIut/0YZQ0kL+JY+q+uilc5R6pmG3oi01RNsb8GgOcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T14:20:47Z"
    mac: ENC[AES256_GCM,data:JDa0VPy5gesIowKjNijV1Xr7r0aKyTNQXpbz0MLgdCn1zC2tOP40BiceogUajT+4x3dT1gBkS1wvPU8l4RiE344AkroObwwnRKO9VfEdFXAGUbUVss+Zr9rCOoYu54Nass+nNGGZAPmPpEPSnkmLoRAKDBpEdwGL6c9ypK7sUVM=,iv:sCt1CKdi3AcfljD3EHh6TPjOQZmJb6v1z8wUstdRhMk=,tag:TjDn5U4n0SrmM8Bhoitttw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
