apiVersion: v1
kind: Namespace
metadata:
    name: gitea
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYTRvSVRLTSthR0dJcnlM
            KzJrUGJTYUg0eXFmTWgzUG5PenpaZUhSbjEwCkUwQ1JWakRIMzZOc0xPMGxKN3JU
            RE9iOUhzS0VIOHVVWjcxSFBjSm41S3MKLS0tIFFrQUVTL3RSdGlHLzRoUmZVdnpo
            VHpkdzNRVFBQbDE0KzNmQllEbUZjZW8KG7q/hcFcPmHdoW9aMnbJChP7yDreVOru
            nJcjpQ2ln1YB1GdMntatlE4e1cRyBq/cV7M4lXRsW6MwynumbxEkGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T16:23:00Z"
    mac: ENC[AES256_GCM,data:VfFwmReD8v+gDLtvrFQWmTs4YLmv4q6Jzhp6kyHGPHI7SJS1ig0gHA+hYQrEwCySAChN/Vbksxn79K6VjTRhEtfeVitqYszKE9zSHavwnBQRYFo1KOr1Lwqj6aDmUZ1WYs9/VsgkhtP4LMmXn8SBfVju2xvMbfYpIZIYJGqDxJg=,iv:zH3Ahk4oHmeVKrKdc+L431KsKSKleXTA6e7SaljTvs8=,tag:8a1L01v7t3NL53alI3moqw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: gitea
    namespace: gitea
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://dl.gitea.com/charts/
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYTRvSVRLTSthR0dJcnlM
            KzJrUGJTYUg0eXFmTWgzUG5PenpaZUhSbjEwCkUwQ1JWakRIMzZOc0xPMGxKN3JU
            RE9iOUhzS0VIOHVVWjcxSFBjSm41S3MKLS0tIFFrQUVTL3RSdGlHLzRoUmZVdnpo
            VHpkdzNRVFBQbDE0KzNmQllEbUZjZW8KG7q/hcFcPmHdoW9aMnbJChP7yDreVOru
            nJcjpQ2ln1YB1GdMntatlE4e1cRyBq/cV7M4lXRsW6MwynumbxEkGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T16:23:00Z"
    mac: ENC[AES256_GCM,data:VfFwmReD8v+gDLtvrFQWmTs4YLmv4q6Jzhp6kyHGPHI7SJS1ig0gHA+hYQrEwCySAChN/Vbksxn79K6VjTRhEtfeVitqYszKE9zSHavwnBQRYFo1KOr1Lwqj6aDmUZ1WYs9/VsgkhtP4LMmXn8SBfVju2xvMbfYpIZIYJGqDxJg=,iv:zH3Ahk4oHmeVKrKdc+L431KsKSKleXTA6e7SaljTvs8=,tag:8a1L01v7t3NL53alI3moqw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: gitea
    namespace: gitea
spec:
    chart:
        spec:
            chart: gitea
            sourceRef:
                kind: HelmRepository
                name: gitea
            version: '*'
    interval: 1m0s
    timeout: 10m0s
    values:
        postExtraInitContainers:
            - name: phorge-theme-install
              image: alpine
              command:
                - sh
                - -c
                - |
                  set -e
                  apk add --no-cache rsync wget unzip
                  mkdir -p /data/gitea
                  wget -O /tmp/main.zip https://github.com/phorge-fr/gitea-phorge-theme/archive/refs/heads/main.zip
                  unzip -n /tmp/main.zip -d /tmp/
                  rsync -a --inplace --checksum /tmp/gitea-phorge-theme-main/ /data/gitea/
                  chown -R 1000:1000 /data/gitea
              volumeMounts:
                - name: data
                  mountPath: /data
        nodeSelector:
            node-role.kubernetes.io/worker: "true"
        gitea:
            admin:
                email: ENC[AES256_GCM,data:8yaww/FnErvNkL1Omq9Ezg==,iv:+QxwELn0n7Gf9mRTr4mtQ7Z/FrVaCZXwAAVXvjqDhTI=,tag:bZqlQRqId+xflY0FqhynWA==,type:str]
                password: ENC[AES256_GCM,data:6/cFgD3LrnpktXrReR91c0L6FGE=,iv:sHOG+rENXJtCILW1NzHXtl9O/fzDRKVGapSw8brOyMA=,tag:SjC+JyE52JWXIkbR9Bs+Cg==,type:str]
                passwordMode: keepUpdated
                username: ENC[AES256_GCM,data:Pzd3F/R09TV+9kY=,iv:dwVcHket7vp08zdpAgUTGU3AhXT+YxqibK1c3vAt1Ts=,tag:o5FTBCPa62QBvTir6B3cMw==,type:str]
            config:
                APP_NAME: φorge
                server:
                    SSH_LISTEN_PORT: 2222
                    SSH_PORT: 22
                    ROOT_URL: https://git.phorge.fr/
                service:
                    DISABLE_REGISTRATION: "false"
                ui:
                    THEMES: phorge-dark
                    DEFAULT_THEME: phorge-dark
                repository:
                    ACCESS_CONTROL_ALLOW_ORIGIN: '*'
                storage:
                    STORAGE_TYPE: minio
                    MINIO_ENDPOINT: 10.3.0.1:9000
                    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:9Hm04xVCj9Jm+Z2cB9VqZh97r4o=,iv:BDKFtPxVoFzKcR0ZbBfyW0NNuANKQWEAezRr2rlllQg=,tag:5JwnrIjr/G3S2kWSIAocOQ==,type:str]
                    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aQrjNOf8cBjvsS+aqcSNMPVd2+B7jlurDPg5R0PecZMBDm93DIVLkQ==,iv:8+u38I9ClYxRHWyD+C1wDexOUwL8S3uPtKTl9iwd68M=,tag:ncPSF9G8j6EVQKUeswg/EA==,type:str]
                    MINIO_BUCKET: ENC[AES256_GCM,data:Q7sA7ck=,iv:erszJFzujJ5F2aerYZcRtRoCCbQzYuczij/bFgg10Yc=,tag:LFNk+AGTwsdnnkR4F7k6ZQ==,type:str]
                    MINIO_REGION: us-east-1
        ingress:
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
                nginx.ingress.kubernetes.io/proxy-body-size: 1024m
            className: nginx
            enabled: true
            hosts:
                - host: git.phorge.fr
                  paths:
                    - path: /
            pathType: Prefix
            tls:
                - hosts:
                    - git.phorge.fr
                  secretName: gitea
        persistence:
            accessModes:
                - ReadWriteOnce
            annotations:
                helm.sh/resource-policy: keep
            claimName: gitea-shared-storage
            create: true
            enabled: true
            labels: {}
            mount: true
            size: 10Gi
            storageClass: null
            subPath: null
            volumeName: ""
        postgresql:
            enabled: true
            global:
                postgresql:
                    auth:
                        database: gitea
                        password: ENC[AES256_GCM,data:itkkIj4=,iv:xKMx898MO+TiYDs2goibsYUHLB+CqxP7rz/lisKiXoI=,tag:CxXiRxt76ed8B/2HI0hb/Q==,type:str]
                        username: ENC[AES256_GCM,data:gEvSR64=,iv:63j77a9JQmERYUKcKA//BLA+HMZj5P60CVIZC3kir/A=,tag:voaV4W9aXFhlxcimpvS5ZQ==,type:str]
                    service:
                        ports:
                            postgresql: 5432
            image:
                repository: bitnamilegacy/postgresql
            metrics:
                image:
                    repository: bitnamilegacy/postgres-exporter
            primary:
                nodeSelector:
                    node-role.kubernetes.io/worker: "true"
                persistence:
                    size: 4Gi
            volumePermissions:
                image:
                    repository: bitnamilegacy/os-shell
        postgresql-ha:
            enabled: false
        service:
            ssh:
                annotations: {}
                clusterIP: None
                externalIPs: null
                externalTrafficPolicy: null
                hostPort: null
                ipFamilies: null
                ipFamilyPolicy: null
                labels: {}
                loadBalancerClass: null
                loadBalancerIP: 10.0.0.13
                loadBalancerSourceRanges: []
                nodePort: null
                port: 22
                type: LoadBalancer
        signing:
            enabled: false
            existingSecret: ""
            gpgHome: /data/git/.gnupg
            privateKey: ""
        valkey:
            primary:
                nodeSelector:
                    node-role.kubernetes.io/worker: "true"
                persistence:
                    size: 1Gi
            enabled: true
        valkey-cluster:
            enabled: false
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYTRvSVRLTSthR0dJcnlM
            KzJrUGJTYUg0eXFmTWgzUG5PenpaZUhSbjEwCkUwQ1JWakRIMzZOc0xPMGxKN3JU
            RE9iOUhzS0VIOHVVWjcxSFBjSm41S3MKLS0tIFFrQUVTL3RSdGlHLzRoUmZVdnpo
            VHpkdzNRVFBQbDE0KzNmQllEbUZjZW8KG7q/hcFcPmHdoW9aMnbJChP7yDreVOru
            nJcjpQ2ln1YB1GdMntatlE4e1cRyBq/cV7M4lXRsW6MwynumbxEkGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T16:23:00Z"
    mac: ENC[AES256_GCM,data:VfFwmReD8v+gDLtvrFQWmTs4YLmv4q6Jzhp6kyHGPHI7SJS1ig0gHA+hYQrEwCySAChN/Vbksxn79K6VjTRhEtfeVitqYszKE9zSHavwnBQRYFo1KOr1Lwqj6aDmUZ1WYs9/VsgkhtP4LMmXn8SBfVju2xvMbfYpIZIYJGqDxJg=,iv:zH3Ahk4oHmeVKrKdc+L431KsKSKleXTA6e7SaljTvs8=,tag:8a1L01v7t3NL53alI3moqw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|MINIO_ACCESS_KEY_ID|MINIO_SECRET_ACCESS_KEY|MINIO_BUCKET)$
    version: 3.11.0
