apiVersion: v1
kind: Namespace
metadata:
    name: gitea
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTXZLOXluMm5SeXdrNFBx
            U2pQM3dMSWp3WlJUNi95THlqRVN0YWJhS0JRCnRLRERCcDJuVDlWaTloZXJMSEEv
            a05DZHM5Q3h1ZUcxT3NBVGdCbmk0blkKLS0tIDJtNWFCZ0x5bERuNGhTT3IxQjU1
            aWtHMkhBcU1ESFR1SERsd2lqMU1kbGsKY/q8N1hUzc2vTzLXRSHVrnCBQT32zxaw
            SW9NqvmYfzOaVkKNa1P1ZzgjcbGA4zerSoDtHtM3J6AytJ0CLfYaBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T16:32:45Z"
    mac: ENC[AES256_GCM,data:iIB+r2EjF9LDff1CD//rqJt12ri+Zq183htSguMO7iNKhhrEG4+x1DK2IOVoQn3FCZ0Kkc4ZvirzeXYEvD61LifEhOsML4VLykXsbFl4PzYnoK7HDpIaqlvHbJ7mF+wljy2zQ16FNSiKf9Du2KHpKUQ9X5oJ5eWj4QcLfsYQadk=,iv:pChCI9vZM0QvVpp0uUq7Zvpwmb6k3zJ0Dh7pBl5uMto=,tag:qQULEhsIoay35fRvhAfJ8g==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: gitea-packages-pvc
    namespace: gitea
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 200Gi
    storageClassName: nfs-uncritical
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTXZLOXluMm5SeXdrNFBx
            U2pQM3dMSWp3WlJUNi95THlqRVN0YWJhS0JRCnRLRERCcDJuVDlWaTloZXJMSEEv
            a05DZHM5Q3h1ZUcxT3NBVGdCbmk0blkKLS0tIDJtNWFCZ0x5bERuNGhTT3IxQjU1
            aWtHMkhBcU1ESFR1SERsd2lqMU1kbGsKY/q8N1hUzc2vTzLXRSHVrnCBQT32zxaw
            SW9NqvmYfzOaVkKNa1P1ZzgjcbGA4zerSoDtHtM3J6AytJ0CLfYaBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T16:32:45Z"
    mac: ENC[AES256_GCM,data:iIB+r2EjF9LDff1CD//rqJt12ri+Zq183htSguMO7iNKhhrEG4+x1DK2IOVoQn3FCZ0Kkc4ZvirzeXYEvD61LifEhOsML4VLykXsbFl4PzYnoK7HDpIaqlvHbJ7mF+wljy2zQ16FNSiKf9Du2KHpKUQ9X5oJ5eWj4QcLfsYQadk=,iv:pChCI9vZM0QvVpp0uUq7Zvpwmb6k3zJ0Dh7pBl5uMto=,tag:qQULEhsIoay35fRvhAfJ8g==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: gitea-lfs-pvc
    namespace: gitea
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Gi
    storageClassName: nfs-uncritical
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTXZLOXluMm5SeXdrNFBx
            U2pQM3dMSWp3WlJUNi95THlqRVN0YWJhS0JRCnRLRERCcDJuVDlWaTloZXJMSEEv
            a05DZHM5Q3h1ZUcxT3NBVGdCbmk0blkKLS0tIDJtNWFCZ0x5bERuNGhTT3IxQjU1
            aWtHMkhBcU1ESFR1SERsd2lqMU1kbGsKY/q8N1hUzc2vTzLXRSHVrnCBQT32zxaw
            SW9NqvmYfzOaVkKNa1P1ZzgjcbGA4zerSoDtHtM3J6AytJ0CLfYaBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T16:32:45Z"
    mac: ENC[AES256_GCM,data:iIB+r2EjF9LDff1CD//rqJt12ri+Zq183htSguMO7iNKhhrEG4+x1DK2IOVoQn3FCZ0Kkc4ZvirzeXYEvD61LifEhOsML4VLykXsbFl4PzYnoK7HDpIaqlvHbJ7mF+wljy2zQ16FNSiKf9Du2KHpKUQ9X5oJ5eWj4QcLfsYQadk=,iv:pChCI9vZM0QvVpp0uUq7Zvpwmb6k3zJ0Dh7pBl5uMto=,tag:qQULEhsIoay35fRvhAfJ8g==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: gitea
    namespace: gitea
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://dl.gitea.com/charts/
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTXZLOXluMm5SeXdrNFBx
            U2pQM3dMSWp3WlJUNi95THlqRVN0YWJhS0JRCnRLRERCcDJuVDlWaTloZXJMSEEv
            a05DZHM5Q3h1ZUcxT3NBVGdCbmk0blkKLS0tIDJtNWFCZ0x5bERuNGhTT3IxQjU1
            aWtHMkhBcU1ESFR1SERsd2lqMU1kbGsKY/q8N1hUzc2vTzLXRSHVrnCBQT32zxaw
            SW9NqvmYfzOaVkKNa1P1ZzgjcbGA4zerSoDtHtM3J6AytJ0CLfYaBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T16:32:45Z"
    mac: ENC[AES256_GCM,data:iIB+r2EjF9LDff1CD//rqJt12ri+Zq183htSguMO7iNKhhrEG4+x1DK2IOVoQn3FCZ0Kkc4ZvirzeXYEvD61LifEhOsML4VLykXsbFl4PzYnoK7HDpIaqlvHbJ7mF+wljy2zQ16FNSiKf9Du2KHpKUQ9X5oJ5eWj4QcLfsYQadk=,iv:pChCI9vZM0QvVpp0uUq7Zvpwmb6k3zJ0Dh7pBl5uMto=,tag:qQULEhsIoay35fRvhAfJ8g==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: gitea
    namespace: gitea
spec:
    chart:
        spec:
            chart: gitea
            sourceRef:
                kind: HelmRepository
                name: gitea
            version: '*'
    interval: 1m0s
    timeout: 10m0s
    values:
        postExtraInitContainers:
            - name: phorge-theme-install
              image: alpine
              command:
                - sh
                - -c
                - |
                  set -e
                  apk add --no-cache rsync wget unzip
                  mkdir -p /data/gitea
                  wget -O /tmp/main.zip https://github.com/phorge-fr/gitea-phorge-theme/archive/refs/heads/main.zip
                  unzip -n /tmp/main.zip -d /tmp/
                  rsync -a --inplace --checksum /tmp/gitea-phorge-theme-main/ /data/gitea/
                  chown -R 1000:1000 /data/gitea
                #   chmod -R 777 /data/packages
                #   chmod -R 777 /data/lfs
              volumeMounts:
                - name: data
                  mountPath: /data
                - name: packages-volume
                  mountPath: /data/packages
                - name: lfs-volume
                  mountPath: /data/lfs
        nodeSelector:
            node-role.kubernetes.io/worker: "true"
        extraVolumes:
            - name: packages-volume
              persistentVolumeClaim:
                claimName: gitea-packages-pvc
            - name: lfs-volume
              persistentVolumeClaim:
                claimName: gitea-lfs-pvc
        extraVolumeMounts:
            - name: packages-volume
              mountPath: /data/packages
            - name: lfs-volume
              mountPath: /data/lfs
        gitea:
            admin:
                email: ENC[AES256_GCM,data:A4XZqpM0HlZl4jsm2LMkEQ==,iv:znnr7TI4Wv4+sibMy9UHwM276rK6XNvNmgsTU2josZs=,tag:6aH2RY6zco6/IEYXRy+IhQ==,type:str]
                password: ENC[AES256_GCM,data:OZQnCSGJO64BQOK0op2vV37oIPA=,iv:lup34Eyeu69ITvDCjKbFABrX4R1tzPvVhTIVU16be24=,tag:eQmpiqtDqrENW199cPMp5g==,type:str]
                passwordMode: keepUpdated
                username: ENC[AES256_GCM,data:G2bMQWHd1hsrYn8=,iv:QudC2RCT68p/ExUrodGkY7q0QhltAqEaxsvJ+6OZm8g=,tag:AOLBJDH9LUMiNq9+wfFkRQ==,type:str]
            config:
                APP_NAME: φorge
                server:
                    SSH_LISTEN_PORT: 2222
                    SSH_PORT: 22
                    ROOT_URL: https://git.phorge.fr/
                service:
                    DISABLE_REGISTRATION: "true"
                ui:
                    THEMES: phorge-dark
                    DEFAULT_THEME: phorge-dark
                repository:
                    ACCESS_CONTROL_ALLOW_ORIGIN: '*'
                storage: {}
        ingress:
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
            className: traefik-public
            enabled: true
            hosts:
                - host: git.phorge.fr
                  paths:
                    - path: /
            pathType: Prefix
            tls:
                - hosts:
                    - git.phorge.fr
                  secretName: gitea-tls
        persistence:
            accessModes:
                - ReadWriteOnce
            annotations:
                helm.sh/resource-policy: keep
            claimName: gitea-shared-storage
            create: true
            enabled: true
            labels: {}
            mount: true
            size: 10Gi
            storageClass: null
            subPath: null
            volumeName: ""
        postgresql:
            enabled: true
            global:
                postgresql:
                    auth:
                        database: gitea
                        password: ENC[AES256_GCM,data:9Jcfwsc=,iv:RvS21/zqcu81twFP5BLNAcVRHwegJ+wb9T3O/nDmco8=,tag:HsarHozLD35vgbdJ/FxkSg==,type:str]
                        username: ENC[AES256_GCM,data:UpX05/U=,iv:/Fz5+hFYvkdY+AskbXfyrSslBUjwcvVAJShyf0u1DWc=,tag:0AZc/5CJorqHBrzabzqOtA==,type:str]
                    service:
                        ports:
                            postgresql: 5432
            image:
                repository: bitnamilegacy/postgresql
            metrics:
                image:
                    repository: bitnamilegacy/postgres-exporter
            primary:
                nodeSelector:
                    node-role.kubernetes.io/worker: "true"
                persistence:
                    size: 4Gi
            volumePermissions:
                image:
                    repository: bitnamilegacy/os-shell
        postgresql-ha:
            enabled: false
        service:
            ssh:
                annotations: {}
                clusterIP: None
                externalIPs: null
                externalTrafficPolicy: null
                hostPort: null
                ipFamilies: null
                ipFamilyPolicy: null
                labels: {}
                loadBalancerClass: null
                loadBalancerIP: 10.0.0.13
                loadBalancerSourceRanges: []
                nodePort: null
                port: 22
                type: LoadBalancer
        signing:
            enabled: false
            existingSecret: ""
            gpgHome: /data/git/.gnupg
            privateKey: ""
        valkey:
            primary:
                nodeSelector:
                    node-role.kubernetes.io/worker: "true"
                persistence:
                    size: 1Gi
            enabled: true
        valkey-cluster:
            enabled: false
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTXZLOXluMm5SeXdrNFBx
            U2pQM3dMSWp3WlJUNi95THlqRVN0YWJhS0JRCnRLRERCcDJuVDlWaTloZXJMSEEv
            a05DZHM5Q3h1ZUcxT3NBVGdCbmk0blkKLS0tIDJtNWFCZ0x5bERuNGhTT3IxQjU1
            aWtHMkhBcU1ESFR1SERsd2lqMU1kbGsKY/q8N1hUzc2vTzLXRSHVrnCBQT32zxaw
            SW9NqvmYfzOaVkKNa1P1ZzgjcbGA4zerSoDtHtM3J6AytJ0CLfYaBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T16:32:45Z"
    mac: ENC[AES256_GCM,data:iIB+r2EjF9LDff1CD//rqJt12ri+Zq183htSguMO7iNKhhrEG4+x1DK2IOVoQn3FCZ0Kkc4ZvirzeXYEvD61LifEhOsML4VLykXsbFl4PzYnoK7HDpIaqlvHbJ7mF+wljy2zQ16FNSiKf9Du2KHpKUQ9X5oJ5eWj4QcLfsYQadk=,iv:pChCI9vZM0QvVpp0uUq7Zvpwmb6k3zJ0Dh7pBl5uMto=,tag:qQULEhsIoay35fRvhAfJ8g==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
