apiVersion: v1
kind: Namespace
metadata:
    name: gitea
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUWgxNDJQREdpRWtJMGNQ
            bVZwQlg3dHk4ZUZHQWkzT2tWVkQ0MHpWWWlrClNxZ2plSXRKaVp2NGRRMFgybnMw
            VXBWdjRtTStNVE1rVUpTcUdyNVc2d28KLS0tIHd4cXgrWTNRS0VaWmlxcFJrYUpl
            SElDa3duYjRuTFlWb0JyL2l3RGxlekUKGONrNgtgmqlkcCMNJUqB8csTcdjurQu+
            HZdsWhB8vrXKHOJ+4PLfGR0mxh3AanhIoBvO9Cbly2yFpX2Bl62kww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T23:11:51Z"
    mac: ENC[AES256_GCM,data:F3hqcEGgF4gkFLLt/yXlhcdaLymvpH1KwiH3V1ON8jSqyk/3C/Z/3EGKbnAKzKdP291tfoHLLh4TU+FFaqBXOOJI0uhDyy+6VUWY7D7L0MnkXTquHmN/bVmCuol48vc4INNX8iFi/ZT31X+CjcEG4xJnwyDoW5qzUmX0fvMd3dI=,iv:4XSFEq6m4cqO9YIiJk+yXVxV8JQ12cFsqbXLC8YRWZM=,tag:0oqShh0tjWvfpbM0TcUlSg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: gitea
    namespace: gitea
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://dl.gitea.com/charts/
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUWgxNDJQREdpRWtJMGNQ
            bVZwQlg3dHk4ZUZHQWkzT2tWVkQ0MHpWWWlrClNxZ2plSXRKaVp2NGRRMFgybnMw
            VXBWdjRtTStNVE1rVUpTcUdyNVc2d28KLS0tIHd4cXgrWTNRS0VaWmlxcFJrYUpl
            SElDa3duYjRuTFlWb0JyL2l3RGxlekUKGONrNgtgmqlkcCMNJUqB8csTcdjurQu+
            HZdsWhB8vrXKHOJ+4PLfGR0mxh3AanhIoBvO9Cbly2yFpX2Bl62kww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T23:11:51Z"
    mac: ENC[AES256_GCM,data:F3hqcEGgF4gkFLLt/yXlhcdaLymvpH1KwiH3V1ON8jSqyk/3C/Z/3EGKbnAKzKdP291tfoHLLh4TU+FFaqBXOOJI0uhDyy+6VUWY7D7L0MnkXTquHmN/bVmCuol48vc4INNX8iFi/ZT31X+CjcEG4xJnwyDoW5qzUmX0fvMd3dI=,iv:4XSFEq6m4cqO9YIiJk+yXVxV8JQ12cFsqbXLC8YRWZM=,tag:0oqShh0tjWvfpbM0TcUlSg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: gitea
    namespace: gitea
spec:
    chart:
        spec:
            chart: gitea
            sourceRef:
                kind: HelmRepository
                name: gitea
            version: '*'
    interval: 1m0s
    values:
        postExtraInitContainers:
            - name: phorge-theme-install
              image: alpine
              command:
                - sh
                - -c
                - |
                  set -e
                  apk add --no-cache rsync wget unzip
                  mkdir -p /data/gitea
                  wget -O /tmp/main.zip https://github.com/phorge-fr/gitea-phorge-theme/archive/refs/heads/main.zip
                  unzip -n /tmp/main.zip -d /tmp/
                  rsync -a --inplace --checksum /tmp/gitea-phorge-theme-main/ /data/gitea/
                  chown -R 1000:1000 /data/gitea
              volumeMounts:
                - name: data
                  mountPath: /data
        nodeSelector:
            node-role.kubernetes.io/worker: "true"
        gitea:
            admin:
                email: ENC[AES256_GCM,data:4t5jZqQi+RBG3QuRgO13cw==,iv:UzuRy3PoykBxIf3jTXi2fjV2Q3m4iwWPkggwBISKSGg=,tag:dD18REaRWsI/ugjn+D2h0g==,type:str]
                password: ENC[AES256_GCM,data:JTRWN/myrY7rhTaZ1XnJ9YubioQ=,iv:vB0uQAkiAJl3TBvqz9kgk9rUT/AtMJeWbG4RZQZqSto=,tag:M10EglWhv2ONSvvSNboiAg==,type:str]
                passwordMode: keepUpdated
                username: ENC[AES256_GCM,data:VpZ7aMyvVPRNm6A=,iv:PA45aoCodeAic7794FVRScEQzbh6lOfQKNS0suDjJM0=,tag:qdc5GvXp/3V67s6hinue1A==,type:str]
            config:
                APP_NAME: Ï†orge
                server:
                    SSH_LISTEN_PORT: 2222
                    SSH_PORT: 22
                    ROOT_URL: https://git.phorge.fr/
                service:
                    DISABLE_REGISTRATION: "false"
                ui:
                    THEMES: phorge-dark
                    DEFAULT_THEME: phorge-dark
                repository:
                    ACCESS_CONTROL_ALLOW_ORIGIN: '*'
        ingress:
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
            className: nginx
            enabled: true
            hosts:
                - host: git.phorge.fr
                  paths:
                    - path: /
            pathType: Prefix
            tls:
                - hosts:
                    - git.phorge.fr
                  secretName: gitea
        persistence:
            accessModes:
                - ReadWriteOnce
            annotations:
                helm.sh/resource-policy: keep
            claimName: gitea-shared-storage
            create: true
            enabled: true
            labels: {}
            mount: true
            size: 4Gi
            storageClass: null
            subPath: null
            volumeName: ""
        postgresql:
            enabled: true
            global:
                postgresql:
                    auth:
                        database: gitea
                        password: ENC[AES256_GCM,data:4y2By7k=,iv:soMTAKmNJAz46AmH7AUe0x0Ss/2V1FIKNoST1ISEdWE=,tag:tW91tDtfWoV1U+zHJH3uWQ==,type:str]
                        username: ENC[AES256_GCM,data:BgeoC14=,iv:iy8F5lfRxKgdEJOyAdQ1SugG9Y4gKwYZIE6OBGnvuuQ=,tag:p/tsB41/yB3C7nkQPoNq9Q==,type:str]
                    service:
                        ports:
                            postgresql: 5432
            image:
                repository: bitnamilegacy/postgresql
            metrics:
                image:
                    repository: bitnamilegacy/postgres-exporter
            primary:
                nodeSelector:
                    node-role.kubernetes.io/worker: "true"
                persistence:
                    size: 10Gi
            volumePermissions:
                image:
                    repository: bitnamilegacy/os-shell
        postgresql-ha:
            enabled: false
        service:
            ssh:
                annotations: {}
                clusterIP: None
                externalIPs: null
                externalTrafficPolicy: null
                hostPort: null
                ipFamilies: null
                ipFamilyPolicy: null
                labels: {}
                loadBalancerClass: null
                loadBalancerIP: null
                loadBalancerSourceRanges: []
                nodePort: null
                port: 22
                type: NodePort
        signing:
            enabled: false
            existingSecret: ""
            gpgHome: /data/git/.gnupg
            privateKey: ""
        valkey:
            primary:
                nodeSelector:
                    node-role.kubernetes.io/worker: "true"
                persistence:
                    size: 1Gi
            enabled: true
        valkey-cluster:
            enabled: false
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUWgxNDJQREdpRWtJMGNQ
            bVZwQlg3dHk4ZUZHQWkzT2tWVkQ0MHpWWWlrClNxZ2plSXRKaVp2NGRRMFgybnMw
            VXBWdjRtTStNVE1rVUpTcUdyNVc2d28KLS0tIHd4cXgrWTNRS0VaWmlxcFJrYUpl
            SElDa3duYjRuTFlWb0JyL2l3RGxlekUKGONrNgtgmqlkcCMNJUqB8csTcdjurQu+
            HZdsWhB8vrXKHOJ+4PLfGR0mxh3AanhIoBvO9Cbly2yFpX2Bl62kww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T23:11:51Z"
    mac: ENC[AES256_GCM,data:F3hqcEGgF4gkFLLt/yXlhcdaLymvpH1KwiH3V1ON8jSqyk/3C/Z/3EGKbnAKzKdP291tfoHLLh4TU+FFaqBXOOJI0uhDyy+6VUWY7D7L0MnkXTquHmN/bVmCuol48vc4INNX8iFi/ZT31X+CjcEG4xJnwyDoW5qzUmX0fvMd3dI=,iv:4XSFEq6m4cqO9YIiJk+yXVxV8JQ12cFsqbXLC8YRWZM=,tag:0oqShh0tjWvfpbM0TcUlSg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
