apiVersion: v1
kind: Namespace
metadata:
    name: headlamp
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWVV5NU5SbzZVRjNIQnRQ
            bXdOL05HTEJvM3RseDBNKzJPV05jMGhlZGtNCjNZbXdZVHpQelk3Mncwemt0aGQv
            djdHNzdSb1NBMjhVRzhMVEJWc29sNmMKLS0tIGd4ejhHdDhHWnBodlVLQjV2N1dk
            MlQvUDdwMS9EMUZOQVY4OW15S1lFRTQKvHzgl+knrQX0fEHUZS649dR68TkZZl1w
            QaYVNzUJeHPNBANPrRA0+RHbjyqpBd0vAyOhKC4l2XJ3AKcvnAhSVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T23:26:12Z"
    mac: ENC[AES256_GCM,data:h0CcKi52EkmM7CQHykJVM5Qr/qlqJ8We2aOgIfvjbUt4iZ0oh1UHSmhE/o7gPVUJSuohe2vctL0iM52Ju77Cc7NN4KQmInGJVU/5qcyMXwNMf/FcA47W9mq+r5PTW+XcMbpvPHJ9RRHqBJCNNVJthpOYWb8wCME3qIXVhfCgvLE=,iv:XsvH0a8OjF90R5906L7uno/0cTZ8pi3i64OyEFcCWm0=,tag:EvULa/YarzTHZpU1x4fhQA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: headlamp
    namespace: headlamp
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://kubernetes-sigs.github.io/headlamp/
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWVV5NU5SbzZVRjNIQnRQ
            bXdOL05HTEJvM3RseDBNKzJPV05jMGhlZGtNCjNZbXdZVHpQelk3Mncwemt0aGQv
            djdHNzdSb1NBMjhVRzhMVEJWc29sNmMKLS0tIGd4ejhHdDhHWnBodlVLQjV2N1dk
            MlQvUDdwMS9EMUZOQVY4OW15S1lFRTQKvHzgl+knrQX0fEHUZS649dR68TkZZl1w
            QaYVNzUJeHPNBANPrRA0+RHbjyqpBd0vAyOhKC4l2XJ3AKcvnAhSVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T23:26:12Z"
    mac: ENC[AES256_GCM,data:h0CcKi52EkmM7CQHykJVM5Qr/qlqJ8We2aOgIfvjbUt4iZ0oh1UHSmhE/o7gPVUJSuohe2vctL0iM52Ju77Cc7NN4KQmInGJVU/5qcyMXwNMf/FcA47W9mq+r5PTW+XcMbpvPHJ9RRHqBJCNNVJthpOYWb8wCME3qIXVhfCgvLE=,iv:XsvH0a8OjF90R5906L7uno/0cTZ8pi3i64OyEFcCWm0=,tag:EvULa/YarzTHZpU1x4fhQA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: headlamp
    namespace: headlamp
spec:
    chart:
        spec:
            chart: headlamp
            sourceRef:
                kind: HelmRepository
                name: headlamp
            version: '*'
    interval: 1m0s
    values:
        ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
            hosts:
                - host: headlamp.frontplane.phorge.fr
                  paths:
                    - path: /
                      type: ImplementationSpecific
            tls:
                - secretName: headlamp-tls
                  hosts:
                    - headlamp.frontplane.phorge.fr
        config:
            inCluster: true
            oidc:
                secret:
                    create: ENC[AES256_GCM,data:BW98pw==,iv:sDf5RPaKrzwoTk2Or1phiMImIJ61NUHLeqpUOKboABo=,tag:w0f//EctQpnMfw541N8ywQ==,type:bool]
                    name: ENC[AES256_GCM,data:U4rysg==,iv:IZVq3aUJhubHdu5pnx0muSUwvMXuCAwac4DF87ydI9k=,tag:o0xgHDOAVmLg04VTcFb66g==,type:str]
                clientID: ENC[AES256_GCM,data:Z1MP93miZaMzuA==,iv:89VgYkvqwtaDQh/Bs+3GDNxSelDMYiHHzZrnSnhIjp8=,tag:zkCdSVCKQpJKZfgimMJ/Tg==,type:str]
                clientSecret: ENC[AES256_GCM,data:BRlOQxEtnTzGlvieGKW5z8G8Mwzx972aWMqq,iv:f+uVOqWRYKsFEiSKQq77YoU7CSaAQ+MwNJZa5wiWPoU=,tag:dwX7/IMX0LVZ4zrhRFppIg==,type:str]
                issuerURL: https://auth.phorge.fr
                scopes: profile, email, groups
                callbackURL: https://headlamp.frontplane.phorge.fr/oidc-callback
                # pluginsDir: /build/plugins
        # initContainers:
        #   - command:
        #       - /bin/sh
        #       - -c
        #       - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        #     image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        #     imagePullPolicy: Always
        #     name: headlamp-plugins
        #     volumeMounts:
        #       - mountPath: /build/plugins
        #         name: headlamp-plugins
        # persistentVolumeClaim:
        #   accessModes:
        #     - ReadWriteOnce
        #   enabled: true
        #   size: 1Gi
        #   volumeMode: Filesystem
        #   storageClassName: longhorn
        # volumeMounts:
        #   - mountPath: /build/plugins
        #     name: headlamp-plugins
        # volumes:
        #   - name: headlamp-plugins
        #     persistentVolumeClaim:
        #       claimName: headlamp
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWVV5NU5SbzZVRjNIQnRQ
            bXdOL05HTEJvM3RseDBNKzJPV05jMGhlZGtNCjNZbXdZVHpQelk3Mncwemt0aGQv
            djdHNzdSb1NBMjhVRzhMVEJWc29sNmMKLS0tIGd4ejhHdDhHWnBodlVLQjV2N1dk
            MlQvUDdwMS9EMUZOQVY4OW15S1lFRTQKvHzgl+knrQX0fEHUZS649dR68TkZZl1w
            QaYVNzUJeHPNBANPrRA0+RHbjyqpBd0vAyOhKC4l2XJ3AKcvnAhSVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T23:26:12Z"
    mac: ENC[AES256_GCM,data:h0CcKi52EkmM7CQHykJVM5Qr/qlqJ8We2aOgIfvjbUt4iZ0oh1UHSmhE/o7gPVUJSuohe2vctL0iM52Ju77Cc7NN4KQmInGJVU/5qcyMXwNMf/FcA47W9mq+r5PTW+XcMbpvPHJ9RRHqBJCNNVJthpOYWb8wCME3qIXVhfCgvLE=,iv:XsvH0a8OjF90R5906L7uno/0cTZ8pi3i64OyEFcCWm0=,tag:EvULa/YarzTHZpU1x4fhQA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: headlamp-admin
    namespace: kube-system
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWVV5NU5SbzZVRjNIQnRQ
            bXdOL05HTEJvM3RseDBNKzJPV05jMGhlZGtNCjNZbXdZVHpQelk3Mncwemt0aGQv
            djdHNzdSb1NBMjhVRzhMVEJWc29sNmMKLS0tIGd4ejhHdDhHWnBodlVLQjV2N1dk
            MlQvUDdwMS9EMUZOQVY4OW15S1lFRTQKvHzgl+knrQX0fEHUZS649dR68TkZZl1w
            QaYVNzUJeHPNBANPrRA0+RHbjyqpBd0vAyOhKC4l2XJ3AKcvnAhSVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T23:26:12Z"
    mac: ENC[AES256_GCM,data:h0CcKi52EkmM7CQHykJVM5Qr/qlqJ8We2aOgIfvjbUt4iZ0oh1UHSmhE/o7gPVUJSuohe2vctL0iM52Ju77Cc7NN4KQmInGJVU/5qcyMXwNMf/FcA47W9mq+r5PTW+XcMbpvPHJ9RRHqBJCNNVJthpOYWb8wCME3qIXVhfCgvLE=,iv:XsvH0a8OjF90R5906L7uno/0cTZ8pi3i64OyEFcCWm0=,tag:EvULa/YarzTHZpU1x4fhQA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: headlamp-admin
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
subjects:
    - kind: ServiceAccount
      name: headlamp-admin
      namespace: kube-system
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWVV5NU5SbzZVRjNIQnRQ
            bXdOL05HTEJvM3RseDBNKzJPV05jMGhlZGtNCjNZbXdZVHpQelk3Mncwemt0aGQv
            djdHNzdSb1NBMjhVRzhMVEJWc29sNmMKLS0tIGd4ejhHdDhHWnBodlVLQjV2N1dk
            MlQvUDdwMS9EMUZOQVY4OW15S1lFRTQKvHzgl+knrQX0fEHUZS649dR68TkZZl1w
            QaYVNzUJeHPNBANPrRA0+RHbjyqpBd0vAyOhKC4l2XJ3AKcvnAhSVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T23:26:12Z"
    mac: ENC[AES256_GCM,data:h0CcKi52EkmM7CQHykJVM5Qr/qlqJ8We2aOgIfvjbUt4iZ0oh1UHSmhE/o7gPVUJSuohe2vctL0iM52Ju77Cc7NN4KQmInGJVU/5qcyMXwNMf/FcA47W9mq+r5PTW+XcMbpvPHJ9RRHqBJCNNVJthpOYWb8wCME3qIXVhfCgvLE=,iv:XsvH0a8OjF90R5906L7uno/0cTZ8pi3i64OyEFcCWm0=,tag:EvULa/YarzTHZpU1x4fhQA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
