apiVersion: v1
kind: Namespace
metadata:
    name: headlamp
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINWFKNWNaWHo0ekladFEz
            M3pBNGU4VTRSMDU5Tmt0SkJQeEo4NGNnMUZNCng3TFBvcko2R2JueVFtV1VHQm9a
            VEpqcnRtZnhPTnY2QnhDbU9odEdXUE0KLS0tIDQ4T2tST210WHRpMnMyclQ3dC9E
            WjlST3JIZkhId2Yyb2dRa3QyRk81dWcKMALFbybf3aWaiijEQx51dJwVjMo0YrF/
            pErqMHK18eHwMg0GUeY36zPyZCLX9J9ruRoko/nq2wvjozMCHjBxfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T23:20:15Z"
    mac: ENC[AES256_GCM,data:OXsWwR3oYdDY8QK0mpaPFLKHsWMOZgHKVeFsGO8L3rHKGk6mKBku/EQUi0ZqD09qeGq0AwPH9BeEYqOtyistoDNwzafcwhi7yjDwarTWWtgBh+rYIGTS5aZUyCl7pk2D9ggQSQm0mzE3ISLJGU6H51gHyOz4RKcCWYj27al1mO0=,iv:ZkpcUr4q2VprIkxLTuZZ5zb2DW5oIXxzPfMPoZZnWN0=,tag:pmuTCiHC5Z2OqP5RSEhNpw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: headlamp
    namespace: headlamp
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://kubernetes-sigs.github.io/headlamp/
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINWFKNWNaWHo0ekladFEz
            M3pBNGU4VTRSMDU5Tmt0SkJQeEo4NGNnMUZNCng3TFBvcko2R2JueVFtV1VHQm9a
            VEpqcnRtZnhPTnY2QnhDbU9odEdXUE0KLS0tIDQ4T2tST210WHRpMnMyclQ3dC9E
            WjlST3JIZkhId2Yyb2dRa3QyRk81dWcKMALFbybf3aWaiijEQx51dJwVjMo0YrF/
            pErqMHK18eHwMg0GUeY36zPyZCLX9J9ruRoko/nq2wvjozMCHjBxfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T23:20:15Z"
    mac: ENC[AES256_GCM,data:OXsWwR3oYdDY8QK0mpaPFLKHsWMOZgHKVeFsGO8L3rHKGk6mKBku/EQUi0ZqD09qeGq0AwPH9BeEYqOtyistoDNwzafcwhi7yjDwarTWWtgBh+rYIGTS5aZUyCl7pk2D9ggQSQm0mzE3ISLJGU6H51gHyOz4RKcCWYj27al1mO0=,iv:ZkpcUr4q2VprIkxLTuZZ5zb2DW5oIXxzPfMPoZZnWN0=,tag:pmuTCiHC5Z2OqP5RSEhNpw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: headlamp
    namespace: headlamp
spec:
    chart:
        spec:
            chart: headlamp
            sourceRef:
                kind: HelmRepository
                name: headlamp
            version: '*'
    interval: 1m0s
    values:
        ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
            hosts:
                - host: headlamp.frontplane.phorge.fr
                  paths:
                    - path: /
                      type: ImplementationSpecific
            tls:
                - secretName: headlamp-tls
                  hosts:
                    - headlamp.frontplane.phorge.fr
        config:
            inCluster: true
            oidc:
                secret:
                    create: ENC[AES256_GCM,data:zNDpPA==,iv:fXgNJfqSkGSCdo7RFs1MG957GHb7meLGkG2w3pQZpdg=,tag:eaz8QalUQSmYtEjHa1m9cQ==,type:bool]
                    name: ENC[AES256_GCM,data:ZQnKTg==,iv:o/KhCyqty1oON0Ho3tFFsYA1I9OU/SR11pRen77KoBk=,tag:5RBWD17KFLVOpFzttEdyxQ==,type:str]
                clientID: ENC[AES256_GCM,data:3gA+kiUMMtazow==,iv:7LP1PZ3/J8eo3Wvq3ONYSrYWyNGUo66FbWXr2rmsv38=,tag:DP5Ta0nQe1487wKBi8hpZQ==,type:str]
                clientSecret: ENC[AES256_GCM,data:nDu6KKJqrFL5wNWDrov//66vrRDZEdOFmbY3,iv:tKcLxT2GG4T6MSnrIzSBhCfzgdW6emxTul9mOQB5AAg=,tag:v8l0px2bDNfxVLfxJr+cew==,type:str]
                issuerURL: https://auth.phorge.frS
                scopes: profile, email, groups
                callbackURL: https://headlamp.frontplane.phorge.fr/oidc-callback
                # pluginsDir: /build/plugins
        # initContainers:
        #   - command:
        #       - /bin/sh
        #       - -c
        #       - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        #     image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        #     imagePullPolicy: Always
        #     name: headlamp-plugins
        #     volumeMounts:
        #       - mountPath: /build/plugins
        #         name: headlamp-plugins
        # persistentVolumeClaim:
        #   accessModes:
        #     - ReadWriteOnce
        #   enabled: true
        #   size: 1Gi
        #   volumeMode: Filesystem
        #   storageClassName: longhorn
        # volumeMounts:
        #   - mountPath: /build/plugins
        #     name: headlamp-plugins
        # volumes:
        #   - name: headlamp-plugins
        #     persistentVolumeClaim:
        #       claimName: headlamp
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINWFKNWNaWHo0ekladFEz
            M3pBNGU4VTRSMDU5Tmt0SkJQeEo4NGNnMUZNCng3TFBvcko2R2JueVFtV1VHQm9a
            VEpqcnRtZnhPTnY2QnhDbU9odEdXUE0KLS0tIDQ4T2tST210WHRpMnMyclQ3dC9E
            WjlST3JIZkhId2Yyb2dRa3QyRk81dWcKMALFbybf3aWaiijEQx51dJwVjMo0YrF/
            pErqMHK18eHwMg0GUeY36zPyZCLX9J9ruRoko/nq2wvjozMCHjBxfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T23:20:15Z"
    mac: ENC[AES256_GCM,data:OXsWwR3oYdDY8QK0mpaPFLKHsWMOZgHKVeFsGO8L3rHKGk6mKBku/EQUi0ZqD09qeGq0AwPH9BeEYqOtyistoDNwzafcwhi7yjDwarTWWtgBh+rYIGTS5aZUyCl7pk2D9ggQSQm0mzE3ISLJGU6H51gHyOz4RKcCWYj27al1mO0=,iv:ZkpcUr4q2VprIkxLTuZZ5zb2DW5oIXxzPfMPoZZnWN0=,tag:pmuTCiHC5Z2OqP5RSEhNpw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: headlamp-admin
    namespace: kube-system
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINWFKNWNaWHo0ekladFEz
            M3pBNGU4VTRSMDU5Tmt0SkJQeEo4NGNnMUZNCng3TFBvcko2R2JueVFtV1VHQm9a
            VEpqcnRtZnhPTnY2QnhDbU9odEdXUE0KLS0tIDQ4T2tST210WHRpMnMyclQ3dC9E
            WjlST3JIZkhId2Yyb2dRa3QyRk81dWcKMALFbybf3aWaiijEQx51dJwVjMo0YrF/
            pErqMHK18eHwMg0GUeY36zPyZCLX9J9ruRoko/nq2wvjozMCHjBxfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T23:20:15Z"
    mac: ENC[AES256_GCM,data:OXsWwR3oYdDY8QK0mpaPFLKHsWMOZgHKVeFsGO8L3rHKGk6mKBku/EQUi0ZqD09qeGq0AwPH9BeEYqOtyistoDNwzafcwhi7yjDwarTWWtgBh+rYIGTS5aZUyCl7pk2D9ggQSQm0mzE3ISLJGU6H51gHyOz4RKcCWYj27al1mO0=,iv:ZkpcUr4q2VprIkxLTuZZ5zb2DW5oIXxzPfMPoZZnWN0=,tag:pmuTCiHC5Z2OqP5RSEhNpw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: headlamp-admin
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
subjects:
    - kind: ServiceAccount
      name: headlamp-admin
      namespace: kube-system
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINWFKNWNaWHo0ekladFEz
            M3pBNGU4VTRSMDU5Tmt0SkJQeEo4NGNnMUZNCng3TFBvcko2R2JueVFtV1VHQm9a
            VEpqcnRtZnhPTnY2QnhDbU9odEdXUE0KLS0tIDQ4T2tST210WHRpMnMyclQ3dC9E
            WjlST3JIZkhId2Yyb2dRa3QyRk81dWcKMALFbybf3aWaiijEQx51dJwVjMo0YrF/
            pErqMHK18eHwMg0GUeY36zPyZCLX9J9ruRoko/nq2wvjozMCHjBxfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T23:20:15Z"
    mac: ENC[AES256_GCM,data:OXsWwR3oYdDY8QK0mpaPFLKHsWMOZgHKVeFsGO8L3rHKGk6mKBku/EQUi0ZqD09qeGq0AwPH9BeEYqOtyistoDNwzafcwhi7yjDwarTWWtgBh+rYIGTS5aZUyCl7pk2D9ggQSQm0mzE3ISLJGU6H51gHyOz4RKcCWYj27al1mO0=,iv:ZkpcUr4q2VprIkxLTuZZ5zb2DW5oIXxzPfMPoZZnWN0=,tag:pmuTCiHC5Z2OqP5RSEhNpw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
