apiVersion: v1
kind: Namespace
metadata:
    name: headlamp
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SzBsekxCQldpMFE3MjAx
            QkU3RDE3UCt2dURCQU0wTXZONk1IYVI0MkZBCnJqZmpYYjg5VUNhd1cwQVY2bTFU
            cXVXK3RtbkQxYXBIVXRKSEdsblJaYVEKLS0tIEpKTGQ0WEJEZG1nU1ZSYVgrSm5h
            eU5QeUVFQjVmcVl2NzJiM0xQYWR3WlkK2n46lkeCZfYVKPMV13bxLT0zZYxXBTjt
            caFUwrVlauzf9SezvWGWjn7nnjTSdE/kadS4GX1Sg1dHoCTzbF5uhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T21:39:22Z"
    mac: ENC[AES256_GCM,data:j1LEsFzv+xi/5Iw47Dxqy60/5z516l0QRkp4M3DO1nzz1WYnnEOJLgcvsT0JfeBd/E+Zvp9lwvfQdsqfgY42W5x9oEwLIR/cR/wDsjg7qH1TwV6Z6Q9TttKvRgAaatAeOv66DYOPsJcgytpBrd4juV3NrAUY+IeFEch4pcpm1mg=,iv:vabRVUkmTXL7BZKpoc1Y4vY24UZfDpJch2ISvkZhX94=,tag:cvGArv/C9D659KryMNAGBg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: headlamp
    namespace: headlamp
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://kubernetes-sigs.github.io/headlamp/
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SzBsekxCQldpMFE3MjAx
            QkU3RDE3UCt2dURCQU0wTXZONk1IYVI0MkZBCnJqZmpYYjg5VUNhd1cwQVY2bTFU
            cXVXK3RtbkQxYXBIVXRKSEdsblJaYVEKLS0tIEpKTGQ0WEJEZG1nU1ZSYVgrSm5h
            eU5QeUVFQjVmcVl2NzJiM0xQYWR3WlkK2n46lkeCZfYVKPMV13bxLT0zZYxXBTjt
            caFUwrVlauzf9SezvWGWjn7nnjTSdE/kadS4GX1Sg1dHoCTzbF5uhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T21:39:22Z"
    mac: ENC[AES256_GCM,data:j1LEsFzv+xi/5Iw47Dxqy60/5z516l0QRkp4M3DO1nzz1WYnnEOJLgcvsT0JfeBd/E+Zvp9lwvfQdsqfgY42W5x9oEwLIR/cR/wDsjg7qH1TwV6Z6Q9TttKvRgAaatAeOv66DYOPsJcgytpBrd4juV3NrAUY+IeFEch4pcpm1mg=,iv:vabRVUkmTXL7BZKpoc1Y4vY24UZfDpJch2ISvkZhX94=,tag:cvGArv/C9D659KryMNAGBg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: headlamp
    namespace: headlamp
spec:
    chart:
        spec:
            chart: headlamp
            sourceRef:
                kind: HelmRepository
                name: headlamp
            version: '*'
    interval: 1m0s
    values:
        ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
            hosts:
                - host: frontplane.phorge.fr
                  paths:
                    - path: /
                      type: ImplementationSpecific
            tls:
                - secretName: headlamp-tls
                  hosts:
                    - frontplane.phorge.fr
        config:
            inCluster: true
            oidc:
                secret:
                    create: ENC[AES256_GCM,data:3kVixw==,iv:MR4O12/bHiu7LPLCVlxRvmSIkmwKXgaFd4Zs/BdYvBI=,tag:PBao2ukFodQ9v4nmZB4VWA==,type:bool]
                    name: ENC[AES256_GCM,data:7UrEMg==,iv:4OQBISlgWqQCAFDmMzD/ak4qabHbNb6TS9kj0F63Jew=,tag:Em838iRNrA209pY8iSF28w==,type:str]
                clientID: ENC[AES256_GCM,data:Lnzs4vBGNHI2sEcObNE2a1PqzOpUK3j2M1ccta+8og9Z5xQq,iv:/ogxxxq9rD9t4VSrbl6mpfpwynKWLQXYERv4KnKHrzY=,tag:0encdMQkzgj2kFsc/v3I0w==,type:str]
                clientSecret: ENC[AES256_GCM,data:a8Iwcru7RdUT8FaLqdLuWdxQ7K+HXARfgnVA7QxFw0aezTdE0LMDabsngDAWRQyJhHArdibw1cY=,iv:lsUw84ylSIfdjq+QHfu2wfCAiQxkJY+vcPe0/77C8zg=,tag:1ws7l7xxqrG5T9KhiFjtCA==,type:str]
                issuerURL: https://git.phorge.fr/
                scopes: profile, email, groups
                callbackURL: https://frontplane.phorge.fr/oidc-callback
                # pluginsDir: /build/plugins
        # initContainers:
        #   - command:
        #       - /bin/sh
        #       - -c
        #       - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        #     image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        #     imagePullPolicy: Always
        #     name: headlamp-plugins
        #     volumeMounts:
        #       - mountPath: /build/plugins
        #         name: headlamp-plugins
        # persistentVolumeClaim:
        #   accessModes:
        #     - ReadWriteOnce
        #   enabled: true
        #   size: 1Gi
        #   volumeMode: Filesystem
        #   storageClassName: longhorn
        # volumeMounts:
        #   - mountPath: /build/plugins
        #     name: headlamp-plugins
        # volumes:
        #   - name: headlamp-plugins
        #     persistentVolumeClaim:
        #       claimName: headlamp
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SzBsekxCQldpMFE3MjAx
            QkU3RDE3UCt2dURCQU0wTXZONk1IYVI0MkZBCnJqZmpYYjg5VUNhd1cwQVY2bTFU
            cXVXK3RtbkQxYXBIVXRKSEdsblJaYVEKLS0tIEpKTGQ0WEJEZG1nU1ZSYVgrSm5h
            eU5QeUVFQjVmcVl2NzJiM0xQYWR3WlkK2n46lkeCZfYVKPMV13bxLT0zZYxXBTjt
            caFUwrVlauzf9SezvWGWjn7nnjTSdE/kadS4GX1Sg1dHoCTzbF5uhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T21:39:22Z"
    mac: ENC[AES256_GCM,data:j1LEsFzv+xi/5Iw47Dxqy60/5z516l0QRkp4M3DO1nzz1WYnnEOJLgcvsT0JfeBd/E+Zvp9lwvfQdsqfgY42W5x9oEwLIR/cR/wDsjg7qH1TwV6Z6Q9TttKvRgAaatAeOv66DYOPsJcgytpBrd4juV3NrAUY+IeFEch4pcpm1mg=,iv:vabRVUkmTXL7BZKpoc1Y4vY24UZfDpJch2ISvkZhX94=,tag:cvGArv/C9D659KryMNAGBg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: headlamp-admin
    namespace: kube-system
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SzBsekxCQldpMFE3MjAx
            QkU3RDE3UCt2dURCQU0wTXZONk1IYVI0MkZBCnJqZmpYYjg5VUNhd1cwQVY2bTFU
            cXVXK3RtbkQxYXBIVXRKSEdsblJaYVEKLS0tIEpKTGQ0WEJEZG1nU1ZSYVgrSm5h
            eU5QeUVFQjVmcVl2NzJiM0xQYWR3WlkK2n46lkeCZfYVKPMV13bxLT0zZYxXBTjt
            caFUwrVlauzf9SezvWGWjn7nnjTSdE/kadS4GX1Sg1dHoCTzbF5uhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T21:39:22Z"
    mac: ENC[AES256_GCM,data:j1LEsFzv+xi/5Iw47Dxqy60/5z516l0QRkp4M3DO1nzz1WYnnEOJLgcvsT0JfeBd/E+Zvp9lwvfQdsqfgY42W5x9oEwLIR/cR/wDsjg7qH1TwV6Z6Q9TttKvRgAaatAeOv66DYOPsJcgytpBrd4juV3NrAUY+IeFEch4pcpm1mg=,iv:vabRVUkmTXL7BZKpoc1Y4vY24UZfDpJch2ISvkZhX94=,tag:cvGArv/C9D659KryMNAGBg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: headlamp-admin
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
subjects:
    - kind: ServiceAccount
      name: headlamp-admin
      namespace: kube-system
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SzBsekxCQldpMFE3MjAx
            QkU3RDE3UCt2dURCQU0wTXZONk1IYVI0MkZBCnJqZmpYYjg5VUNhd1cwQVY2bTFU
            cXVXK3RtbkQxYXBIVXRKSEdsblJaYVEKLS0tIEpKTGQ0WEJEZG1nU1ZSYVgrSm5h
            eU5QeUVFQjVmcVl2NzJiM0xQYWR3WlkK2n46lkeCZfYVKPMV13bxLT0zZYxXBTjt
            caFUwrVlauzf9SezvWGWjn7nnjTSdE/kadS4GX1Sg1dHoCTzbF5uhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T21:39:22Z"
    mac: ENC[AES256_GCM,data:j1LEsFzv+xi/5Iw47Dxqy60/5z516l0QRkp4M3DO1nzz1WYnnEOJLgcvsT0JfeBd/E+Zvp9lwvfQdsqfgY42W5x9oEwLIR/cR/wDsjg7qH1TwV6Z6Q9TttKvRgAaatAeOv66DYOPsJcgytpBrd4juV3NrAUY+IeFEch4pcpm1mg=,iv:vabRVUkmTXL7BZKpoc1Y4vY24UZfDpJch2ISvkZhX94=,tag:cvGArv/C9D659KryMNAGBg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
