apiVersion: v1
kind: Namespace
metadata:
    name: headlamp
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDJFTWpBblA1OTZtbFFa
            aDk3QXpwSjdPMW54T3p3bGlzZFNtSTRmRFVvCmhlbUtHNEpHMTRGcGVOYW9BbGRC
            MDRQWml2bjRjNGlMTjdGaTJ2UzJZVHcKLS0tIEV5aFN0NW80aWNxMWR6Rk5ZOWZX
            b1ViNEdLOE9jRnUzMjZtWG80aDh6akEKqMK0Zt4+7MfIjtCqzEQK+WWqHvuJnHCC
            5K0xcrC42i7Iqf6i57/1M/G7Y9fLqiymXo9iLUzFz9W+4KJaNUvgDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T23:23:27Z"
    mac: ENC[AES256_GCM,data:5CHozxZv0Tqqkl6BUsebwt96ENSpAhKSdUdq12xKlclWBDl0ahUD/h6C5p8BzCsm5B7QJ1kNxlsvX5IfR38u0rTKZCMldwm+W2hZRA7cDi9oyqj5u3Isn/tatiLn9ftvxcsj8VyERaz48oMgBMGQG1aEllvLlC+H6+G2d3Bq/cI=,iv:W6so8hNy+QmtswrPmdSk/wbsp1xlnoxPfVugDDY2fQE=,tag:WlhakoJK1oYMbGC66Hs12g==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: headlamp
    namespace: headlamp
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://kubernetes-sigs.github.io/headlamp/
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDJFTWpBblA1OTZtbFFa
            aDk3QXpwSjdPMW54T3p3bGlzZFNtSTRmRFVvCmhlbUtHNEpHMTRGcGVOYW9BbGRC
            MDRQWml2bjRjNGlMTjdGaTJ2UzJZVHcKLS0tIEV5aFN0NW80aWNxMWR6Rk5ZOWZX
            b1ViNEdLOE9jRnUzMjZtWG80aDh6akEKqMK0Zt4+7MfIjtCqzEQK+WWqHvuJnHCC
            5K0xcrC42i7Iqf6i57/1M/G7Y9fLqiymXo9iLUzFz9W+4KJaNUvgDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T23:23:27Z"
    mac: ENC[AES256_GCM,data:5CHozxZv0Tqqkl6BUsebwt96ENSpAhKSdUdq12xKlclWBDl0ahUD/h6C5p8BzCsm5B7QJ1kNxlsvX5IfR38u0rTKZCMldwm+W2hZRA7cDi9oyqj5u3Isn/tatiLn9ftvxcsj8VyERaz48oMgBMGQG1aEllvLlC+H6+G2d3Bq/cI=,iv:W6so8hNy+QmtswrPmdSk/wbsp1xlnoxPfVugDDY2fQE=,tag:WlhakoJK1oYMbGC66Hs12g==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: headlamp
    namespace: headlamp
spec:
    chart:
        spec:
            chart: headlamp
            sourceRef:
                kind: HelmRepository
                name: headlamp
            version: '*'
    interval: 1m0s
    values:
        ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
            hosts:
                - host: headlamp.frontplane.phorge.fr
                  paths:
                    - path: /
                      type: ImplementationSpecific
            tls:
                - secretName: headlamp-tls
                  hosts:
                    - headlamp.frontplane.phorge.fr
        config:
            inCluster: true
            oidc:
                secret:
                    create: ENC[AES256_GCM,data:nOyV9g==,iv:zEWE1P6iKUkN11KJdKxlzY3Nz8Q7N8R5u4avqEZVZuk=,tag:svLW50d3wTNh0g/G3c1yYw==,type:bool]
                    name: ENC[AES256_GCM,data:pVE7sw==,iv:dkvWJG+8J23jAPkW2NuWqN3oElWyNLA2skEhPSJ+yVE=,tag:DKhfgyeE2XV2hbddAzMQFg==,type:str]
                clientID: ENC[AES256_GCM,data:74Qzx0Ek2oHRtQ==,iv:AJtEzEPXtQC64ulnsTj9HEgBg7MawqI6I6wpJMLPY6k=,tag:/RfNYGR4zNtxEhf/hybQAA==,type:str]
                clientSecret: ENC[AES256_GCM,data:6KcZbjor/E6HjQOwYXk8mfZlEioCYOhHQAhf,iv:ia/leCZgU4kHOPRfiXVIgga/Au8Qtt4d1yHOAVR4kZA=,tag:w5lbZ0/n88MvjKZQ68gnAw==,type:str]
                issuerURL: https://auth.phorge.fr/dex
                scopes: profile, email, groups
                callbackURL: https://dashboard.frontplane.phorge.fr/oidc-callback
                # pluginsDir: /build/plugins
        # initContainers:
        #   - command:
        #       - /bin/sh
        #       - -c
        #       - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        #     image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        #     imagePullPolicy: Always
        #     name: headlamp-plugins
        #     volumeMounts:
        #       - mountPath: /build/plugins
        #         name: headlamp-plugins
        # persistentVolumeClaim:
        #   accessModes:
        #     - ReadWriteOnce
        #   enabled: true
        #   size: 1Gi
        #   volumeMode: Filesystem
        #   storageClassName: longhorn
        # volumeMounts:
        #   - mountPath: /build/plugins
        #     name: headlamp-plugins
        # volumes:
        #   - name: headlamp-plugins
        #     persistentVolumeClaim:
        #       claimName: headlamp
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDJFTWpBblA1OTZtbFFa
            aDk3QXpwSjdPMW54T3p3bGlzZFNtSTRmRFVvCmhlbUtHNEpHMTRGcGVOYW9BbGRC
            MDRQWml2bjRjNGlMTjdGaTJ2UzJZVHcKLS0tIEV5aFN0NW80aWNxMWR6Rk5ZOWZX
            b1ViNEdLOE9jRnUzMjZtWG80aDh6akEKqMK0Zt4+7MfIjtCqzEQK+WWqHvuJnHCC
            5K0xcrC42i7Iqf6i57/1M/G7Y9fLqiymXo9iLUzFz9W+4KJaNUvgDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T23:23:27Z"
    mac: ENC[AES256_GCM,data:5CHozxZv0Tqqkl6BUsebwt96ENSpAhKSdUdq12xKlclWBDl0ahUD/h6C5p8BzCsm5B7QJ1kNxlsvX5IfR38u0rTKZCMldwm+W2hZRA7cDi9oyqj5u3Isn/tatiLn9ftvxcsj8VyERaz48oMgBMGQG1aEllvLlC+H6+G2d3Bq/cI=,iv:W6so8hNy+QmtswrPmdSk/wbsp1xlnoxPfVugDDY2fQE=,tag:WlhakoJK1oYMbGC66Hs12g==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword)$
    version: 3.11.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: headlamp-admin
    namespace: kube-system
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDJFTWpBblA1OTZtbFFa
            aDk3QXpwSjdPMW54T3p3bGlzZFNtSTRmRFVvCmhlbUtHNEpHMTRGcGVOYW9BbGRC
            MDRQWml2bjRjNGlMTjdGaTJ2UzJZVHcKLS0tIEV5aFN0NW80aWNxMWR6Rk5ZOWZX
            b1ViNEdLOE9jRnUzMjZtWG80aDh6akEKqMK0Zt4+7MfIjtCqzEQK+WWqHvuJnHCC
            5K0xcrC42i7Iqf6i57/1M/G7Y9fLqiymXo9iLUzFz9W+4KJaNUvgDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T23:23:27Z"
    mac: ENC[AES256_GCM,data:5CHozxZv0Tqqkl6BUsebwt96ENSpAhKSdUdq12xKlclWBDl0ahUD/h6C5p8BzCsm5B7QJ1kNxlsvX5IfR38u0rTKZCMldwm+W2hZRA7cDi9oyqj5u3Isn/tatiLn9ftvxcsj8VyERaz48oMgBMGQG1aEllvLlC+H6+G2d3Bq/cI=,iv:W6so8hNy+QmtswrPmdSk/wbsp1xlnoxPfVugDDY2fQE=,tag:WlhakoJK1oYMbGC66Hs12g==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword)$
    version: 3.11.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: headlamp-admin
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
subjects:
    - kind: ServiceAccount
      name: headlamp-admin
      namespace: kube-system
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDJFTWpBblA1OTZtbFFa
            aDk3QXpwSjdPMW54T3p3bGlzZFNtSTRmRFVvCmhlbUtHNEpHMTRGcGVOYW9BbGRC
            MDRQWml2bjRjNGlMTjdGaTJ2UzJZVHcKLS0tIEV5aFN0NW80aWNxMWR6Rk5ZOWZX
            b1ViNEdLOE9jRnUzMjZtWG80aDh6akEKqMK0Zt4+7MfIjtCqzEQK+WWqHvuJnHCC
            5K0xcrC42i7Iqf6i57/1M/G7Y9fLqiymXo9iLUzFz9W+4KJaNUvgDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T23:23:27Z"
    mac: ENC[AES256_GCM,data:5CHozxZv0Tqqkl6BUsebwt96ENSpAhKSdUdq12xKlclWBDl0ahUD/h6C5p8BzCsm5B7QJ1kNxlsvX5IfR38u0rTKZCMldwm+W2hZRA7cDi9oyqj5u3Isn/tatiLn9ftvxcsj8VyERaz48oMgBMGQG1aEllvLlC+H6+G2d3Bq/cI=,iv:W6so8hNy+QmtswrPmdSk/wbsp1xlnoxPfVugDDY2fQE=,tag:WlhakoJK1oYMbGC66Hs12g==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword)$
    version: 3.11.0
