apiVersion: v1
kind: Namespace
metadata:
    name: kops
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRVBLZUMyZWRzT1lPTjlR
            VjZoOTRDQ3NFR2tjK1M0MTRHTWd5bXJNLzJvCkpQOGdSZ24xalphUkRtblJIRWlW
            bktYVFJjdmg5d0FKWTdhZlZVV3dzN1kKLS0tIGpuMTRUYTlrRnFhTjFkVENtY3B5
            ejhIYVdqZFQyVlRuNnJSVHpuU2lxRHMKaRg6b6HK59Yh+0T4D2n51ygRFlkNWd+X
            MGNMbROy4M7+NO8GndnifM+RBwRsi3DcEyxEU8rybdJSjD8xrlRnLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T11:36:59Z"
    mac: ENC[AES256_GCM,data:8dbTgIADHlR6zyik586qdhuVGuAKw8pkotQ0pzlXlpXH7YQQAawXDRBBq66q8kAIYJJ+uU9lL3J+oLhjnBLRrtFUiHmj7r3/cjBKC4vt5vSVNcywYCbWzIlUEImrb6cbh94N6Pm24oU8XNg3ieB/xZcG5YQSra9NjOhQNdkGkxI=,iv:Dc+UePXWyYSNgUwJr6fo+KmAb/y5sG3VIUSh43F586U=,tag:eeDkEIUo9Jaub0YbPuYAbQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared-keys)$
    version: 3.11.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: kube-ops-view
    namespace: kops
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRVBLZUMyZWRzT1lPTjlR
            VjZoOTRDQ3NFR2tjK1M0MTRHTWd5bXJNLzJvCkpQOGdSZ24xalphUkRtblJIRWlW
            bktYVFJjdmg5d0FKWTdhZlZVV3dzN1kKLS0tIGpuMTRUYTlrRnFhTjFkVENtY3B5
            ejhIYVdqZFQyVlRuNnJSVHpuU2lxRHMKaRg6b6HK59Yh+0T4D2n51ygRFlkNWd+X
            MGNMbROy4M7+NO8GndnifM+RBwRsi3DcEyxEU8rybdJSjD8xrlRnLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T11:36:59Z"
    mac: ENC[AES256_GCM,data:8dbTgIADHlR6zyik586qdhuVGuAKw8pkotQ0pzlXlpXH7YQQAawXDRBBq66q8kAIYJJ+uU9lL3J+oLhjnBLRrtFUiHmj7r3/cjBKC4vt5vSVNcywYCbWzIlUEImrb6cbh94N6Pm24oU8XNg3ieB/xZcG5YQSra9NjOhQNdkGkxI=,iv:Dc+UePXWyYSNgUwJr6fo+KmAb/y5sG3VIUSh43F586U=,tag:eeDkEIUo9Jaub0YbPuYAbQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared-keys)$
    version: 3.11.0
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: kube-ops-view
rules:
    - apiGroups:
        - ""
      resources:
        - nodes
        - pods
      verbs:
        - list
    - apiGroups:
        - metrics.k8s.io
      resources:
        - nodes
        - pods
      verbs:
        - get
        - list
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRVBLZUMyZWRzT1lPTjlR
            VjZoOTRDQ3NFR2tjK1M0MTRHTWd5bXJNLzJvCkpQOGdSZ24xalphUkRtblJIRWlW
            bktYVFJjdmg5d0FKWTdhZlZVV3dzN1kKLS0tIGpuMTRUYTlrRnFhTjFkVENtY3B5
            ejhIYVdqZFQyVlRuNnJSVHpuU2lxRHMKaRg6b6HK59Yh+0T4D2n51ygRFlkNWd+X
            MGNMbROy4M7+NO8GndnifM+RBwRsi3DcEyxEU8rybdJSjD8xrlRnLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T11:36:59Z"
    mac: ENC[AES256_GCM,data:8dbTgIADHlR6zyik586qdhuVGuAKw8pkotQ0pzlXlpXH7YQQAawXDRBBq66q8kAIYJJ+uU9lL3J+oLhjnBLRrtFUiHmj7r3/cjBKC4vt5vSVNcywYCbWzIlUEImrb6cbh94N6Pm24oU8XNg3ieB/xZcG5YQSra9NjOhQNdkGkxI=,iv:Dc+UePXWyYSNgUwJr6fo+KmAb/y5sG3VIUSh43F586U=,tag:eeDkEIUo9Jaub0YbPuYAbQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared-keys)$
    version: 3.11.0
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: kube-ops-view
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kube-ops-view
subjects:
    - kind: ServiceAccount
      name: kube-ops-view
      namespace: kops
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRVBLZUMyZWRzT1lPTjlR
            VjZoOTRDQ3NFR2tjK1M0MTRHTWd5bXJNLzJvCkpQOGdSZ24xalphUkRtblJIRWlW
            bktYVFJjdmg5d0FKWTdhZlZVV3dzN1kKLS0tIGpuMTRUYTlrRnFhTjFkVENtY3B5
            ejhIYVdqZFQyVlRuNnJSVHpuU2lxRHMKaRg6b6HK59Yh+0T4D2n51ygRFlkNWd+X
            MGNMbROy4M7+NO8GndnifM+RBwRsi3DcEyxEU8rybdJSjD8xrlRnLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T11:36:59Z"
    mac: ENC[AES256_GCM,data:8dbTgIADHlR6zyik586qdhuVGuAKw8pkotQ0pzlXlpXH7YQQAawXDRBBq66q8kAIYJJ+uU9lL3J+oLhjnBLRrtFUiHmj7r3/cjBKC4vt5vSVNcywYCbWzIlUEImrb6cbh94N6Pm24oU8XNg3ieB/xZcG5YQSra9NjOhQNdkGkxI=,iv:Dc+UePXWyYSNgUwJr6fo+KmAb/y5sG3VIUSh43F586U=,tag:eeDkEIUo9Jaub0YbPuYAbQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared-keys)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: basic-auth
    namespace: kops
data:
    auth: ENC[AES256_GCM,data:Fp7l7n+Q/xvJAKmzcOPGfptPHXS4dSXx8OYpkK8I4IJWEQxxmA+tYE0VJyvSWu2CJfZ3f0qhGhi1U27x,iv:zQ8RLOvaanDjgN/JGOWbLK4ACtlUPGF0cXpKp+5xtfk=,tag:eOIGfVuE9Gm+Hy8BHbfIbA==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRVBLZUMyZWRzT1lPTjlR
            VjZoOTRDQ3NFR2tjK1M0MTRHTWd5bXJNLzJvCkpQOGdSZ24xalphUkRtblJIRWlW
            bktYVFJjdmg5d0FKWTdhZlZVV3dzN1kKLS0tIGpuMTRUYTlrRnFhTjFkVENtY3B5
            ejhIYVdqZFQyVlRuNnJSVHpuU2lxRHMKaRg6b6HK59Yh+0T4D2n51ygRFlkNWd+X
            MGNMbROy4M7+NO8GndnifM+RBwRsi3DcEyxEU8rybdJSjD8xrlRnLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T11:36:59Z"
    mac: ENC[AES256_GCM,data:8dbTgIADHlR6zyik586qdhuVGuAKw8pkotQ0pzlXlpXH7YQQAawXDRBBq66q8kAIYJJ+uU9lL3J+oLhjnBLRrtFUiHmj7r3/cjBKC4vt5vSVNcywYCbWzIlUEImrb6cbh94N6Pm24oU8XNg3ieB/xZcG5YQSra9NjOhQNdkGkxI=,iv:Dc+UePXWyYSNgUwJr6fo+KmAb/y5sG3VIUSh43F586U=,tag:eeDkEIUo9Jaub0YbPuYAbQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared-keys)$
    version: 3.11.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        application: kube-ops-view
        component: redis
    name: kube-ops-view-redis
    namespace: kops
spec:
    replicas: 1
    selector:
        matchLabels:
            application: kube-ops-view
            component: redis
    template:
        metadata:
            labels:
                application: kube-ops-view
                component: redis
        spec:
            containers:
                - name: redis
                  image: redis:7-alpine
                  ports:
                    - containerPort: 6379
                      protocol: TCP
                  readinessProbe:
                    tcpSocket:
                        port: 6379
                  resources:
                    limits:
                        cpu: 100m
                        memory: 100Mi
                    requests:
                        cpu: 50m
                        memory: 50Mi
                  securityContext:
                    readOnlyRootFilesystem: true
                    runAsNonRoot: true
                    # we need to use the "redis" uid
                    runAsUser: 999
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRVBLZUMyZWRzT1lPTjlR
            VjZoOTRDQ3NFR2tjK1M0MTRHTWd5bXJNLzJvCkpQOGdSZ24xalphUkRtblJIRWlW
            bktYVFJjdmg5d0FKWTdhZlZVV3dzN1kKLS0tIGpuMTRUYTlrRnFhTjFkVENtY3B5
            ejhIYVdqZFQyVlRuNnJSVHpuU2lxRHMKaRg6b6HK59Yh+0T4D2n51ygRFlkNWd+X
            MGNMbROy4M7+NO8GndnifM+RBwRsi3DcEyxEU8rybdJSjD8xrlRnLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T11:36:59Z"
    mac: ENC[AES256_GCM,data:8dbTgIADHlR6zyik586qdhuVGuAKw8pkotQ0pzlXlpXH7YQQAawXDRBBq66q8kAIYJJ+uU9lL3J+oLhjnBLRrtFUiHmj7r3/cjBKC4vt5vSVNcywYCbWzIlUEImrb6cbh94N6Pm24oU8XNg3ieB/xZcG5YQSra9NjOhQNdkGkxI=,iv:Dc+UePXWyYSNgUwJr6fo+KmAb/y5sG3VIUSh43F586U=,tag:eeDkEIUo9Jaub0YbPuYAbQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared-keys)$
    version: 3.11.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        application: kube-ops-view
        component: frontend
    name: kube-ops-view
    namespace: kops
spec:
    replicas: 1
    selector:
        matchLabels:
            application: kube-ops-view
            component: frontend
    template:
        metadata:
            labels:
                application: kube-ops-view
                component: frontend
        spec:
            serviceAccountName: kube-ops-view
            imagePullSecrets:
                - name: regcred
            containers:
                - name: service
                  image: registry.haum.lnmch.fr/kops:latest
                  imagePullPolicy: Always
                  args:
                    - --redis-url=redis://kube-ops-view-redis:6379
                  ports:
                    - containerPort: 8080
                      protocol: TCP
                  readinessProbe:
                    httpGet:
                        path: /health
                        port: 8080
                    initialDelaySeconds: 5
                    timeoutSeconds: 1
                  livenessProbe:
                    httpGet:
                        path: /health
                        port: 8080
                    initialDelaySeconds: 30
                    periodSeconds: 30
                    timeoutSeconds: 10
                    failureThreshold: 5
                  resources:
                    limits:
                        cpu: 100m
                        memory: 100Mi
                    requests:
                        cpu: 50m
                        memory: 50Mi
                  securityContext:
                    readOnlyRootFilesystem: true
                    runAsNonRoot: true
                    runAsUser: 1000
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRVBLZUMyZWRzT1lPTjlR
            VjZoOTRDQ3NFR2tjK1M0MTRHTWd5bXJNLzJvCkpQOGdSZ24xalphUkRtblJIRWlW
            bktYVFJjdmg5d0FKWTdhZlZVV3dzN1kKLS0tIGpuMTRUYTlrRnFhTjFkVENtY3B5
            ejhIYVdqZFQyVlRuNnJSVHpuU2lxRHMKaRg6b6HK59Yh+0T4D2n51ygRFlkNWd+X
            MGNMbROy4M7+NO8GndnifM+RBwRsi3DcEyxEU8rybdJSjD8xrlRnLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T11:36:59Z"
    mac: ENC[AES256_GCM,data:8dbTgIADHlR6zyik586qdhuVGuAKw8pkotQ0pzlXlpXH7YQQAawXDRBBq66q8kAIYJJ+uU9lL3J+oLhjnBLRrtFUiHmj7r3/cjBKC4vt5vSVNcywYCbWzIlUEImrb6cbh94N6Pm24oU8XNg3ieB/xZcG5YQSra9NjOhQNdkGkxI=,iv:Dc+UePXWyYSNgUwJr6fo+KmAb/y5sG3VIUSh43F586U=,tag:eeDkEIUo9Jaub0YbPuYAbQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared-keys)$
    version: 3.11.0
---
apiVersion: v1
kind: Service
metadata:
    labels:
        application: kube-ops-view
        component: redis
    name: kube-ops-view-redis
    namespace: kops
spec:
    selector:
        application: kube-ops-view
        component: redis
    type: ClusterIP
    ports:
        - port: 6379
          protocol: TCP
          targetPort: 6379
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRVBLZUMyZWRzT1lPTjlR
            VjZoOTRDQ3NFR2tjK1M0MTRHTWd5bXJNLzJvCkpQOGdSZ24xalphUkRtblJIRWlW
            bktYVFJjdmg5d0FKWTdhZlZVV3dzN1kKLS0tIGpuMTRUYTlrRnFhTjFkVENtY3B5
            ejhIYVdqZFQyVlRuNnJSVHpuU2lxRHMKaRg6b6HK59Yh+0T4D2n51ygRFlkNWd+X
            MGNMbROy4M7+NO8GndnifM+RBwRsi3DcEyxEU8rybdJSjD8xrlRnLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T11:36:59Z"
    mac: ENC[AES256_GCM,data:8dbTgIADHlR6zyik586qdhuVGuAKw8pkotQ0pzlXlpXH7YQQAawXDRBBq66q8kAIYJJ+uU9lL3J+oLhjnBLRrtFUiHmj7r3/cjBKC4vt5vSVNcywYCbWzIlUEImrb6cbh94N6Pm24oU8XNg3ieB/xZcG5YQSra9NjOhQNdkGkxI=,iv:Dc+UePXWyYSNgUwJr6fo+KmAb/y5sG3VIUSh43F586U=,tag:eeDkEIUo9Jaub0YbPuYAbQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared-keys)$
    version: 3.11.0
---
apiVersion: v1
kind: Service
metadata:
    labels:
        application: kube-ops-view
        component: frontend
    name: kube-ops-view
    namespace: kops
spec:
    selector:
        application: kube-ops-view
        component: frontend
    type: ClusterIP
    ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRVBLZUMyZWRzT1lPTjlR
            VjZoOTRDQ3NFR2tjK1M0MTRHTWd5bXJNLzJvCkpQOGdSZ24xalphUkRtblJIRWlW
            bktYVFJjdmg5d0FKWTdhZlZVV3dzN1kKLS0tIGpuMTRUYTlrRnFhTjFkVENtY3B5
            ejhIYVdqZFQyVlRuNnJSVHpuU2lxRHMKaRg6b6HK59Yh+0T4D2n51ygRFlkNWd+X
            MGNMbROy4M7+NO8GndnifM+RBwRsi3DcEyxEU8rybdJSjD8xrlRnLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T11:36:59Z"
    mac: ENC[AES256_GCM,data:8dbTgIADHlR6zyik586qdhuVGuAKw8pkotQ0pzlXlpXH7YQQAawXDRBBq66q8kAIYJJ+uU9lL3J+oLhjnBLRrtFUiHmj7r3/cjBKC4vt5vSVNcywYCbWzIlUEImrb6cbh94N6Pm24oU8XNg3ieB/xZcG5YQSra9NjOhQNdkGkxI=,iv:Dc+UePXWyYSNgUwJr6fo+KmAb/y5sG3VIUSh43F586U=,tag:eeDkEIUo9Jaub0YbPuYAbQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared-keys)$
    version: 3.11.0
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: kops-ing
    namespace: kops
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
        nginx.ingress.kubernetes.io/auth-realm: Authentication Required
spec:
    tls:
        - hosts:
            - kops.frontplane.phorge.fr
          secretName: kops-tls
    rules:
        - host: kops.frontplane.phorge.fr
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: kube-ops-view
                        port:
                            number: 80
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRVBLZUMyZWRzT1lPTjlR
            VjZoOTRDQ3NFR2tjK1M0MTRHTWd5bXJNLzJvCkpQOGdSZ24xalphUkRtblJIRWlW
            bktYVFJjdmg5d0FKWTdhZlZVV3dzN1kKLS0tIGpuMTRUYTlrRnFhTjFkVENtY3B5
            ejhIYVdqZFQyVlRuNnJSVHpuU2lxRHMKaRg6b6HK59Yh+0T4D2n51ygRFlkNWd+X
            MGNMbROy4M7+NO8GndnifM+RBwRsi3DcEyxEU8rybdJSjD8xrlRnLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T11:36:59Z"
    mac: ENC[AES256_GCM,data:8dbTgIADHlR6zyik586qdhuVGuAKw8pkotQ0pzlXlpXH7YQQAawXDRBBq66q8kAIYJJ+uU9lL3J+oLhjnBLRrtFUiHmj7r3/cjBKC4vt5vSVNcywYCbWzIlUEImrb6cbh94N6Pm24oU8XNg3ieB/xZcG5YQSra9NjOhQNdkGkxI=,iv:Dc+UePXWyYSNgUwJr6fo+KmAb/y5sG3VIUSh43F586U=,tag:eeDkEIUo9Jaub0YbPuYAbQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared-keys)$
    version: 3.11.0
