apiVersion: v1
kind: Namespace
metadata:
    name: kube-prometheus-stack
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhck40U2l3c0FTSCtLZ3Rm
            dThYUGJ3QWpjblYrZkJGWHRXVWRNenZOcEdvClFBMzVrT3hCYjU0bksveUg5MHhk
            eU1MZTJPTmozWldsbXNtbVZDcndrOHcKLS0tIDBOdXlMV1BheGpiSFhKUjZsYWx1
            OUQ5am1IQ1JxbGNDRHpVK3B1MWlWaTQKvEM2UwkCxq6ANgJvRnD00nJApxMibcfx
            6ufCbFVeBFdkDs3iW/an/BvMnt5a/B/heMdh9v8mBT+VcBIw0G46oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:56:02Z"
    mac: ENC[AES256_GCM,data:2P/CpATi5vSxNFIvP29+ziMDI7U0oBKBhTYM1w+Qrol9rkY0ZK82rVHBlUkpcKYcgy+RZDW1wTSG4AUpUYKgGCJ2o+GyKNTyFOuwInfl+O74WxrHjzd2yAI6BBLWPEzbZ5Kor+Q21WC84oVqQBMJshSU1IyzxZ3TYcuMeKe+vSg=,iv:wYJ5VxBCmAqUVFH13RvHrria57ry5XjlT1ikXOukuzw=,tag:dqOpIalvRjYekYXkwy4YpQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:NQWcnMMdUCW/5Rq+Xu6OY8FPFA43TabsGoIf4g6EuqdqgXFr,iv:95zSb9hOwh4yYu2T3WLxD0zGS7t3ilpGsmg6ZojPKW4=,tag:knHqUhDbRmUU6+S8o+7Cow==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:yDxIhQBbO5PtW10ACFBDigUk0ArHHLzDKpGxFywHwWKxf0L6aAR3xpkAejIu/z07OTMK1FHvKC8=,iv:SpemJooFJhBEdLIjRU7EG8lqQpbeO0bi+IlZ85f1aa4=,tag:5zcbl0dpz8TehvQB5FMlzA==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhck40U2l3c0FTSCtLZ3Rm
            dThYUGJ3QWpjblYrZkJGWHRXVWRNenZOcEdvClFBMzVrT3hCYjU0bksveUg5MHhk
            eU1MZTJPTmozWldsbXNtbVZDcndrOHcKLS0tIDBOdXlMV1BheGpiSFhKUjZsYWx1
            OUQ5am1IQ1JxbGNDRHpVK3B1MWlWaTQKvEM2UwkCxq6ANgJvRnD00nJApxMibcfx
            6ufCbFVeBFdkDs3iW/an/BvMnt5a/B/heMdh9v8mBT+VcBIw0G46oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:56:02Z"
    mac: ENC[AES256_GCM,data:2P/CpATi5vSxNFIvP29+ziMDI7U0oBKBhTYM1w+Qrol9rkY0ZK82rVHBlUkpcKYcgy+RZDW1wTSG4AUpUYKgGCJ2o+GyKNTyFOuwInfl+O74WxrHjzd2yAI6BBLWPEzbZ5Kor+Q21WC84oVqQBMJshSU1IyzxZ3TYcuMeKe+vSg=,iv:wYJ5VxBCmAqUVFH13RvHrria57ry5XjlT1ikXOukuzw=,tag:dqOpIalvRjYekYXkwy4YpQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: kube-prometheus-stack
    namespace: kube-prometheus-stack
spec:
    interval: 1m0s
    timeout: 15m0s
    url: https://prometheus-community.github.io/helm-charts
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhck40U2l3c0FTSCtLZ3Rm
            dThYUGJ3QWpjblYrZkJGWHRXVWRNenZOcEdvClFBMzVrT3hCYjU0bksveUg5MHhk
            eU1MZTJPTmozWldsbXNtbVZDcndrOHcKLS0tIDBOdXlMV1BheGpiSFhKUjZsYWx1
            OUQ5am1IQ1JxbGNDRHpVK3B1MWlWaTQKvEM2UwkCxq6ANgJvRnD00nJApxMibcfx
            6ufCbFVeBFdkDs3iW/an/BvMnt5a/B/heMdh9v8mBT+VcBIw0G46oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:56:02Z"
    mac: ENC[AES256_GCM,data:2P/CpATi5vSxNFIvP29+ziMDI7U0oBKBhTYM1w+Qrol9rkY0ZK82rVHBlUkpcKYcgy+RZDW1wTSG4AUpUYKgGCJ2o+GyKNTyFOuwInfl+O74WxrHjzd2yAI6BBLWPEzbZ5Kor+Q21WC84oVqQBMJshSU1IyzxZ3TYcuMeKe+vSg=,iv:wYJ5VxBCmAqUVFH13RvHrria57ry5XjlT1ikXOukuzw=,tag:dqOpIalvRjYekYXkwy4YpQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: kube-prometheus-stack
spec:
    chart:
        spec:
            chart: kube-prometheus-stack
            sourceRef:
                kind: HelmRepository
                name: kube-prometheus-stack
            version: '*'
    interval: 1m0s
    values:
        grafana:
            envFromSecret: grafana-oauth-secret
            grafana.ini:
                auth.generic_oauth:
                    enabled: true
                    auth_url: https://git.phorge.fr/login/oauth/authorize
                    token_url: https://git.phorge.fr/login/oauth/access_token
                    api_url: https://git.phorge.fr/login/oauth/userinfo
                    scopes: openid, groups, email
                server:
                    domain: monitoring.phorge.fr
                    root_url: https://monitoring.phorge.fr/
            enabled: true
            adminPassword: ENC[AES256_GCM,data:TiHbPb1iykyqoeUJTECLd2Qhu0bCFfMe,iv:ITGhNw0n8rCgGRHtDqDhi/9weu1WkyCLfHs24rG5OEU=,tag:hLmUy4w566yPK52PDOIHcg==,type:str]
            service:
                type: ClusterIP
            ingress:
                enabled: true
                ingressClassName: traefik-public
                annotations:
                    cert-manager.io/cluster-issuer: letsencrypt
                hosts:
                    - monitoring.phorge.fr
                tls:
                    - secretName: grafana-tls
                      hosts:
                        - monitoring.phorge.fr
            persistence:
                enabled: false
            grafana:
                sidecar:
                    dashboards:
                        enabled: true
                        label: grafana_dashboard
                        labelValue: "1"
                        searchNamespace: kube-prometheus-stack
            additionalDataSources:
                - name: Loki
                  type: loki
                  access: proxy
                  url: http://loki.loki.svc.cluster.local:3100
                  isDefault: false
                  jsonData:
                    timeout: 60
                    maxLines: 1000
        prometheus:
            prometheusSpec:
                securityContext:
                    runAsGroup: 65534
                    runAsNonRoot: true
                    runAsUser: 65534
                    fsGroup: 65534
                nodeSelector:
                    node-role.kubernetes.io/worker: "true"
                retention: 30d
                retentionSize: 35GiB
                serviceMonitorSelector: {}
                secrets:
                    - incus-metrics-credentials
                storageSpec:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: nfs-uncritical
                            accessModes:
                                - ReadWriteOnce
                            resources:
                                requests:
                                    storage: 40Gi
                additionalScrapeConfigs:
                    - job_name: incus
                      metrics_path: /1.0/metrics
                      scheme: https
                      static_configs:
                        - targets:
                            - 10.1.0.1:8444
                            - 10.1.0.2:8444
                            - 10.1.0.3:8444
                            - 10.1.0.4:8444
                            - 10.1.0.5:8444
                            - 10.1.0.6:8444
                      tls_config:
                        ca_file: /etc/prometheus/secrets/incus-metrics-credentials/ca.crt
                        cert_file: /etc/prometheus/secrets/incus-metrics-credentials/metrics.crt
                        key_file: /etc/prometheus/secrets/incus-metrics-credentials/metrics.key
                        server_name: iaas.phorge.fr
                        insecure_skip_verify: true
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhck40U2l3c0FTSCtLZ3Rm
            dThYUGJ3QWpjblYrZkJGWHRXVWRNenZOcEdvClFBMzVrT3hCYjU0bksveUg5MHhk
            eU1MZTJPTmozWldsbXNtbVZDcndrOHcKLS0tIDBOdXlMV1BheGpiSFhKUjZsYWx1
            OUQ5am1IQ1JxbGNDRHpVK3B1MWlWaTQKvEM2UwkCxq6ANgJvRnD00nJApxMibcfx
            6ufCbFVeBFdkDs3iW/an/BvMnt5a/B/heMdh9v8mBT+VcBIw0G46oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:56:02Z"
    mac: ENC[AES256_GCM,data:2P/CpATi5vSxNFIvP29+ziMDI7U0oBKBhTYM1w+Qrol9rkY0ZK82rVHBlUkpcKYcgy+RZDW1wTSG4AUpUYKgGCJ2o+GyKNTyFOuwInfl+O74WxrHjzd2yAI6BBLWPEzbZ5Kor+Q21WC84oVqQBMJshSU1IyzxZ3TYcuMeKe+vSg=,iv:wYJ5VxBCmAqUVFH13RvHrria57ry5XjlT1ikXOukuzw=,tag:dqOpIalvRjYekYXkwy4YpQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: incus-metrics-credentials
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    metrics.crt: ENC[AES256_GCM,data:CLbgpYINbbCMkFxSCzSgCBauhtwjwsiMw5ORN/CLjpeGxkq6HB00GvG47lzOyy8SljWCEm3dz9GjqVtA4lOKj/j8sFBigYWbOHkOLQXj6JYW7GyFgSH1Yj+N+Jtpmp9vLBHoS/t0NyQ68T9QIIRmrojh731DChQZpNTpMCiGz30lNTk37nMEymfwTTcy2liW/4w72DzV3jWchc/ryqceojP3snnlKwCZ2ZNmtHlHY1ESelXanEdNiAlQ1FcFPmvctHH5fcjMxhy22pFAnUt6FWzqb64d+n6lTVBcd07dG/3HzCrEnSKJghhf8ecWxbho60nPgLEDxoYWvDL+7YkPufyFCzJ+n4sJ2E5dc9qkQ/OAC4rZimAY4ju17jQzifQNltJLgrey0tBCJmpAZ8PSeMNxy1HFptuoCfK4sU3P6oF3cRZ9JSrZZg9ravLpnerlkFNebBKeQOMIVGMP17GJsch3rbdGds6wJ37a/OsnVaiKat9xiTMHIsw/b67XOsfMWmJmVWU2sI6SN5TJ6Pxa/ETM+qcRHgq6BWrNmv8xoBV0xJOucc/8POvRYVdpmO+lD0oNe1rpcNGugyQW4IishKkFXKDX1QY8MTI0XG13sFWVETCt6Q39rYb/RsOMfB5EswXW9ZF7QygeRFYkrqHsP4hNfDw1cZMdlXwT3iT8FJjKR8xp/hMEvlo3zdKxAjqQEML81ViyXzpCppCOiryPunu7DlWSL14v2OWuF5xdp0v8OyQ1btgfCNhvXEoW2uzscsz9957uJ9R3VqJAfyiHAtP+SwgCuLxNlkVsnb1fYByX8o79XotTfgy/qE2UOsGuGvm9WdxxeNp8WhjWsvnWL7HT6LftNLEmVS0nCdZSu/2/HY/Z6YnmP+91e6dy0cz1,iv:vpH59lpH+EG5e6KPJB79WnoKK6qLATf+ZrbYUgdalgA=,tag:o+G+d/IBwa29iHjZ+i4FhQ==,type:str]
    metrics.key: ENC[AES256_GCM,data:Sx/pbB8Tf0uTVaSEWbkcfN3TlvySiPwoKnq9aI6R7RRTxEfrbfLSHGYbHn7AdGJVhSgLWn01svfDf4Z1L/jgpXK+Yhq3E/xLGvcvEkUD5SvGrC2W3YOgSEAPrEr/GbmzeDS8Z/4GWvHvoSww6sGxdfoqtcS2d+wxi0n8wOVoJPhMaplUT1y8hDmtPfWAQ5b9JBO5P2b3pD96FMmlwssbuAZBoh9eK9MzjLJI6H0gUFXwg6/T63D8Y4CZRLHwTZJN7AuCEyYGDasUnpX58iRq6pmbGS1CWPqCmqPzTqseYX/v+wdeBc1hXYbaQGQ+H1kdNymY1VlfZXaiVxFtCfGWB5U63Zj1/25HtwNnhnNS+oixkwqO8K+qx/n1mq6OdR9ADveiNwqirRb+KHSZ9kkzqwpJ,iv:wLvCyqzkQAVFVWOmaBLQCLO3drl96vtMoXe6XVDNCK0=,tag:b0UIrwAloRGc1c4n4dPbpA==,type:str]
    ca.crt: ENC[AES256_GCM,data:Wz/XrCs7bWye6SOg6MZXvznD0mMcTzUi81SZUGNLpTS9jMTeSji/bg/Np/yw+tiOB6U72LpYMQ0TZxOB71tfQk/27f8fcO36Q/l9sX//spT88kh8rigWQxiAnV2R50szPRJ1fVuJPe4ddAclhfEsxJAxhkDJFUW2/Xzpifg4bvII+Ju2ToAFnF/KNsPGunPAlFC3lavB3xj+wR8OI/PXbMHoyN9OkvXyt8hmMdzq1DBxWNXflUmCTwLOAjafRrMIUwOIzepq3IgSbZ9tjY8lpSsRpHQ02qiBhgIDKirH6a4i6iXpnAhPqfWDUAn4wOHYCd2o3ldy4mylPA8ZmJlT3ZtaKm8UI2SRFlG+dqA7H/dkyCXI4CNwrmcTY4yLpfWk58vdObtwSxtziE5Movq0UPCUJESjJmTDU+pbTqoch0cI4TvWJqTCXSbCJPmyeXijWWM+pH/ioNXrdYxf/95w+/wp3V0waSjQp3lkXmhORcT/5A5KwC8xUyqJ7Ts/pgJIrhag9fWG2BFgF5nHXt8qwiEcx3cyIUOjGe2jhOum/QU5ko8oKgZlkDP7trEexcjr+2LiD+skWkWM2Lp2J9E4LJrzyY4Q9bvdxvMAWooK0sZK8zsR3SGq6kPKO4X3tDKIOu/ympC4ZP3DrkmUbPgMfaMywgBjTM00znFjZFlKnXJGpFg8oQzMEBN9MNKZChLVBye63umf05QBP4GN+QAlvYVW/MXasDcRqfdiw+IBt8kGqa392Z4pjzsBQ7e9cbW4ebkRhNw+Povn6AGYYzx9c8dMzNsXioWZjb2OUy1D+MRfrU3odvlhfQzb/bGK33+RVOJA82Kn93XfBrwEE7xldWTLNURQx/+PNn2iOoGovfiQo1puolWwR30oDKbYtdMdGPut+s3RaanpbhkdaUAo/dCKO7Qg6TUi9n+xJsvoRoJcbB1CHnccMBy26OFG6djYbMltRUTRcPJPTK1LQdY6y3px7iX+J8gY7WIyRYuv0pgc0Ir+EvjSfOb+iA8wZw1eMw05XLvI,iv:jCgywZTw4wasL8tphaYYQZtyCFzWSkmt/yjhFnWrNlU=,tag:SA1+DiLi9EAuPcZYx96Ulw==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhck40U2l3c0FTSCtLZ3Rm
            dThYUGJ3QWpjblYrZkJGWHRXVWRNenZOcEdvClFBMzVrT3hCYjU0bksveUg5MHhk
            eU1MZTJPTmozWldsbXNtbVZDcndrOHcKLS0tIDBOdXlMV1BheGpiSFhKUjZsYWx1
            OUQ5am1IQ1JxbGNDRHpVK3B1MWlWaTQKvEM2UwkCxq6ANgJvRnD00nJApxMibcfx
            6ufCbFVeBFdkDs3iW/an/BvMnt5a/B/heMdh9v8mBT+VcBIw0G46oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:56:02Z"
    mac: ENC[AES256_GCM,data:2P/CpATi5vSxNFIvP29+ziMDI7U0oBKBhTYM1w+Qrol9rkY0ZK82rVHBlUkpcKYcgy+RZDW1wTSG4AUpUYKgGCJ2o+GyKNTyFOuwInfl+O74WxrHjzd2yAI6BBLWPEzbZ5Kor+Q21WC84oVqQBMJshSU1IyzxZ3TYcuMeKe+vSg=,iv:wYJ5VxBCmAqUVFH13RvHrria57ry5XjlT1ikXOukuzw=,tag:dqOpIalvRjYekYXkwy4YpQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
