apiVersion: v1
kind: Namespace
metadata:
    name: kube-prometheus-stack
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVjFBVktZR1Evakc4OVh6
            ZTd2Yk5nYys4TE5BRmR3MTl6ZmNhLzJmR1djCm5WWjJNQThrN2FYMFovZnhqT0Fq
            dldYQnYxM200ckJNbDN1MUhZRzJ5MWsKLS0tIENHZ2pPL2NjNVo3azBsanhjbDVO
            UFFJTEN1T0hyOFNJNjdZVjNOQ3JHSFUKZ2UEhAKPq9LC4b+jQfpBPF/kdsSEMgMy
            xzAeLa99zc1FpF7PmnmjBJjkLHQBsOMB41K5SziOym96O5UxTBhiSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T20:14:21Z"
    mac: ENC[AES256_GCM,data:5qsAjHgi3KEoYOK+aNDqjdijDr5pMG8USIhFq0KQLbhJVG/6v8eiz/aPhyi1R4ViMSA1BpMHhSeMpG0AEaCCNNgeaP+nBmuPl2yWGao/xmGUOxJtlf/+DyhKH2Bv8xP5IUBGF/dzBmukODwyS2QzE17Vn6MNVyIF2XcAaUG2uBI=,iv:mIEJvNFnrFZcY4oDq6MdXOnV7hXbMAuXzfmDaRV4ctU=,tag:7EunAU73zF3MUCwE90N5Iw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: kube-prometheus-stack
    namespace: kube-prometheus-stack
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://prometheus-community.github.io/helm-charts
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVjFBVktZR1Evakc4OVh6
            ZTd2Yk5nYys4TE5BRmR3MTl6ZmNhLzJmR1djCm5WWjJNQThrN2FYMFovZnhqT0Fq
            dldYQnYxM200ckJNbDN1MUhZRzJ5MWsKLS0tIENHZ2pPL2NjNVo3azBsanhjbDVO
            UFFJTEN1T0hyOFNJNjdZVjNOQ3JHSFUKZ2UEhAKPq9LC4b+jQfpBPF/kdsSEMgMy
            xzAeLa99zc1FpF7PmnmjBJjkLHQBsOMB41K5SziOym96O5UxTBhiSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T20:14:21Z"
    mac: ENC[AES256_GCM,data:5qsAjHgi3KEoYOK+aNDqjdijDr5pMG8USIhFq0KQLbhJVG/6v8eiz/aPhyi1R4ViMSA1BpMHhSeMpG0AEaCCNNgeaP+nBmuPl2yWGao/xmGUOxJtlf/+DyhKH2Bv8xP5IUBGF/dzBmukODwyS2QzE17Vn6MNVyIF2XcAaUG2uBI=,iv:mIEJvNFnrFZcY4oDq6MdXOnV7hXbMAuXzfmDaRV4ctU=,tag:7EunAU73zF3MUCwE90N5Iw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: kube-prometheus-stack
spec:
    chart:
        spec:
            chart: kube-prometheus-stack
            sourceRef:
                kind: HelmRepository
                name: kube-prometheus-stack
            version: '*'
    interval: 1m0s
    values:
        grafana:
            grafana.ini:
                server:
                    domain: monitoring.phorge.fr
                    root_url: https://monitoring.phorge.fr/
            enabled: true
            adminPassword: ENC[AES256_GCM,data:s9/xNW0WYsBb1WY9Tel4ldwKTQLCCXcP,iv:cmAVqSjf4BtAxR3S5s0tBaj9Gfonua5MTo8LD8oCBHE=,tag:aU7dJXZdKvRR6WYbD1uRkg==,type:str]
            service:
                type: ClusterIP
            ingress:
                enabled: true
                ingressClassName: nginx
                annotations:
                    cert-manager.io/cluster-issuer: letsencrypt
                hosts:
                    - monitoring.phorge.fr
                tls:
                    - secretName: grafana-tls
                      hosts:
                        - monitoring.phorge.fr
            persistence:
                enabled: true
                accessModes:
                    - ReadWriteOnce
                size: 1Gi
        prometheus:
            prometheusSpec:
                retention: 15d
                serviceMonitorSelector: {}
                secrets:
                    - incus-metrics-credentials
                storageSpec:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: longhorn
                            accessModes:
                                - ReadWriteOnce
                            resources:
                                requests:
                                    storage: 20Gi
                additionalScrapeConfigs:
                    - job_name: incus
                      metrics_path: /1.0/metrics
                      scheme: https
                      static_configs:
                        - targets:
                            - 10.1.0.1:8444
                            - 10.1.0.2:8444
                            - 10.1.0.3:8444
                            - 10.1.0.4:8444
                            - 10.1.0.5:8444
                            - 10.1.0.6:8444
                      tls_config:
                        ca_file: /etc/prometheus/secrets/incus-metrics-credentials/ca.crt
                        cert_file: /etc/prometheus/secrets/incus-metrics-credentials/metrics.crt
                        key_file: /etc/prometheus/secrets/incus-metrics-credentials/metrics.key
                        server_name: iaas.phorge.fr
                        insecure_skip_verify: true
                    - job_name: incus-node-exporter
                      static_configs:
                        - targets:
                            - 10.1.0.1:9100
                            - 10.1.0.2:9100
                            - 10.1.0.3:9100
                            - 10.1.0.4:9100
                            - 10.1.0.5:9100
                            - 10.1.0.6:9100
                    - job_name: hpc-node-exporter
                      static_configs:
                        - targets:
                            - 10.5.0.1:9100
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVjFBVktZR1Evakc4OVh6
            ZTd2Yk5nYys4TE5BRmR3MTl6ZmNhLzJmR1djCm5WWjJNQThrN2FYMFovZnhqT0Fq
            dldYQnYxM200ckJNbDN1MUhZRzJ5MWsKLS0tIENHZ2pPL2NjNVo3azBsanhjbDVO
            UFFJTEN1T0hyOFNJNjdZVjNOQ3JHSFUKZ2UEhAKPq9LC4b+jQfpBPF/kdsSEMgMy
            xzAeLa99zc1FpF7PmnmjBJjkLHQBsOMB41K5SziOym96O5UxTBhiSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T20:14:21Z"
    mac: ENC[AES256_GCM,data:5qsAjHgi3KEoYOK+aNDqjdijDr5pMG8USIhFq0KQLbhJVG/6v8eiz/aPhyi1R4ViMSA1BpMHhSeMpG0AEaCCNNgeaP+nBmuPl2yWGao/xmGUOxJtlf/+DyhKH2Bv8xP5IUBGF/dzBmukODwyS2QzE17Vn6MNVyIF2XcAaUG2uBI=,iv:mIEJvNFnrFZcY4oDq6MdXOnV7hXbMAuXzfmDaRV4ctU=,tag:7EunAU73zF3MUCwE90N5Iw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: incus-metrics-credentials
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    metrics.crt: ENC[AES256_GCM,data:ifxPUb4aUd2hoZjxqkO4N7+JDz8ll6FVjW81vlkodKvdi0zSjWtqkh/0xs3JaSddcIQx7kODyQnu6Yihf8gOhfFWfCCmHJVOxmjhT+8ahrFAfdliEge6DJMS7geDfUDfXG7XGLiSmJz1Em8qgRzsJvcJE6g9WD3E/354tFxGJdOztZKxkVcvrjnIYOQLZtnUbCWrSOCyOFZVDJcvPygtbIMulVwjiTUQn5hoE22BETTfD08t3/cnOWx5RW1vVoAmH+Wi0KmK+a/9IR/Yhb8wpf0qhtUMop5mPxDoCCelr5qRu6UJFSzB1lK3k/PkAWELuJGur1NjGcw2AqUXzLUmEGlEqzfE/yrdZ0qaV9rbZHfPJmGmWOaeWmOz1NSS/7PSSSIV4a5Fdf34fpv+JoeDuXHBl+X6TJoiAH0ECcN4dlNz1ZF0g0b+B9qIu3NKBuYZABKeHF43JBoqKt7xhdmf68n54+hKGOeQLseAgjolgkbUyqhufJqzPEfe1478TBpVMaAt2P9MCmk6Jpf2vRY4L+f6CWtRjKqClBkg+2arrOV5mpGUtIx1H657h/zQ2HHmJlJp4cWCSlhUbE6pSce2JgAYz9pmLyB/q/n+e/ZuCmhsaAfKJQW2P94C3+sxbn1HjPQkMC40ghU9/uKtfMPw7MZW+nlNtkwttvxk6u1CK5jzOUIPRDmfc8GuZshqePscHF56ON59NdDoIFgecpGZ7AKLncUkX9C+iCCbiNYTFxv5IEVJ4T3+TXObdLIfOZgM8VpadQ66s/mkK4SNpahs2IEOEm9f3vaa9shB+oAZ0sjnpbwnTGz3PO1Y/+Epj1uu8pYRAyS5INvBt/4VJZ5nNewV688IPxSGMD48uvOpTVIXoz5POwLDIk4f4sczv1ER,iv:aJv3G4TSf7oWXle548NEW2PCpq8rD91gQhIClDvhu4I=,tag:VGvI2HzJPEhWZLN3Ayl7RA==,type:str]
    metrics.key: ENC[AES256_GCM,data:jntU5znda6T4P52dRV8EDyuCQPJAlPIzSAI1x0mAeSLWI1yYFdSx0aX5SfrrhDSW9K9ANNQ7jtKuzS039hJN9ZGLaciOC4pFJPfNq/Rk/dfygVQ6ucp1dOJaJXLBugsC43/mDy1nTsVBAt0jG0ueBTzcoapt6z5OBIqk7+J/vmwXszZcLRQYdSVvmFrn8UDs9iy5SlOTnRzFMlmkFLsIwFG5fbq7FamTw5pojCfxI/tUQBF3a2mfhmVoQOy5y6rwT2DgdQwrxNmKLtiTvY765xA+8l+AmJPzsYuPo+bnIdiEDq55jCJTkg0joqP4WSKe6P1mtMdRKUuREFqAu399EPlPP9p/nxkz68AVI2loo0X3MasMtcl7OIP2qHVjXdbAhkh70nKK5XODr4OlOOSIRRcG,iv:bUOQ6ypRSCNGteE6xeTliD/4e/SJBQaQ5JHKogh9CDk=,tag:kK1wLfHvv9KU62I/K0MiFg==,type:str]
    ca.crt: ENC[AES256_GCM,data:kCEODmwhUv4IB2ErlYo+7Ja5t8ecLnkkuJQ2PLUXj+NNF8CWSUcCVor4wyO0kAHGKaD8UCKuT9xelfpka+2gTj+iOENGndtrcvUirMOLWAxueXfMy+sQH9gzKUtXx4Ymkwl13fzBGfggxQt3OI7xRT41Pz+USIVLdthBlzKdFyuciAHM85RVGaCkgSBQPdcverUBv/zXgbn+gH6g5LLk1fOUod3BvS8/oI5p2iLPMqyQXOjeWcfRc2i3AQNz4HPRkRgufI8oaijA0k48WynIHF/QhCp79rt8tpAjHjE0j+gGXsUgTrWY4NPDJ95aTsRJFnxYF2f8jbtB/sMutQG6g8yOCcOJ/RhZ1ILM11bAon2F8oTncVdO298miCt/jwXzoAZyyLaejUK7wMdH2kR6NH8cKfg2OK26wmJJKZkwj9d+TfuUqN8hFqnAzxvbYKQTBxabVrPIqS5J2ZThE8rpKUrxXuEaOuj8jeL6ngbYOMWWWalwy1NMhXUz1Ks5VywHegklaTEvfgMEA5T67rakXiMkpw3kwdjUo1Q9fUywHVwhNIHZCPwGyu72iB7GY44fLK3bGlZDqQyURveFbDSqWJxoZmZWO6qjiNCaNzmHodopmIrTUxgFLt5YSYbvB5H1KQXVTn8zkbQHvLkwa3yhH69vWoHAV33IZzlFllElJY/jau0mLyHz9hTwIFveY74ceJhCXpKBJdzzKqmv2zYIbX0ouwtKOF70edFcCpFpjKZ9YqnODidHwnQMLoSZmatIr589n4/aLaXbL8eR+ATUla5xLy/WsWCKN7Eb+FEnnIFGLj6B8SWZNriNWhJbYmm6TeeDOvFx//bfKRj0cNhdtPqDzDN+C64Wale9HzzsD5AgouCqS5uaeaeGhQ+5GtffTfW9W71JPpJ60ctCrcoQJCX4uHZwFBExIIjTXOnKG3YktF7m4AQ2UFOVglwylWy1Xa2x79aZw9XrspdIn9N0StTgsXJuQUZAmU/aBzYbVA78xNpPU5J7wVemIuLDtRG26rXJW0Jj,iv:flFf3EgBiUcov1ezCpoAg0/nkeOACGOarL9w8Eqzy7g=,tag:qlVpzhi/T78Lm6/PGyDMLg==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVjFBVktZR1Evakc4OVh6
            ZTd2Yk5nYys4TE5BRmR3MTl6ZmNhLzJmR1djCm5WWjJNQThrN2FYMFovZnhqT0Fq
            dldYQnYxM200ckJNbDN1MUhZRzJ5MWsKLS0tIENHZ2pPL2NjNVo3azBsanhjbDVO
            UFFJTEN1T0hyOFNJNjdZVjNOQ3JHSFUKZ2UEhAKPq9LC4b+jQfpBPF/kdsSEMgMy
            xzAeLa99zc1FpF7PmnmjBJjkLHQBsOMB41K5SziOym96O5UxTBhiSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T20:14:21Z"
    mac: ENC[AES256_GCM,data:5qsAjHgi3KEoYOK+aNDqjdijDr5pMG8USIhFq0KQLbhJVG/6v8eiz/aPhyi1R4ViMSA1BpMHhSeMpG0AEaCCNNgeaP+nBmuPl2yWGao/xmGUOxJtlf/+DyhKH2Bv8xP5IUBGF/dzBmukODwyS2QzE17Vn6MNVyIF2XcAaUG2uBI=,iv:mIEJvNFnrFZcY4oDq6MdXOnV7hXbMAuXzfmDaRV4ctU=,tag:7EunAU73zF3MUCwE90N5Iw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared)$
    version: 3.11.0
