apiVersion: v1
kind: Namespace
metadata:
    name: kube-prometheus-stack
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaGdoa1BVdTBHUWdHSEQ1
            cXdueTBHdEFDNUhLeFZ1YWtnMFJnK3djdlVzClhZRHBwSUhrNE5BdUFSUWd2Mm5W
            N2FOK1F0OXI1MUxzVitzU2JCN3V3MTQKLS0tIDlna1Q2SmdtdzhZTnNzbEZBcEZL
            YWpEQ3l0UTlOSi9yZmVkQWtwbS9aMm8K9r0PCe6E0KDy62xPqxZGu2ILj51iHRYH
            G1xZW4IDXYeG5Pie5/ZdL+cmgTZiF4J4QerKaabM+TBiLPKxBAu8Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T21:49:37Z"
    mac: ENC[AES256_GCM,data:nKr8LmBK0GhO3p1Qk6aJU3yzUyJxuZRk2brrWzRXOcEB8zJyjZvO5FmASpr61dQB8S2Zre78vEyIruPty/f7PIARuVkqlQjWgJ1drUgjpRpeO6cTlsNcF78p360tExLatl7QTENTWih/ybdIvikYTNdKRsmNsIjCDYvcqWyWzEg=,iv:xWFe3vxcz/TuQ23OjYdHphmjJ1EUw43m773CQUzh2x8=,tag:U+3z68sfmCMQGPHqU5abwg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: kube-prometheus-stack
    namespace: kube-prometheus-stack
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://prometheus-community.github.io/helm-charts
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaGdoa1BVdTBHUWdHSEQ1
            cXdueTBHdEFDNUhLeFZ1YWtnMFJnK3djdlVzClhZRHBwSUhrNE5BdUFSUWd2Mm5W
            N2FOK1F0OXI1MUxzVitzU2JCN3V3MTQKLS0tIDlna1Q2SmdtdzhZTnNzbEZBcEZL
            YWpEQ3l0UTlOSi9yZmVkQWtwbS9aMm8K9r0PCe6E0KDy62xPqxZGu2ILj51iHRYH
            G1xZW4IDXYeG5Pie5/ZdL+cmgTZiF4J4QerKaabM+TBiLPKxBAu8Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T21:49:37Z"
    mac: ENC[AES256_GCM,data:nKr8LmBK0GhO3p1Qk6aJU3yzUyJxuZRk2brrWzRXOcEB8zJyjZvO5FmASpr61dQB8S2Zre78vEyIruPty/f7PIARuVkqlQjWgJ1drUgjpRpeO6cTlsNcF78p360tExLatl7QTENTWih/ybdIvikYTNdKRsmNsIjCDYvcqWyWzEg=,iv:xWFe3vxcz/TuQ23OjYdHphmjJ1EUw43m773CQUzh2x8=,tag:U+3z68sfmCMQGPHqU5abwg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: kube-prometheus-stack
spec:
    chart:
        spec:
            chart: kube-prometheus-stack
            sourceRef:
                kind: HelmRepository
                name: kube-prometheus-stack
            version: '*'
    interval: 1m0s
    values:
        grafana:
            grafana.ini:
                server:
                    domain: monitoring.phorge.fr
                    root_url: https://monitoring.phorge.fr/
            enabled: true
            adminPassword: ENC[AES256_GCM,data:LFYDHDijbxiwtZaJomTah5ubDDK/nbQy,iv:uHA6iz4tfgHjsEOGYKZNeNx8EyAZSS56xtkR7mWsOfI=,tag:rka7FRCRzoGXkywRHTyF1Q==,type:str]
            service:
                type: ClusterIP
            ingress:
                enabled: true
                ingressClassName: nginx
                annotations:
                    cert-manager.io/cluster-issuer: letsencrypt
                hosts:
                    - monitoring.phorge.fr
                tls:
                    - secretName: grafana-tls
                      hosts:
                        - monitoring.phorge.fr
            persistence:
                enabled: true
                accessModes:
                    - ReadWriteOnce
                size: 1Gi
        prometheus:
            prometheusSpec:
                retention: 15d
                serviceMonitorSelector: {}
                storageSpec:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: longhorn
                            accessModes:
                                - ReadWriteOnce
                            resources:
                                requests:
                                    storage: 20Gi
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaGdoa1BVdTBHUWdHSEQ1
            cXdueTBHdEFDNUhLeFZ1YWtnMFJnK3djdlVzClhZRHBwSUhrNE5BdUFSUWd2Mm5W
            N2FOK1F0OXI1MUxzVitzU2JCN3V3MTQKLS0tIDlna1Q2SmdtdzhZTnNzbEZBcEZL
            YWpEQ3l0UTlOSi9yZmVkQWtwbS9aMm8K9r0PCe6E0KDy62xPqxZGu2ILj51iHRYH
            G1xZW4IDXYeG5Pie5/ZdL+cmgTZiF4J4QerKaabM+TBiLPKxBAu8Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T21:49:37Z"
    mac: ENC[AES256_GCM,data:nKr8LmBK0GhO3p1Qk6aJU3yzUyJxuZRk2brrWzRXOcEB8zJyjZvO5FmASpr61dQB8S2Zre78vEyIruPty/f7PIARuVkqlQjWgJ1drUgjpRpeO6cTlsNcF78p360tExLatl7QTENTWih/ybdIvikYTNdKRsmNsIjCDYvcqWyWzEg=,iv:xWFe3vxcz/TuQ23OjYdHphmjJ1EUw43m773CQUzh2x8=,tag:U+3z68sfmCMQGPHqU5abwg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword)$
    version: 3.11.0
