apiVersion: v1
kind: Namespace
metadata:
    name: loki
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMjM1aXBuSXFYS0tGWGFy
            V1cxUjNPMHQrNWxLZk1HQlZLMkFjVE5QbnlnCkJVbmN1dXFsWWVmMjdodVpTYWdF
            MHRkaHJCWktycTZYQTVOM05PcGlhWUEKLS0tIC8vaDUzMFFicDUxOEw0Ukx6NXll
            TDNIZy9vWnQ0c1FwZ1l6bHYvRkgyYkUKiRPTn+IerthQdsD99qC0x0wvtIqDeP7r
            fvS1KKEn4HXo/nK3MUXhogqoWINs3NzTLISamlvrim2K6LiHH1d/5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T11:44:24Z"
    mac: ENC[AES256_GCM,data:/bZLsi8sbI4Oek6rh56ZOqCLfwgZNacMMSM/ffIy8o3Mq0mR9ZSHcydKYAOCEpHv+d2K3Oj7HCJQYlXWAZQZUqoJsnd+Hb2uYG/a8dNfGnOiqB4hCBnU7sNm4lY7sqVF2qhDX2pcWRzOSn7wZw1/g96HNSPlJkMPbxkrXjNY8ow=,iv:nfPRzvMVLj9Ebs9oEO2W6ufln0I3xFeCRAOj5V2dpnA=,tag:Wrsekq4hWkICxjSisNidAw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: loki-config
    namespace: loki
data:
    loki-config.yaml: ENC[AES256_GCM,data:Uy2czAP3+DacEVs8QBrXG2pyMegIKYzzsgSWxPaae/WeZOPpIjd+RmFhKnha7fNzHIJDarLD3PGovxvSZJ0B8vEdsrH5JBTNPYI7bxwJKkB34tMb9uGbgvlSQOpYNUuQUBc9HhbCVB0dpN1nYPlwyH9NXeeBpoBz7OeXAa1rg6jr6WYUHVvSsuqyCU2ZxmvAnee3fxeG25XLOsRb7krVe0vvjkgXgQw/64IK70wso2yxBKrEtOigueon3PGNrBCGIzR9RcuE3TpcfQj/qz76EqsA8Pc5vQH7Fsj+bxY5xzZHarLOxZ39+4Ro/o4O1vPQ19ozoons0ppQQ4PKKOv3WS3K5ZXpx0+rTHVVHMZatjzuwt1JP8/xkSj8YepW2BF5GQNFeO1bGoNFxZS+XvWdXIT1ILSVL82l+T1HQI8iEh6UfLEsGTU92GRVuDsxgV4Y+YO67lHulvlktadZVmIEPKpZZ04bAxgaDWI3JXtNPOIJJeuMVJNCvr8qIGglZEzcy24cdJc2jFXlLJBCV486/853JADjVh0lGlzF3FRpAJj0ljY75HFHgi/6odzyUUL+HKB3u+l3/Xb8hVgn7osQTOG98NP1M6U2J4UP/KIumiMEKP1LTYRHKgT0bfRS+LbAVY2FLTvwsXqxzXlKykcKOKTmVMuZU5lrHX/IaP388evSRginP/xRXmEd4MVMW/rOOJoh9oR54kcmPX0F6i0GV3L3FxfJqJjvkXpY1zKZF8bzBJQi4nC6kuAzM/Ij+WseGgrgPU/Cma18NeSaEj5esoKY/ax0r1yMq3vnTt17fsCGaEHsWu+rkHwnoJu2v0ihNJpoInfkB37Xw5UKzEYQykwY0QbJRpcnV4lZmVr+3NFQ4vm78zdt1uqCbq0pmlravXPchkPnj5j2A7XbNono/Ct8NlOFt75J4S9NIPrNPWMZdbbXgBBI2PjkHHd/bvgflBl8jvFTfYAvFUcuOnuRgnyoHUWrD4hOhWerYYSy3m6SP2iSAhzsJK7fhQ8qNMVSKmOS2ZChsvncmQ8y2raM76UiGw4OcyJnCf4r9lmK4qTBw1AwTms1k8B+/rSlFxAPORpK96XujBSD8TDb2zXkbsvTweDD5BQk8SqoaOoOMscsqz30A4E+wOM010y9Ax2Ux3+okbeAwd8=,iv:EGS6z80XrCn9U2yWvdO9c/5Jc7XBxzRguClHjS2lv2E=,tag:qyaSnyQKHG2dgR2gsxCdsg==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMjM1aXBuSXFYS0tGWGFy
            V1cxUjNPMHQrNWxLZk1HQlZLMkFjVE5QbnlnCkJVbmN1dXFsWWVmMjdodVpTYWdF
            MHRkaHJCWktycTZYQTVOM05PcGlhWUEKLS0tIC8vaDUzMFFicDUxOEw0Ukx6NXll
            TDNIZy9vWnQ0c1FwZ1l6bHYvRkgyYkUKiRPTn+IerthQdsD99qC0x0wvtIqDeP7r
            fvS1KKEn4HXo/nK3MUXhogqoWINs3NzTLISamlvrim2K6LiHH1d/5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T11:44:24Z"
    mac: ENC[AES256_GCM,data:/bZLsi8sbI4Oek6rh56ZOqCLfwgZNacMMSM/ffIy8o3Mq0mR9ZSHcydKYAOCEpHv+d2K3Oj7HCJQYlXWAZQZUqoJsnd+Hb2uYG/a8dNfGnOiqB4hCBnU7sNm4lY7sqVF2qhDX2pcWRzOSn7wZw1/g96HNSPlJkMPbxkrXjNY8ow=,iv:nfPRzvMVLj9Ebs9oEO2W6ufln0I3xFeCRAOj5V2dpnA=,tag:Wrsekq4hWkICxjSisNidAw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: loki-pvc
    namespace: loki
spec:
    storageClassName: nfs-uncritical
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 15Gi
    volumeMode: Filesystem
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMjM1aXBuSXFYS0tGWGFy
            V1cxUjNPMHQrNWxLZk1HQlZLMkFjVE5QbnlnCkJVbmN1dXFsWWVmMjdodVpTYWdF
            MHRkaHJCWktycTZYQTVOM05PcGlhWUEKLS0tIC8vaDUzMFFicDUxOEw0Ukx6NXll
            TDNIZy9vWnQ0c1FwZ1l6bHYvRkgyYkUKiRPTn+IerthQdsD99qC0x0wvtIqDeP7r
            fvS1KKEn4HXo/nK3MUXhogqoWINs3NzTLISamlvrim2K6LiHH1d/5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T11:44:24Z"
    mac: ENC[AES256_GCM,data:/bZLsi8sbI4Oek6rh56ZOqCLfwgZNacMMSM/ffIy8o3Mq0mR9ZSHcydKYAOCEpHv+d2K3Oj7HCJQYlXWAZQZUqoJsnd+Hb2uYG/a8dNfGnOiqB4hCBnU7sNm4lY7sqVF2qhDX2pcWRzOSn7wZw1/g96HNSPlJkMPbxkrXjNY8ow=,iv:nfPRzvMVLj9Ebs9oEO2W6ufln0I3xFeCRAOj5V2dpnA=,tag:Wrsekq4hWkICxjSisNidAw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: loki
    namespace: loki
    labels:
        app: loki
spec:
    replicas: 1
    selector:
        matchLabels:
            app: loki
    template:
        metadata:
            labels:
                app: loki
        spec:
            nodeSelector:
                node-role.kubernetes.io/worker: "true"
            containers:
                - name: loki
                  image: grafana/loki:2.9.1
                  args:
                    - -config.file=/etc/loki/local-config.yaml
                  ports:
                    - containerPort: 3100
                  volumeMounts:
                    - name: loki-data
                      mountPath: /loki
                    - name: loki-config
                      mountPath: /etc/loki/local-config.yaml
                      subPath: loki-config.yaml
                  securityContext:
                    runAsUser: 0
            volumes:
                - name: loki-data
                  persistentVolumeClaim:
                    claimName: loki-pvc
                - name: loki-config
                  configMap:
                    name: loki-config
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMjM1aXBuSXFYS0tGWGFy
            V1cxUjNPMHQrNWxLZk1HQlZLMkFjVE5QbnlnCkJVbmN1dXFsWWVmMjdodVpTYWdF
            MHRkaHJCWktycTZYQTVOM05PcGlhWUEKLS0tIC8vaDUzMFFicDUxOEw0Ukx6NXll
            TDNIZy9vWnQ0c1FwZ1l6bHYvRkgyYkUKiRPTn+IerthQdsD99qC0x0wvtIqDeP7r
            fvS1KKEn4HXo/nK3MUXhogqoWINs3NzTLISamlvrim2K6LiHH1d/5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T11:44:24Z"
    mac: ENC[AES256_GCM,data:/bZLsi8sbI4Oek6rh56ZOqCLfwgZNacMMSM/ffIy8o3Mq0mR9ZSHcydKYAOCEpHv+d2K3Oj7HCJQYlXWAZQZUqoJsnd+Hb2uYG/a8dNfGnOiqB4hCBnU7sNm4lY7sqVF2qhDX2pcWRzOSn7wZw1/g96HNSPlJkMPbxkrXjNY8ow=,iv:nfPRzvMVLj9Ebs9oEO2W6ufln0I3xFeCRAOj5V2dpnA=,tag:Wrsekq4hWkICxjSisNidAw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
kind: Service
metadata:
    name: loki
    namespace: loki
    labels:
        app: loki
spec:
    type: ClusterIP
    ports:
        - port: 3100
          targetPort: 3100
          protocol: TCP
          name: loki
    selector:
        app: loki
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMjM1aXBuSXFYS0tGWGFy
            V1cxUjNPMHQrNWxLZk1HQlZLMkFjVE5QbnlnCkJVbmN1dXFsWWVmMjdodVpTYWdF
            MHRkaHJCWktycTZYQTVOM05PcGlhWUEKLS0tIC8vaDUzMFFicDUxOEw0Ukx6NXll
            TDNIZy9vWnQ0c1FwZ1l6bHYvRkgyYkUKiRPTn+IerthQdsD99qC0x0wvtIqDeP7r
            fvS1KKEn4HXo/nK3MUXhogqoWINs3NzTLISamlvrim2K6LiHH1d/5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T11:44:24Z"
    mac: ENC[AES256_GCM,data:/bZLsi8sbI4Oek6rh56ZOqCLfwgZNacMMSM/ffIy8o3Mq0mR9ZSHcydKYAOCEpHv+d2K3Oj7HCJQYlXWAZQZUqoJsnd+Hb2uYG/a8dNfGnOiqB4hCBnU7sNm4lY7sqVF2qhDX2pcWRzOSn7wZw1/g96HNSPlJkMPbxkrXjNY8ow=,iv:nfPRzvMVLj9Ebs9oEO2W6ufln0I3xFeCRAOj5V2dpnA=,tag:Wrsekq4hWkICxjSisNidAw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
data:
    users: ENC[AES256_GCM,data:YWsefg5pr4Msp1zBiTThX2dnI6R+fmB/T1E5dG2wnl4FcjVsAPdpB2TXN3fN/geLWcy6DNPx+uqJ7y7DkxnU8EJPR7fCwr0f+LkfYJXDRJA2tPTW76nWWmuSI9grAqlK2+egtwmDe9nvvsdKatE42fWphuravhVvaviDcJATc5ipeD8qKcGagS2LAl5L1ZGYmtu9IDvK9zEex31g2sF8ylqJogANJjgt72NtP1+VpvI1uvRWa04/HfNjvclJkUTKJtbw1V0FzK6ZtsIm99jGLId/M/rC0oksKiawMXLRETCs40G8HJEVsOWDN8Uv2Agfs9Q7M/8dTgl5jqdLTQQd5hW7uEhGuM1+6DLOM7Xmz6k=,iv:HtVn30ZaGjl5f5BBUR+qkfj7e5YuLd1AjN1jSdqT0I8=,tag:qVzDCOKzugRcUVFacVpuHw==,type:str]
kind: Secret
metadata:
    name: loki-basic-auth-secret
    namespace: loki
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMjM1aXBuSXFYS0tGWGFy
            V1cxUjNPMHQrNWxLZk1HQlZLMkFjVE5QbnlnCkJVbmN1dXFsWWVmMjdodVpTYWdF
            MHRkaHJCWktycTZYQTVOM05PcGlhWUEKLS0tIC8vaDUzMFFicDUxOEw0Ukx6NXll
            TDNIZy9vWnQ0c1FwZ1l6bHYvRkgyYkUKiRPTn+IerthQdsD99qC0x0wvtIqDeP7r
            fvS1KKEn4HXo/nK3MUXhogqoWINs3NzTLISamlvrim2K6LiHH1d/5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T11:44:24Z"
    mac: ENC[AES256_GCM,data:/bZLsi8sbI4Oek6rh56ZOqCLfwgZNacMMSM/ffIy8o3Mq0mR9ZSHcydKYAOCEpHv+d2K3Oj7HCJQYlXWAZQZUqoJsnd+Hb2uYG/a8dNfGnOiqB4hCBnU7sNm4lY7sqVF2qhDX2pcWRzOSn7wZw1/g96HNSPlJkMPbxkrXjNY8ow=,iv:nfPRzvMVLj9Ebs9oEO2W6ufln0I3xFeCRAOj5V2dpnA=,tag:Wrsekq4hWkICxjSisNidAw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: loki-basic-auth-middleware
    namespace: loki
spec:
    basicAuth:
        secret: ENC[AES256_GCM,data:DPMezsDe//qnur/QMjdLX3qn3TSDTg==,iv:aIpmV5nSn1/gmJOOdcD7IOLWnVs0+4QtW0LyWgDbJ0M=,tag:6PbHYV//lTz3mnBxmn7DkA==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMjM1aXBuSXFYS0tGWGFy
            V1cxUjNPMHQrNWxLZk1HQlZLMkFjVE5QbnlnCkJVbmN1dXFsWWVmMjdodVpTYWdF
            MHRkaHJCWktycTZYQTVOM05PcGlhWUEKLS0tIC8vaDUzMFFicDUxOEw0Ukx6NXll
            TDNIZy9vWnQ0c1FwZ1l6bHYvRkgyYkUKiRPTn+IerthQdsD99qC0x0wvtIqDeP7r
            fvS1KKEn4HXo/nK3MUXhogqoWINs3NzTLISamlvrim2K6LiHH1d/5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T11:44:24Z"
    mac: ENC[AES256_GCM,data:/bZLsi8sbI4Oek6rh56ZOqCLfwgZNacMMSM/ffIy8o3Mq0mR9ZSHcydKYAOCEpHv+d2K3Oj7HCJQYlXWAZQZUqoJsnd+Hb2uYG/a8dNfGnOiqB4hCBnU7sNm4lY7sqVF2qhDX2pcWRzOSn7wZw1/g96HNSPlJkMPbxkrXjNY8ow=,iv:nfPRzvMVLj9Ebs9oEO2W6ufln0I3xFeCRAOj5V2dpnA=,tag:Wrsekq4hWkICxjSisNidAw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: loki
    namespace: loki
    annotations:
        traefik.ingress.kubernetes.io/router.middlewares: loki-loki-basic-auth-middleware@kubernetescrd
        cert-manager.io/cluster-issuer: local-issuer
        cert-manager.io/common-name: loki.frontplane.phorge
spec:
    ingressClassName: traefik-local
    tls:
        - hosts:
            - loki.frontplane.phorge
          secretName: loki-tls
    rules:
        - host: loki.frontplane.phorge
          http:
            paths:
                - path: /loki/api/v1/push
                  pathType: Exact
                  backend:
                    service:
                        name: loki
                        port:
                            number: 3100
                - path: /ready
                  pathType: Exact
                  backend:
                    service:
                        name: loki
                        port:
                            number: 3100
                - path: /healthy
                  pathType: Exact
                  backend:
                    service:
                        name: loki
                        port:
                            number: 3100
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMjM1aXBuSXFYS0tGWGFy
            V1cxUjNPMHQrNWxLZk1HQlZLMkFjVE5QbnlnCkJVbmN1dXFsWWVmMjdodVpTYWdF
            MHRkaHJCWktycTZYQTVOM05PcGlhWUEKLS0tIC8vaDUzMFFicDUxOEw0Ukx6NXll
            TDNIZy9vWnQ0c1FwZ1l6bHYvRkgyYkUKiRPTn+IerthQdsD99qC0x0wvtIqDeP7r
            fvS1KKEn4HXo/nK3MUXhogqoWINs3NzTLISamlvrim2K6LiHH1d/5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T11:44:24Z"
    mac: ENC[AES256_GCM,data:/bZLsi8sbI4Oek6rh56ZOqCLfwgZNacMMSM/ffIy8o3Mq0mR9ZSHcydKYAOCEpHv+d2K3Oj7HCJQYlXWAZQZUqoJsnd+Hb2uYG/a8dNfGnOiqB4hCBnU7sNm4lY7sqVF2qhDX2pcWRzOSn7wZw1/g96HNSPlJkMPbxkrXjNY8ow=,iv:nfPRzvMVLj9Ebs9oEO2W6ufln0I3xFeCRAOj5V2dpnA=,tag:Wrsekq4hWkICxjSisNidAw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
