apiVersion: v1
kind: Namespace
metadata:
    name: loki
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: grafana
    namespace: loki
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: loki
    namespace: loki
spec:
    chart:
        spec:
            chart: loki
            sourceRef:
                kind: HelmRepository
                name: grafana
            version: '*'
    interval: 1m0s
    values:
      loki:
        auth_enabled: false
        commonConfig:
          replication_factor: 1
          ring:
            kvstore:
              store: inmemory
        
        # Setting up schemaConfig for better performance
        schemaConfig:
          configs:
            - from: "2023-01-01"
              store: tsdb
              object_store: filesystem
              schema: v13
              index:
                prefix: loki_index_
                period: 24h
        
        # Storage configuration
        storage:
          type: filesystem
        
        # Enable resources limits and requests
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        
        # Pattern ingester for better performance
        pattern_ingester:
          enabled: true
        
        # Configure limits for stability
        limits_config:
          ingestion_rate_mb: 8
          ingestion_burst_size_mb: 16
          max_global_streams_per_user: 5000
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          retention_period: 168h # 7 days retention
          allow_structured_metadata: true
          volume_enabled: true
        
        # Persistence configuration
        persistence:
          enabled: true
          size: 10Gi