apiVersion: v1
kind: Namespace
metadata:
    name: loki
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: loki-config
    namespace: loki
data:
    loki-config.yaml: |
      auth_enabled: false

      server:
        http_listen_port: 3100

      ingester:
        lifecycler:
          address: 127.0.0.1
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
        chunk_idle_period: 5m
        chunk_retain_period: 30s
        max_transfer_retries: 0

      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h

      storage_config:
        boltdb_shipper:
          active_index_directory: /loki/index
          cache_location: /loki/cache
          shared_store: filesystem
        filesystem:
          directory: /loki/chunks

      limits_config:
        ingestion_rate_mb: 10
        ingestion_burst_size_mb: 20
        max_concurrent_tail_requests: 20

      compactor:
        working_directory: /loki/compactor
        shared_store: filesystem

      table_manager:
        retention_deletes_enabled: true
        retention_period: 24h
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: loki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: loki
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.1
          args:
            - -config.file=/etc/loki/local-config.yaml
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-data
              mountPath: /loki
            - name: loki-config
              mountPath: /etc/loki/local-config.yaml
              subPath: loki-config.yaml
          securityContext:
            runAsUser: 0
      volumes:
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-pvc
        - name: loki-config
          configMap:
            name: loki-config
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: loki
  labels:
    app: loki
spec:
  type: LoadBalancer
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
      name: loki
  selector:
    app: loki