apiVersion: v1
kind: Namespace
metadata:
    name: openfga
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbFNsc09UYit4TWlGRWVH
            STJGZmJpR3I5QVBvOWxWeG95b2tQaGRlQWpNClNHVXNGNlhONWpZQzBEWmVnbTQ2
            YnJJRHhLQlpMWGJnSWV5WGlwTmdEU28KLS0tIEVrMkVZL3NTN3JLSzFYRVFYQ3gv
            cyt5cVVxREtjalRZay9zMTJZRVpDTkUKRn5974wvFusDlXcb/fLDYe+tbERKNyZ8
            qiO6Jq3tQhfdQWlUa22obrbT3Dh236Sj4j7CgrmeBkKr/jkDZmZdxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T00:27:13Z"
    mac: ENC[AES256_GCM,data:BOMVJB6junclTdYJeGcp6bAetl2m3yZ5JAUUnv29BcpZ0OsT1xGiuV5AcaBziLFBvr9y0Us8XM76SIVv2N7OWblhP2Q4RfQfHA6EkOTT7kwd5/r+LSE1HuM4TlTruhrSoSrm2uE0IndVdO7HfJ5VYp5ETd+GZlxmN+bGTmQ3uAQ=,iv:WmrpozJJk0XyzGlRbftBOof9MdTZI6l5htV7TEW/buY=,tag:/ah1I8m0lLVVjKQYIkWj6Q==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: openfga
    namespace: openfga
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://openfga.github.io/helm-charts
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbFNsc09UYit4TWlGRWVH
            STJGZmJpR3I5QVBvOWxWeG95b2tQaGRlQWpNClNHVXNGNlhONWpZQzBEWmVnbTQ2
            YnJJRHhLQlpMWGJnSWV5WGlwTmdEU28KLS0tIEVrMkVZL3NTN3JLSzFYRVFYQ3gv
            cyt5cVVxREtjalRZay9zMTJZRVpDTkUKRn5974wvFusDlXcb/fLDYe+tbERKNyZ8
            qiO6Jq3tQhfdQWlUa22obrbT3Dh236Sj4j7CgrmeBkKr/jkDZmZdxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T00:27:13Z"
    mac: ENC[AES256_GCM,data:BOMVJB6junclTdYJeGcp6bAetl2m3yZ5JAUUnv29BcpZ0OsT1xGiuV5AcaBziLFBvr9y0Us8XM76SIVv2N7OWblhP2Q4RfQfHA6EkOTT7kwd5/r+LSE1HuM4TlTruhrSoSrm2uE0IndVdO7HfJ5VYp5ETd+GZlxmN+bGTmQ3uAQ=,iv:WmrpozJJk0XyzGlRbftBOof9MdTZI6l5htV7TEW/buY=,tag:/ah1I8m0lLVVjKQYIkWj6Q==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: openfga
    namespace: openfga
spec:
    chart:
        spec:
            chart: openfga
            sourceRef:
                kind: HelmRepository
                name: openfga
            version: '*'
    interval: 1m0s
    values:
        nodeSelector:
            node-role.kubernetes.io/worker: "true"
        replicaCount: 1
        datastore:
            migrationType: initContainer
            engine: postgres
            uri: ENC[AES256_GCM,data:JnrpOrDRup13bHIhD9Mf4lRGMieXi3HKcwVFUNwobGezITl1ywtMnG7ez4xa+oLx0zyOyD2OBT6qrDtTZIRscUZfoZZDVSs0/SdE04AXalY6AyyVe3mvGF7QEK5DgOaDKK37MAnw7mBJvo5BLdeaWYpf,iv:QHTb7Ma8AYB1bB5byuNnFUsIJuLAn0sVe4htCQrAbdQ=,tag:DR7a8KPHSX2gj/eL3p+TQg==,type:str]
        postgresql:
            image:
                tag: latest
            enabled: true
            auth:
                postgresPassword: ENC[AES256_GCM,data:67F+/8hOiBtTuRlj6khGOTn2RQ==,iv:vTMwyemwWNvCErSdYi7bwBzEzg17+MFSCBNc+8VYsrg=,tag:osfx4aoEClxKhlLBRdU3Hw==,type:str]
                database: postgres
            primary:
                persistence:
                    enabled: true
                    size: 10Gi
        service:
            type: LoadBalancer
        authn:
            method: preshared
            preshared:
                keys:
                    - ENC[AES256_GCM,data:1oMQ1bHUlLIgHRtlfbjgdQ==,iv:+hHTAj7o2JYeGR+L31Msre4QYyfZslDH1NuDe2CPtjI=,tag:EPbrA/64u0Nu6fmSEC627g==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbFNsc09UYit4TWlGRWVH
            STJGZmJpR3I5QVBvOWxWeG95b2tQaGRlQWpNClNHVXNGNlhONWpZQzBEWmVnbTQ2
            YnJJRHhLQlpMWGJnSWV5WGlwTmdEU28KLS0tIEVrMkVZL3NTN3JLSzFYRVFYQ3gv
            cyt5cVVxREtjalRZay9zMTJZRVpDTkUKRn5974wvFusDlXcb/fLDYe+tbERKNyZ8
            qiO6Jq3tQhfdQWlUa22obrbT3Dh236Sj4j7CgrmeBkKr/jkDZmZdxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T00:27:13Z"
    mac: ENC[AES256_GCM,data:BOMVJB6junclTdYJeGcp6bAetl2m3yZ5JAUUnv29BcpZ0OsT1xGiuV5AcaBziLFBvr9y0Us8XM76SIVv2N7OWblhP2Q4RfQfHA6EkOTT7kwd5/r+LSE1HuM4TlTruhrSoSrm2uE0IndVdO7HfJ5VYp5ETd+GZlxmN+bGTmQ3uAQ=,iv:WmrpozJJk0XyzGlRbftBOof9MdTZI6l5htV7TEW/buY=,tag:/ah1I8m0lLVVjKQYIkWj6Q==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
