apiVersion: v1
kind: Namespace
metadata:
    name: openfga
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYzJQK0pWRXovNDNiYUJ1
            b2JOaUs1ZXltelowcEgyS2M0SDRRdDRZcUNJCm5WRUF4TGZ3Z2NUZFpub0JBNU1S
            T1hCQk9qU1pMeEMvT2lxbmFWbUo2OW8KLS0tIGRUQzlDR3g3ck92SmVKZjVCNy9w
            SW03Z3ZFY24yTXhBWmFtMXMyallTVncKuU8zRByxZBldzxbUVdq5s2GdCvpm0S2o
            I6t1DnsIOLKck4/f49I+LZIwSxbrm7vaR9MshQ0y53eICtUeLOQNYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T21:28:07Z"
    mac: ENC[AES256_GCM,data:8AdRiQ8ZwsDd6h3MSbapD5bBPyYFUqoKQkL5iUNsW00gk/cLa2iDYeXSwamGs92SVA4Mr1EZaz66lj48+GzshRrnXK1AehR0uNcGO3jZ/dKHkz+aNjOkfQ9zxeW91cSq3gkBODx/4aC0efcsAfrZBYR9CanTmRMWpK4vm6Ok6kA=,iv:LuSxXZ2tzlHGcxzT2k63w2awKtCyV/WrRsLUaWEvCm8=,tag:1R+QAEC9aon1y0/76W8kmQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: openfga
    namespace: openfga
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://openfga.github.io/helm-charts
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYzJQK0pWRXovNDNiYUJ1
            b2JOaUs1ZXltelowcEgyS2M0SDRRdDRZcUNJCm5WRUF4TGZ3Z2NUZFpub0JBNU1S
            T1hCQk9qU1pMeEMvT2lxbmFWbUo2OW8KLS0tIGRUQzlDR3g3ck92SmVKZjVCNy9w
            SW03Z3ZFY24yTXhBWmFtMXMyallTVncKuU8zRByxZBldzxbUVdq5s2GdCvpm0S2o
            I6t1DnsIOLKck4/f49I+LZIwSxbrm7vaR9MshQ0y53eICtUeLOQNYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T21:28:07Z"
    mac: ENC[AES256_GCM,data:8AdRiQ8ZwsDd6h3MSbapD5bBPyYFUqoKQkL5iUNsW00gk/cLa2iDYeXSwamGs92SVA4Mr1EZaz66lj48+GzshRrnXK1AehR0uNcGO3jZ/dKHkz+aNjOkfQ9zxeW91cSq3gkBODx/4aC0efcsAfrZBYR9CanTmRMWpK4vm6Ok6kA=,iv:LuSxXZ2tzlHGcxzT2k63w2awKtCyV/WrRsLUaWEvCm8=,tag:1R+QAEC9aon1y0/76W8kmQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: openfga
    namespace: openfga
spec:
    chart:
        spec:
            chart: openfga
            sourceRef:
                kind: HelmRepository
                name: openfga
            version: '*'
    interval: 1m0s
    values:
        image:
            tag: latest
        replicaCount: 1
        datastore:
            applyMigrations: false
            waitForMigrations: false
            engine: postgres
            uri: ENC[AES256_GCM,data:KmoF5Gpr71LxCPsQDCCjZ2JUHQRg7F4TwLA8+7cvw731Dgh69OomqGxIcnWXrKlGO1zV7GMY4esYNL13yf3F9CHbkaI5vUhW9EJIAsy3An8JrGNaweUslHFra7vg9ZQMZRiLpVi2uEGuQftGa8lHuhIA,iv:05m208ouLUhErxLbGAkfzKnydVbMTF68vbOw40DCC4o=,tag:O8o+5IQ0tZaL8sJR44thUQ==,type:str]
        postgresql:
            enabled: true
            auth:
                postgresPassword: ENC[AES256_GCM,data:piSToPI4xlZzOwEUmjvfMrJyTA==,iv:iC22/60Ghfn3Co19fE6bjY8c04v8k06/Q1c1+0wrteM=,tag:ClmVgvtabGV0XK8+7r4quQ==,type:str]
                database: postgres
            primary:
                persistence:
                    enabled: true
                    size: 10Gi
        ingress:
            enabled: true
            className: nginx
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
            hosts:
                - host: openfga.phorge.fr
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
            tls:
                - hosts:
                    - openfga.phorge.fr
                  secretName: openfga-tls
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYzJQK0pWRXovNDNiYUJ1
            b2JOaUs1ZXltelowcEgyS2M0SDRRdDRZcUNJCm5WRUF4TGZ3Z2NUZFpub0JBNU1S
            T1hCQk9qU1pMeEMvT2lxbmFWbUo2OW8KLS0tIGRUQzlDR3g3ck92SmVKZjVCNy9w
            SW03Z3ZFY24yTXhBWmFtMXMyallTVncKuU8zRByxZBldzxbUVdq5s2GdCvpm0S2o
            I6t1DnsIOLKck4/f49I+LZIwSxbrm7vaR9MshQ0y53eICtUeLOQNYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T21:28:07Z"
    mac: ENC[AES256_GCM,data:8AdRiQ8ZwsDd6h3MSbapD5bBPyYFUqoKQkL5iUNsW00gk/cLa2iDYeXSwamGs92SVA4Mr1EZaz66lj48+GzshRrnXK1AehR0uNcGO3jZ/dKHkz+aNjOkfQ9zxeW91cSq3gkBODx/4aC0efcsAfrZBYR9CanTmRMWpK4vm6Ok6kA=,iv:LuSxXZ2tzlHGcxzT2k63w2awKtCyV/WrRsLUaWEvCm8=,tag:1R+QAEC9aon1y0/76W8kmQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword)$
    version: 3.11.0
