apiVersion: v1
kind: Namespace
metadata:
    name: retake-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        run: website
    name: website
    namespace: retake-web
spec:
    replicas: 1
    selector:
        matchLabels:
            run: website
    template:
        metadata:
            labels:
                run: website
        spec:
            containers:
                - name: website
                  image: git.phorge.fr/retake/retake.fr:latest
                  ports:
                    - containerPort: 3000
                  resources:
                    requests:
                        memory: 64Mi
                        cpu: 100m
                    limits:
                        memory: 256Mi
                        cpu: 1000m
---
apiVersion: v1
kind: Service
metadata:
    name: website-svc
    namespace: retake-web
spec:
    selector:
        run: website
    ports:
        - name: http
          port: 3000
          targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: website-ing
    namespace: retake-web
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-retake
        nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
    ingressClassName: nginx
    tls:
        - hosts:
            - retake.fr
            - www.retake.fr
          secretName: retake.fr
    rules:
        - host: retake.fr
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: website-svc
                        port:
                            number: 3000
        - host: www.retake.fr
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: website-svc
                        port:
                            number: 3000
