apiVersion: v1
kind: Namespace
metadata:
    name: semaphoreui
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyanVpSk42Y3FCa1dBWnpq
            STlGTW5UWWJ6Y3M1bjhPL1Rwb1p6dFhneFVFCmFzMGRlYUdmNmxZb2NhSkhtbHJi
            cTdNL0NydkM0TGRkUWlIcC80ZUhoanMKLS0tIHhRSm1KOUZsMXFWUk9mdXdKdGM2
            TC9SWkJYdThCNktvSlFJS2ZERjVvRFUKs+4oanKGlohTNVsInEHwLc4zpXSGFe0S
            KEfRbySMJv260jKv7OhGLMhRWHLSxnPBKP8+/wULywxRiKJmGrZ7qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T00:35:53Z"
    mac: ENC[AES256_GCM,data:9//ypG/NOSUm3E5fJCJ1ksBDc3ccN2GYv/8XRlGKAaK31RgwDvQvYaXqmIVj653onj1tkfyIMhOyn6c8ed4BxfYvnjAMrb4fNPt/mOJ13WtBHavuginuBqBPxhHXrF0N+cWZciMgO5NdUqtVTd7G3d1diyvCOElusX7WjqUiRgs=,iv:xdddpZfST/pzM7fQrEx6/r9PqlJI+PvGz4qW1cxkNZ0=,tag:YbiU2BY6scD8xjp/IiS/bA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: semaphoreui
    namespace: semaphoreui
spec:
    interval: 1m0s
    timeout: 1m0s
    url: https://semaphoreui.github.io/charts
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyanVpSk42Y3FCa1dBWnpq
            STlGTW5UWWJ6Y3M1bjhPL1Rwb1p6dFhneFVFCmFzMGRlYUdmNmxZb2NhSkhtbHJi
            cTdNL0NydkM0TGRkUWlIcC80ZUhoanMKLS0tIHhRSm1KOUZsMXFWUk9mdXdKdGM2
            TC9SWkJYdThCNktvSlFJS2ZERjVvRFUKs+4oanKGlohTNVsInEHwLc4zpXSGFe0S
            KEfRbySMJv260jKv7OhGLMhRWHLSxnPBKP8+/wULywxRiKJmGrZ7qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T00:35:53Z"
    mac: ENC[AES256_GCM,data:9//ypG/NOSUm3E5fJCJ1ksBDc3ccN2GYv/8XRlGKAaK31RgwDvQvYaXqmIVj653onj1tkfyIMhOyn6c8ed4BxfYvnjAMrb4fNPt/mOJ13WtBHavuginuBqBPxhHXrF0N+cWZciMgO5NdUqtVTd7G3d1diyvCOElusX7WjqUiRgs=,iv:xdddpZfST/pzM7fQrEx6/r9PqlJI+PvGz4qW1cxkNZ0=,tag:YbiU2BY6scD8xjp/IiS/bA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: semaphoreui
    namespace: semaphoreui
spec:
    chart:
        spec:
            chart: semaphoreui
            sourceRef:
                kind: HelmRepository
                name: semaphoreui
            version: '*'
    interval: 1m0s
    values:
        ingress:
            enabled: true
            className: nginx
            hosts:
                - host: semaphore.frontplane.phorge.fr
                  paths:
                    - path: /
                      pathType: Prefix
            tls:
                - secretName: semaphore-tls
                  hosts:
                    - semaphore.frontplane.phorge.fr
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
        admin:
            create: true
            fullname: QWRtaW5pc3RyYXRvcg==
            username: ENC[AES256_GCM,data:rihY16jdL/eSdqBK,iv:1Pm09oOwByiF0vrCkMNosfxaauGaeY0gy0Nfc5zw9hs=,tag:aQSaerYD8CBcK+aUC4byxw==,type:str]
            password: ENC[AES256_GCM,data:wvh58axC6uWxtl2THb+D1ImAAI48nWfafZ3OO7YOChI=,iv:rOZJgmfRgtcuabL8bNoPLp7zmlnZJrqP3ALdinj0uwQ=,tag:p3bZYygZJu8mP6O5QkvCqw==,type:str]
            email: ENC[AES256_GCM,data:UDlNEkm03E8sOmKSy+VB3vQ44EnVA8rl4xazGi7efSfaGFj3,iv:EFVbu/017U0zDOC4xaLfDFXnGoBcRuBlVkIVEQ+5Tw8=,tag:FFdi/u3pgg0A5E1kJRulyg==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyanVpSk42Y3FCa1dBWnpq
            STlGTW5UWWJ6Y3M1bjhPL1Rwb1p6dFhneFVFCmFzMGRlYUdmNmxZb2NhSkhtbHJi
            cTdNL0NydkM0TGRkUWlIcC80ZUhoanMKLS0tIHhRSm1KOUZsMXFWUk9mdXdKdGM2
            TC9SWkJYdThCNktvSlFJS2ZERjVvRFUKs+4oanKGlohTNVsInEHwLc4zpXSGFe0S
            KEfRbySMJv260jKv7OhGLMhRWHLSxnPBKP8+/wULywxRiKJmGrZ7qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T00:35:53Z"
    mac: ENC[AES256_GCM,data:9//ypG/NOSUm3E5fJCJ1ksBDc3ccN2GYv/8XRlGKAaK31RgwDvQvYaXqmIVj653onj1tkfyIMhOyn6c8ed4BxfYvnjAMrb4fNPt/mOJ13WtBHavuginuBqBPxhHXrF0N+cWZciMgO5NdUqtVTd7G3d1diyvCOElusX7WjqUiRgs=,iv:xdddpZfST/pzM7fQrEx6/r9PqlJI+PvGz4qW1cxkNZ0=,tag:YbiU2BY6scD8xjp/IiS/bA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username)$
    version: 3.11.0
