apiVersion: v1
kind: Namespace
metadata:
    name: loki
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOajJ3bE8yMmhwcytKRG9E
            bkc5NjZuczdjRWU2SzBQTFV6QU1uOEp0U25zCmdYcWxyNDlKUjB6QjV0cXVvaThm
            Szdob2pmOGR4TnBNTDhqelZkWUF5UWsKLS0tIFN6Um1rczVSd0J5bmtrc2tCR01M
            d0dQL3FpM3UxbUNvWW54U1FKK29JYTQKWAW7ANZkqCU1OfBma9PY5k/Wm0u9zA7f
            x7+K0xXc3OtXXi31p+MfzQSUiWANNAAzwR6TVQpFedF23LKGgLUGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T16:38:41Z"
    mac: ENC[AES256_GCM,data:xXthV2ypICAIfLAyZa0MJZ0/f+RInUafdLCptJX0BIp0QIGJ+uZRYj5mtZGPAFxVvVo+4o9JVEOS5yCkTLa5AoW9ckQUO675Uwlayptn1PFiM8zuEj5t46uTgDxSKSZDaPseIE1dS9HBuSzBkcGjEr83605RzdoW2mdxI27WQtY=,iv:2oft7bMjCGk/KAReXRGCIdkpzUlq+DlgE9PHX7fBTnA=,tag:dzqTGQmSRYIlIXZkDeKdmg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: loki-config
    namespace: loki
data:
    loki-config.yaml: ENC[AES256_GCM,data:H6aYzB6aih4V71ASm404McDBTnET8fMRlCdgteLC2DE7ES9Eq1XLcbh5R8Ok1w0f21CLbbz9qdF6pNB6RnHXpvo7VKQsp5m9X3Pk1nGmOXaAVibYO18IWA8DeCMohnlqpyP84+E25SUXs2tpf+kc3HTvFr4AboXu1wApFqxiQY0ddaZ5Bo4BUmxKgXfkE1ZeVZC3oz4+y+PUr5bynSNidoaBsNvbFemepgJqTlMYk8yuOzffJhsVGcH2gybUFOnlOeH7hkQA7psFQQ2+bLqAqvLLrvi0ZdXGxVdPW129RuvZi6NSOz8E4HK1R9Q+iMRb3wXO2XBBvdGmgL6F4TqOlAeMwjxtNaBvCXQCS4tA2+Z0cuf7dCwm1AbqX1IILLCEnRbf1OkVsgGpIVngA17KWq2mHxZlsfAxBJC8/2iBrWOIUNc7FltK69k03JVWc1/AcHe45ALbnVlHOzHkMxqJ11Mk1fAulcWy8hfzaUIO7oNaFhZv1Q3elQNdxO3ESZH5eDmRaeGZjNOA+ddgxa+hPIKqrreK2WMipUNpLW4U9ydzzj6UYHtn7ftdlCoTp8p9pMipGRWzW0No56kaCOu7ofSzaF6HS57JPna5EltlU3o6UYUmVtAVqc2bg/FLzAQH7hB24rNl3U+qvHyvDDedAK3H243tvCGJlQCau33aq40AMI2mxoMsIMpOZHnUmVEFSQHw6d086+dMzKMBKH0fyoBX5w1vTOFE0jLjWV42/qfm/UjRxTAnnjKOP13J7xldKqkzweY17/qYxYfAHbqpej1Z4xSe9TSd3mAObrrewb/dotWW9z02+L3ytjx41MKzPZcRbEykRvIRBHp3IrqwJuv64dLGorh3B8LIPQF/Wd86peQ/KabC5xh3KGyqKuDqsxpRRC8WKovBEltvTUJ6j3Np2BSJ5J/vtd68s/8a1Wy8bL/tjg3U7dl/JqGs2EUKL0tdiv8bLernr6Tvq0bQPRGckpcBgI5sV0haPcVtMr7QFw5d4DXkvSDuLFsJo0mUX6vvtHcP4lrX868mkyg6xzzi34iFqJm49NZ0HSBXssX+hxede56JVcrr3lSS/JFb9IoxpBb2q2rp,iv:FKDe7fkP51bIgwG9v9Vm/dkXjIsQKnsGPwpuGvH6MYA=,tag:YcabQl8qAXTUsWTwVzlKYg==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOajJ3bE8yMmhwcytKRG9E
            bkc5NjZuczdjRWU2SzBQTFV6QU1uOEp0U25zCmdYcWxyNDlKUjB6QjV0cXVvaThm
            Szdob2pmOGR4TnBNTDhqelZkWUF5UWsKLS0tIFN6Um1rczVSd0J5bmtrc2tCR01M
            d0dQL3FpM3UxbUNvWW54U1FKK29JYTQKWAW7ANZkqCU1OfBma9PY5k/Wm0u9zA7f
            x7+K0xXc3OtXXi31p+MfzQSUiWANNAAzwR6TVQpFedF23LKGgLUGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T16:38:41Z"
    mac: ENC[AES256_GCM,data:xXthV2ypICAIfLAyZa0MJZ0/f+RInUafdLCptJX0BIp0QIGJ+uZRYj5mtZGPAFxVvVo+4o9JVEOS5yCkTLa5AoW9ckQUO675Uwlayptn1PFiM8zuEj5t46uTgDxSKSZDaPseIE1dS9HBuSzBkcGjEr83605RzdoW2mdxI27WQtY=,iv:2oft7bMjCGk/KAReXRGCIdkpzUlq+DlgE9PHX7fBTnA=,tag:dzqTGQmSRYIlIXZkDeKdmg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: loki-pvc
    namespace: loki
spec:
    storageClassName: longhorn
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 15Gi
    volumeMode: Filesystem
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOajJ3bE8yMmhwcytKRG9E
            bkc5NjZuczdjRWU2SzBQTFV6QU1uOEp0U25zCmdYcWxyNDlKUjB6QjV0cXVvaThm
            Szdob2pmOGR4TnBNTDhqelZkWUF5UWsKLS0tIFN6Um1rczVSd0J5bmtrc2tCR01M
            d0dQL3FpM3UxbUNvWW54U1FKK29JYTQKWAW7ANZkqCU1OfBma9PY5k/Wm0u9zA7f
            x7+K0xXc3OtXXi31p+MfzQSUiWANNAAzwR6TVQpFedF23LKGgLUGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T16:38:41Z"
    mac: ENC[AES256_GCM,data:xXthV2ypICAIfLAyZa0MJZ0/f+RInUafdLCptJX0BIp0QIGJ+uZRYj5mtZGPAFxVvVo+4o9JVEOS5yCkTLa5AoW9ckQUO675Uwlayptn1PFiM8zuEj5t46uTgDxSKSZDaPseIE1dS9HBuSzBkcGjEr83605RzdoW2mdxI27WQtY=,iv:2oft7bMjCGk/KAReXRGCIdkpzUlq+DlgE9PHX7fBTnA=,tag:dzqTGQmSRYIlIXZkDeKdmg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: loki
    namespace: loki
    labels:
        app: loki
spec:
    replicas: 1
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: loki
    template:
        metadata:
            labels:
                app: loki
        spec:
            containers:
                - name: loki
                  image: grafana/loki:3.7.7
                  args:
                    - -config.file=/etc/loki/local-config.yaml
                  ports:
                    - containerPort: 3100
                  volumeMounts:
                    - name: loki-data
                      mountPath: /loki
                    - name: loki-config
                      mountPath: /etc/loki/local-config.yaml
                      subPath: loki-config.yaml
                  securityContext:
                    runAsUser: 0
            volumes:
                - name: loki-data
                  persistentVolumeClaim:
                    claimName: loki-pvc
                - name: loki-config
                  configMap:
                    name: loki-config
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOajJ3bE8yMmhwcytKRG9E
            bkc5NjZuczdjRWU2SzBQTFV6QU1uOEp0U25zCmdYcWxyNDlKUjB6QjV0cXVvaThm
            Szdob2pmOGR4TnBNTDhqelZkWUF5UWsKLS0tIFN6Um1rczVSd0J5bmtrc2tCR01M
            d0dQL3FpM3UxbUNvWW54U1FKK29JYTQKWAW7ANZkqCU1OfBma9PY5k/Wm0u9zA7f
            x7+K0xXc3OtXXi31p+MfzQSUiWANNAAzwR6TVQpFedF23LKGgLUGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T16:38:41Z"
    mac: ENC[AES256_GCM,data:xXthV2ypICAIfLAyZa0MJZ0/f+RInUafdLCptJX0BIp0QIGJ+uZRYj5mtZGPAFxVvVo+4o9JVEOS5yCkTLa5AoW9ckQUO675Uwlayptn1PFiM8zuEj5t46uTgDxSKSZDaPseIE1dS9HBuSzBkcGjEr83605RzdoW2mdxI27WQtY=,iv:2oft7bMjCGk/KAReXRGCIdkpzUlq+DlgE9PHX7fBTnA=,tag:dzqTGQmSRYIlIXZkDeKdmg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
kind: Service
metadata:
    name: loki
    namespace: loki
    labels:
        app: loki
spec:
    type: ClusterIP
    ports:
        - port: 3100
          targetPort: 3100
          protocol: TCP
          name: loki
    selector:
        app: loki
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOajJ3bE8yMmhwcytKRG9E
            bkc5NjZuczdjRWU2SzBQTFV6QU1uOEp0U25zCmdYcWxyNDlKUjB6QjV0cXVvaThm
            Szdob2pmOGR4TnBNTDhqelZkWUF5UWsKLS0tIFN6Um1rczVSd0J5bmtrc2tCR01M
            d0dQL3FpM3UxbUNvWW54U1FKK29JYTQKWAW7ANZkqCU1OfBma9PY5k/Wm0u9zA7f
            x7+K0xXc3OtXXi31p+MfzQSUiWANNAAzwR6TVQpFedF23LKGgLUGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T16:38:41Z"
    mac: ENC[AES256_GCM,data:xXthV2ypICAIfLAyZa0MJZ0/f+RInUafdLCptJX0BIp0QIGJ+uZRYj5mtZGPAFxVvVo+4o9JVEOS5yCkTLa5AoW9ckQUO675Uwlayptn1PFiM8zuEj5t46uTgDxSKSZDaPseIE1dS9HBuSzBkcGjEr83605RzdoW2mdxI27WQtY=,iv:2oft7bMjCGk/KAReXRGCIdkpzUlq+DlgE9PHX7fBTnA=,tag:dzqTGQmSRYIlIXZkDeKdmg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
data:
    users: ENC[AES256_GCM,data:O4VpKd/AZenEPFdGxLbfsJ/3c0wJSiK+ocdXya8Q9K38mEcnm283d7tpeWMlkUHjiJun7VpHakzzCssbKiWvmpZsFC9aw1tMPYmEy0AV3x2EfYNc1QSOIg1cck1WZpgS+oqs9IlkuzQJCZG9q5gg1vhHbbita48Ws3l8nCStU5OY4aGLttK0wq0awQlcE3AK/EShqv1buxfSdrd5lk56w+UU9DfsfAmRucvuCyH1dJbfmwwfkqCxSjF2Sd2ap2Kw5R0MNNqrA0BwFJQVJETq60d+Vmu9QTx1lRxkz4LXbjFSpNzs8qh0Nh9xtpzLyNGWAaiXBWSHmNt2OSJzCsyMHAabGUZ8zNsB8xwqnklePMyzetCYdeYDiwa7NFCBFsaac7LU5xmSjtt3L6a5jH6zvRCoudeuXWfbWu2yUTCUuNO2medLnmD2/FyJ/DBG6BiDdipTKV1aUebXECpo5jBCeB5lKlXABvT+Z7iPEPCwdbK0fs5hlnggC0R9IC5CK2GT1x2YAqCCfmrcyLHD9a+0Sb6UgyhqlqqtyF6w1SxV/eZK+tL8YTwEgczcPkNK9lvx/VU94xkssB4ggRDHq/ArIlQRee0wB4RynEbAtQ==,iv:KqKYCM8iA01VCoZlYX34xvLUl/XkfwE5lyQUVksWFUw=,tag:A1CzBWu2f6+wT9WEOQlMlQ==,type:str]
kind: Secret
metadata:
    name: loki-basic-auth-secret
    namespace: loki
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOajJ3bE8yMmhwcytKRG9E
            bkc5NjZuczdjRWU2SzBQTFV6QU1uOEp0U25zCmdYcWxyNDlKUjB6QjV0cXVvaThm
            Szdob2pmOGR4TnBNTDhqelZkWUF5UWsKLS0tIFN6Um1rczVSd0J5bmtrc2tCR01M
            d0dQL3FpM3UxbUNvWW54U1FKK29JYTQKWAW7ANZkqCU1OfBma9PY5k/Wm0u9zA7f
            x7+K0xXc3OtXXi31p+MfzQSUiWANNAAzwR6TVQpFedF23LKGgLUGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T16:38:41Z"
    mac: ENC[AES256_GCM,data:xXthV2ypICAIfLAyZa0MJZ0/f+RInUafdLCptJX0BIp0QIGJ+uZRYj5mtZGPAFxVvVo+4o9JVEOS5yCkTLa5AoW9ckQUO675Uwlayptn1PFiM8zuEj5t46uTgDxSKSZDaPseIE1dS9HBuSzBkcGjEr83605RzdoW2mdxI27WQtY=,iv:2oft7bMjCGk/KAReXRGCIdkpzUlq+DlgE9PHX7fBTnA=,tag:dzqTGQmSRYIlIXZkDeKdmg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: loki-basic-auth-middleware
    namespace: loki
spec:
    basicAuth:
        secret: ENC[AES256_GCM,data:vwjhrLtkVQznm9Yinyw6MH8IOzO7Jw==,iv:eu2yJeHKFDEkR8uuGWk2rm0ROGJiX+xsXiAs9UizIFc=,tag:gP7M6TPLmMRSkKjd9ZeWVw==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOajJ3bE8yMmhwcytKRG9E
            bkc5NjZuczdjRWU2SzBQTFV6QU1uOEp0U25zCmdYcWxyNDlKUjB6QjV0cXVvaThm
            Szdob2pmOGR4TnBNTDhqelZkWUF5UWsKLS0tIFN6Um1rczVSd0J5bmtrc2tCR01M
            d0dQL3FpM3UxbUNvWW54U1FKK29JYTQKWAW7ANZkqCU1OfBma9PY5k/Wm0u9zA7f
            x7+K0xXc3OtXXi31p+MfzQSUiWANNAAzwR6TVQpFedF23LKGgLUGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T16:38:41Z"
    mac: ENC[AES256_GCM,data:xXthV2ypICAIfLAyZa0MJZ0/f+RInUafdLCptJX0BIp0QIGJ+uZRYj5mtZGPAFxVvVo+4o9JVEOS5yCkTLa5AoW9ckQUO675Uwlayptn1PFiM8zuEj5t46uTgDxSKSZDaPseIE1dS9HBuSzBkcGjEr83605RzdoW2mdxI27WQtY=,iv:2oft7bMjCGk/KAReXRGCIdkpzUlq+DlgE9PHX7fBTnA=,tag:dzqTGQmSRYIlIXZkDeKdmg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: loki
    namespace: loki
    annotations:
        traefik.ingress.kubernetes.io/router.middlewares: loki-loki-basic-auth-middleware@kubernetescrd
        cert-manager.io/cluster-issuer: local-issuer
        cert-manager.io/common-name: loki.core.phorge
spec:
    ingressClassName: traefik-local
    tls:
        - hosts:
            - loki.core.phorge
          secretName: loki-tls
    rules:
        - host: loki.core.phorge
          http:
            paths:
                - path: /loki/api/v1/push
                  pathType: Exact
                  backend:
                    service:
                        name: loki
                        port:
                            number: 3100
                - path: /ready
                  pathType: Exact
                  backend:
                    service:
                        name: loki
                        port:
                            number: 3100
                - path: /healthy
                  pathType: Exact
                  backend:
                    service:
                        name: loki
                        port:
                            number: 3100
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOajJ3bE8yMmhwcytKRG9E
            bkc5NjZuczdjRWU2SzBQTFV6QU1uOEp0U25zCmdYcWxyNDlKUjB6QjV0cXVvaThm
            Szdob2pmOGR4TnBNTDhqelZkWUF5UWsKLS0tIFN6Um1rczVSd0J5bmtrc2tCR01M
            d0dQL3FpM3UxbUNvWW54U1FKK29JYTQKWAW7ANZkqCU1OfBma9PY5k/Wm0u9zA7f
            x7+K0xXc3OtXXi31p+MfzQSUiWANNAAzwR6TVQpFedF23LKGgLUGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T16:38:41Z"
    mac: ENC[AES256_GCM,data:xXthV2ypICAIfLAyZa0MJZ0/f+RInUafdLCptJX0BIp0QIGJ+uZRYj5mtZGPAFxVvVo+4o9JVEOS5yCkTLa5AoW9ckQUO675Uwlayptn1PFiM8zuEj5t46uTgDxSKSZDaPseIE1dS9HBuSzBkcGjEr83605RzdoW2mdxI27WQtY=,iv:2oft7bMjCGk/KAReXRGCIdkpzUlq+DlgE9PHX7fBTnA=,tag:dzqTGQmSRYIlIXZkDeKdmg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
