apiVersion: v1
kind: Namespace
metadata:
    name: loki
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bnFpTnZhVEpHQVpuaDRj
            WmJZK1VFbzJ0WXQ0amVmSGNGREM3TUJ0MFRJCllTeGlvY1Y0REhZL0tDQmlRakQ5
            ZjJweE9MVjREQitoUWxMTEUvUldnbUkKLS0tIGFsblZVVnhGQXV0cUt0aGRVckp3
            SW9JeVFCQU1nUW9IdTBNOXcxU0hHeHMKMMZyUGfw0wjTk+gSPR+b50VTEnN7TYdm
            0WBjXpyZDCm1H9dNCGfJn6aiqCk1jukYvkxZMvZhv6qDqB7LiwoFqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T12:06:48Z"
    mac: ENC[AES256_GCM,data:Jf41wtKANLekqDb36nfC3uIHeElIdBZbiNJOJWHNX3ufLr6nIe/Dq9pCl3KlzKewDyIvzOH0WU8/FlL4VEQQjhA58CWnj3oRidC3dIsswGLz1ChpCWxKrC4sNtuma/VFYp3K44GvS5doQX4efJI/F1iL4qVjMdu8Je89PnZUlDo=,iv:8Zp7h+iXLMXM+9320FZ/l0Lp31tqWTxXtUyz7iNFztQ=,tag:ZlK4yN7hGzNAHG45jL4Orw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: loki-config
    namespace: loki
data:
    loki-config.yaml: ENC[AES256_GCM,data:rnhojf5hwbQ/8QJxzqQjuIsCT05g/HAAuXiTfEC5VkW2KTfMEFXh7kwgWkc2PVDHdyqvhdWtmrr+rb45sJdAhC7aG4BLkWaVEt8sg+/gpxfeZpvm4DUvACHHQA/Wih404snrH9RpoWqCUrZ6cabg1TIVGBo0pWJYgGDgF+6MxSPq/sdCDNvfFGOOXsrwjsolGJs/MjV5HGyvP0+3eGoyX5qVR54xP3lack9W1Pkg9DgkiqqelCfAbM9wnONSVM34ryhUFtifBE535+oP0+VQ98Hw1RR7/eqi6Phja4dtD0TmhTZsWnBenvTNtGcZ4+s3NBCIVeFKU4/BDxUz5Hou6KzolKSE3OKXA3SYzPSdOuXsOxqEsWSE09ijaGvRP2n+WQidU0MdzAiG+WFUb6ryuCqLhjOch3jjK2N48LKLU6BlCRYWR/JgwupUJQHZpm2ubX1Y2ItPgsd3odpK+4zE8OwcYpuq67wCGmwOrdl0lOkjOveYEixZ+HJvjZ6IlKx039obkJ12q1z1YQwKXxGBnwhHp+4e6gewjGmJq7CT9leGa33Aiv7gWa+Erunt9HDF/rgcTExvyMw/fualGcrGVMuShmt4plRBW8XpInaC2ycueuwPm9SwP4vGBXhX71l9eBpkstoIKZZQU2nYLKWiA65Yh29+pcW6m0c/LNUGAZJcEVp7tHF+0shihfrtj65zmstKg630x8vFI3tpWIjEORq5EcTNIUlgxht8E3VNmUgvzaBPUk/fl3q8cDitwIRHLi/uN/p52B2BXeMs3uqCQ6rTtcRzbP8GPNeqLRNE5gbdw2wrbtlbviuONcW3Rqx3kk4n/TxOu+NGeHTYPlIMaBChMjdlvaeST4DFMHrJmBWmfxOUGZBEssGyH7bhtMijf+rMwTGfPVYCFCH9egFrn8DMtDQXQpo2BKAvoeaqW8fAvNc3gntVpYp/6ls+7a2ZNRVT6ENmzUkBuSGxEjY8PJpDwwBt80xtC5CsJsivsIavpoP6ffbBGqpfDbfsWML+XEDBNQxVG6fdhXs3GPxZyDJ7B7Xu1l2vdUDmRiOcvaEr9kultK1HBHQWuOZi5QEn44XWux0jH/TE96BeRAe4j3tgWRPlxplaez5+t77gzrC3VRQNB9VYOiCqRcW1ZoheCEtJX22Iy/ZbeK9xBjvS+0tT8hFG36ACQz3iVOO9qBIKhRwe03jLxhJbnYP51SXADfqagRAdbIUAsGv20MKlrca3+Xtggh/Ddgyhb+uc3MAlgcIr1u0VW/iJR/kSf5UvcZR7RaSes0kEeZpS9iKJei3KMcKkYCeoMJ3UkV2TAagrdSVvU15FjrcWJwyn2CNdZUTN130DfQUaljDqE2j/OJlrkZX8cuuAl1ibV8uapPiEA0U8Sqh9pnp0V38zH8GIdKj3s4Tho3qj/P9bX9SIrdkv8+Z4bLDSYQft6pmI8wkmspDjWg==,iv:GGBCqTczwejH8FrddNoU7DyxhOJ4zJ7kq1S2IT9rlOo=,tag:77illsNV6CJsocz6cTtFXw==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bnFpTnZhVEpHQVpuaDRj
            WmJZK1VFbzJ0WXQ0amVmSGNGREM3TUJ0MFRJCllTeGlvY1Y0REhZL0tDQmlRakQ5
            ZjJweE9MVjREQitoUWxMTEUvUldnbUkKLS0tIGFsblZVVnhGQXV0cUt0aGRVckp3
            SW9JeVFCQU1nUW9IdTBNOXcxU0hHeHMKMMZyUGfw0wjTk+gSPR+b50VTEnN7TYdm
            0WBjXpyZDCm1H9dNCGfJn6aiqCk1jukYvkxZMvZhv6qDqB7LiwoFqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T12:06:48Z"
    mac: ENC[AES256_GCM,data:Jf41wtKANLekqDb36nfC3uIHeElIdBZbiNJOJWHNX3ufLr6nIe/Dq9pCl3KlzKewDyIvzOH0WU8/FlL4VEQQjhA58CWnj3oRidC3dIsswGLz1ChpCWxKrC4sNtuma/VFYp3K44GvS5doQX4efJI/F1iL4qVjMdu8Je89PnZUlDo=,iv:8Zp7h+iXLMXM+9320FZ/l0Lp31tqWTxXtUyz7iNFztQ=,tag:ZlK4yN7hGzNAHG45jL4Orw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: loki-pvc
    namespace: loki
spec:
    storageClassName: longhorn
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 15Gi
    volumeMode: Filesystem
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bnFpTnZhVEpHQVpuaDRj
            WmJZK1VFbzJ0WXQ0amVmSGNGREM3TUJ0MFRJCllTeGlvY1Y0REhZL0tDQmlRakQ5
            ZjJweE9MVjREQitoUWxMTEUvUldnbUkKLS0tIGFsblZVVnhGQXV0cUt0aGRVckp3
            SW9JeVFCQU1nUW9IdTBNOXcxU0hHeHMKMMZyUGfw0wjTk+gSPR+b50VTEnN7TYdm
            0WBjXpyZDCm1H9dNCGfJn6aiqCk1jukYvkxZMvZhv6qDqB7LiwoFqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T12:06:48Z"
    mac: ENC[AES256_GCM,data:Jf41wtKANLekqDb36nfC3uIHeElIdBZbiNJOJWHNX3ufLr6nIe/Dq9pCl3KlzKewDyIvzOH0WU8/FlL4VEQQjhA58CWnj3oRidC3dIsswGLz1ChpCWxKrC4sNtuma/VFYp3K44GvS5doQX4efJI/F1iL4qVjMdu8Je89PnZUlDo=,iv:8Zp7h+iXLMXM+9320FZ/l0Lp31tqWTxXtUyz7iNFztQ=,tag:ZlK4yN7hGzNAHG45jL4Orw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: loki
    namespace: loki
    labels:
        app: loki
spec:
    replicas: 1
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: loki
    template:
        metadata:
            labels:
                app: loki
        spec:
            containers:
                - name: loki
                  image: grafana/loki:3.7.7
                  args:
                    - -config.file=/etc/loki/local-config.yaml
                  ports:
                    - containerPort: 3100
                  volumeMounts:
                    - name: loki-data
                      mountPath: /loki
                    - name: loki-config
                      mountPath: /etc/loki/local-config.yaml
                      subPath: loki-config.yaml
                  securityContext:
                    runAsUser: 0
            volumes:
                - name: loki-data
                  persistentVolumeClaim:
                    claimName: loki-pvc
                - name: loki-config
                  configMap:
                    name: loki-config
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bnFpTnZhVEpHQVpuaDRj
            WmJZK1VFbzJ0WXQ0amVmSGNGREM3TUJ0MFRJCllTeGlvY1Y0REhZL0tDQmlRakQ5
            ZjJweE9MVjREQitoUWxMTEUvUldnbUkKLS0tIGFsblZVVnhGQXV0cUt0aGRVckp3
            SW9JeVFCQU1nUW9IdTBNOXcxU0hHeHMKMMZyUGfw0wjTk+gSPR+b50VTEnN7TYdm
            0WBjXpyZDCm1H9dNCGfJn6aiqCk1jukYvkxZMvZhv6qDqB7LiwoFqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T12:06:48Z"
    mac: ENC[AES256_GCM,data:Jf41wtKANLekqDb36nfC3uIHeElIdBZbiNJOJWHNX3ufLr6nIe/Dq9pCl3KlzKewDyIvzOH0WU8/FlL4VEQQjhA58CWnj3oRidC3dIsswGLz1ChpCWxKrC4sNtuma/VFYp3K44GvS5doQX4efJI/F1iL4qVjMdu8Je89PnZUlDo=,iv:8Zp7h+iXLMXM+9320FZ/l0Lp31tqWTxXtUyz7iNFztQ=,tag:ZlK4yN7hGzNAHG45jL4Orw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
kind: Service
metadata:
    name: loki
    namespace: loki
    labels:
        app: loki
spec:
    type: ClusterIP
    ports:
        - port: 3100
          targetPort: 3100
          protocol: TCP
          name: loki
    selector:
        app: loki
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bnFpTnZhVEpHQVpuaDRj
            WmJZK1VFbzJ0WXQ0amVmSGNGREM3TUJ0MFRJCllTeGlvY1Y0REhZL0tDQmlRakQ5
            ZjJweE9MVjREQitoUWxMTEUvUldnbUkKLS0tIGFsblZVVnhGQXV0cUt0aGRVckp3
            SW9JeVFCQU1nUW9IdTBNOXcxU0hHeHMKMMZyUGfw0wjTk+gSPR+b50VTEnN7TYdm
            0WBjXpyZDCm1H9dNCGfJn6aiqCk1jukYvkxZMvZhv6qDqB7LiwoFqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T12:06:48Z"
    mac: ENC[AES256_GCM,data:Jf41wtKANLekqDb36nfC3uIHeElIdBZbiNJOJWHNX3ufLr6nIe/Dq9pCl3KlzKewDyIvzOH0WU8/FlL4VEQQjhA58CWnj3oRidC3dIsswGLz1ChpCWxKrC4sNtuma/VFYp3K44GvS5doQX4efJI/F1iL4qVjMdu8Je89PnZUlDo=,iv:8Zp7h+iXLMXM+9320FZ/l0Lp31tqWTxXtUyz7iNFztQ=,tag:ZlK4yN7hGzNAHG45jL4Orw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
data:
    users: ENC[AES256_GCM,data:GfVFsyameJRf58Hvh2ptR0srfYhKYIXGwO76bDhlVn7Xze3TB7AiW5MzZzDV0VbYUEI8VCXzWAGeqNSC4fQrHaZgr6xGTmuF6nZsLAuwER8JgLh+DLzPxq8nVGCuOss6Jtmmlwy9JexcPdHRWtqPe8s/mus2XnNWd71prnPvjwNpXdgXlcFHEUIJnk6g9GiwjYjyuDROAqlksGWXq4Ys6e0a4jBcUr0hE98Zm8KyCdUF3TPRbiPkCnH+4tKXVfwdpVGhPcXL5GCpGcoZoDAM2RlLQdxaTHwZPB6Lbc5IutyQ18XvHl8OEs96qLYD5ByAqvH9rNVg4Yjv9ZmFw45OhsTD7qiFwRVx/BFqcGlK9l6x6pertYy5KjUuFC6MY2uYn1hognhJdc3yzW3Pt131Y0hRNArB+cYl3SvzmM3iwO/IVBJo2LzEAwX6zkQPmPMC63YP4c/EnrkSbcGg0yi1Imx1sTnIjfknZDemHLKo1tqA17HtlOc2bOKhBqhvcdbBqtR5fNluoSQ+Rb5EcvRrH9RCglGdyxmDJjYBQjbEgc4EN+ciYGasjVYIyX2bhypGi9clCw9x6Cs9PMqt9yFxeXA+VMzsvjAaC2RgOg==,iv:j1HouCs5APPFnhEnBpMKv9cdc9L9KPFaaqcndglSbbc=,tag:kW2C3MvfMkJSkM4mq6tHbw==,type:str]
kind: Secret
metadata:
    name: loki-basic-auth-secret
    namespace: loki
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bnFpTnZhVEpHQVpuaDRj
            WmJZK1VFbzJ0WXQ0amVmSGNGREM3TUJ0MFRJCllTeGlvY1Y0REhZL0tDQmlRakQ5
            ZjJweE9MVjREQitoUWxMTEUvUldnbUkKLS0tIGFsblZVVnhGQXV0cUt0aGRVckp3
            SW9JeVFCQU1nUW9IdTBNOXcxU0hHeHMKMMZyUGfw0wjTk+gSPR+b50VTEnN7TYdm
            0WBjXpyZDCm1H9dNCGfJn6aiqCk1jukYvkxZMvZhv6qDqB7LiwoFqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T12:06:48Z"
    mac: ENC[AES256_GCM,data:Jf41wtKANLekqDb36nfC3uIHeElIdBZbiNJOJWHNX3ufLr6nIe/Dq9pCl3KlzKewDyIvzOH0WU8/FlL4VEQQjhA58CWnj3oRidC3dIsswGLz1ChpCWxKrC4sNtuma/VFYp3K44GvS5doQX4efJI/F1iL4qVjMdu8Je89PnZUlDo=,iv:8Zp7h+iXLMXM+9320FZ/l0Lp31tqWTxXtUyz7iNFztQ=,tag:ZlK4yN7hGzNAHG45jL4Orw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: loki-basic-auth-middleware
    namespace: loki
spec:
    basicAuth:
        secret: ENC[AES256_GCM,data:iPDLpruj6wVAmqJC7GAfPPJSBYuRaA==,iv:y8KjnnU8p4zo/TveH5XWH0BBNtg/d1tyxmm+RMEq1gY=,tag:zm/FUe11e5XNhJycDOcCKA==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bnFpTnZhVEpHQVpuaDRj
            WmJZK1VFbzJ0WXQ0amVmSGNGREM3TUJ0MFRJCllTeGlvY1Y0REhZL0tDQmlRakQ5
            ZjJweE9MVjREQitoUWxMTEUvUldnbUkKLS0tIGFsblZVVnhGQXV0cUt0aGRVckp3
            SW9JeVFCQU1nUW9IdTBNOXcxU0hHeHMKMMZyUGfw0wjTk+gSPR+b50VTEnN7TYdm
            0WBjXpyZDCm1H9dNCGfJn6aiqCk1jukYvkxZMvZhv6qDqB7LiwoFqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T12:06:48Z"
    mac: ENC[AES256_GCM,data:Jf41wtKANLekqDb36nfC3uIHeElIdBZbiNJOJWHNX3ufLr6nIe/Dq9pCl3KlzKewDyIvzOH0WU8/FlL4VEQQjhA58CWnj3oRidC3dIsswGLz1ChpCWxKrC4sNtuma/VFYp3K44GvS5doQX4efJI/F1iL4qVjMdu8Je89PnZUlDo=,iv:8Zp7h+iXLMXM+9320FZ/l0Lp31tqWTxXtUyz7iNFztQ=,tag:ZlK4yN7hGzNAHG45jL4Orw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: loki
    namespace: loki
    annotations:
        traefik.ingress.kubernetes.io/router.middlewares: loki-loki-basic-auth-middleware@kubernetescrd
        cert-manager.io/cluster-issuer: local-issuer
        cert-manager.io/common-name: loki.core.phorge
spec:
    ingressClassName: traefik-local
    tls:
        - hosts:
            - loki.core.phorge
          secretName: loki-tls
    rules:
        - host: loki.core.phorge
          http:
            paths:
                - path: /loki/api/v1/push
                  pathType: Exact
                  backend:
                    service:
                        name: loki
                        port:
                            number: 3100
                - path: /ready
                  pathType: Exact
                  backend:
                    service:
                        name: loki
                        port:
                            number: 3100
                - path: /healthy
                  pathType: Exact
                  backend:
                    service:
                        name: loki
                        port:
                            number: 3100
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bnFpTnZhVEpHQVpuaDRj
            WmJZK1VFbzJ0WXQ0amVmSGNGREM3TUJ0MFRJCllTeGlvY1Y0REhZL0tDQmlRakQ5
            ZjJweE9MVjREQitoUWxMTEUvUldnbUkKLS0tIGFsblZVVnhGQXV0cUt0aGRVckp3
            SW9JeVFCQU1nUW9IdTBNOXcxU0hHeHMKMMZyUGfw0wjTk+gSPR+b50VTEnN7TYdm
            0WBjXpyZDCm1H9dNCGfJn6aiqCk1jukYvkxZMvZhv6qDqB7LiwoFqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T12:06:48Z"
    mac: ENC[AES256_GCM,data:Jf41wtKANLekqDb36nfC3uIHeElIdBZbiNJOJWHNX3ufLr6nIe/Dq9pCl3KlzKewDyIvzOH0WU8/FlL4VEQQjhA58CWnj3oRidC3dIsswGLz1ChpCWxKrC4sNtuma/VFYp3K44GvS5doQX4efJI/F1iL4qVjMdu8Je89PnZUlDo=,iv:8Zp7h+iXLMXM+9320FZ/l0Lp31tqWTxXtUyz7iNFztQ=,tag:ZlK4yN7hGzNAHG45jL4Orw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
