apiVersion: v1
data:
    users: ENC[AES256_GCM,data:X9/0LKfwIkQW9l/ZnJtOUYo5BI5HS5PIJc2IJuCsTwWiuNAvbI6cYLFwYVTl9LOBIMFwQa4XZB8VYvgxOFZR4zAJ2yV2Nt89+4eVGYp6PVYgyojpQm3mj73FxCR7l+Sd7fz3/KilK77Yk44OF/SB0gAcSaiQ8IaNSoVWyAQZIJn03oMyGR/jq9bpdVDVUXDvgDJuV9IaVfrhmFwhpahi9Am7fTYb9w9IfSRbdbZuVxZWrJXWwRtt+v99Mf89i1E78ZIWz6ImSl02mN3mrp3zYVW1C44TAJbI+F2L5kHLwz0CsHyuhJRRujx7ggVEL9tl0D+BpnVefundc6sTrctk0bOPgyhK5rB9yhFrsPyemn4lx/plOqfXfEWvscZ8Cj+SQ0omeGky+pfqY9CD0wlYHXTcJd5PTfwxw0uq4UqFMmP/cqtATmCOQNvY5y2pdgNL35B4k7MXkLJHCmbFMI6/tvMHrOP+jQHVMNuzhkn5ZnLtT3Tev0dbQumaB+K/D5ezwoCsfIbvM/xS4dZ5RMdlv3wpw/4t91/VyVsGxS21Rv4XuBpIuKYknLp8pOc4fPTSAFf3pfRZwQ+MkY9sXO2TpSN9n0Mi94sxnz5w6g==,iv:YVIgHBsHFrdHidYFZzwwsqgM6dIZO7xd5jTDJ7cqEn0=,tag:jRlzwfQ6PeRNOtz8G9vKZg==,type:str]
kind: Secret
metadata:
    name: loki-basic-auth-secret
    namespace: loki
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVE9jWTUrVnVCbG11RUV6
            UllaOWc0cVB5WjR2SkI2M1FOb0RtUVZLbGdnCmRCNURBNUZicVU5c2F3SlVVd0My
            L0t0T1ZYaUhjV28wSGdHWG1tYjllTlUKLS0tIGZxRURwQWdQWnFjY3FJeHZvNm1x
            eVovc0plSHkzVEVDaHo3eVZRMkczdjAKKVpiFGEyBVsLUhU2Npt1OjrtqB0nMOVf
            W3jsn4OwqoE7wcs0VFAsW5VihdEhw4AH58LS0S5daLihXv+lvsD9PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T01:15:52Z"
    mac: ENC[AES256_GCM,data:jDJ6NrL1HbUQYuOURA2d9uR2yMlM98cAI78vCZLFp64gj0mQBX/h9aDdcZ52EFCA9qutlZi+J/Ja8SLGYrwke5+yiNJJCkA/GJiXH58DX3XJP319qFcHKTvrOcxm5r7Nf+q5TmX4/pAi6Vfii4b9clQXe1qkK6SLjIrG5UvcXGI=,iv:tbHwlmnkHxq11P4ZVAme+2Zp858zPSP11ZeEFtyvkSA=,tag:2vxHvIAaYqFayXYMC3DBrA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
