apiVersion: v1
data:
    users: ENC[AES256_GCM,data:PYMbXxweb4yW+yXrNHL3xWXXGy9kBqzK8hM7qJ+1gR/iepEoDtMkWQB0+u/k/sjXnSMmc2fxOuhuXaT/wZYm3Gz0j+wRT6/i5uTCvOQMJT97eoP5gp3LFsJiZAhTRh+0osZhWLn+FM++9FhSNnB5xYYyyCjkW3nXwzujeDMvKXqmZzlnB56GpGp72ijaYEFiZCn37Tptzx14X6cuxNexhEy4UKxYkJyJJcX3Diu41yFXhWw0xA0otPnZF4EfDnIXNA4pmsWeK26QH6+l2BZ1rvxVMb45XLWllNb3b4dWEoG79yUmKbB51ucO/YUhRD+W1zwaOD/h5H1kfzgmK1KJoiDgZSLDc+4hQqMMhPeG4ibc6/BtHwSXpXQjeI5GA8O0ufLCFwyxaOcqq25f5VlPhSLB5GcxBdwu3a/NRdyAl7wgWvlHXVMUVBpLFeheaBO9DuB9JknEERHvMICxD9LMn6ir23jQjkK76We5IsNBBb1ZEoYD9mZfkBaKbhkPWoJbW4WjToDw0i/+KmloOUQ9hbUJIuCK13i4QwJEAzoHv+sqsvPyxQpX7NN6nPWqRqTfzNGBEsHM2r2RBXskCWjhGEOl20S/0mCBYzV2SQ==,iv:8dffTWfmg3DwHokpCAH4AmYBvtyM5d4zX7BZlFHxTXY=,tag:cS74fkQVR8KrPMtsefkwjw==,type:str]
kind: Secret
metadata:
    name: loki-basic-auth-secret
    namespace: loki
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UVJ5c1d3aTY1SEFiMzda
            dkJ4L0dSQWQyZXEvalFsM3lHTkVHOUsxa0RvCmMvNmJ5NGJ2c0FyQ2grZlp5OWhq
            cS85UmkydWEzOGM4WHNUc1dWWTZtcHMKLS0tIEtCWHVBZkVENUR3cFFCNzRmTXNX
            TUp3aWIrclZ5R25rYzEySGxwa25xSk0KfiiFHlZtyDZGKpsk0xXL30wVItNNnAvH
            ogJxA6hxQU1ZGHjCklo8gh/W3N5S86XaWA0ZKuWUY9/C/JwyDHVuuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T19:32:49Z"
    mac: ENC[AES256_GCM,data:TjKfObFCVJ6LxIXLLPga1c80jPFmmk91h9X3FFOOMUg6Z+9QVf0K/AduaDKBOD5st5TbuF18RdVuXpyEQB0Lsd/uDXyERGgp4dHbPpthyYzObGZdSH70Flgm6BEkcTWx3bSDQRNeSPN95WEKp6cRIwYwVBxSBplafhi9E5P9oYM=,iv:54IEtsQpLgkXPGK6yMsMuOwgtHl48kFPsw9oqHaqTkE=,tag:5WoEuAMSMl2NEoaoCUyKIg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
