apiVersion: v1
data:
    users: ENC[AES256_GCM,data:LMNY04MO8HhHePw1Z/VU1bH0GNlLMX+5shHO4MAVSoPueUqVaKuQv637oW4RWcH63A5ypbgbPDWBX5e/mzKBnUZJwWi2Oml2OWfKWRliFQ7NFRGQBjuJ0sEIettC2T0gJ0eJGvOBuVfXDswRIE21ukskt1h7/U5naFnop+xg/iBvX3SbpHlTI9WBhwwl8gAJDPFoBSHpF4m96dIKa/899Jb8cZNtEWAhmNHZ+15G0bQT3ge90Mk+a3AadQxCK6EZ1O8Nmsg9RRX/S5mNkx9rpM86+AeMPW26pVDnvvMQ5WMgwmDMfn2gXGlgBClheXekRgBF+QU/QkVWTaGlw+m6be7ATZhCnjyAV7V+nvFjqn6Yqf/VC10rLTUgSvpA/RbaeZa7AAxEKTQtK7Y3aYVzOkfHoKAjr0vHP6yNSxtL4Hwz6TcYWFfvZRXA2rXGsnVx4vOKFS5RvbLdYnIgE7Fp0qXvq5Mw50CiqvHkTs1YFrdMWyEYVrSfu274l9EFsRS3iGl1rcFy2A1O/VcvXHoaZ/BeqDsmxQ4TUU6Wssqu8EzKFG+dJ/3O7J6I8v7Hy03+ExwS560NxNcj9wLAVcDOP9DCpZzezGJfoedfCQ==,iv:Tz6H3fTQXMPEvbcaR2VcF1MheOawMXUi7gbJ5nngHIQ=,tag:JwTF2JCMenmgLhSZ/HQVkA==,type:str]
kind: Secret
metadata:
    name: loki-basic-auth-secret
    namespace: loki
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTlZpWnM1ZldHZjZmbGtt
            QWs2UDhPYXZyTkJJY2lWdmRJVlNOYjFmWEQ0CnhTL3RmdTZ6Z0tWeE5XeWttN2lT
            WWtkSHc2T0tQM211bHN0UVpwVHpYbjQKLS0tIEVqN2xtZTZiWmt2MUNwSk5ndlJQ
            SHdva0NoVms4V2h0ekJ0K210K3BsV2cKHpuqelaAc4d040KxZHy+KjLvJ2D+ZTFk
            a0apNS6NOwLqd/edCuYHqyrc7U1VFQWeXymtDF65/mmFUzC9zBtK5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T20:47:13Z"
    mac: ENC[AES256_GCM,data:hSW6QScVjxgO5ODccFswjDm+MYPLfcL9lWJvEGETv4o7lnYRym+CSazTFoIqaHUdSo5zrzgG1Lm6Ofd/jYGnazT3hN3SZY52tIhf9OrLRglRxnypw11DpXV5oY2Ijk1NtKxv/j1JwUzRQTaWI8X+HEkrvXHwMJNEl1su2ZNr7Nc=,iv:85sMoR8hxANTg1PElW+7E331Gw8JcZf2lOEvyptvCdY=,tag:SRU9BPvkrNxXORj4d/zdCQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
