apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: kube-prometheus-stack
stringData:
    webhook-url: ENC[AES256_GCM,data:yfvUviNEU+KaRueojmUrzJZC1SLCNgT5HVDHBqQRFCn1sO0yHbCbdn9WsRLsa4t8ExAsLK1a3fHwNbSS8QLeZS4ZGyZyoO0BNRHQtXXZ1QJbbpkP+ZtIm8L4jOCMCsdUPDdJpEsqdI8JtKk+gE3bp9savmcizKmy+Q==,iv:eKjbvPfKRUF1JUa3hlyoFT2RLbzBunTgMGZ0JUw1Hr4=,tag:9td5AMiZftsB+bk2TzFaSQ==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeGFqTkdqNTNra2ttaklF
            Zmo5bEtQT2R0MnZPVE4zM292MW5JZmNBNWtBCkFRSTdCdG1Ram9IaGl5cmFCLzd6
            dzBLZUJGQ0Z2SDI3cGNRQ21meXR2UEEKLS0tIGtQUzRIbjBscCtnNWtCS056YWJz
            TFMrOUg2elViMVltTW1tcGd1QUZCaXcKdrIKKGLbrGDyMOhtRThvsvFEBTD0Gj3Z
            6qYQ/WaVZglEKwKD2rYLWbJb3kZxh+bud4M1xf6jhpeNovsR2BwnMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T17:32:30Z"
    mac: ENC[AES256_GCM,data:dhVv8U8YLDJSBdLPIYrXTb5mdHsVGLZVH0edA0ACzS8fcP+GsI1V8wlOb7zU3yq+UOA+1m3J5hlefVKbqE131FH6ConaztxFBCW0jzjQlt5gVr5Q/icduUCEl3Vztqs4DAmt1uqcGp8W13vLMegcZeKV/CDUtoPfzaVzZ6qg57I=,iv:4Sg1YhVQK39pyvryOsXi3tf2xa8wMjFBZ9nHdciMwkM=,tag:MSCjWundJxx+1K9cEoZ3kg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
