apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-healthchecks
    namespace: kube-prometheus-stack
stringData:
    ping-url: ENC[AES256_GCM,data:vpZu13EvSXDgCj4uAb3I86GBSpJgISztWTIdM6wz6Z8ijr1FKZ7M4nLdIsGUls33ovE15IyRq+s=,iv:Hdapp2S//nmwoS7mO8LMqAN/zJphXprVAHzSaEaQcsE=,tag:QzWVlxzUKVeV+bSddYP/sA==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIY1MzeDFVWE02TG5LM3Fh
            ZmJXYVF0SVZRdlVnTCtYdXVJUlpGd0lMRkFRClZKYndWVmZOWmw3WmU3VTVnUGlx
            amFpVXhEUmcwSVVPcldWOUdITWhjbHcKLS0tIFNUdUNrSmF6b2ptdE1FMm5zQ0Nw
            NWpOL2ZXWDhMMDBjbnFrWVAvTGxQaDgKE05GeOASWlkyLKOj0qW/3d5/DZJiB+j9
            XijyKr16sPLz+6J+ywDyqmEazFVxQZfli+AfMB/xVZUHdxsZckhMIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T17:50:32Z"
    mac: ENC[AES256_GCM,data:vWX7nLra/zv5tOI3RR/Kfx8L3VdQhq03sqRVG8ZabTdAN/BXaPkFYnt+t0Ysi1/mjFafRQnpRK49dLPtrWvJrQwV50ERUD7/3Ezu56/DtnUt4HLQVPlBzvgwmaRu3/+KmIHWtnWyZPXaM7kkNfyfIA+zSbuvaLqjeGg44Yi2drQ=,iv:TJv7rR5xZ8n06c2cdTGu+KRphbAcC2NVurzbLSjwsy4=,tag:+vntBC+tvmNXi7uZdTaSig==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
