apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth-secret
    namespace: kube-prometheus-stack
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:zda9SoPIQqkQxdOu42a80oGfx6A1T1tLhYlEVIU6BYRefHRq,iv:RuKmZRVOuXFV/thKyf7151s6qe8kyqC5kgdr70hQISk=,tag:+xKnGVsimXJMg/KnNbK0pw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:/lV9nfhv+Udll+OKmrr3I76VYJgOb70iIJsGV3NbST+ebGlIHiSD/5FFGN9UJ8WmSJRs+4Cwhvs=,iv:6UxC+ctXsbgX9eudJU6DFeAOEzg9kagPG+nwaxv/5/0=,tag:s3TS5BotBlMXjPH0/LkP9Q==,type:str]
    adminPassword: ENC[AES256_GCM,data:Hx+KxACYs53aPSqfVEiaOxKbD96Dp2FT,iv:/zGiAambCrX60N2zOJ4GpJ2gNLAEj9rQJpIYUVsaYic=,tag:yYrVDyCVyQakc4Bb2MeVKw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SE5GSjl3R2w3V1RVbFJs
            dHU0SXlQNXE1anVoUHlBNDU1dkxZZ0h0ZFJJCllNTjlSOVRwSndYbGw0SFVHYnFj
            U0FCdW9SR2phWXU4dTVyeVgzT1A1MHMKLS0tIHVUNythNkkxVHgzeE05eHdiOUcv
            SnppcGxSeFFXTVZ1bEVqUVpzWVEzdzQKWoiC557NruLbAPwEczjcsho3YD+vqCWk
            a02GvqZI5uf5By4RT317M269mnbYuNl7BOHY9GBitIrh5bXjAMPigA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T19:39:17Z"
    mac: ENC[AES256_GCM,data:YSjxPn786ZzpN13FJbRsX6BYv148X7N5S90xrZwa+svUGSFxAtKKLYaF9MprsttHjeUh+xuHqxPqKYU8G0WIt8mhH6vw395ULTwJ3cIaxJu7ciGos1s+SxisChAtH/+n8rLm3mRxW7fBbZgmt+wzCjJoz6N2ROP8dLdmla9Panw=,iv:KvCQGyyPUEytWlUMObd08koN6FuNiHlexF5khV8fGvc=,tag:epdbdxoCO3RpI2Xpz4dyVw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
---
apiVersion: v1
data:
    users: ENC[AES256_GCM,data:dzeLM8mom+Khhb9mtt56tjlQUBjSaYU3VvzIY211iYm/RlQd9X64EDvqFf9I9jz7c8sf5++kBJzXr6sAcz0jez/CYE74Mg9VZyrP624+PztWgYPawnOs8xJaiJDD8h+d2qWN8lMEVPv2amSUr6KyCQrnHziaFuoA7qDbYu/YclJiGJQ7SEjvRpwi+It3ewidsU3tYJIKulqZx7KRHmkU4YhVGy8Tzp6ToTJ4njV9bdKUIIUvrDW9XyxOnyWk4kkcmvV46KBUQ4O9lRI7PCxfuFo25rosfMrlFYBZpTKu7CMh+EnZnlfrG2KiESJCf2ZODmG9BriR03LtFunGtSMR+71x0Jpq86xdVXC3InrBet2sS3Px5srhI6hvaadMKZ9T3ogNUwM5fFJPaZIfWLjqnmoZ3ReLP3kR7ZzILhqskL8iv/ep3z14rFLp6XoVMqs3RnocAkIV/HlMzzXIHAGQXJjIHBQmD3HSRcx/IlbIwaYu6l/ERRkAy7mKFP9IpmuoMElbcBHFb6rxyUcDOEHGLXvMwn2dilV46081CD6RSwQbIlPA1w+fuAJGf+U2A9Qh42EVKGtle9WJ2y0a8amxeIQs4NTRVjrxmPi7zGTv9E4FaoWk7J/ym6im3YXwDxUJTB/pixu0VQg+WnT/d/xHS/6V/UHE4zbccblfsPkevyYQRlq4tPglZVsJCKJVF8S05wHZKLVN1DsirRqT4bay4eVvRH8=,iv:Kht9awfHm1ShQU/mQPb0f82xjImi4HkYcGkBYH3vk4c=,tag:893f+I5h9rbY8r4/8NqRlw==,type:str]
kind: Secret
metadata:
    name: prometheus-basic-auth-secret
    namespace: kube-prometheus-stack
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SE5GSjl3R2w3V1RVbFJs
            dHU0SXlQNXE1anVoUHlBNDU1dkxZZ0h0ZFJJCllNTjlSOVRwSndYbGw0SFVHYnFj
            U0FCdW9SR2phWXU4dTVyeVgzT1A1MHMKLS0tIHVUNythNkkxVHgzeE05eHdiOUcv
            SnppcGxSeFFXTVZ1bEVqUVpzWVEzdzQKWoiC557NruLbAPwEczjcsho3YD+vqCWk
            a02GvqZI5uf5By4RT317M269mnbYuNl7BOHY9GBitIrh5bXjAMPigA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T19:39:17Z"
    mac: ENC[AES256_GCM,data:YSjxPn786ZzpN13FJbRsX6BYv148X7N5S90xrZwa+svUGSFxAtKKLYaF9MprsttHjeUh+xuHqxPqKYU8G0WIt8mhH6vw395ULTwJ3cIaxJu7ciGos1s+SxisChAtH/+n8rLm3mRxW7fBbZgmt+wzCjJoz6N2ROP8dLdmla9Panw=,iv:KvCQGyyPUEytWlUMObd08koN6FuNiHlexF5khV8fGvc=,tag:epdbdxoCO3RpI2Xpz4dyVw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
