apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:4KpOgfAwfZdnbV9oEm2nvik1k71Bdyd6esBi+VGyVsCU5ukF,iv:+2SR8XLUTovCS3M+V0T3nmf2Ch1QewmUsrJOJsgcDz4=,tag:16bqIS9XjoNtAjVSx2fRAA==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:xmwMU9k8pklcXPwYx/IjVc2znB8nBW6Gu932WeUG2Ion/z285L4QIXSvUq7KMtZ32hSYhQc0+EQ=,iv:MPp57XRBP/aputB0bzNkQytftHp78TwJ+EPCcghVKNo=,tag:6GGWPUs5JfaH+dOobWT20g==,type:str]
    adminPassword: ENC[AES256_GCM,data:5Q2NY/9ijxsXyfKLDOHOHyD7gpOVtcYi,iv:Xvezhy0OMdzVa71r0SuaAzAxpGsRWnxKLuI756VmO7s=,tag:fkZpoajYS1j3E+jYRyOBAQ==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaGc0LzRpcUhoTER4Z2V4
            aHR5VmtJeU91ZlRPL25MT0VuYlZGSDdzamtBCjNlUVIrL0NPUWkvV3RFdGFJRzh5
            U0RiQndZVUZVblF5aWJuNWVDWWhRV28KLS0tIGhuRDVvYjAwbGNGQmhHTlEvb2JC
            YWp3eWVCVktsUDZ0bE1jenpNR0gyQ0kKJdM5/ScF5jnQefKewKduO1/RfFvdxZch
            07Su/CcgHAQq/BbffFLcEDf466sglecV5HgVvGqo2noevtwxh4fsGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T16:42:01Z"
    mac: ENC[AES256_GCM,data:+CdMkJTo0puQU6ckvMFSjn7neh58m/VaVV9txuobNWvaBqfCKFWXltW6rXVnLyatJ9Dxr9RwN3nr1Es/td0kwlmbtIOyUdSVJd+v/P1Lz5pz3LCh3SKirGSN5mEN3zyBBX6bFaqNvOFWVs5xqWmGigCST2J9DwWbEpb9sj/JbMA=,iv:KrY9W5kEFSnasUmUcrb7O9FnuYcdj1RIwT2J9VTYZpg=,tag:jgmLrSj0H3EeuaO15yC+1Q==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
---
apiVersion: v1
data:
    users: ENC[AES256_GCM,data:H5MNXnK4CtC+n9uAXNyXrjuv+mbaQP50jvM4UHfoN84AsycBb1XVmM2JCLyNYLl0isZTjdIfl/kNCQ/M2M4JyeIhRzyP8I1UIt4KAlFepNI7vR+R2BkkIUqOM92bFcDWvPj8yByEvivrr0960jDDXuAPHD4pPyY0cerxAfb5PoszUnwlMestE17n7QiJ8tEg2DMi5gWx/MNZQIY9IeY4sfbCps+Cjhzo+KY+OaM81zEtSuRGFJno8O1w3fIEDB3V6hwCWxSe//QcH+yht7gJGFchQTcJ+XD9lDtg1m16mQMxAakAJowDiOuvV+2gN7JArPVOD1Zu6fQNxkxh/XR8/gmdPOnIbV0yWbLJRw==,iv:Is0dcHBSYskB0Gv8gweL242FqmJBqQs2P75inFLUeGU=,tag:Mh00pRdiX8/KIrKNjDiIsQ==,type:str]
kind: Secret
metadata:
    name: prometheus-basic-auth-secret
    namespace: kube-prometheus-stack
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaGc0LzRpcUhoTER4Z2V4
            aHR5VmtJeU91ZlRPL25MT0VuYlZGSDdzamtBCjNlUVIrL0NPUWkvV3RFdGFJRzh5
            U0RiQndZVUZVblF5aWJuNWVDWWhRV28KLS0tIGhuRDVvYjAwbGNGQmhHTlEvb2JC
            YWp3eWVCVktsUDZ0bE1jenpNR0gyQ0kKJdM5/ScF5jnQefKewKduO1/RfFvdxZch
            07Su/CcgHAQq/BbffFLcEDf466sglecV5HgVvGqo2noevtwxh4fsGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T16:42:01Z"
    mac: ENC[AES256_GCM,data:+CdMkJTo0puQU6ckvMFSjn7neh58m/VaVV9txuobNWvaBqfCKFWXltW6rXVnLyatJ9Dxr9RwN3nr1Es/td0kwlmbtIOyUdSVJd+v/P1Lz5pz3LCh3SKirGSN5mEN3zyBBX6bFaqNvOFWVs5xqWmGigCST2J9DwWbEpb9sj/JbMA=,iv:KrY9W5kEFSnasUmUcrb7O9FnuYcdj1RIwT2J9VTYZpg=,tag:jgmLrSj0H3EeuaO15yC+1Q==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
