apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth-secret
    namespace: kube-prometheus-stack
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:3pdjuUbHhuw0yDOo1NTaNBbq6iWmRqirFqHGR3YQdI1VMS/C,iv:UdJDhrab66PcKtFvmYoenc/WUvmyiAx1gxTVJx45Y5A=,tag:gmlQizyJUifsVICRsWEkhA==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:XvDPQXlbx/gxAjgoC9VjPcD9JmrhrVBTLzyvLbG+wT3h/yB6SwrtZCGWe9akKz9Y4WbAVzI6Vss=,iv:s0BKYamn/yQGNWNK8iwc9+3xKtMSzUoXNn0dD19jn7U=,tag:AozcgEK6/0DoVr1J3hLOTg==,type:str]
    adminPassword: ENC[AES256_GCM,data:2a3fn0hqa9pr8C8zGiCjyeLjk9kBjTae,iv:zlqpg/U2jyMRGa5QvFdAoJknMapg9vWk0ZD6nHoOCJA=,tag:yUvot+xNqUWpj2kK0FIxMQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUXEySGZTZFV1ZzhnU3Ro
            bXFrelZlOTIxSUlWcm51c2xrdzJVeEdFWEdRCkRLY0VBN1lqeGZ4Ti9rY0Y3cjdt
            YlErWUpWeWl3eWVuaERPcmtZM3JYd1UKLS0tIG11V0I5eURjWFJpYTVLSGsveGJ3
            aGNTWm9SUFEvN2xUNlBKbTluaXFnUlEKXPEMEGM/fgO75ukII/rHRN+ooBMP9ze1
            2KL/vuoVM5Tfgp3cEuiF4QlDtwnd/vKDo8UDmEemATZvm4RijFuA3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T19:32:32Z"
    mac: ENC[AES256_GCM,data:1o7FXByQeZ7/I8Epf+orGm+FFAY39S8+o2jj7pk6AwQsoWRnBVSk6lEnt+jGb8728M/dM6JvfGQo4Vj2QXsvcDrlH0E/KzmnBE8tf4Dv3C9dJ36Nj7FVUcB7J1r0FLHBLgjabdIGSIRg7aZN4uitcxP7ceNGotGo9APhHDAzv88=,iv:GtK6r+1/cpK5EPB6Cq+SIOiUXZ9/V34Ouw5Syt5uWSM=,tag:LFmUWxenRSQ2mM1yzbOflw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
---
apiVersion: v1
data:
    users: ENC[AES256_GCM,data:/Ku8GQsHVPqPKAeJYkd1L6JNNl1hst9ZPFPmMozjBdi8M9Oiyr3SG0slJ9Zxgg2rwgI1VbxCUh7xeFRgvxSfRI4dThYNRE0keJSY+6y1wEr03JbHkPh3BomVBJi2/20aSd1vx/EQrlBBhfCm+FM1difNVYf7riEHUwpzkutdyjxeFB70QfqPmrOT5BDjtSy3CjaXJNMx7LCs1fa77eLaUVYxYC61wfOOBY/nNx5a8gdRfaz9pptT3g/QN7qj4GjenR0INKn+nCx9on6V42YdRiTxD/YVhUF8ncO+9fVPinEJMyws7NOmVhgOePOF5TFxtxljKQJhcpogn1uTVM2UVCba2IJtskGHJd8wk11uMkBLF/kBAr/38PI6I/mAg0pujCaM0WDxw81Jp9pukqmLQqSGSwHZk4I9QeMNFcirtVV94qbmT1QMtx1kmHoVf5u7PS882JxdkO8tDhPE/RYgtYYTVplCwUZqr5IfPl2anz8adovhj0DUHvpe+pulPdITFYu9Jez0+ioCJU1XizkoZM9Pm4qqvlW1VyejOjO/kY1PgfcqIqqivJ0NuPaEmawV9D6AB9AXkFZuPCItPImcgoYetR2NWE7RY9fGJA==,iv:EFR4zZFSYfOgzoyaqrDo4HpzM/5NUJ7Dz7YiMGOVjw4=,tag:V3r6atQT3nKYs2OL8A3I6A==,type:str]
kind: Secret
metadata:
    name: prometheus-basic-auth-secret
    namespace: kube-prometheus-stack
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUXEySGZTZFV1ZzhnU3Ro
            bXFrelZlOTIxSUlWcm51c2xrdzJVeEdFWEdRCkRLY0VBN1lqeGZ4Ti9rY0Y3cjdt
            YlErWUpWeWl3eWVuaERPcmtZM3JYd1UKLS0tIG11V0I5eURjWFJpYTVLSGsveGJ3
            aGNTWm9SUFEvN2xUNlBKbTluaXFnUlEKXPEMEGM/fgO75ukII/rHRN+ooBMP9ze1
            2KL/vuoVM5Tfgp3cEuiF4QlDtwnd/vKDo8UDmEemATZvm4RijFuA3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T19:32:32Z"
    mac: ENC[AES256_GCM,data:1o7FXByQeZ7/I8Epf+orGm+FFAY39S8+o2jj7pk6AwQsoWRnBVSk6lEnt+jGb8728M/dM6JvfGQo4Vj2QXsvcDrlH0E/KzmnBE8tf4Dv3C9dJ36Nj7FVUcB7J1r0FLHBLgjabdIGSIRg7aZN4uitcxP7ceNGotGo9APhHDAzv88=,iv:GtK6r+1/cpK5EPB6Cq+SIOiUXZ9/V34Ouw5Syt5uWSM=,tag:LFmUWxenRSQ2mM1yzbOflw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
