apiVersion: v1
kind: Secret
metadata:
    name: openfga-postgres-secret
    namespace: openfga
stringData:
    postgresPassword: ENC[AES256_GCM,data:0enBra5I0uni8clcXXcrwjfiDmdJQKxyPpg3xowlqD0=,iv:nyUkRq0v/ID8k/qVdCniODHTCmR1FC2g8JV/5QRhH5g=,tag:gXj1TzLX2ZKHwLNPme4xbg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUa0JzeGZpc2U1cStLazZV
            NVFQcytveTUyS3c2RmhXWmM3RlVLTk8zTnhzCmJxcmVteGdiUkphUDZGb3BGQWhY
            UG1ET3A4YnFnSVpYTlNlRnZQLzhxWDAKLS0tIEFaejltaWl1RFBSRUYxMW9ianFX
            S250a0Rha2VoaGdncm9QNmFFbE4zZk0KBkds5sTpBb06TsYQmO1Njj66eBjWaZyg
            XPryXUzVoFIPzIsCM3EiKes+76v+EwM29oVwNoSVdA6AL1c9Rq/YpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T20:47:13Z"
    mac: ENC[AES256_GCM,data:iAoy3YGvvkAYg262vTfQaX1qNEfaDC11OqEELBn1YSGEAhDL0HkSLwuMOkYcLhO8JneZ2oKN3O2Adjg6dg9DfUGgDM2JfDwdWdlOy3Di+N0+Td2IgD9y9IhITeDx2Q2rdYTVhZVkznFCkH4CExTW7tWY29gVIqiXyO4op84udbE=,iv:EulSbA0VFEgplPIysMJfKFkHLdw0yndF2c4nxcEyuBs=,tag:dOTq6ieDTfuHFkGF6TgLng==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: openfga-secrets
    namespace: openfga
stringData:
    datastoreUri: ENC[AES256_GCM,data:HfCv0N7X+XbB41hb02nTwL0v89m7g1yBriZQbbEcWlunBVEbBR7I3AdEM/Wow2YdmPUOslhVa/Fe7USlL0ZF2KaNizKXXg8g1lrhl6Hpa9ptf9CB7mqeEdHkswMKg3cIjA==,iv:D5BCCxo6DV35E5SuqJjdHpRUrCE/TRWgSp4HANAyODM=,tag:s0Kk54E78XlknRDz2EH+Xg==,type:str]
    keys: ENC[AES256_GCM,data:5McgTPzWO36x7jmovy2pysVpVrVvwRB9tAbJUDVmiZACL1wW3dPuAQ==,iv:qwghGxokZSSRsLEjpB+/e50ICRAgYpiqTyXlkV/e8WA=,tag:fnQohWNZ6m39M+9tbPEB/g==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUa0JzeGZpc2U1cStLazZV
            NVFQcytveTUyS3c2RmhXWmM3RlVLTk8zTnhzCmJxcmVteGdiUkphUDZGb3BGQWhY
            UG1ET3A4YnFnSVpYTlNlRnZQLzhxWDAKLS0tIEFaejltaWl1RFBSRUYxMW9ianFX
            S250a0Rha2VoaGdncm9QNmFFbE4zZk0KBkds5sTpBb06TsYQmO1Njj66eBjWaZyg
            XPryXUzVoFIPzIsCM3EiKes+76v+EwM29oVwNoSVdA6AL1c9Rq/YpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T20:47:13Z"
    mac: ENC[AES256_GCM,data:iAoy3YGvvkAYg262vTfQaX1qNEfaDC11OqEELBn1YSGEAhDL0HkSLwuMOkYcLhO8JneZ2oKN3O2Adjg6dg9DfUGgDM2JfDwdWdlOy3Di+N0+Td2IgD9y9IhITeDx2Q2rdYTVhZVkznFCkH4CExTW7tWY29gVIqiXyO4op84udbE=,iv:EulSbA0VFEgplPIysMJfKFkHLdw0yndF2c4nxcEyuBs=,tag:dOTq6ieDTfuHFkGF6TgLng==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
---
apiVersion: v1
data:
    users: ENC[AES256_GCM,data:mikXL/FmtaIVrhnAfQiIX9+Uz6cIDKeceTRo4sQH/T7Gf56HdqWx+99ztzs7dwOgDrVrs5RVUpXqIw/gNrZZ/jnu/471+Zx3xO6EfNdA2RYszfNnTjVEEQoe7/8=,iv:MHkxITwkf36WdIIPrzbuJ7mS0BqHzlzKfoZWA4mXlKY=,tag:oa2WcBvAd5D9P37ndKyaPQ==,type:str]
kind: Secret
metadata:
    name: openfga-basic-auth-secret
    namespace: openfga
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUa0JzeGZpc2U1cStLazZV
            NVFQcytveTUyS3c2RmhXWmM3RlVLTk8zTnhzCmJxcmVteGdiUkphUDZGb3BGQWhY
            UG1ET3A4YnFnSVpYTlNlRnZQLzhxWDAKLS0tIEFaejltaWl1RFBSRUYxMW9ianFX
            S250a0Rha2VoaGdncm9QNmFFbE4zZk0KBkds5sTpBb06TsYQmO1Njj66eBjWaZyg
            XPryXUzVoFIPzIsCM3EiKes+76v+EwM29oVwNoSVdA6AL1c9Rq/YpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T20:47:13Z"
    mac: ENC[AES256_GCM,data:iAoy3YGvvkAYg262vTfQaX1qNEfaDC11OqEELBn1YSGEAhDL0HkSLwuMOkYcLhO8JneZ2oKN3O2Adjg6dg9DfUGgDM2JfDwdWdlOy3Di+N0+Td2IgD9y9IhITeDx2Q2rdYTVhZVkznFCkH4CExTW7tWY29gVIqiXyO4op84udbE=,iv:EulSbA0VFEgplPIysMJfKFkHLdw0yndF2c4nxcEyuBs=,tag:dOTq6ieDTfuHFkGF6TgLng==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
