apiVersion: v1
kind: Secret
metadata:
    name: openfga-postgres-secret
    namespace: openfga
stringData:
    postgresPassword: ENC[AES256_GCM,data:MI9VN9nzrspGC30qbS1GGeA2STWmmol4FFOl1Y7kebo=,iv:Kmumn81CI54pki+w5mv+tSUickD7fjQ9l9u8btqkGoA=,tag:dFX5SfUPe7teHca+VFu2aQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a1UvalN0a3pLSkJSQ2lH
            L1QxR0NhaEhNNWVBL25UR211d2lXSFRvZG1NCmhXaXJzaDlCZ3VlRTlYMEZhbXhC
            Wi9TN0dLaERXMGtRT1BLaGhLSnVRUlUKLS0tIFlIdHUzNnovaTZvVTVZMnA3Snhz
            aWVrcVlBbmVqVG51ZmFLbzQ3VzNpamcKm9mWOay5B+EVoFHLg5sc9EZH/wQnIcqJ
            U+0C3obHTxk/Z1dXSH3NobeCyRgBFVThs+zJDx86LmI4h3kuyPpJww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T21:49:14Z"
    mac: ENC[AES256_GCM,data:shu9L1LXb6u+Ad+SnG4ludxPVKPLSzosQh+QBX1XyCkm/AYDNrn1QeVZnDmYzwVDo23x4S4ySFQyL24k1eLzlTUET4rWDW0R0nmDRDvZMGFzjHkd8RVJq2lI/1ELUvWZis1O6ddSBStja21DxJs6boiCs2CDo6CnMJ+hEmjtA38=,iv:kfgUYm4/CMX9uLhrNhRzmkplxCoGKQ2oKSNDl6MJiBU=,tag:1rMSRCYPkmGsO7GDQlIsDQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: openfga-secrets
    namespace: openfga
stringData:
    datastoreUri: ENC[AES256_GCM,data:xI4/iDjqqkOX46Yd/7VIlK9s/By6xOwYBYM5v3H5NFNXe+O3Mye6b7G5YYvUNJR6bwnbDDM2EMFqzQ1hEDyf3gD+78sC1THbL35GBKpmdmC3ERLzcrtB6jitsfoWNibQdA==,iv:o9nSf2xKmBt1EpZ39wFbBl2Mttg81YjhLy4GFAWqiKI=,tag:9M9Q3W84BT28xQUntDISbA==,type:str]
    keys: ENC[AES256_GCM,data:Qt4UhIgCxw40m87LKaV6YoSy5vD+vAZErbb/mQ7KhjTD8VbeLZ07mA==,iv:3VGS4vKcxDfk0xFHcuAh0F92zZmtVT+5HUd1xtYI/Ac=,tag:wva7GHAqX0XS6ZfidFxXuQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a1UvalN0a3pLSkJSQ2lH
            L1QxR0NhaEhNNWVBL25UR211d2lXSFRvZG1NCmhXaXJzaDlCZ3VlRTlYMEZhbXhC
            Wi9TN0dLaERXMGtRT1BLaGhLSnVRUlUKLS0tIFlIdHUzNnovaTZvVTVZMnA3Snhz
            aWVrcVlBbmVqVG51ZmFLbzQ3VzNpamcKm9mWOay5B+EVoFHLg5sc9EZH/wQnIcqJ
            U+0C3obHTxk/Z1dXSH3NobeCyRgBFVThs+zJDx86LmI4h3kuyPpJww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T21:49:14Z"
    mac: ENC[AES256_GCM,data:shu9L1LXb6u+Ad+SnG4ludxPVKPLSzosQh+QBX1XyCkm/AYDNrn1QeVZnDmYzwVDo23x4S4ySFQyL24k1eLzlTUET4rWDW0R0nmDRDvZMGFzjHkd8RVJq2lI/1ELUvWZis1O6ddSBStja21DxJs6boiCs2CDo6CnMJ+hEmjtA38=,iv:kfgUYm4/CMX9uLhrNhRzmkplxCoGKQ2oKSNDl6MJiBU=,tag:1rMSRCYPkmGsO7GDQlIsDQ==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
