apiVersion: v1
kind: Secret
metadata:
    name: openfga-postgres-secret
    namespace: openfga
type: Opaque
stringData:
    postgresPassword: ENC[AES256_GCM,data:ZLI/SNFF/HXLjyIxcxkauEPx4rh8S7anA66VxrnR58k=,iv:uavuWHlcdE13fji55tGjm6QjzPdUUc/JcY5pDkK7tlQ=,tag:DxQfrkZAnVkMYlm7ASTJ8Q==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTmFscnl0dG1zUDUzcmJN
            Qm5vM3Mxak8wWGtyMXFkVGZqNjFrVExQV0ZRCk40LzhhQjlxMjBtdlNzQXhtVXZz
            dVZyTDNPOFRTQ2tvcnhGVXUvWkFUTzQKLS0tIHJnRkpKaWRFTG85SHlzSS9MT0xo
            eWl5dEM0VGFVdHYrVEk0Z2xDV2srbVkKG1W+q7PGs3O/xHLpOGmc3u/C6slqjpCY
            4aJgHeHv7YisKkem1kWTM7R0oP0oe1KQRMXlnsQhTaGr2WTvXFsYXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T01:16:17Z"
    mac: ENC[AES256_GCM,data:Vw+D2AvcKVYmMO66adibguyzv+w9B3LWjAVUnsOpvRyNWVgManh5HCOx1YXP1LU59xyXsuVSdp7urzwo2Oyy1EL3P9Ll4bWqFsfUp67PipH/9DzEQRp4RgTfyVoPR2d035oaSNFnPIa5y47+gpm+CB7ozxuOh+T/fsriKNxQQeg=,iv:XhYdWVT0Geaed0xCZjz5VW3vIe3ub0+yVpDSJOxFGQI=,tag:oHG0jnp2gByS6MBXgitghg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: openfga-secrets
    namespace: openfga
type: Opaque
stringData:
    datastoreUri: ENC[AES256_GCM,data:uu7xGRzT5msm2+9vtEj6FXv8/WXvZ0tdndCO7obZvpE7hXUCPO5PtiOK5ExTwO60+8NwCgBLRIu/wOuGWkgQ6TtGSOiferUqf3XlyxxDRNhyRhqVZn4OeTXaueEGLt13yQ==,iv:ebUgCctAOqkHxhKOc5Vt/sue+vLdkK5C55Im07DLIH8=,tag:ElZa5U64U2bfpId8On7vJg==,type:str]
    keys: ENC[AES256_GCM,data:hJqp8ugqzSYLmr0FJ7GbrUHQEnBOGGToA9RFcw8Zu+zJM1q0z8H73g==,iv:bFFcBJx2IwqrcTLcxwOQIoOaHMSUW5xgH0uvmpK3ep8=,tag:Ci3eK1lQUog6YbOvl/lLFQ==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTmFscnl0dG1zUDUzcmJN
            Qm5vM3Mxak8wWGtyMXFkVGZqNjFrVExQV0ZRCk40LzhhQjlxMjBtdlNzQXhtVXZz
            dVZyTDNPOFRTQ2tvcnhGVXUvWkFUTzQKLS0tIHJnRkpKaWRFTG85SHlzSS9MT0xo
            eWl5dEM0VGFVdHYrVEk0Z2xDV2srbVkKG1W+q7PGs3O/xHLpOGmc3u/C6slqjpCY
            4aJgHeHv7YisKkem1kWTM7R0oP0oe1KQRMXlnsQhTaGr2WTvXFsYXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T01:16:17Z"
    mac: ENC[AES256_GCM,data:Vw+D2AvcKVYmMO66adibguyzv+w9B3LWjAVUnsOpvRyNWVgManh5HCOx1YXP1LU59xyXsuVSdp7urzwo2Oyy1EL3P9Ll4bWqFsfUp67PipH/9DzEQRp4RgTfyVoPR2d035oaSNFnPIa5y47+gpm+CB7ozxuOh+T/fsriKNxQQeg=,iv:XhYdWVT0Geaed0xCZjz5VW3vIe3ub0+yVpDSJOxFGQI=,tag:oHG0jnp2gByS6MBXgitghg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: openfga-basic-auth-secret
    namespace: openfga
data:
    users: ENC[AES256_GCM,data:R/buzkHSZfGn98nQNuNWxhbzfSivDNIylVM4s0vk5C+p/U3ioqrvRr441Xm4wetZ1XGp5QdeufP8xeu5J4Eq8tN5MG3VvLZDycFVu8HYUgw8/Gi6SjVpXdfQSE0=,iv:AQcpmihdmq+EdiSHnsFncBUGbEw9xlpjL2HrwMbRUFM=,tag:ghzISdMW9kPkN/DDB5uLPA==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTmFscnl0dG1zUDUzcmJN
            Qm5vM3Mxak8wWGtyMXFkVGZqNjFrVExQV0ZRCk40LzhhQjlxMjBtdlNzQXhtVXZz
            dVZyTDNPOFRTQ2tvcnhGVXUvWkFUTzQKLS0tIHJnRkpKaWRFTG85SHlzSS9MT0xo
            eWl5dEM0VGFVdHYrVEk0Z2xDV2srbVkKG1W+q7PGs3O/xHLpOGmc3u/C6slqjpCY
            4aJgHeHv7YisKkem1kWTM7R0oP0oe1KQRMXlnsQhTaGr2WTvXFsYXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T01:16:17Z"
    mac: ENC[AES256_GCM,data:Vw+D2AvcKVYmMO66adibguyzv+w9B3LWjAVUnsOpvRyNWVgManh5HCOx1YXP1LU59xyXsuVSdp7urzwo2Oyy1EL3P9Ll4bWqFsfUp67PipH/9DzEQRp4RgTfyVoPR2d035oaSNFnPIa5y47+gpm+CB7ozxuOh+T/fsriKNxQQeg=,iv:XhYdWVT0Geaed0xCZjz5VW3vIe3ub0+yVpDSJOxFGQI=,tag:oHG0jnp2gByS6MBXgitghg==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
