apiVersion: v1
kind: Secret
metadata:
    name: alloy-secrets
    namespace: alloy
type: Opaque
stringData:
    ALLOY_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:oJ1/+2GqjeNlsXZI/baTbj1v99ccClTbQyQCMLXS1A==,iv:FRv3jTQUq0tvRGYJb8QdqWVH+0bpQaHuAFxutcVHMlg=,tag:/8bUukXGzRQEiXeFdOAU4A==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MnErOGh5ZEpieG1vQUJD
            RVFxOGpUL1lqWWhKeVlxR0dtSVk0dHBYZjFRCjdlVi9HNDZ5MHRaYnFMWFBISHVh
            UXZYRFVlZFd0Z2hQc0JaKzcxNHVlME0KLS0tIFZHN0dvMndHR2RrRURGOUVRTnhk
            MEM5NGxRelBQRG96OWVCRFE4b2J5SFEKVSBkiKWd0qPeRRAIjcXdtwMCIQtO4jtQ
            fYKoqjQ8oe20NKUNmH8oCetuwaeY4oBPrpzQG3Kr1z7SYBuMXnifEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T16:38:09Z"
    mac: ENC[AES256_GCM,data:ILKVnbsopr8I+wSvWqg3vfQnlXekcAPtWL/lZhXKJQfSn0ln1+Xo3nxzH2EHgHwxsMV+zXWdXf9mMNPS5bz0RSp8fH6R5scZww2jKi+ze31ihB+m423eM0x/kVdvfgqgXn1lQasptoWiwBQQgsWn4hxotyGq0PkkQNUNvhtHKtk=,iv:/Lu5hMWir6wCYCty3ZC5kU4chNCwRannGIdVouYPC7c=,tag:Oo4U6oDQA0ETjOqt8igz5w==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
