apiVersion: v1
kind: Secret
metadata:
    name: alloy-secrets
    namespace: alloy
type: Opaque
stringData:
    ALLOY_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:5ENWcG/8CXRs2p3OQMIJCbIVwu4H1qayIzuu8+0mQw==,iv:yJZXMDESjt83GUieTywkajo+uKDF9m+Ce+q2AqfWQl4=,tag:jUqC0cHa7ucG2IsDUUDiug==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWmpBSWxzeFZuanVLMllQ
            bTJPa1RRSEJXNXdUOU85cDNvTkZGUWl4a2xJCnRCWTFIZXFQNkxSS2ZYTVErdnFt
            bEgyRkoyR3FsYnA2eXdvTGU0TmhweG8KLS0tIFcvR0FtZEY2NURHdkJEa1ZLVnVP
            TjNITlJ0WVprNjBuZjdPUmlna2UzQXMK97dy5WIo1dRVAgouFpjN2js4TshAM2IT
            RmVabnnoFC3lPbNhLajPtWmLj25zjP5XhptmDSdMWDgwM7Ju8dh6tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T15:27:00Z"
    mac: ENC[AES256_GCM,data:kv2nPGJwgC34Kmds8XEppod9J9sLuRD7NiL0P+8DWeeS9kktVm2hnpg79Hl/Spt052MyqOi8C5ac4KNfVl4Ik2s/KwFWV8GBiYbryZNevPQ2ajzdtzw+k/5zy7BaJnSwoHPJGHd5nVwCGInYOL5EkUJYmmYs2AP9aTHaNLQM8bY=,iv:NWjzBXGVH1i+MM4NUN/e6+4BLmf4ucmM93fOAXGeUvs=,tag:x8bSRRUiMholIYqALU2nKw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
