apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:MPjmxfAWaqrNwks=,iv:qmhQLdDNfeM/Re2m8A7ipqnwOGpMqd9RfkeP01fZENw=,tag:RmqAPax0DN3TsE8f4WQffw==,type:str]
    password: ENC[AES256_GCM,data:U5Pbx4501YXXrx+/mbpva1vY0X8=,iv:u0fWOHQAlEaPUFp/jIxJByq/l0QC1eRHtAlvuCZK3es=,tag:s+WJqZPgmbTGUjQoYhtQBw==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUEVmT0xXbnZ5OTJCbXNy
            eHZGUHFvQ1ZBY1FISTZQRHBqNDcwTXdwVEZrCkpubmlBMTJ2Y1ErdXdVa2dGV0pw
            QStlbnAvS1hBNjhodEZnNzhJLzhxa0UKLS0tIDF4blVPRkdlTFIzQWVJS2xadGV3
            djM5MjRnbnNKOUpmM01Zc3VBUHZSeW8K79hTAQ8ALA6I4e4unM2nIco/ykNePgAw
            59mM5AWkkANwP7g2fN01GB15nWoi76xd4zWsxpugRv3DLDrZNxvSiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T15:27:00Z"
    mac: ENC[AES256_GCM,data:sA8Y4wONnyIoKuutVwYasftg7ed2EWuyHuQtNio+aYqJDo5pF5w+PM0v7Vc3iTWWp+IDgnHV4oMEsPJda/InrCzifi1fMZp/ETwOAOvC6XHHefp1RIJkQc5cWjGcFEcFmsdJ9cBcLrQNO8wdYWVCP9kaSTJBbqCkJFnSIIziX2A=,iv:Sd9uHCg6DE4xQ/2oSnXUcV55zhHJuuq+guE3yaP3w58=,tag:AoJjGoCGB5gcyTHD/WkCBw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
