apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:njzvqAw8brTE52o=,iv:H/TgY+rZgILudz894sGhRaqNwWi8Jm1ShJj+aWiMOpQ=,tag:Nl2i2K3rTaDt+PID2Y2eJA==,type:str]
    password: ENC[AES256_GCM,data:inDSy1+dd2qR/vfobV7nJ36MR84=,iv:iFxdDXzDA949p8SjDYUBSKBgvLzBVlnEdkeUCrGIQm4=,tag:tWKyVdUXFeLiGTN5Hvk8xg==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcGFiOEZIdEpCRlZYSVBP
            by96bCtXbVlmVWowUWpQRzRURW05VUJXZFE0Cm9hQ2NuTDFPRXZMWG4yZ3Z6RWR6
            T0ducG1CWkNubXkvWVFaampyUGRNOWcKLS0tIC8wTzZTVlB2Q3BiWUhLbEVvbEtX
            U1VodnBxcXR3ejk3MFU4ZGQyeXFWQzQKEh2UAR5yM1yCJbA3ujIVo4qA0pv/Mq6o
            jj7OSLSK6Rs9PY2L+MjEVELZ05SXMEKlfjrszYi2B92pAClMzfwQWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T16:14:28Z"
    mac: ENC[AES256_GCM,data:PV/kpeRvsBc8USKYMH+3uqnyJinoP9svDTpOf7cUT5kW/7W6KrdwvuVOaUTKXz5RrxRMhAqPSWRo1xP+CE+1eYFTutoQHU1qa8sPXGF9AyFWuYu1k3OWhpj+w4/ONyMCKMezvchYgmpvSJV58d1gjHEMoQOOqTjYnQbCiYuJLdo=,iv:VAJtWd1g9Z0m3PKsD2a6Xc63ScP0Ne8d3SIsZJaNvlM=,tag:/zLatPwCDl/1FKg5IK0PoA==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
