apiVersion: v1
kind: Secret
metadata:
    name: forgejo-oidc-secret
    namespace: forgejo
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:S5DcN0HutXV5FDx8Ra1zkX6Nd5ktoswwtUZRc6F9LzMFcViX,iv:VKNooo59MDvi7WiYiEdyBZptRlWsN9nlymyKkjSzmec=,tag:KAnkjg9gob7wWh79HO1y7Q==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:LKapBAPMMhZkqbjJ8PGHw/0b70ookkQ4muDPYaeAvuUIxFvU44YrYXh7X3v3g3UAF62r5nPNP+UO,iv:Fs7xb56B7rWVXb83Yn07dv9hPDVdHK+gWzebpbQFw0k=,tag:Qza3V6b2C7gkQOvpWpVTDg==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZHM2Y1lyNnVIQS9WdlhU
            RmZhLytwcmNYQmphV01KS094cHdrSTFrRWljClpPVU9qaW9TYWZJaFBEQWFEdDlY
            NWtGemVBZWNDejhBeURhSExhaUsxY2MKLS0tIHNObzRvSHg2bFFKVy9VL0pLR0Jz
            eFRqaU4vbGlmbm1TRk5GdXN6ZC9VT1EKmjHX7K751KAI6jfYehJb1tTI/e1IyusW
            6i4W3rAQIzoOqFLnVe4Yu1weIp2mw45kSdtApTzizLLh5x6dNBUIuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T15:26:59Z"
    mac: ENC[AES256_GCM,data:JqWMQ6qWAQwC2FyC0vBQN1jhyKTY1FJjQhud2sfvZGSr4pQjUod3++c92H1J/W/UQFYN6Cw+0EyUR37Tpn7nkPV0aelUl11s9JIXal4vheVcWQKf0lLx7DudjevFMYd56DteDpZ+gfWkQB+ZOBMwl4nljsxs8Gxvd1t7Ok78tdU=,iv:g1/8gdkfStZ7H3Tb3ZRxQxDcy3l5N8cb9ePlk68r8t4=,tag:fxVp/UEyuyhZL0lxfhSrUw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key|authPass)$
    version: 3.11.0
