apiVersion: v1
kind: Secret
metadata:
    name: forgejo-oidc-secret
    namespace: forgejo
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:NjP4KMdlqlKJ+IwkSK4cKr4cWgk2Rwcg2uUI3aovbnLhz/8F,iv:4F95GhjJ3RbqvDyyVATkQcky1mkS9bztyz7P8eNvAls=,tag:DAunA7xLh5WQYUcXW0R6rA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:OWhakgvezYaceC4ksxDjjdxRwdlmnNoU1EBNRvdiaJ4/xaC/3EoxZuLEWeiZwxk8LdBm/jR7WIF+,iv:8lKHKhSlGboheACq0jPN8a0XRHWokiA+P6hziy6Q3i4=,tag:8haZF1mAJGCTEhZsejnZug==,type:str]
sops:
    age:
        - recipient: age1ae6yk6xtlt8h40272xqxegz3t3zpvvuxj0jwy489xs6e34k0y9xsvpmt03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXblo1L1Z1SDl6d284Z1Vw
            YXFJK1I0K0pnTFhtVjFORWdiS1U5a2UrYUdFCmh5VzJQR1FsVlNnV1Z2Q3RYM0VP
            U25uRVBNZUN1R1pieFdTdWwwRm9malUKLS0tIFdERUxXcUE4MmNEWlJKRVc1V2FS
            MWk4SnF2cGMrMVR1ZXkwNFBhdkR6clkKh1dFghc3jOIR4qmDNm0oWp+/kzb9bRA+
            D4DkaQUXKqQTcdzvbV/+atthFvMIaayvNsz/LnFvpampYVjECbe2bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T16:11:15Z"
    mac: ENC[AES256_GCM,data:tDuPdKynqoGcz9ng7V4NngSgzGZGU3i4HwWneMd7XVpmT0wKzjxF+W6frBegX1/FZmKYTL7iNm8/eLQOzmpLdDjSBWjWI2jkdB3JKyGVZHEdPQTjoC7Brttb5LfTQXJwVLtCoJOhXv4zDIBXMqmK1bJ3RTg3L+/7nsktD585GrM=,iv:8y6Dxg4Gt2iD68JTfyKpP1b0Fpcs6/RqRvshvgHQkxc=,tag:n0NcEUnoj1jZa5Oouyi2yw==,type:str]
    encrypted_regex: ^(email|password|secret_key|data|stringData|ca|crt|key|id|secret|token|aggregatorCA|serviceAccount|bootstraptoken|secretboxencryptionsecret|secretboxEncryptionSecret|clientSecret|clientId|clientID|external-dns.alpha.kubernetes.io/target|adminPassword|metrics.crt|metrics.key|ca.crt|uri|postgresPassword|preshared|username|cloud-init.user-data|access_key|secret_key)$
    version: 3.11.0
