name: Renovate

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch: {}

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.2.6
        env:
          RENOVATE_REPOSITORIES: '["phorge-fr/Frontplane"]'
        with:
          configurationFile: renovate.json
          token: '${{ secrets.GITHUB_TOKEN }}'
